### ISSUE TITLE
bug: Error: insufficient funds on "prepareSendTransaction"

### ISSUE THREAD

**Issue by Droppix** [wevm/wagmi#1397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.6

### Current Behavior

Hi,
I install last version of @wagmi/core@0.7.6, and when I try to prepare a transaction (prepareSendTransaction) with Binance Smart Chain Testnet, I always get an error code (see below), while the version @wagmi/core@0.7.5 works fine.

Moreover, the error specifies that I have 0 on my account while my account has an amount higher than what is requested.

Error on @agmi/core@0/7.6 is:

```
[Log] Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ]
 (error={"code":-32000,"message":"insufficient funds for gas * price + value: address 
**0x89AD57faa0AE99F7c73181bcd2aeCbb48148c462 have 0 want 14499999999999999**"}, 
method="estimateGas", transaction=
{"from":"0x89AD57faa0AE99F7c73181bcd2aeCbb48148c462","to":"0x84E6C3e6B322fb58ecA71D1CDC16f2ED67fc3602",
"value":{"type":"BigNumber","hex":"0x3383ac553e3fff"},"accessList":null}, code=INSUFFICIENT_FUNDS,
 version=providers/5.7.2)
```

The error specifies **0x89AD57faa0AE99F7c73181bcd2aeCbb48148c462 have 0 want 14499999999999999** but it's not true, my balance is **5.4942**  and not **0**

### Steps To Reproduce

I have **5.4942 BNB** on my account, I try prepareSendTransaction with **value = '0.0144' BNB**.

My code is: (work on 0.7.5 but not on 0.7.6)

```
try {
  config = await prepareSendTransaction({
    request: {
      to,
      value: utils.parseEther(value)
    }
  })
} catch (err) {
 console.log(err)
}
```

Any suggestion?

Thanks

**Comment by tmm** [comment]
This is preparing a transaction to send ETH instead of BNB. You likely want to use [`prepareWriteContract`](https://wagmi.sh/core/actions/prepareWriteContract) (with [`writeContract`](https://wagmi.sh/core/actions/writeContract)) instead.

**Comment by Droppix** [comment]
No, I'm on chainId '97', so it's not an ERC20, but BNB (native currency)

**Comment by tmm** [comment]
Got it. My initial thought was incorrect (stuck it out above). Nothing sticks out as being wrong above.

Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by Droppix** [comment]
ok, thanks
