### ISSUE TITLE
bug: mock connector error

### ISSUE THREAD

**Issue by essserrr** [wevm/wagmi#1688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.11

### Current Behavior

Mock connector doesn't respect disconnecting
When you disconnect mock connector and refresh page, mock connect will be connected no mater what.
The same is true when you connect-disconnect any OTHER connector

If you add  `isAuthorized: false`, then mock is NEVER autoconnected

### Expected Behavior

When you click disconnect mock connector shouldn't be reconnected
When you connect and then disconnect some wallet (metamask), mock wallet shouldn't be reconnected

OR

When you are adding  `isAuthorized: false`, then mock should be autoconnected if it was selected before

### Steps To Reproduce

1. Connect mock connector, check console (mock is connected)
2. Disconnect mock connector
3. Refresh page
4. Check console, mock connector is reconnected

///
1. Connect metamask
2. Disconnect metamask
3. Refresh page
4. Check console, mock connector is reconnected

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/wagmi-no-signer-update-forked-cefnuu?file=/src/App.js

**Comment by legendarykamal** [comment]
hi @tmm can I take on this issue?

**Comment by tmm** [comment]
@legendarykamal go for it!

**Comment by Volchunovich** [comment]
@tmm can I take it?

**Comment by tmm** [comment]
Go for it!

**Comment by tmm** [comment]
Fixed in Wagmi v2
