### ISSUE TITLE
bug: @wagmi/cli (React plugin) - HookNameError throws when a contract contains two similar named functions with / without underscore (e.g. totalSupply & _totalSupply)

### ISSUE THREAD

**Issue by zilayo** [wevm/wagmi#2297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.0

### Current Behavior

In some cases a contract may contain two similar named functions which are external/public. For example totalSupply and _totalSupply, or name and _name.

If the Wagmi CLI config file includes the React plugin this will throw with the error ``Hook name "useFooTotalSupply" must be unique for contract "foo"``.

The lines which use the pascalCase function on the function names strips it off any non letters / numbers ([here](https://github.com/wagmi-dev/wagmi/blob/7b47ac330810d67be0215ae541951b1990d25ff0/packages/cli/src/plugins/react.ts#LL214C20-L214C20) and [here](https://github.com/wagmi-dev/wagmi/blob/7b47ac330810d67be0215ae541951b1990d25ff0/packages/cli/src/plugins/react.ts#LL214C20-L214C20))

This is the default behavior of the change-case package.

So it tries to generate two hooks both named "useFooTotalSupply".

### Expected Behavior

It should be able to generate hooks for all external/public functions.

In the case where there are two functions with identical names (but one beginning with an underscore) it should generate hooks for both.

### Steps To Reproduce

In a wagmi.config.ts file:

```
import { defineConfig } from "@wagmi/cli";
import { actions, react } from "@wagmi/cli/plugins";
import { comptrollerAbi } from "./src/abis/comptroller_abi.js";
import { ctokenAbi } from "./src/abis/ctoken_abi.js";

export default defineConfig({
  out: "src/generated.ts",
  contracts: [
    { name: "foo", 
       abi: [
                {
                  type: 'function',
                  name: 'totalSupply',
                  stateMutability: 'view',
                  inputs: [],
                  outputs: [{ type: 'uint256' }],
                },
                {
                  type: 'function',
                  name: '_totalSupply',
                  stateMutability: 'view',
                  inputs: [],
                  outputs: [{ type: 'uint256' }],
                },
              ] },
  ],
  plugins: [react()],
});
```

``yarn wagmi generate``

Expected error:
``Hook name "useFooTotalSupply" must be unique for contract "foo"``

**Comment by tmm** [comment]
Related https://github.com/wagmi-dev/wagmi/issues/2724

**Comment by wkyleg** [comment]
Is this still active? I would be happy to take

**Comment by zilayo** [comment]
I tried patching in #2298 which has been working for me

**Comment by HarishPrasannaV** [comment]
Hey, I'm a beginner, and I'd like to contribute. can you please assign me?

**Comment by tmm** [comment]
Check out Wagmi CLI v2's [`getHookName`](https://wagmi.sh/cli/api/plugins/react#gethookname) option.
