### ISSUE TITLE
bug: Next 13.4 and Metamask button Disabled (Server Component and Client Component Issue)

### ISSUE THREAD

**Issue by berkaycirak** [wevm/wagmi#2463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.9

### Current Behavior

I am trying to make a web3 app via Next.js app router. However my metamask button is being always disabled even if it comes ready = true from the client. I have noticed that it is false in the server while coinbase is true but I couldn't understand the point. Also in the browser, it gives me that error even if it comes false from the server.

#Error on the browser

<img width="246" alt="Screenshot 2023-05-30 at 13 29 35" src="https://github.com/wagmi-dev/wagmi/assets/81809211/fb33f36f-59cd-420f-80f3-9ddf047a04e8">

#Server console log of connectors
<img width="631" alt="Screenshot 2023-05-30 at 13 30 43" src="https://github.com/wagmi-dev/wagmi/assets/81809211/8a362f49-7ea8-4e90-958f-a2dce5693e67">

Here is my code

```
"use client";
import React, { useEffect } from "react";
import { useAccount, useConnect } from "wagmi";


const Authentication = () => {
      const { connector: activeConnector, isConnected } = useAccount();
      const { connect, connectors, error, isLoading, pendingConnector } =
            useConnect();

      return (
            <>
                  {/* {isConnected && (
                        <div>Connected to {activeConnector.name}</div>
                  )} */}
                  <div className=" flex flex-col gap-3">
                        {connectors.map((connector) => (
                              <button
                                    className=" bg-red-500 rounded-xl border disabled:bg-black"
                                    disabled={!connector.ready}
                                    key={connector.id}
                                    onClick={() => connect({ connector })}
                              >
                                    {connector.name}
                                    {isLoading &&
                                          pendingConnector?.id ===
                                                connector.id &&
                                          " (connecting)"}
                              </button>
                        ))}
                  </div>

                  {error && <div>{error.message}</div>}
            </>
      );
};

export default Authentication;
```

### Expected Behavior

I expect ready = true and my metamask button is not be disabled on the client

**Comment by tmm** [comment]
This is not a wagmi specific issue. You need to use good SSR hygiene.
