### ISSUE TITLE
bug: Fallback provider not working

### ISSUE THREAD

**Issue by rafinskipg** [wevm/wagmi#2477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.9

### Current Behavior

When configuring a jsonRPCProvider and a publicProvider, in case the jsonRPCProvider fails, it does not fallback to the public provider.

It used to work before the upgrade to wagmi v1.

### Expected Behavior

The publicProvider is used

### Steps To Reproduce

```
 configureChains(
    [mainnet, goerli, localhost],
    [

      jsonRpcProvider({
        
        rpc: chain => {
         // you can ignore this, is just the way we find the RPC config
          const rpc = rpcs.find(i => i.chainId === chain.id);
          return rpc && rpc.url !== ''
            ? {
                http: rpc.url
              }
            : null;
        }
      }),
      publicProvider(),

    ]
```

**Comment by jxom** [comment]
It seems to work on my end (with an invalid Alchemy API key). Can you please provide a minimal reproducible example via https://new.wagmi.sh so we can look into it further?

Will re-open the issue once a reproduction is provided.

**Comment by rafinskipg** [comment]
@jxom idk , but i don't see the public provider working

https://stackblitz.com/edit/new-wagmi-caamxh?file=src%2Fwagmi.ts

**Comment by rafinskipg** [comment]
![image](https://github.com/wagmi-dev/wagmi/assets/1152768/2e90bd6a-316f-468e-921c-ff65ea38150c)

Only publicprovider, no websocket, only metamask connector, no injected connector.

It does not fallback to public provider

**Comment by jxom** [comment]
My bad. I just realised I typed in a malformed Alchemy URL (not a valid URL with an invalid API Key) which it does fall back for. But yeah, right now, we don't fall back for 401s, but I agree that we should (in case a Dapp gets locked out for some reason). Will look into a fix!

To confirm, was a 401 the original error you were seeing that it was not falling back on?

**Comment by rafinskipg** [comment]
yeah @jxom i think it was a 401 or 409 , but i guess any 40X or 500 should resort to fallback, wdyt?

**Comment by jxom** [comment]
i agree

**Comment by aureliusbtc** [comment]
I'm often seeing 429 on pre-flight requests and CORS errors, is this currently not expected to fallback to other configured RPCs?

**Comment by aureliusbtc** [comment]
Following up here, still seeing this as an issue @jxom

**Comment by tmm** [comment]
We have moved on to Wagmi v2. Feel free to re-open this with a minimal reproduction if this still exists there.
