### ISSUE TITLE
bug: [variableName].write() is not a function

### ISSUE THREAD

**Issue by br0wnD3v** [wevm/wagmi#2751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.8

### Current Behavior

I have certain state variables that I am picking up from the user via a form(tokenType, isAbove, targetPrice, dueDate, basePrice) and based on that creating the write handler for a function on for a given contract. 

This is the current scheme of write handler I have created ->
```
  const { config: createPredictionConfig, error: createPredictionWriteError } =
    usePrepareContractWrite({
      address: tradingAddress,
      abi: tradingABI,
      functionName: "createPrediction",
      args: [tokenType, isAbove, targetPrice, dueDate, basePrice],
    });
  const createPredictionWrite = useContractWrite(createPredictionConfig);
  const waitCreatePrediction = useWaitForTransaction({
    hash: createPredictionWrite.data?.hash,
    onSuccess() {
      console.log("Success Market Creation.");
      setCreatedPrediction(true);
    },
  });
```
Now the `createPredictionWrite.write()` runs with the help of a useEffect as ->
```
 useEffect(() => {
    if (startCreation) {
      createPredictionWrite.write();
    }
  }, [startCreation]);
```
The thing that keeps on happening right now is that, on every first load of the web application I get a client side error that 
```createPredictionWrite.write() is not a function.```. 

NOTE : The thing is I have another such write handler but for a usdc approve method and that works like a charm but for some reason the above mentioned always fails on the first load but goes through on the second load with no problem.

Any help is appreciated thank you!

### Expected Behavior

On the first load the `createPredictionWrite.write()` shouldn't stay undefined or unavailable and go through without the client side exception.

**Comment by tmm** [comment]
When you are preparing the contract write, `write` can be undefined.
