### ISSUE TITLE
bug: GetContract does not return Correct contract when chainId is specified

### ISSUE THREAD

**Issue by layinka** [wevm/wagmi#2759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.8

### Current Behavior

If I am connected to a network and try to call a contract instance read method on another network( by passing a different chainid to the currently connected network) , the read method fails.

For example, the code below works if am connected to chain 31337, but if i switch my metamask to chain mainnet and try to call the same method,it fails

```
const contract = getContract({
      address: address as any,
      abi: ABI,
      chainId: 31337
})

const amount = contract.read.name([])
```

### Expected Behavior

The Contract instance should support read methods for any supported chain, by passing the respective chainId. It should use the currently connected chain if chainId is not specified but override the chainId with the chainId passed in if specified

**Comment by layinka** [comment]
I have added a minimal reproducible example here

```
import { mainnet, moonbeam, bsc, polygon, avalancheFuji,sepolia, hardhat } from 'wagmi/chains
import { configureChains, createConfig, WagmiConfig } from 'wagmi'
import { EthereumClient, w3mConnectors, w3mProvider } from '@web3modal/ethereum'
import { getAccount, readContract, getContract,   getPublicClient, getWalletClient, fetchBalance, fetchToken, getNetwork ,switchNetwork, erc20ABI} from '@wagmi/core';
import { Web3Modal } from '@web3modal/html'

const chainsSupported= [mainnet,sepolia,  hardhat]
const projectId = environment.walletConnectProjectId;

const { publicClient  } = configureChains(chainsSupported, [w3mProvider({ projectId: projectId })])

const wagmiClient = createConfig({
  autoConnect: true,
  connectors: [
	...w3mConnectors({ projectId: projectId,  chains: chainsSupported }),
  ],
  publicClient,  
})
const ethereumClient = new EthereumClient(wagmiClient, chainsSupported)

const web3Modal = new Web3Modal({ 
  projectId: projectId,
  themeMode: "light",
  enableNetworkView: true,
  enableExplorer: true,

}, ethereumClient)

const ethToken = '0xdac17f958d2ee523a2206206994597c13d831ec7'
const sToken = '0xf08A50178dfcDe18524640EA6618a1f965821715'

const ethContract = getContract({
      address: ethToken as `0x${string}`,
      abi: erc20ABI,
      chainId: 1
})

const ethName = await ethContract.read.name([])

const sContract = getContract({
      address: sToken as `0x${string}`,
      abi: erc20ABI,
      chainId: 11155111
})

const sName = await sContract.read.name([])

// both sName and ethName should be non-null, regardless of which chain the user is connected to
console.log(sName, ethName)
```

**Comment by tmm** [comment]
A minimal reproduction should only include the code I need to reproduce the bug and be runnable. The code you posted above is not runnable. You can use [new.wagmi.sh](https://new.wagmi.sh) or a GitHub repo. The above code is also not minimal as it includes Web3Modal. Finally, there are no instructions on how Hardhat is set up or info on what viem version you are using.
