### ISSUE TITLE
bug: useContractInfiniteReads paging issue with multicall

### ISSUE THREAD

**Issue by dankelleher** [wevm/wagmi#2863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

The number of results per page was not taking into account the number of calls. As a result, if the number of calls made exceeds the page size, it failed the getNextPageParam check, which made wagmi think there were no more pages.

### Expected Behavior

When a page of 10 is requested, and each request is two calls, 20 results are returned (this works)
If a second page exists, fetchNextPage should return the next page (another twenty calls) (this does not work)

### Steps To Reproduce

```ts
useContractInfiniteReads({
            cacheKey: 'posts',
            ...paginatedIndexesConfig(
                (index: number) => {
                    return [
                        {
                            ...boardContractConfig,
                            functionName: 'getPost',
                            args: [BigInt(index)] as const,
                        },
                        {
                            ...boardContractConfig,
                            functionName: 'getLikesByPostId',
                            args: [BigInt(index)] as const,
                        },
                    ];
                },
                { start: 0, perPage: 10, direction: 'increment' },
            ),
        })
```

This will fail to retrieve posts beyond 0-9

### Anything else?

Fixed by PR #2862

**Comment by tmm** [comment]
Thanks for creating this issue and the associated PR! We changed the way things work in Wagmi v2 so this is no longer an issue.

For folks using Wagmi v1, they can add this updated [`paginatedIndexesConfig`](https://github.com/wevm/wagmi/pull/2862/files#diff-d4aaac6d3c3aa2ce2bf703b1755a53d0c9a0c06aafc82958f3b5d82cc715f066R174-R210) directly to their codebase.
