### ISSUE TITLE
bug: Overriding `AddressType` dosen't work with latest wagmi / viem versions

### ISSUE THREAD

**Issue by technophile-04** [wevm/wagmi#2898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.10

### Current Behavior

Even after  Updating `Config` in `.d.ts` as mentioned in`abitype` docs [here](https://abitype.dev/config#overview) the type are not overriden

In my [abi.d.ts](https://github.com/technophile-04/wagmi-debug/blob/main/src/types/abitype/abi.d.ts) I tried updating `AddressType` for both `viem` and `wagmi` and it's not working, it still setting it as `0x{string}`

![Screenshot 2023-08-15 at 2 07 10 PM](https://github.com/wagmi-dev/wagmi/assets/80153681/3a0ee1b1-9ad0-41ae-8ba0-8fd2b2e9abea)

### Expected Behavior

I think it should work as suggested [here](https://abitype.dev/config#overview)  in `abitype` docs

### Steps To Reproduce

Here is the GitHub repo for testing -> https://github.com/technophile-04/wagmi-debug/tree/main

I just bootstrapped it using [create-wagmi](https://github.com/wagmi-dev/wagmi/tree/main/packages/create-wagmi) and updated `wagmi` and `viem` to their latest versions 

1. Clone the repo and cd
```
git clone https://github.com/technophile-04/wagmi-debug.git && cd wagmi-debug
```

2. Npm Install : 
```
npm install
```

3. Checkout [WriteContract.tsx](https://github.com/technophile-04/wagmi-debug/blob/08a0f88e065549e009358dd7ed63a726fb665c10/src/components/WriteContract.tsx#L10) line 10 with error 

Even thought I have overridden types in [`abi.d.ts`](https://github.com/technophile-04/wagmi-debug/blob/main/src/types/abitype/abi.d.ts)

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/technophile-04/wagmi-debug/

### Anything else?

I have created #2736  but there we have more errors, like after updating `wagmi` and `viem` to latest version for some reason the `typescript` started checking `node_modules/viem/dist/types` 

Just wanted to keep things simple here with minimal-reproducible repo and targeting `AddressType` issue only 

Tysm guys 🙏

**Comment by tmm** [comment]
See https://github.com/wevm/wagmi/pull/2884#issuecomment-1878937077
