### ISSUE TITLE
bug: two useWalletClients on different chains cause infinite loop thrash if using WalletConnectConnector

### ISSUE THREAD

**Issue by shrugs** [wevm/wagmi#2942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

wagmi@1.3.10

### Current Behavior

occurs when connected to WalletConnect v2 connector and two `usePrepareContractWrite` on the same page with different `chainId`s

1. `usePrepareContractWrite` calls `useWalletClient` which establishes a `watchWalletClient` handler
2. WallectConnectConnector#getProvider calls `switchChain()` https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/walletConnect.ts#L190 which calls the `wallet_switchEthereumChain` rpc method https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/walletConnect.ts#L263
3. this method causes the WC Connector to `handleSwitchChain` https://github.com/WalletConnect/walletconnect-monorepo/blob/1d2c0e24ca7a4154abd3b7cf6a1256602eb536ce/providers/universal-provider/src/providers/eip155.ts#L143
4. which calls `setDefaultChain()` which emits a change event https://github.com/WalletConnect/walletconnect-monorepo/blob/1d2c0e24ca7a4154abd3b7cf6a1256602eb536ce/providers/universal-provider/src/providers/eip155.ts#L72 which passes through the `UniversalProvider` https://github.com/WalletConnect/walletconnect-monorepo/blob/1d2c0e24ca7a4154abd3b7cf6a1256602eb536ce/providers/universal-provider/src/UniversalProvider.ts#L465 which re-emits a `chainChanged` event
5. this event is handled by the wagmi config here https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/config.ts#L375
6. which causes a store update and for this handler to run https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/config.ts#L413 and update the state once more. the original `watchWalletClient` sees this change https://github.com/wagmi-dev/wagmi/blob/ce712126eeb7132fe0b063f0b5dcc41a6a181dab/packages/react/src/hooks/viem/useWalletClient.ts#L52
7. this change causes `getWalletClient({ chainId })` to be called https://github.com/wagmi-dev/wagmi/blob/ce712126eeb7132fe0b063f0b5dcc41a6a181dab/packages/core/src/actions/viem/watchWalletClient.ts#L18
8. ... which calls `WallectConnectConnector#getProvider`, starting the process once again

each loop differs only in the chainId it's connected to, alternating between `1` and `8453`

<img width="1315" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/1535001/3b12cf5a-b783-49be-af3e-f5298bc0eb4f">

<img width="1313" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/1535001/d39700b1-d66b-4743-b7ca-f51d7d4aaad3">

### Expected Behavior

no loop lol

### Steps To Reproduce

run demo linked below

while not connected, navigate between pages, no loop

connect to walletconect, and it might just freeze instantly, otherwise navigate between pages to trigger the loop

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/shrugs/wc-loop-repro

**Comment by shrugs** [comment]
if anyone stumbles upon this, my temporary fix was to ensure that one of the calls is conditionally mounted, which seems to solve the issue — in my case the second prepare was in a bridge modal (as part of a minting flow) and i was able to conditionally mount the hook iff the modal was open (though not ideal). note that the `enabled:` config doesn't affect anything because `usePrepareContractWrite`'s `useWalletClient` will always `watchWalletClient`

**Comment by siosio34** [comment]
I'm really sorry, but can you give me a code example? @shrugs

**Comment by shrugs** [comment]
not really, the solution is specific to your app. if you're experiencing this specific problem it's because you have two separate `usePrepareContractWrite` hooks mounted at the same time using different chain ids. this should be supported, but seems to interact poorly with walletconnect's provider, specifically. my solution was to make sure my app only rendered one of them at a time, but i imagine you could also ensure that they two calls use the same chainId and then ignore any errors generated by the hook you don't currently care about. not ideal

**Comment by glitch-txs** [comment]
is this still an issue=

**Comment by siosio34** [comment]
yes @glitch-txs

**Comment by Tura187** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Package Version
> wagmi@1.3.10
> 
> ### Current Behavior
> occurs when connected to WalletConnect v2 connector and two `usePrepareContractWrite` on the same page with different `chainId`s
> 
> 1. `usePrepareContractWrite` calls `useWalletClient` which establishes a `watchWalletClient` handler
> 2. WallectConnectConnector#getProvider calls `switchChain()` https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/walletConnect.ts#L190 which calls the `wallet_switchEthereumChain` rpc method https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/walletConnect.ts#L263
> 3. this method causes the WC Connector to `handleSwitchChain` https://github.com/WalletConnect/walletconnect-monorepo/blob/1d2c0e24ca7a4154abd3b7cf6a1256602eb536ce/providers/universal-provider/src/providers/eip155.ts#L143
> 4. which calls `setDefaultChain()` which emits a change event https://github.com/WalletConnect/walletconnect-monorepo/blob/1d2c0e24ca7a4154abd3b7cf6a1256602eb536ce/providers/universal-provider/src/providers/eip155.ts#L72 which passes through the `UniversalProvider` https://github.com/WalletConnect/walletconnect-monorepo/blob/1d2c0e24ca7a4154abd3b7cf6a1256602eb536ce/providers/universal-provider/src/UniversalProvider.ts#L465 which re-emits a `chainChanged` event
> 5. this event is handled by the wagmi config here https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/config.ts#L375
> 6. which causes a store update and for this handler to run https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/config.ts#L413 and update the state once more. the original `watchWalletClient` sees this change https://github.com/wagmi-dev/wagmi/blob/ce712126eeb7132fe0b063f0b5dcc41a6a181dab/packages/react/src/hooks/viem/useWalletClient.ts#L52
> 7. this change causes `getWalletClient({ chainId })` to be called https://github.com/wagmi-dev/wagmi/blob/ce712126eeb7132fe0b063f0b5dcc41a6a181dab/packages/core/src/actions/viem/watchWalletClient.ts#L18
> 8. ... which calls `WallectConnectConnector#getProvider`, starting the process once again
> 
> each loop differs only in the chainId it's connected to, alternating between `1` and `8453`
> 
> <img alt="image" width="1315" src="https://private-user-images.githubusercontent.com/1535001/262750688-3b12cf5a-b783-49be-af3e-f5298bc0eb4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjEwMzYsIm5iZiI6MTcwNDQyMDczNiwicGF0aCI6Ii8xNTM1MDAxLzI2Mjc1MDY4OC0zYjEyY2Y1YS1iNzgzLTQ5YmUtYWYzZS1mNTI5OGJjMGViNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDIxMjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzM5NDhmNmIzNjc0ZTkzMzZkZjgwYjc1ODg3YTgxYjU3NWE2MDExMDJkZDg1MjIyODRiMWNkNTUwMDM4NmI0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hD5tHKFfmnCjoSjS6bwpzm3qofyzXzIIzsLGkZuNaYo"> <img alt="image" width="1313" src="https://private-user-images.githubusercontent.com/1535001/262747547-d39700b1-d66b-4743-b7ca-f51d7d4aaad3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjEwMzYsIm5iZiI6MTcwNDQyMDczNiwicGF0aCI6Ii8xNTM1MDAxLzI2Mjc0NzU0Ny1kMzk3MDBiMS1kNjZiLTQ3NDMtYjdjYS1mNTFkN2Q0YWFhZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDIxMjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDNiZDQ1NDFmYTgzMGMwN2RkNGY0OTE5Mzc4MDY2MDFjMDg2NmQyOTU2MjRlMmVmODNlYTdmNjk0NThmNDljOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bGzKfd6fnXfjg5wU7-Kqs18uygyVfpMjDqb9bI8vQNs">
> ### Expected Behavior
> no loop lol
> 
> ### Steps To Reproduce
> run demo linked below
> 
> while not connected, navigate between pages, no loop
> 
> connect to walletconect, and it might just freeze instantly, otherwise navigate between pages to trigger the loop
> 
> ### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)
> https://github.com/shrugs/wc-loop-repro
> 
> ### Anything else?
> _No response_

Cancel jobs

**Comment by Tura187** [comment]
Cancel jobs

**Comment by tmm** [comment]
We have moved on to Wagmi v2. Feel free to re-open this with a minimal reproduction if this still exists there.
