### ISSUE TITLE
bug: `useWalletClient` hook returns the client object after disconnecting in next.js apps

### ISSUE THREAD

**Issue by mmv08** [wevm/wagmi#2969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^1.0.6

### Current Behavior

Using `useWalletClient` hook, it returns the wallet client object even after the user disconnected the wallet

### Expected Behavior

It would return null

### Steps To Reproduce

The minimal reproducible example can be found at https://github.com/mmv08/wagmi-nextjs-bug

The project was bootstrapped with `npm init wagmi` with `Next.js` and `RainbowKit` selected. After the project creation, I updated viem to the latest version (1.9.5 at the moment of writing) and added a console log of the `useWalletClient()` return value: https://github.com/mmv08/wagmi-nextjs-bug/blob/main/src/components/ConnectButton.tsx

I could also reproduce it with next.js and web3modal, so it doesn't seem specific to the wallet connection library. I couldn't reproduce it with a Vite app.

Steps to reproduce:
1. `git clone https://github.com/mmv08/wagmi-nextjs-bug.git`
2. `npm i && npm run dev`
3. Open the console and observe the logged return value
4. Connect the wallet, and see that a client is now returned
5. Disconnect the wallet, and observe the client is still returned

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/mmv08/wagmi-nextjs-bug

**Comment by 1997roylee** [comment]
Because your wallet extension still connecting the website.

**Comment by stefanofa** [comment]
Any news on this issue? Is this considered a bug or is it the intended way of working?
cc: @tmm @jxom

**Comment by tmm** [comment]
Seems like a bug, but haven't looked into it yet. We are working on [Wagmi v2](https://github.com/wagmi-dev/wagmi/discussions/3068), which doesn't have this issue.

**Comment by BerkliumBirb** [comment]
It doesn't disconnect even in simple react applications.

Have to check useAccount()#isConnected to "hide" walletClient

**Comment by tmm** [comment]
Fixed by Wagmi v2
