### ISSUE TITLE
bug: `useWalletClient` returns incorrect chainId

### ISSUE THREAD

**Issue by mmv08** [wevm/wagmi#2991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.1

### Current Behavior

The `useWalletClient` hook returns an incorrect chain id in `client.chain` object. It always returns 1, no matter which chain the wallet is connected to

### Expected Behavior

The wallet client object contains the wallet's currently connected chain 

### Steps To Reproduce

```
  const { data: walletClient } = useWalletClient();
  
  console.log(walletClient?.chain?.id)
```

Minimal reproducible example is available below

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-lp8bpf?file=src%2FApp.tsx

### Anything else?

![Screenshot 2023-09-09 at 18 47 15](https://github.com/wagmi-dev/wagmi/assets/16622558/a0c55f3a-2d1d-4272-8823-2639aad89eff)

**Comment by imaksp** [comment]
it seems it is returning public client chain id & it does not even update on chain change, 
& chain for useNetwork hook gets updated properly.

**Comment by salzbrenner** [comment]
@mmv08 I forked your example, updated the wagmi config so there's 2 chains https://stackblitz.com/edit/new-wagmi-m1ryz3?file=src%2Fwagmi.ts. What's the issue? I see the chain id being updated correctly

**Comment by mmv08** [comment]
> @mmv08 I forked your example, updated the wagmi config so there's 2 chains https://stackblitz.com/edit/new-wagmi-m1ryz3?file=src%2Fwagmi.ts. What's the issue? I see the chain id being updated correctly

Hey, I believe that doesn't solve my issue, as it still doesn't return the wallet's chain ID. In my application, I can't make assumptions about which chains the user will be connected to and, therefore have them in the config.

**Comment by salzbrenner** [comment]
> > @mmv08 I forked your example, updated the wagmi config so there's 2 chains https://stackblitz.com/edit/new-wagmi-m1ryz3?file=src%2Fwagmi.ts. What's the issue? I see the chain id being updated correctly
> 
> Hey, I believe that doesn't solve my issue, as it still doesn't return the wallet's chain ID. In my application, I can't make assumptions about which chains the user will be connected to and, therefore, have them in the config.

Got it, I misunderstood the original issue. The walletClient, at least with wagmi, seems tied to the publicClient and/or configured chains, so what you describe is the expected behavior, from the source code anyway. I can see how having walletClient always reflect current network being more transparent. But the current behavior ties wallet actions to the chains configured, which seems beneficial. I'm not educated enough to know which is the better behavior

Does useNetwork not meet your needs for this case?

**Comment by zeeshanhanif** [comment]
I'm also facing the same issue, walletClient provided by useWalletClient alwasy have chainid 1

**Comment by siosio34** [comment]
I think this issue https://github.com/MetaMask/metamask-mobile/issues/7206 is also related to this issue. There is a video attached to this issue, but it is even reproduced exactly on the wagmi example page.

**Comment by tmm** [comment]
We have moved on to Wagmi v2. Feel free to re-open this with a minimal reproduction if this still exists there.
