### ISSUE TITLE
Safe Wallet and Wallet Connect Not Working With Multiple Chains Configured 

### ISSUE THREAD

**Issue by murtrax** [wevm/wagmi#3027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.2

### Current Behavior

I have a numerous list of chains that I have configured with my Wagmi below. If I wish to connect to Goerli via wallet connect through gnosis safe wallet. If goerli is not the first chain in the list, wallet connect will not form a connection to the safe app. 

Instead giving the following error

Error: Connection refused: This Safe Account is in Goerli but the Wallet Connect session proposal is not valid because it contains: 1) A required chain different than Goerli 2) Does not include Goerli between the optional chains 3) No EVM compatible chain is included

  [
    mainnetConfig,
    goerli,
    arbitrum,
    arbitrumGoerli,
    avalanche,
    bsc,
    bscTestnet,
    fantom,
    polygon,
    sepolia,
    cronos,
    etc,
    etcTestnet,
    heco,
    kava,
    kavaTestnet,
    pulseChain,
    velas,
    baseMainnet,
  ]
  
   new WalletConnectConnector({
      chains,
      options: {
        showQrModal: true,
        projectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_KEY,
      },
    }),
    
Error in my localhost env 

![Screenshot 2023-09-20 at 6 31 56 PM](https://github.com/wagmi-dev/wagmi/assets/44900656/ae3df9f3-50a7-45d8-8c3c-22ef4cd56b75)

![Screenshot 2023-09-20 at 6 32 09 PM](https://github.com/wagmi-dev/wagmi/assets/44900656/56948f21-4f1c-4ba6-ab02-e132820ecbf9)

Error in Safe App Console Log

![Screenshot 2023-09-20 at 6 31 51 PM](https://github.com/wagmi-dev/wagmi/assets/44900656/f3ba28f0-d06b-44da-8c65-9cd49fa42d70)

### Expected Behavior

It should work with wallet connect connecting to safe, no matter how many chains are configured within my Wagmi Config and irrelevant of the order. Have seen similar posts to this, but none of them detail a true solution. Any info or solution on this would be greatly greatly appreciated.

**Comment by oxSaturn** [comment]
A similar issue reported before https://github.com/wagmi-dev/references/issues/469, and a fix for that https://github.com/wagmi-dev/references/pull/470

**Comment by jacob-abe** [comment]
@oxSaturn How I worked against this is, we have multiple chains on our app. But the chain is dependent on the slug in our case. So depending on the slug, I set the a single chain in the chains in the wagmi config for the walletconnect connector. Feels like this needs some attention as its being complained about in multiple places!

**Comment by dzek69** [comment]
@oxSaturn the fix got rejected.

A lot of wallets seems to be affected, from what I know this issue is causing Trust Wallet and Ledger to not connect to any network that is not first on the list of chains passed to `WalletConnectConnector`.

I'm thinking about any workaround, but I see none, except asking user to select the network first in my app UI and then use the wallet with correct network selected when connecting

if anyone has a solution or even workaround that'd be great

**Comment by meri-maki** [comment]
+1 Seeing the same behavior with UniSwap wallet as well
