### ISSUE TITLE
bug: write?.() from useContractWrite doesn't ask to redirect to wallet app

### ISSUE THREAD

**Issue by meri-maki** [wevm/wagmi#3211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.6

### Current Behavior

I have a production project on react with build made 2 weeks ago
I'm using wagmi hooks and web3modal for connection and mint (```useContractWrite```)

Few days ago we wanted to have a small update to the website, but after the new build was made, the automatic redirection to wallet app on mobile stopped working (click on button with ```write?.()```)
this redirection:
![IMG_4503](https://github.com/wagmi-dev/wagmi/assets/97887955/14f23998-0b01-4836-8387-7cc667d4fa25)

It's really strange because even if I copy working branch and make new build - it stops working correctly

I've tried: removing all logic and reproducing super minimal version, updating all packages to the newest, downgrading again
ONLY the files from old build works

I have a test project that is similar to my prod
This version is updated, with new build and the redirection doesn't work --->  https://wagmi-read-non-working.vercel.app/
This version is old, with old build and same logic and here is works ---> https://wagmi-read.vercel.app/

### Expected Behavior

```write()``` should cause a popup with 'redirect' options
and it worked fine until recently

i'm not sure if it's wagmi issue or something with WalletConnect

I would really appreciate an advice bc I've been trying to fix this for 3 days now....

The repo is https://github.com/meri-maki/useSwitchNetwork/blob/main/src/MintNFT/MintNFT.jsx
It stopped working after this commit https://github.com/meri-maki/useSwitchNetwork/commit/cee536cc69ccb8d42bafb6788cc10ff875588927#diff-1df931291a82be390da0d0fd4b7c8a3ee13e2b122aa1f124eb8ddde995b1168f

### Steps To Reproduce

On mobile, IOS preferably
To see the **Expected** behavior:
1. open https://wagmi-read.vercel.app/
2. with WalletConnect connect ZERION or TRUST wallet
3. Click on Mint
4. See pop up "Open in "Zerion"?"

To see the **Current** behavior:
1. open https://wagmi-read-non-working.vercel.app/
2. repeat steps from above and there won't be any popup

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/meri-maki/useSwitchNetwork/

### Anything else?

**IMPORTANT NOTE**: ```write()``` works, I can see the notification in my wallet

**Comment by glitch-txs** [comment]
can you make the example *minimal*? I'm not able to reproduce it

**Comment by meri-maki** [comment]
@glitch-txs hi! which one you are not able to reproduce?

**Comment by meri-maki** [comment]
@glitch-txs i minimized the non-working example at https://wagmi-read-non-working.vercel.app/
After authorization with zerion/trust, the click on Mint doesn't redirect to app even though the transaction appears in the app

**Comment by glitch-txs** [comment]
thanks! could you share the repo?

**Comment by meri-maki** [comment]
yep https://github.com/meri-maki/useSwitchNetwork/
last commit here
please let me know if there is anything more i can do to resolve this

**Comment by meri-maki** [comment]
..any news?..

**Comment by meri-maki** [comment]
**UPD**: forcefully downgrading to ```"viem": "1.17.2",``` brought the redirection back

**Comment by meri-maki** [comment]
Hi team! Any news? Will this be fixed in newer versions?

**Comment by htadeusiak** [comment]
I'm running into a similar if not same issue where useSignMessage does not redirect to MM onClick.

@meri-maki both your "read" and "non working read" both do not open the redirect "Open in blank" for me on mobile IOS. Is the read version working for you?

Downgrading did now work in my case.

**Comment by meri-maki** [comment]
@htadeusiak thank you for pointing out that the examples do not work (it worked though)
The reason might be that vercel builds project on server while in my production project it's build locally

However the issue remains and I hope we will get a fix
The older version is a temporary fix, and I would love to use newer viem but if redirect is not fixed I would need to build additional UI so the user is not lost

**Comment by alienzhangyw** [comment]
Same problem with MetaMask since it upgraded a new version in July. User has to manually switch to wallet app and switch back to browser after signed.

**Comment by remibeaufils** [comment]
> @htadeusiak thank you for pointing out that the examples do not work (it worked though) The reason might be that vercel builds project on server while in my production project it's build locally
> 
> However the issue remains and I hope we will get a fix The older version is a temporary fix, and I would love to use newer viem but if redirect is not fixed I would need to build additional UI so the user is not lost


@meri-maki could you kindly tell me with which older versions this works for you?

I also have the problem, using these versions:
```json
"@web3modal/wagmi": "3.3.2", "viem": "1.19.1", "wagmi": "1.4.6",
```

I tried using following older versions and the redirect doesn't work either:
```json
"@web3modal/wagmi": "3.1.0", "viem": "1.17.2", "wagmi": "1.4.5",
```

**Comment by tmm** [comment]
This is likely an upstream issue. Check out Wagmi v2 to see if it's still present.
