### ISSUE TITLE
bug: Invalid option in build() call: "watch"

### ISSUE THREAD

**Issue by saymon-develop** [wevm/wagmi#3230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.5.2

### Current Behavior

Can't generate types and hooks from ABIs using `npx wagmi generate` .

Just throw error:
```
[ERROR] Invalid option in build() call: "watch"

/home/projects/vitejs-vite-ljvjfz/node_modules/esbuild/lib/main.js:245:12:
    throw new Error(`Invalid option ${where}: ${quote(key)}`);
```

### Expected Behavior

Types and hooks generated without errors.

### Steps To Reproduce

- Bootstrap new project using [vite 5](https://vitejs.dev/blog/announcing-vite5) and [react-ts](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-react-ts) template `npm create vite@latest reproduce-error-app -- --template react-ts`.
- Add [wagmi](https://wagmi.sh/) deps `npm i wagmi viem`.
- Add [wagmi/cli](https://wagmi.sh/cli/getting-started) dev deps `npm i --save-dev @wagmi/cli`.
- Define minimal **wagmi.config.ts** file using `npx wagmi init` command.
- provide prebundled `erc20ABI` contract from _wagmi_ and `react` plugin from _@wagmi/cli/plugins_.
- Try to generate using `npx wagmi generate` command from [docs](https://wagmi.sh/cli/getting-started).

Or you can use [Link to stackblitz](https://stackblitz.com/edit/vitejs-vite-ljvjfz?file=wagmi.config.ts) which is same as steps below (just last step need to do for reproducing).

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/vitejs-vite-ljvjfz?file=wagmi.config.ts

### Anything else?

When try generate out of Vite environment all work fine. 
It looks like error with higher `esbuild` version in Vite.

**Comment by mathieu-bour** [comment]
I had the same issue and after manually installing this specific version of esbuild, the generation worked.

```
npm i -D esbuild@0.16
```

**Comment by saymon-develop** [comment]
> I had the same issue and after manually installing this specific version of esbuild, the generation worked.
> 
> ```
> npm i -D esbuild@0.16
> ```

Look's like resolution, work for me)
Thanks 🤝
