### ISSUE TITLE
bug: useWaitForTransaction returns TransactionNotFoundError: Transaction with hash `` could not be found.

### ISSUE THREAD

**Issue by zewebdev1337** [wevm/wagmi#3241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.7

### Current Behavior

when calling useWaitForTransaction, shortly before the txn is confirmed by metamask, the component logs an error saying the transaction at hash X could not be found
Further, its isSuccess value will not change after the txn is confirmed.

The hook seems to be mishandling some value once the txn is actually confirmed which causes it to report the txn was not found and leaving isSuccess stuck in false given that the message always pops up instants before metamasks shows a confirmation. 

### Expected Behavior

isSuccess should change to true once the txn is mined successfully and no errors should be logged

### Steps To Reproduce

Set up a simple contract write project using https://wagmi.sh/examples/contract-write
Mint an NFT and watch the terminal.
Error pops up a few seconds before txn is confirmed on metamask.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/~/github.com/zewebdev1337/wagmi-useWaitForTransaction-TransactionNotFoundError-repro

### Anything else?

Chromium 119 on archlinux, Metamask
dApp: Preact TS on Vite but also reproducible in new.wagmi.sh
wagmi: 1.4.7
viem: 1.19.8

**Comment by Tura187** [comment]
My coinbase keeps resetting

**Comment by Yuripetusko** [comment]
Getting this quite consistently on Base too. Tried 3 different rpc providers. Doing a manual CURL few minutes later, returnes result just fine. I think either `retryCount` or `delay` should be configurable by user in viem's `waitForTransactionReceipt`

**Comment by firnprotocol** [comment]
i have gotten this before too on mainnet, but only sporadically. it is very hard to reproduce.

btw, this seems to be the same:
- https://github.com/wevm/wagmi/issues/2799
- https://github.com/wevm/wagmi/issues/3152

**Comment by tmm** [comment]
We have moved on to Wagmi v2. Feel free to re-open this with a minimal reproduction if this still exists there.

**Comment by Yuripetusko** [comment]
> i have gotten this before too on mainnet, but only sporadically. it is very hard to reproduce.
> 
> btw, this seems to be the same:
> 
> * [TransactionNotFoundError: Transaction with hash "0x00...." could not be found. #2799](https://github.com/wevm/wagmi/issues/2799)
> * [frequent "transactionNotFoundError" #3152](https://github.com/wevm/wagmi/issues/3152)

Indeed, it is hard to reproduce. I updated to wagmi/viem 2.0.x now, so will keep an eye, but it happens more often on Base for some reason, maybe something to do with the opstack and how it reports confirmations 🤷  but hard to tell. If it happens again, i'll report here, but I doubt that reproducable example will be possible, as I haven't been able to notice any pattern behind it, besides it happening on Base more often
