### ISSUE TITLE
bug: publicClient.call required data param

### ISSUE THREAD

**Issue by y1feng200156** [wevm/wagmi#3243]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

1.4.7

### Current Behavior

https://github.com/wagmi-dev/wagmi/blob/dc893d1e108667893ff2e588f876e2fae5017c29/packages/core/src/actions/transactions/waitForTransaction.ts#L51

The call method on line 51 should take `txn.input` as the `data` parameter, otherwise the exception will be UNKNOWN REASON.

```javascript
if (receipt.status === 'reverted') {
  const txn = await publicClient.getTransaction({
    hash: receipt.transactionHash,
  })
  const code = (await publicClient.call({
    ...txn,
    gasPrice: txn.type !== 'eip1559' ? txn.gasPrice : undefined,
    maxFeePerGas: txn.type === 'eip1559' ? txn.maxFeePerGas : undefined,
    maxPriorityFeePerGas:
      txn.type === 'eip1559' ? txn.maxPriorityFeePerGas : undefined,
  } as CallParameters)) as unknown as string
  const reason = hexToString(`0x${code.substring(138)}`)
  throw new Error(reason)
}
```

### Expected Behavior

https://github.com/wagmi-dev/wagmi/blob/dc893d1e108667893ff2e588f876e2fae5017c29/packages/core/src/actions/transactions/waitForTransaction.ts#L52

Add `data: tnx.input` after line 52.

```javascript
if (receipt.status === 'reverted') {
  const txn = await publicClient.getTransaction({
    hash: receipt.transactionHash,
  })
  const code = (await publicClient.call({
    ...txn,
    data: txn.input,
    gasPrice: txn.type !== 'eip1559' ? txn.gasPrice : undefined,
    maxFeePerGas: txn.type === 'eip1559' ? txn.maxFeePerGas : undefined,
    maxPriorityFeePerGas:
      txn.type === 'eip1559' ? txn.maxPriorityFeePerGas : undefined,
  } as CallParameters)) as unknown as string
  const reason = hexToString(`0x${code.substring(138)}`)
  throw new Error(reason)
}
```

### Steps To Reproduce

none

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

[Missing data attribute](https://stackblitz.com/edit/wagmi-dev-viem-nmtbdo?file=index.ts)

Please open the browse console, you can see `Uncaught CallExecutionError: Execution reverted for an unknown reason`.

Adding `data: tnx.input` to this will give you the correct exception message, `Uncaught CallExecutionError: Execution reverted with reason: price was expired.`

[Has data attribute](https://stackblitz.com/edit/wagmi-dev-viem-78m66x?file=index.ts)

### Anything else?

none

**Comment by tmm** [comment]
We have moved on to Wagmi v2. Wagmi v2 passes along all parameters to Viem. Feel free to re-open this with a minimal reproduction if this still exists there.
