### ISSUE TITLE
bug: Cannot access array mapping data on clientside dApp

### ISSUE THREAD

**Issue by REPTILEHAUS** [wevm/wagmi#3245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.1

### Current Behavior

It outputs nothing at all

### Expected Behavior

It should output the value under the array mapping of the given user address

### Steps To Reproduce

Not sure if this is related to this [issue](https://github.com/wevm/wagmi/discussions/2866) or not but i am trying to access data from an array mapping and getting no results, i had to revert back to EthersJS to get access to it.

```
      const params = {
        address: this.raffleContract,
        abi: [ {
          "inputs": [],
          "name": "myTickets",
          "outputs": [
            {
              "internalType": "uint256[]",
              "name": "",
              "type": "uint256[]"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        }],
        functionName: 'myTickets',
        args: [],
        watch: true
      }
      const tickets: any = await readContract(params)    
      
      console.log(`ticket ${JSON.stringify(tickets)} ${tickets.length} ${this.activeSignerAddress} `)  
```

the contract looks like this

```
contract Competition is Ownable {
    
    mapping(address => uint256[]) public userTickets;

    function myTickets() public view returns (uint256[] memory) {
        return userTickets[msg.sender];
    }

```

When i check it in Remix (also ethers) I can see the users Tickets at that given address but using Wagmi I get nothing 

Im using Wagmi Core 1.4.1 with Angular 16

### Anything else?

No everything is explained above.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
