### ISSUE TITLE
bug: useSendTransaction error "Cannot read properties of undefined (reading 'symbol')"

### ISSUE THREAD

**Issue by meri-maki** [wevm/wagmi#3246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.5

### Current Behavior

When sending transaction and then canceling it in the wallet app
The useSendTransaction hook returns this error:
```Cannot read properties of undefined (reading 'symbol')```

![Снимок экрана 2023-11-26 в 16 55 14](https://github.com/wevm/wagmi/assets/97887955/de442787-a709-48b9-b259-34837cc16d8c)

### Expected Behavior

I use contractWrite in my app as well and when I cancel transaction I usually get this error:

![Снимок экрана 2023-11-26 в 16 54 26](https://github.com/wevm/wagmi/assets/97887955/c3f77e83-d0b9-4353-96dc-1da03d356826)

### Steps To Reproduce

Open stackblitz
Connect with walletConnect or Metamask injected
Click Send Transaction button
Reject transaction
Get error

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-4scqzy?file=src%2FApp.tsx

### Anything else?

Thought the issue was with goerli, so tried with mainnet - same thing

**Comment by meri-maki** [comment]
..any news?

**Comment by Luykin** [comment]
I have the same question

**Comment by tmm** [comment]
We have moved on to Wagmi v2. Feel free to re-open this with a minimal reproduction if this still exists there.
