### ISSUE TITLE
bug: v2 reports - injected error - peerDependency missing in Core

### ISSUE THREAD

**Issue by glitch-txs** [wevm/wagmi#3253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

    "@wagmi/connectors": "4.0.0-beta.5",     "@wagmi/core": "2.0.0-beta.5",     "viem": "2.0.0-beta.6"

### Current Behavior

- [ ] On page load getting this error, since @tanstack/query-core is a peer dependency but not installed (following docs)
![image](https://github.com/wevm/wagmi/assets/66949816/3ab237b6-ccd8-492c-adac-e2d33a347b6d)

- [ ] When using target in injected params it doesn't work, it works without params though

This doesn't work:
```ts
await connect(config, { connector: injected({ target(){ return window.ethereum } }) })
```

This works:
```ts
await connect(config, { connector: injected() })
```

### Steps To Reproduce

I've added "@tanstack/query-core": "^5.8.7", as dependency to avoid the first error.

Press connect while having a browser extension wallet installed. When target is set it will throw an error otherwise it will request the connection.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/glitch-txs/v2-mre/blob/main/src/main.ts

**Comment by tmm** [comment]
>  On page load getting this error, since @tanstack/query-core is a peer dependency but not installed (following docs)

Fixed the `@tanstack/query-core` error via `@wagmi/core@2.0.0-beta.7`. You shouldn't need to install it, unless you are using the `@wagmi/core/query` entrypoint moving forward.

> When using target in injected params it doesn't work, it works without params though

The API for `target` is a little different (docs were incorrect so [I updated them](https://beta.wagmi.sh/core/api/connectors/injected#target)).

```diff
const result = await connect(config, {
  connector: injected({
    target() {
-    return window.ethereum
+    return {
+      id: 'windowProvider',
+      name: 'Window Provider',
+      provider: window.ethereum,
+   },
  }),
})

```
