### ISSUE TITLE
bug: wagmi says account is connected when metamask is locked

### ISSUE THREAD

**Issue by elboletaire** [wevm/wagmi#3256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.6

### Current Behavior

Looks like a regression of #444 (changing the methods with the current ones in version 1.x ofc).

### Expected Behavior

To not have a connected status if metamask is locked, or show the metamask prompt to the user so they know it's currently locked and they need to unlock.

### Steps To Reproduce

- Go to https://wagmi.sh/examples/connect-wallet and connect using metamask
- Restart your browser
- Accessing the connect page again will show your wallet connected, but no network available (since metamask is locked).
- If you navigate to a page where a transaction can be done, everything is just disabled, and metamask does not prompt asking for password.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/examples/connect-wallet

### Anything else?

This is how it looks when metamask is locked:
![imatge](https://github.com/wevm/wagmi/assets/153305/b5133d88-d019-44ac-8826-e45e1155f363)

**Comment by tmm** [comment]
Fixed in Wagmi v2 https://github.com/wevm/wagmi/issues/3080#issuecomment-1761972262

**Comment by elboletaire** [comment]
Considering version 2 is not yet published and it'll be breaking, wouldn't you release a fix for version 1...?

**Comment by elboletaire** [comment]
or at least a workaround @tmm ?
