### ISSUE TITLE
bug: switchNetwork wrong trigger for MetaMask connector

### ISSUE THREAD

**Issue by BeycanDeveloper** [wevm/wagmi#3264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.7

### Current Behavior

I've created this before in the web3modal and viem repos but it rejected the issue on both sides. Therefore, when I downloaded all the packages one by one and checked the code, I finally found that this was caused by wagmi. It is launched from the line whose link I left below. But it is something that should not happen.

https://vscode.dev/github/wevm/wagmi/blob/main/packages/connectors/src/injected.ts#L271

### Expected Behavior

When I send a request directly to the MetaMask "ethereum" object with the "wallet_switchEthereumChain" method and it waits for my response via MetaMask. A correct response is returned depending on whether I cancel or accept.

However, as you can see on Codesanbox, after sending a network change request to MetaMask once and rejecting it, the console returns the answers whose pictures I shared, without waiting for your response on a second network change request.

Therefore, this should not happen and it should wait for us to accept or reject it.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/devbox/elegant-ardinghelli-n53nwj?file=%2Fsrc%2Findex.mjs%3A18%2C10

### Anything else?

If you use the network switching feature during the connection process and reject the network switching instead of accepting it, everything will work fine at first.

However, when you try the connection for the second time, the network switching screen appears, but w3m does not wait for the response from the wallet and terminates the process by giving the warning in the picture below.

![image](https://github.com/wevm/wagmi/assets/50718965/690351bb-6b4f-477b-a4fb-ac0a578dedb7)

When you press connect for the first time and reject it on the change screen, it will be written to the console as "Error". When you press connect for the second time, before you do anything, a warning will appear as shown in the picture below. Therefore, from now on, no action will be taken by the user whether you approve or reject it. Because it has already been received as rejection.

![image](https://github.com/wevm/wagmi/assets/50718965/394a2951-471e-42b8-90f1-14434a45323a)

List of related npm package versions
"@wagmi/core": "^1.4.7"
"@web3modal/wagmi": "^3.3.2"
"viem": "^1.19.9"

**Comment by tmm** [comment]
Seems like this is a valid error from MetaMask. Please create a minimal example that uses Wagmi without other connect wallet libraries and I'm happy to take a look.
