### ISSUE TITLE
issue: <Hooks generated by the CLI are not testable in as they do not inherit the WagmiConfig from the custom RenderHook function (per usePrepareContractWrite.test.ts)>

### ISSUE THREAD

**Issue by hardingjam** [wevm/wagmi#3288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^1.0.6

### Current Behavior

Having reproduced the the testing environment from [usePrepareContractWrite.test.ts](https://github.com/wevm/wagmi/blob/main/packages/react/src/hooks/contracts/usePrepareContractWrite.test.ts), I am trying to test a wrapper hook that wraps a generatedFromAbiPrepareContractWrite function from wagmi/cli.  

I use the same custom renderHook as in wagmi's tests, which wraps the renderHook in a WagmiConfig provider. However when I try to mount my wrapper hook, i see the following error:

```

FAIL  lib/useCreate.test.tsx > useCreate > mounts
Error: `useConfig` must be used within `WagmiConfig`.

Read more: https://wagmi.sh/react/WagmiConfig
 ❯ useConfig node_modules/wagmi/dist/index.js:75:11
 ❯ useNetwork node_modules/wagmi/dist/index.js:841:18
 ❯ Module.usePrepareContractWrite node_modules/wagmi/dist/index.js:1825:34
 ❯ Module.generatedFromAbiPrepareContractWrite lib/generated.ts:5417:12
    5415|     > & { chainId?: keyof typeof address } = {} as any
    5416| ) {
    5417|     return usePrepareContractWrite({
       |            ^
    5418|         abi: myABI,
    5419|         address: myAddress[5],
 ❯ Module.useCreate lib/useCreate.ts:94:9
 ❯ lib/useCreate.test.tsx:40:13
 ❯ TestComponent node_modules/@testing-library/react/dist/pure.js:283:27
 ❯ renderWithHooks node_modules/react-dom/cjs/react-dom.development.js:16305:18
 ❯ mountIndeterminateComponent node_modules/react-dom/cjs/react-dom.development.js:20074:13
 ❯ beginWork node_modules/react-dom/cjs/react-dom.development.js:21587:16

```

### Expected Behavior

Wrapper hooks/CLI generated hooks which utlise wagmi/react hooks should be mountable using the custom renderHook function.

**Comment by tmm** [comment]
Not sure how you have your test suite set up, but `` `useConfig` must be used within `WagmiConfig` `` is a valid error. Make sure you wrap your test render function in `WagmiConfig`.
