### ISSUE TITLE
bug: Legacy octal escape is not permitted in strict mode

### ISSUE THREAD

**Issue by chybisov** [wevm/wagmi#3289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0-beta.5

### Current Behavior

<img width="759" alt="image" src="https://github.com/wevm/wagmi/assets/18644653/3f08c557-223f-4844-8c14-30a197a46913">

When we try to use `wagmi` with Next.js 14 we see `Legacy octal escape is not permitted in strict mode` error coming from `qrcode-terminal` dependency in `@metamask/sdk`. 
The thing is, we don't even use metaMask connector, but somehow because it is exported with other connectors via barrel file, it looks like tree-shaking doesn't work correctly to eliminate that import.

Please see this issue https://github.com/vercel/next.js/issues/12557

### Expected Behavior

1) Ask MetaMask to copy `qrcode-terminal` code and update the code internally. It's an outdated dependency without any hope of being updated.

2) Allow direct import of connectors from @wagmi/connectors like `import { safe } from '@wagmi/connectors/safe'`. It would be best at least to release a fix for this until MM resolution.

3) There is no hope of being fixed on the Next.js level as that issue is 3 years old.

### Steps To Reproduce

Try to use wagmi v2 in Next.js 14.

Run example https://github.com/lifinance/widget/tree/main/examples/nextjs14

**Comment by chybisov** [comment]
@tmm thank you, I'll give it a try for our internal use. Unfortunately this won't work for our widget npm package so hope for a more robust solution 🙂

**Comment by tmm** [comment]
[`wagmi@2.0.0-beta.6`](https://www.npmjs.com/package/wagmi/v/2.0.0-beta.6) fixes the octal issue and works with tree-shaking. Let me know if anything else comes up!

**Comment by chybisov** [comment]
@tmm works perfectly! Thank you 🙂
