### ISSUE TITLE
bug: autoConnect (still) broken

### ISSUE THREAD

**Issue by ashconnell** [wevm/wagmi#3306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.11

### Current Behavior

If you follow the [Getting Started](https://wagmi.sh/react/getting-started) guide exactly, it sets `autoConnect: true` but since its not configured properly, autoConnect doesn't actually work. This is confusing to new developers who are likely to expect that they remain connected after refreshing the page.

[This issue](https://github.com/wevm/wagmi/issues/2511) was closed and locked down without any resolution, fix or comment from maintainers, even after many people expressed a reproducible problem.

### Expected Behavior

Either:

A) Setting `autoConnect: true` works as expected, refreshing the page maintains connections, or
B) Enhancing the docs with the recommended way to get autoConnect working.

**Comment by tmm** [comment]
Feel free to update the docs. I commented on the original thread [here](https://github.com/wevm/wagmi/issues/2511#issuecomment-1594827274).

Wagmi v2 "fixes" this by removing reconnection for core so it must be explicitly called whereas the React reconnection behavior hooks into React's lifecycle.
