### ISSUE TITLE
bug: TransactionExecutionError when wallet extension opens on a new tab

### ISSUE THREAD

**Issue by GFialho** [wevm/wagmi#3308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.3

### Current Behavior

I am using wagmi with coinbase. When I am on full screen mode and I run `sendTransaction`, coinbase wallet opens on a new tab with the url "chrome-extension://hnfanknoc...." and wagmi throws an error: 
"TransactionExecutionError: User rejected the request."

Even though I didn't click to cancel

This is the code:

`            const walletClient = await getWalletClient({ chainId});
            txHash = await walletClient.sendTransaction(tx);
`

**Comment by tmm** [comment]
Probably best to [create an issue upstream](https://github.com/coinbase/coinbase-wallet-sdk) with a minimal reproducible example.
