### ISSUE TITLE
bug: `getWalletClient` returns `null` with `SafeConnector` and web3modal

### ISSUE THREAD

**Issue by microHoffman** [wevm/wagmi#3312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.12

### Current Behavior

I've tried to connect my Safe via Safe Apps using the `SafeConnector`. I'm also using `web3modal` (version 3.4.0). Unfortunately when I try to connect my Safe using `SafeConnector`, the `getWalletClient` returns `null`. Other connectors works fine.

This is my init of config and web3 modal:
```ts
    const wagmiConfig = createConfig({
      autoConnect: true,
      connectors: [
        new WalletConnectConnector({ chains, options: { projectId, showQrModal: false, metadata } }),
        new InjectedConnector({ chains, options: { shimDisconnect: true } }),
        new CoinbaseWalletConnector({ chains, options: { appName: metadata.name } }),
        new SafeConnector({
          chains,
          options: {
            allowedDomains: [/gnosis-safe.io$/, /app.safe.global$/, /cronos-safe.org$/, /multisig.mantle.xyz$/],
            debug: true,
          },
        }),
      ],
      publicClient,
      webSocketPublicClient,
    })

    const connectedChainInWagmiType = computed(() => allSupportedChainsWagmi.value.find(chain => chain.id === connectedChain.value))

    const web3modal = createWeb3Modal({
      wagmiConfig,
      projectId,
      chains: wagmiConfig.chains,
      defaultChain: connectedChainInWagmiType.value,
      connectorImages: {
        safe: safeLogo,
      },
      enableAnalytics: true,
    })
```

Then I have watcher using `watchWalletClient`. This watcher gets triggered when I click on connect in web3modal, but unfortunately the call to `getWalletClient` returns `null` here.
```ts
watchWalletClient({}, async () => {
      // this returns null
      const walletClient = await getWalletClient({ chainId: connectedChain.value })
```

Because of this issue I'm not able to correctly setup login using `SafeConnector`.

### Expected Behavior

I'd assume that `getWalletClient` should return a value even when using `SafeConnector`.

### Steps To Reproduce

1) Make sure you are in project that uses `SafeConnector` (+ possibly web3modal with wagmi)
2) Go to https://app.safe.global
3) Connect your multisig to the app via Custom Apps option
4) Try to login and see the result of `getWalletClient` (it should be `null`)

**Comment by tmm** [comment]
We don't develop Web3Modal. Probably better if you ask on the [Web3Modal repo](https://github.com/WalletConnect/web3modal).
