### ISSUE TITLE
Documentation bug: Typo

### ISSUE THREAD

**Issue by nicktaras** [wevm/wagmi#3320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

docs

### Current Behavior

https://wagmi.sh/core/chains

In the  documentation section "Supported chains" the list includes "bronos" but believe this should be "cronos".

### Expected Behavior

"bronos" and "bronosTestnet" are "cronos" and "cronosTestnet"

### Steps To Reproduce

Via https://wagmi.sh/core/chains navigate to to the "Supported chains" section.

**Comment by tmm** [comment]
Feel free to update!
