### ISSUE TITLE
Problem with Ethereum Mainnet Contract Transfer Function

### ISSUE THREAD

**Issue by amandeep-coolplugin** [wevm/wagmi#3321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.12

### Current Behavior

Encountering problems while transferring USDT on the Ethereum main network. 
This issue came with only Ethereum main network, with rest network worked just fine.
The following errors have been identified

ContractFunctionExecutionError: Missing or invalid parameters.

Double check you have provided the correct parameters.

URL: https://cloudflare-eth.com
Request body: {"method":"eth_call","params":[{"from":"0x1546851C84E9163D6FD51C489708085515d1e065","data":"0xa9059cbb0000000000000000000000001dc52984f107ba6c5c5cc86a2f52a5ba1ef9ac71000000000000000000000000000000000000000000000000f985cabce5860000","to":"0xdac17f958d2ee523a2206206994597c13d831ec7"},"latest"]}
 
Raw Call Arguments:
  from:  0x1546851C84E9163D6FD51C489708085515d1e065
  to:    0xdac17f958d2ee523a2206206994597c13d831ec7
  data:  0xa9059cbb0000000000000000000000001dc52984f107ba6c5c5cc86a2f52a5ba1ef9ac71000000000000000000000000000000000000000000000000f985cabce5860000
 
Contract Call:
  address:   0xdac17f958d2ee523a2206206994597c13d831ec7
  function:  transfer(address recipient, uint256 amount)
  args:              (0x1dC52984F107bA6c5c5cC86a2f52a5bA1Ef9AC71, 17980000000000000000)
  sender:    0x1546851C84E9163D6FD51C489708085515d1e065

Docs: https://viem.sh/docs/contract/simulateContract.html
Details: invalid opcode: INVALID
Version: viem@1.20.2
    at getContractError (getContractError.js:26:1)
    at simulateContract (simulateContract.js:73:31)
    at async prepareWriteContract (chunk-TSH6VVF4.js:2079:29)

### Steps To Reproduce

Try making payment on Ethereum main network with tokens.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
