### ISSUE TITLE
bug: autoConnect often fails, a problem many people encounter, why not fix it?

### ISSUE THREAD

**Issue by cong1223** [wevm/wagmi#3324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.12

### Current Behavior

In react applications, refreshing the page causes the link status to be lost

### Expected Behavior

auto connect

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/devbox/wagmi-reproduction-75cx2s?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqdfbu7n00073b6jqvovk4pb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqdfbu7n00023b6jgdfrxtga%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqdfbu7n00043b6jt4arlwt1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqdfbu7n00063b6jdokw6jsm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqdfbu7n00023b6jgdfrxtga%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdfbu7m00013b6jod2dowv9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqdfbu7n00023b6jgdfrxtga%2522%252C%2522activeTabId%2522%253A%2522clqdfbu7m00013b6jod2dowv9%2522%257D%252C%2522clqdfbu7n00063b6jdokw6jsm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdfbu7n00053b6j5lpfj3qn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqdfbu7n00063b6jdokw6jsm%2522%252C%2522activeTabId%2522%253A%2522clqdfbu7n00053b6j5lpfj3qn%2522%257D%252C%2522clqdfbu7n00043b6jt4arlwt1%2522%253A%257B%2522id%2522%253A%2522clqdfbu7n00043b6jt4arlwt1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdfbu7n00033b6jrf3k59o2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqdfbu7n00033b6jrf3k59o2%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by tmm** [comment]
In order for Wagmi to reconnect, you need to connect with a connector from the config.

```diff
const { connectAsync, connectors } = useConnect()

- connectAsync({ connector: new MetaMaskConnector(), chainId: 1 })
+ connectAsync({ connector: connectors[0], chainId: 1 })
```
