### ISSUE TITLE
bug: connection issues with Gnosis Safe via WalletConnect after wagmi/viem upgrade

### ISSUE THREAD

**Issue by nakedfool** [wevm/wagmi#3326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.12

### Current Behavior

Hi all,

We recently upgraded our wagmi and viem versions and have since encountered connection issues with Gnosis Safe via WalletConnect. Additionally, there's a reported issue with connecting from the Rainbow wallet on mobile devices.

- Previous Versions: wagmi 1.3.9, viem 1.4.1
- Upgraded Versions: wagmi 1.4.12, viem 1.19.15

The primary issue observed is a `JSON is not a valid request object.` error. This seems to occur when you try to connect to a Gnosis Safe via WalletConnect.

### Expected Behavior

User should be able to connect via wallet connect with gnosis safe to our app, visit app [here](https://jokerace.xyz/)

### Steps To Reproduce

1. Visit https://jokerace.xyz/ and copy wallet connect link ( use polygon as connected network )
2. Head over to gnosis safe account and try to connect with wallet connect to app

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
