### ISSUE TITLE
bug: TanStack Query Devtools failing to debug BigInt parameters

### ISSUE THREAD

**Issue by MidnightLightning** [wevm/wagmi#3328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

Unhandled Runtime Error thrown with details of "TypeError: Do not know how to serialize a BigInt"

### Expected Behavior

Devtools able to enumerate background processes wagmi is using

### Steps To Reproduce

* Install `@tanstack/react-query-devtools` v4.36.1 alongside `wagmi`.
* Add `ReactQueryDevtools` to top-level configuration, just inside `WagmiConfig` context (as described in #2888)
* Browse to a page that uses a `useContractRead` hook that calls a contract with a `uint256` input argument (which needs to be passed as a BigInt value.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-qqhzxm?file=src%2FApp.tsx

### Anything else?

This issue stems from the fact that `JSON.stringify` cannot handle BigInt values. When passing the contract arguments to TanStack to be used as query keys, wagmi needs to convert them to standard Numbers or Strings so they can be parsed properly.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by MidnightLightning** [comment]
@tmm Added example now

**Comment by MidnightLightning** [comment]
@tmm FYI, it appears there's no button for me to be able to "reopen" this issue on my own.

**Comment by tmm** [comment]
For proper TanStack Query Devtools support, upgrade to Wagmi v2.
