### ISSUE TITLE
bug: failure to switch chains using WalletConnect in Wagmi 2

### ISSUE THREAD

**Issue by firnprotocol** [wevm/wagmi#3347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

rc (for wagmi 2)

### Current Behavior

calling `switchChain` or `switchChainAsync` with WalletConnect throws:
```javascript
SwitchChainError: An error occurred when attempting to switch chain.

Details: Cannot set properties of undefined (setting 'defaultChain')
Version: viem@2.0.0-rc.0
    at Object.switchChain (walletConnect.js:184:1)
    at async switchChain (switchChain.js:14:1)
```

### Expected Behavior

should work.

### Steps To Reproduce

connect using WalletConnect; then switch chain.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/vitejs-vite-ty17d7

**Comment by cheshirrrcat** [comment]
I have the same issue with 1.4.12 version

**Comment by chybisov** [comment]
I got this error from your example 👀

`An error occurred when attempting to switch chain. Details: {"code":-32602,"message":"May not specify default MetaMask chain."} Version: viem@2.0.0-rc.2`

<img width="826" alt="image" src="https://github.com/wevm/wagmi/assets/18644653/a1392076-799e-45c0-a152-0116990a65a8">

I got `Details: Cannot set properties of undefined (setting 'defaultChain')` in my code but can't reproduce it now 😅

**Comment by chybisov** [comment]
Something is really off with this chain switching using WalletConnect. I have another issue https://github.com/wevm/wagmi/issues/3350 😄

**Comment by firnprotocol** [comment]
yes, you're right! i also get a _DIFFERENT_ error in the sandbox: "An error occurred when attempting to switch chain. Details: Missing or invalid. request() method: wallet_switchEthereumChain Version: viem@2.0.0-rc.2"

**Comment by glitch-txs** [comment]
@firnprotocol which wallet?

**Comment by glitch-txs** [comment]
hi, this is a WalletConnect issue, I've open an issue [here](https://github.com/WalletConnect/walletconnect-monorepo/issues/4089) feel free to close here/track there. Thanks!
