### ISSUE TITLE
bug: unresolved promise when switching chains using WalletConnect

### ISSUE THREAD

**Issue by chybisov** [wevm/wagmi#3350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0-rc.1

### Current Behavior

I'm continuing to test WalletConnect and found one more issue. 

Prerequisites: We have a dApp where users can swap/bridge tokens. WagmiProvider chains setup has Ethereum and Optimism chains, and they are provided as optional chains when connected via WalletConnect. MetaMask Mobile has both Ethereum and Optimism added. 

1. We have MetaMask Mobile connected via WalletConnect. The default chain is set to Ethereum.
2. We try to switch the chain to Optimism. The part with `wallet_addEthereumChain` will be called first. At this stage MetaMask Mobile asks us to switch chain to Optimism. 
3. Then the part with `wallet_switchEthereumChain` request is called, and that promise is never resolved.
4. The execution is stuck because we need to return from the switchChain method to continue.
5. switchChain method throws an error in ~5 minutes `Error: Request expired. Please try again.
    at http://localhost:3000/node_modules/.vite/deps/@wagmi_connectors.js?v=d59c1b8e:71223:10`

Maybe something is wrong with calling `wallet_switchEthereumChain` after `wallet_addEthereumChain`?

<img width="588" alt="image" src="https://github.com/wevm/wagmi/assets/18644653/69579580-d456-4d6b-8199-806707d2dc9e">

<img width="904" alt="image" src="https://github.com/wevm/wagmi/assets/18644653/73f54cd8-158a-44b7-9741-6a75dc3f5d1b">

### Expected Behavior

The switch chain method for the WalletConnect connector should work and resolve successfully, no matter if the chain is added or not.

### Steps To Reproduce

1. Connect wallet via WalletConnect
2. Select from and to chain and token (should be different from the connected chain in the wallet)
3. Start swapping/bridging
4. UI will ask you to switch chain, and after switching it in the wallet (I used MetaMask Mobile for testing), nothing happens due to the `wallet_switchEthereumChain` request never resolving.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://playground.li.fi/

**Comment by glitch-txs** [comment]
hi, this is a WalletConnect <> MetaMask issue, I've open an issue [here](https://github.com/WalletConnect/walletconnect-monorepo/issues/4089) we'll communicate with MetaMask if needed, feel free to close here/track there. Thanks!
