### ISSUE TITLE
bug: different versions of abitype in viem and wagmi

### ISSUE THREAD

**Issue by AoDev** [wevm/wagmi#3354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.12

### Current Behavior

Webpack build fails due to the following error (`formatAbiItem` not present)

```
ERROR in ./node_modules/viem/_esm/utils/hash/getFunctionSignature.js 7:15-28
export 'formatAbiItem' (imported as 'formatAbiItem') was not found in 'abitype' (possible exports: BaseError, CircularReferenceError, InvalidAbiItemError, InvalidAbiParameterError, InvalidAbiParametersError, InvalidAbiTypeParameterError, InvalidFunctionModifierError, InvalidModifierError, InvalidParameterError, InvalidParenthesisError, InvalidSignatureError, InvalidStructSignatureError, SolidityProtectedKeywordError, UnknownSignatureError, UnknownTypeError, narrow, parseAbi, parseAbiItem, parseAbiParameter, parseAbiParameters)
```

### Expected Behavior

Shouldn't happen

### Steps To Reproduce

I'm following the ["getting started" instructions](https://wagmi.sh/core/getting-started)
- Installed both @wagmi/core (1.4.12) and viem (1.21.3).
- Then used the first snippets of the getting started.

After some digging, I've found that they use different abitype versions, that'd probably explain the issue. 
As I'm writing now:
- @wagmi/core wants [abitypes@0.8.7](https://github.com/wevm/wagmi/blob/main/packages/core/package.json#L120)
- view wants [abitypes@0.9.8](https://github.com/wevm/viem/blob/main/src/package.json#L142)

Normally, npm / webpack should be capable of resolving multiple packages versions and maybe it's something on my end. But, let's put that aside for a moment.

Just asking: shouldn't these libraries use the same version?

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

I'll create a repo to reproduce if needed.

### Anything else?

I have created a dapp with npm init wagmi using rainbow. The app works. 

But the dependencies are quite far from the latest versions.

*    "viem": "~0.3.36",
*  "wagmi": "^1.0.6"

I solved the issue by installing `viem@0.3.50` instead of latest. (this is the version that was installed when I used `npm init wagmi`)

It would be nice to have some clarification as whether any version of viem works for any version of wagmi. 
In general, it would be beneficial to have the same version for common libs like abitype. Especially that it is not yet a 1.x version, which could involve breaking changes more often. ([0.10.3](https://github.com/wevm/abitype/blob/main/packages/abitype/package.json#L4C23-L4C23) being the latest at the time of writing)

**Comment by tmm** [comment]
Since Viem is a peer dependency of Wagmi, there were many different versions of Viem that had different ABIType versions than Wagmi. With Wagmi v2, ABIType is no longer a dependency of Wagmi and is only a Viem dependency.
