### ISSUE TITLE
Bug: Unable to Interface with OKS Mobile Wallet: Functionality Not Working as Expected

### ISSUE THREAD

**Issue by amandeep-coolplugin** [wevm/wagmi#3360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.12

### Current Behavior

Encountered Failure While Attempting to Initiate a Test Transaction on Your Documentation Site Using OKX Mobile Wallet

### Steps To Reproduce

Establish a Connection on Your Website with OKX Mobile Wallet and Attempt a Transaction: Visit https://wagmi.sh/examples/send-transaction

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/examples/send-transaction

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
