### ISSUE TITLE
bug: Suspected to be incompatible with viem 2.0.0, error TypeError: Cannot read properties of undefined (reading 'http')

### ISSUE THREAD

**Issue by gonghaibo** [wevm/wagmi#3366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.13

### Current Behavior

Configure WagmiProvider configureChains

### Steps To Reproduce

`"use client";
import { WagmiConfig, configureChains, createConfig } from "wagmi";
import { mainnet, localhost } from "wagmi/chains";
import { publicProvider } from "wagmi/providers/public";

import { CoinbaseWalletConnector } from "wagmi/connectors/coinbaseWallet";
import { InjectedConnector } from "wagmi/connectors/injected";
import { MetaMaskConnector } from "wagmi/connectors/metaMask";
import { WalletConnectConnector } from "wagmi/connectors/walletConnect";

const projectId = "XXXXXXXXXXXXXXXXXXXXX";

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [mainnet, localhost],
  [publicProvider()]
);

const config = createConfig({
  autoConnect: false,
  connectors: [
    new MetaMaskConnector({ chains }),
    new CoinbaseWalletConnector({
      chains,
      options: {
        appName: "Starfab.io",
      },
    }),
    new WalletConnectConnector({
      chains,
      options: {
        projectId: "XXXXXXXXXXXXXXXXXXXXX",
      },
    }),
    new InjectedConnector({
      chains,
      options: {
        name: "Browser wallet",
        shimDisconnect: true,
      },
    }),
  ],
  publicClient,
  webSocketPublicClient,
});

export function WagmiProvider({ children }: { children: React.ReactNode }) {
  return <WagmiConfig config={config}>{children}</WagmiConfig>;
}
`

![image](https://github.com/wevm/wagmi/assets/36252719/dbe03060-3db7-4402-be7f-ba4c22732ccd)

### Anything else?

It works fine with the old version viem 1.21.4.

**Comment by imaksp** [comment]
Hi, viem v2 is still in beta, when its out of beta, I am sure that wagmi will release new version with its support.

**Comment by glitch-txs** [comment]
just use the <2 version until Wagmi v2 is stable 😄

**Comment by glpecile** [comment]
> Hi, viem v2 is still in beta, when its out of beta, I am sure that wagmi will release new version with its support.

@imaksp viem v2 is now stable as of [yesterday](https://github.com/wevm/viem/releases/tag/viem%402.0.0)! And wagmi v2 stable seems to be releasing [this week](https://github.com/wevm/wagmi/discussions/3068#discussioncomment-7903438).

**Comment by tmm** [comment]
Correct, Viem v2 and Wagmi v2 work together.
