### ISSUE TITLE
error in useConnect does not change when connect() fails.

### ISSUE THREAD

**Issue by sinolopes** [wevm/wagmi#3373]
### Describe the bug

On version 1, the "error" in useConnect changes when the user refuses the connection request.

For example, consider the following use case:

1. Execute `connect();` on button click.
2. Refuse connection on the MetaMask popup.
3. Catch the error in useEffect (e.g., to push a toast):

```jsx
React.useEffect(() => {
    console.log(error instanceof UserRejectedRequestError ? "Please accept the request on your wallet" : error?.message);
    // push toast
}, [error]);
```

In version 2, the "error" in useConnect does not change when the user refuses the connect request.

I'm unsure if this behavior is normal, and I'm not aware of another method to achieve the same result.

### Steps To Reproduce

1. Execute connect();
2. Deny connection on the wallet.
3. Error remains unchanged.

### Package Version

2.0.1

### Viem Version

2.0.0

### TypeScript Version

5.3.3

### Validations

- [X] Checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) that exists for the bug you encountered.
- [X] Followed the [Code of Conduct](https://github.com/wevm/.github/blob/main/CODE_OF_CONDUCT.md).

**Comment by tmm** [comment]
What wallet are you using?

**Comment by sinolopes** [comment]
MetaMask

**Comment by maximecd** [comment]
Hello, for information i ran into the exact same issue, using either MetaMask, Phantom, or WalletConnect

**Comment by sinolopes** [comment]
Thanks @tmm !!
