### ISSUE TITLE
useConnect's connect() succeeds even if the user refuses the chain switch.

### ISSUE THREAD

**Issue by sinolopes** [wevm/wagmi#3374]
### Describe the bug

In version 1, the 'error' in useConnect changes when the user refuses the chain switch request for the specified chain id in connect().

For example, consider the following use case:

1. Execute connect(chainId); on button click.
2. Accept the connection on the MetaMask popup.
3. Refuse the chain switch on the MetaMask popup.
4. Connection is reverted, and the 'error' in useConnect is set to UserRejectedRequestError.

On version 2:
1. Execute connect(chainId); on button click.
2. Accept the connection on the MetaMask popup.
3. Refuse the chain switch on the MetaMask popup.
4. Connection is successful.

I'm unsure if this behavior is normal, and I'm not aware of another method to achieve the same result.

### Steps To Reproduce

1. Execute connect(chainId); on button click.
2. Accept the connection on the MetaMask popup.
3. Refuse the chain switch on the MetaMask popup.

### Package Version

2.0.1

### Viem Version

2.0.0

### TypeScript Version

5.3.3

### Validations

- [X] Checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) that exists for the bug you encountered.
- [X] Followed the [Code of Conduct](https://github.com/wevm/.github/blob/main/CODE_OF_CONDUCT.md).

**Comment by tmm** [comment]
#3384 fixes this. Keep in mind that error bubbling for this is considered best effort as some connectors are multichain by default (e.g. WalletConnect) or don't support the `chainId` parameter when connecting (e.g. Safe).
