### ISSUE TITLE
connect() does not work on the EIP-1193 connector target.

### ISSUE THREAD

**Issue by sinolopes** [wevm/wagmi#3375]
### Describe the bug

I am using the following configuration:

```javascript
const config = createConfig({
  chains: chains,
  connectors: [
    injected({
      target: "metaMask",
    }),
    injected({
      target: "braveWallet",
    }),
  ],
  transports: transports,
});
```

Metamask works fine with `connect()`, but Brave Wallet does not. A temporary fix is as follows:

```javascript
const config = createConfig({
  chains: chains,
  connectors: [
    injected({
      target: "metaMask",
    }),
    injected({
      target() {
        return {
          id: "braveWallet",
          name: "Brave Wallet",
          provider: window.ethereum,
        };
      },
    }),
  ],
  transports: transports,
});
```

### Steps To Reproduce

Set config connectors to : [
    injected({
      target: "metaMask",
    }),
    injected({
      target: "braveWallet",
    }),
  ],
  
  try to connect on braveWallet.

### Package Version

2.0.1

### Viem Version

2.0.0

### TypeScript Version

5.3.3

### Validations

- [X] Checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) that exists for the bug you encountered.
- [X] Followed the [Code of Conduct](https://github.com/wevm/.github/blob/main/CODE_OF_CONDUCT.md).

**Comment by tmm** [comment]
Brave and MetaMask tend to clash with each other over `window.ethereum` so the best thing to do is rely on [EIP-6963 support](https://wagmi.sh/react/api/createConfig#multiinjectedproviderdiscovery) in Wagmi to determine what connectors t show or use your current workaround.
