### ISSUE TITLE
Automatically add MetaMask to connectors.

### ISSUE THREAD

**Issue by sinolopes** [wevm/wagmi#3376]
### Describe the bug

I want to have only Brave Wallet in connectors, but every time I get Metamask when I call connectors:

```javascript
const { connectors } = useConnect();
```

Configuration:

```javascript
const config = createConfig({
  chains: chains,
  connectors: [
    injected({
      target() {
        return {
          id: "braveWallet",
          name: "Brave Wallet",
          provider: window.ethereum,
        };
      },
    }),
  ],
  transports: transports,
});
```

### Package Version

2.0.1

### Viem Version

2.0.0

### TypeScript Version

5.3.3

### Validations

- [X] Checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) that exists for the bug you encountered.
- [X] Followed the [Code of Conduct](https://github.com/wevm/.github/blob/main/CODE_OF_CONDUCT.md).

**Comment by tmm** [comment]
Set [`multiInjectedProviderDiscovery`](https://wagmi.sh/react/api/createConfig#multiinjectedproviderdiscovery) to `false`.

**Comment by sinolopes** [comment]
thank you, sorry to have an issue for this 😳
