### ISSUE TITLE
 @wagmi/connectors@rc, @wagmi/core@rc  incompatible with viem@2.x 

### ISSUE THREAD

**Issue by OfficialMindAI** [wevm/wagmi#3377]
### Describe the bug

Hi everyone, i am trying to create a custom config using WalletConnect and Wagmi. In order to use createConfig to disable autoConnect i have tried to import { walletconnect} from '@wagmi/connectors' which i tried to install but gave the following dependencies issues.
`npm install @wagmi/core@rc viem@2.x @wagmi/connectors@rc
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mindai_website@0.1.0
npm ERR! Found: viem@2.0.0
npm ERR! node_modules/viem
npm ERR!   viem@"2.x" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer viem@"2.0.0-rc.4" from @wagmi/core@2.0.0-rc.3
npm ERR! node_modules/@wagmi/core
npm ERR!   @wagmi/core@"2.0.0-rc.3" from the root project
npm ERR!   peer @wagmi/core@"2.0.0-rc.3" from @wagmi/connectors@4.0.0-rc.3
npm ERR!   node_modules/@wagmi/connectors
npm ERR!     @wagmi/connectors@"4.0.0-rc.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:`

Here you can find further details:

- /context/web3Modal.jsx as per walletconnect documentation [here ](https://docs.walletconnect.com/web3modal/nextjs/about)
- next v.14^ 
-packages version: viem@1.21.4

`
const chains = [mainnet]
// const wagmiConfig = defaultWagmiConfig({ chains, projectId, metadata })
const wagmiConfig = createConfig({
    autoConnect: false, //<-- setting this to false fixes the issue
    connectors: [
      new walletConnect({ chains, options: { projectId, showQrModal: false, metadata } }),
    //   new EIP6963Connector({ chains }),
    //   new InjectedConnector({ chains, options: { shimDisconnect: true } }),
    //   new CoinbaseWalletConnector({ chains, options: { appName: metadata.name } })
    ],
    publicClient,
  });
const defaultChain = mainnet;
const themeVariables = {
    '--w3m-z-index': 4000
}
createWeb3Modal({ wagmiConfig, projectId, chains , defaultChain, themeVariables})

export function Web3Modal({ children }) {
    const [ready, setReady] = useState(false);

	useEffect(() => {
		setReady(true);
	}, []);
  return  ready ? ( <WagmiConfig config={wagmiConfig}>{children}</WagmiConfig>) : null ;
}`

-M - MindAI Team

### Package Version

1.4.12

### Viem Version

1.4.13

### Validations

- [X] Checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) that exists for the bug you encountered.
- [X] Followed the [Code of Conduct](https://github.com/wevm/.github/blob/main/CODE_OF_CONDUCT.md).

**Comment by glitch-txs** [comment]
Web3Modal doesn't support wagmi v2 yet, we'll release an alpha version soon. You can check the supported version [here](https://docs.walletconnect.com/web3modal/react/about#installation)
