### ISSUE TITLE
how to watch network change, add it to documentation please

### ISSUE THREAD

**Issue by Xi-yu** [wevm/wagmi#3381]
### What is the type of issue?

Documentation is missing

### What is the issue?

how to watch network change, add it to documentation please

### Where did you find it?

https://wagmi.sh/

**Comment by tmm** [comment]
If you are using Wagmi Core, you can use [`watchChainId`](https://wagmi.sh/core/api/actions/watchChainId). If you are using Wagmi, you can use [`useChainId`](https://wagmi.sh/react/api/hooks/useChainId).

**Comment by Xi-yu** [comment]
Do the networks that want to monitor changes have to be added to the chains of createConfig?
eg:
```
export const config = createConfig({
  chains: [bsc, mainnet],
  connectors: [injected()],
  transports: {
    [bsc.id]: http(),
  },
});
```
It can only be monitored when the network is switched from bsc to mainnet.
If you switch from bsc to zksync, you cannot monitor it because zkSync is not in chains.
is that so?
