### ISSUE TITLE
After upgrade to @wagmi/core 2.0 build size increased from 800kb to 2,400kb

### ISSUE THREAD

**Issue by Alexander-Stulov** [wevm/wagmi#3383]
### Describe the bug

Web component uses @wagmi/core, viem, vue and vite
Before upgrading to 2.0, the total build size was around 800kb (all libs and dependencies included). After the upgrade (no other changes than the upgrade), the build size increased three times to ~2,400kb. 
According to documentation, the build size should stay small. Please advise 

### Wagmi Version

2.0.1

### Viem Version

2.0.0

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
How are you measuring this? There are more features in Wagmi Core v2 so as a result the amount of total code increased. Everything is tree-shakable so depending on what features you are using in your app, the bundle size will be different.

**Comment by Alexander-Stulov** [comment]
The size issue is related to **@wagmi/connectors** (core, without react)
Link to sample project:
https://stackblitz.com/edit/vitejs-vite-bbzuv4?file=vite.config.ts

Steps to reproduce:

1. Download sample project (the only logic it has is to connect to MetaMask wallet, image 1)
2. Run npm run build (it prepares production-ready build). Stackblitz doesn't have this option
3. Produced file size: 1,703.50 kb (image 2)
4. If I exclude @wagmi/connectors (image 3), the file size drops to 103.56 kb (image 4). **Diff: 1,599.94 kb**

The previous version @wagmi/core 1.4.12 doesn't have such an issue. Please advise.

<img width="425" alt="image 1" src="https://github.com/wevm/wagmi/assets/2744160/069534dd-f7e6-4008-b15c-fa9343ffd315">
<img width="502" alt="image 2" src="https://github.com/wevm/wagmi/assets/2744160/1595f164-2f67-48dd-9b0e-40caccbda52e">
<img width="609" alt="image 3" src="https://github.com/wevm/wagmi/assets/2744160/fc4ea494-d816-408d-8c0a-bf4ba025929f">
<img width="453" alt="image 4" src="https://github.com/wevm/wagmi/assets/2744160/2347c631-c07d-4472-b9a2-55b49f58ada1">

**Comment by tmm** [comment]
The `metaMask` connector is different in v2. It uses the MetaMask SDK for mobile and desktop support instead of just being a wrapper around browser EIP-1193. That's likely what the size increase is related to.

Migration guide for more info: https://wagmi.sh/core/guides/migrate-from-v1-to-v2#removed-metamaskconnector
