### ISSUE TITLE
TypeError: _wagmi_core__WEBPACK_IMPORTED_MODULE_4__.getBalance is not a function

### ISSUE THREAD

**Issue by SquanchingInHere** [wevm/wagmi#3386]
### Describe the bug

I'm getting the following error when I try to call the getBalance action within a useEffect hook:

TypeError: _wagmi_core__WEBPACK_IMPORTED_MODULE_4__.getBalance is not a function

I'm importing getBalance as follows:

import { getBalance } from "@wagmi/core"

I'm using @wagmi/core@1.4.12.  My component is wrapped with WagmiConfig, and here's a stripped down version of the useEffect:

useEffect(() => {
    if (isConnected) {
      const balance = getBalance({ address: userAddress })
    }
  }, [userAddress])

I know there's a useBalance hook, but I would like to call the wagmi action directly.  However, I don't understand what's causing this error (the function is referenced in the docs: https://wagmi.sh/core/api/actions/getBalance).

### Wagmi Version

1.4.12

### Viem Version

1.21.1

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Import `getBalance` from `'wagmi/actions'`

```diff
- import { getBalance } from "@wagmi/core"
+ import { getBalance } from "wagmi/actions"
```

**Comment by SquanchingInHere** [comment]
Thanks for the response.

I realized I was looking at the v2 docs.

There isn't a getBalance in v1 -- it's fetchBalance in v1.
