### ISSUE TITLE
Missing documentation for v 1.4

### ISSUE THREAD

**Issue by Alexander-Stulov** [wevm/wagmi#3389]
### What is the type of issue?

Documentation is missing

### What is the issue?

Website https://wagmi.sh/ support only v2.* (no links or references to documentation for previous versions)
I need help finding a way to access documentation for 1.4.*

### Where did you find it?

Website https://wagmi.sh/ support only v2.* (no links or references to documentation for previous versions)

**Comment by tmm** [comment]
There's a link under the [migration guide](https://wagmi.sh/react/guides/migrate-from-v1-to-v2#overview) to the previous docs.

Posting here as well:
https://1.x.wagmi.sh

**Comment by Alexander-Stulov** [comment]
Great! Thank you (I missed that link)
