### ISSUE TITLE
bug: `SDK state invalid -- undefined mobile provider` error occurs after executing switchChain

### ISSUE THREAD

**Issue by POKENA7** [wevm/wagmi#3400]
### Describe the bug

After executing `switchChain` and switching the chain, following error occurs.

```
VM11055:1 Uncaught Error: SDK state invalid -- undefined mobile provider
    at bx.getMobileProvider (864f171b-47a89c017c44194e.js:51:166357)
    at f.<anonymous> (864f171b-47a89c017c44194e.js:51:159330)
    at i (<anonymous>:1:14107)
    at f.emit (<anonymous>:1:14647)
    at f._handleChainChanged (<anonymous>:1:111724)
    at f._handleChainChanged (<anonymous>:1:122281)
    at f._handleChainChanged (<anonymous>:1:119789)
    at s.<anonymous> (<anonymous>:1:121493)
    at i (<anonymous>:1:14107)
    at s.emit (<anonymous>:1:14647)
```

### Link to Minimal Reproducible Example

https://github.com/POKENA7/wagmi-reproduce-sample

### Steps To Reproduce

1. Click `metamask` button to connect.
2. Click `mainnet` or `sepolia` button in the Switch Chain section.
    →A popup appears, and you can switch chains. However, an error occurs after completion.

### Wagmi Version

2.0.3

### Viem Version

2.0.3

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

I think it's the same as this one, but I couldn't figure out why...
https://github.com/wevm/wagmi/blob/main/packages/connectors/src/metaMask.ts#L190-L192

**Comment by jxom** [comment]
This is a MetaMask SDK issue. Will get in touch with MetaMask on this. 

Feel free to just use the Injected Connector (for desktop), and WalletConnect (for mobile), for the meantime.

**Comment by zoubair-hattab** [comment]
Hello, guys,

I encountered an issue while trying to use the project that Teams Wagmi developed for connecting multiple wallets. Does anyone have an idea about this and can guide me? The issue occurs especially when switching accounts, networks, or disconnecting wallet.

**Comment by tmm** [comment]
Probably best to report this upstream as Wagmi does all it can to catch and standardize the error.

**Comment by kristiegiles** [comment]
> This is a MetaMask SDK issue. Will get in touch with MetaMask on this.
> 
> Feel free to just use the Injected Connector (for desktop), and WalletConnect (for mobile), for the meantime.

Do you know whether there is an issue for this we can track on the MetaMask side?

**Comment by omridan159** [comment]
@POKENA7
Here is the PR that addresses the issue on the package `@metamask/sdk` package
https://github.com/MetaMask/metamask-sdk/pull/663

This is the PR on Wagmi that updated the `@metamask/sdk` package to version `0.14.3`, which includes this fix:
[wevm/wagmi#3567](https://github.com/wevm/wagmi/pull/3567)

**Comment by POKENA7** [comment]
@omridan159 Thanks for your improvement!
