### ISSUE TITLE
SSR: split cookie by "=" will cause unexpected issue in some case

### ISSUE THREAD

**Issue by Songkeys** [wevm/wagmi#3401]
### Describe the bug

I am using wagmi with rainbowkit. The cookie of "wagmi.store" contains the `=` string in some fields:

<img width="442" alt="SCR-20240108-mivp" src="https://github.com/wevm/wagmi/assets/22665058/e601056e-84f2-4459-9e81-92ba9ef2c87f">

This will cause unterminated json string error when parsing cookie. The cause comes from the following code:

https://github.com/wevm/wagmi/blob/b886c8dcf700344ca8dd43fb71a9e677ae490ce8/packages/core/src/utils/cookie.ts#L29-L34

### Wagmi Version

2.0.3

### Viem Version

^2

### TypeScript Version

^5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

My suggestion: [split only the first `=`](https://stackoverflow.com/a/50452780/7422256)

I'm not sure if there is still some other edge case though.

I'm happy to make a PR if you think this is ok.

**Comment by jxom** [comment]
Happy for you to make a PR :)
