### ISSUE TITLE
[docs] Reference `use-wagmi` for vue

### ISSUE THREAD

**Issue by ennioVisco** [wevm/wagmi#3404]
### What is the issue?

I would like to shout out to the amazing work done by unicape that maps very closely the wagmi react hooks to vue. Repo here: https://github.com/unicape/use-wagmi.

Perhaps it can be mentioned somewhere in the docs?

### Where did you find it?

-

**Comment by tmm** [comment]
Feel free to create a new [show and tell](https://github.com/wevm/wagmi/discussions/categories/show-and-tell) discussion thread for now! Maybe in the future, we can highlight community projects, like we did in [awesome-wagmi](https://github.com/wevm/awesome-wagmi). The challenge with lists is it's often a lot of work to keep them up-to-date.
