### ISSUE TITLE
wagmi cli actions codegen using `functionName` instead of `eventName`

### ISSUE THREAD

**Issue by o-az** [wevm/wagmi#3409]
### Describe the bug

wagmi cli actions codegen using `functionName` instead of `eventName`. It's generating events code and using `functionName` where it should be `eventName`.

Example:

```ts
/**
 * Wraps __{@link watchContractEvent}__ with `abi` set to __{@link efpAccountMetadataAbi}__ and `eventName` set to `"OwnershipTransferred"`
 */
export const watchEfpAccountMetadataOwnershipTransferredEvent =
  /*#__PURE__*/ createWatchContractEvent({
    abi: efpAccountMetadataAbi,
    functionName: 'OwnershipTransferred', // should be eventName
  })
```

I'm also using the `react` plugin to generate hooks, and there it's correctly using `eventName`. Generated code example:

```tsx
/**
 * Wraps __{@link useWatchContractEvent}__ with `abi` set to __{@link efpAccountMetadataAbi}__ and `eventName` set to `"OwnershipTransferred"`
 */
export const useWatchEfpAccountMetadataOwnershipTransferredEvent =
  /*#__PURE__*/ createUseWatchContractEvent({
    abi: efpAccountMetadataAbi,
    eventName: 'OwnershipTransferred',
  })
  ```
  
  
Foundry versions:

```sh
forge 0.2.0 (d46bcb3 2024-01-09T00: 29: 50.351345000Z)
cast 0.2.0 (d46bcb3 2024-01-09T00: 29: 49.923846000Z)
anvil 0.2.0 (d46bcb3 2024-01-09T00: 29: 50.070798000Z)
chisel 0.2.0 (d46bcb3 2024-01-09T00: 29: 50.212750000Z)
```

### Link to Minimal Reproducible Example

https://github.com/ethereumfollowprotocol/contracts-beta

### Steps To Reproduce

install dependencies with `bun install`,
ensure foundry is installed (`curl -L https://foundry.paradigm.xyz | bash` to install/update),
run build with `bun run build`,
check `generated/actions.ts`, most of the errors are at the end of the file so it's faster to start looking from the end of the file.

### Wagmi Version

2.0.3

### Viem Version

2.0.3

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

I would provide a stackblitz link but since this project uses foundry, I couldn't install foundry in stackblitz. If another repro setup is preferred please let me know.

I'm not committing the generated actions file at the moment since it's not passing lint and typechecking. I uploaded the generated code here: https://gist.github.com/o-az/176089103bf74f31b8f798fd986d4846

**Comment by tmm** [comment]
PR welcome: https://github.com/wevm/wagmi/blob/main/packages/cli/src/plugins/actions.ts#L236 Very easy fix!
