### ISSUE TITLE
SSR: TypeError: connections.get is not a function

### ISSUE THREAD

**Issue by adityanithariya** [wevm/wagmi#3415]
### Describe the bug

Connected metamask wallet using wagmi in Next.js 13.4.4
`initialState` is parsed and deserialized on server side in `cookieToInitialState()` in `@wagmi/core/src/utils/cookie.ts`
But it is then parsed to transfer to client side, hence it loses the classes due to parsing.
Due to which `connections`, a Map inside `initialState` gives the error as it doesn't contain `get()` method on client side

### Steps To Reproduce

Next.js `v13.4.4`
Configure WagmiProvider according to [SSR](https://wagmi.sh/react/guides/ssr) guide.
Connect to metamask and then reload, you'll get following error:

![image](https://github.com/wevm/wagmi/assets/74248365/444cb1a0-9c96-4ea7-bdc3-90551d52c4f7)

Error Stacktrace:
```
Uncaught TypeError: connections.get is not a function
    at eval (createConfig.js:141:77)
    at listener (middleware.mjs:244:27)
    at eval (vanilla.mjs:14:39)
    at Set.forEach (<anonymous>)
    at setState (vanilla.mjs:14:17)
    at api.setState (middleware.mjs:490:5)
    at Object.setState (createConfig.js:250:19)
    at hydrate (hydrate.js:10:16)
    at Hydrate (hydrate.js:12:77)
    at renderWithHooks (react-dom.development.js:10648:18)
    at mountIndeterminateComponent (react-dom.development.js:15731:13)
    at beginWork$1 (react-dom.development.js:17306:16)
    at beginWork (react-dom.development.js:25650:14)
    at performUnitOfWork (react-dom.development.js:24501:12)
    at workLoopSync (react-dom.development.js:24217:5)
    at renderRootSync (react-dom.development.js:24182:7)
    at recoverFromConcurrentError (react-dom.development.js:23428:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:23334:22)
    at workLoop (scheduler.development.js:261:34)
    at flushWork (scheduler.development.js:230:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:537:21)
```

### Wagmi Version

2.0.3

### Viem Version

^2

### TypeScript Version

-

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

My suggestion: Modify `connnections` when passed to `WagmiProvider`, which is on client side
Before passing `parameters` to `createElement` in `@wagmi/packages/react/src/context.ts`

Happy to make a PR if you think it's ok, or let me know what approach should I follow while fixing this issue!

**Comment by jxom** [comment]
Is this in the App Directory?

**Comment by adityanithariya** [comment]
> Is this in the App Directory?

@jxom Yes, this is in Next.js 13 App Router

**Comment by adityanithariya** [comment]
@tmm For reproduction, use Next.js v13.4.4 App router with wagmi v2.0.3, followed the official [SSR guide](https://wagmi.sh/react/guides/ssr) from wagmi docs, please let me know if more info needed around reproducing the issue!

**Comment by adityanithariya** [comment]
@tmm @jxom Any updates for fixes, should I work on it?

**Comment by glitch-txs** [comment]
@adityanithariya I think it's easier if you could set up an MRE as stated above :)

**Comment by adityanithariya** [comment]
@tmm Minimum Reproducible Example can be checked [here](https://github.com/adityanithariya/wagmi-mre)

**Comment by glitch-txs** [comment]
@adityanithariya I wasn't able to make it run with SSR feature as well

MRE: https://stackblitz.com/edit/stackblitz-starters-yye1sh?file=app%2Flayout.tsx

**Comment by adityanithariya** [comment]
> @adityanithariya I wasn't able to make it run with SSR feature as well
> 
> MRE: https://stackblitz.com/edit/stackblitz-starters-yye1sh?file=app%2Flayout.tsx

@glitch-txs Unable to use `headers()` within stackblitz environment, that's why I created one repo for illustrating the issue, please check that

**Comment by glitch-txs** [comment]
yep, might be because it's running in an iframe?

I'll check, I ran something locally too and I was getting error after connecting

**Comment by jxom** [comment]
Fixed in https://github.com/wevm/wagmi/commit/3be5bb7b0b38646e12e6da5c762ef74dff66bcc2

**Comment by 0xbid** [comment]
Hey @jxom, thanks so much! Is there any chance there could be a new releaee with this fix in?
