### ISSUE TITLE
useReadContract no enabled parameter

### ISSUE THREAD

**Issue by GHChrisSu** [wevm/wagmi#3418]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

I want to use useReadContract to read state, I need enabled parameter to not read contract when wallet not connected, it was fine in 1.x, there is no enabled in 2.x, and will throw the error toast when connecting

### Where did you find it?

https://wagmi.sh/react/api/hooks/useReadContract

**Comment by tmm** [comment]
Check out the [`enabled`](https://wagmi.sh/react/api/hooks/useReadContract#enabled) parameter on the docs.

**Comment by GHChrisSu** [comment]
> Check out the [`enabled`](https://wagmi.sh/react/api/hooks/useReadContract#enabled) parameter on the docs.

yes, it's in doc, but not incode

**Comment by Yuripetusko** [comment]
Seeing the same thing with version 2.1.2. Also stack trace is super long for the function

<img width="1210" alt="image" src="https://github.com/wevm/wagmi/assets/666169/0ee285b4-49c9-47b1-b46a-38344018ae7d">

**Comment by Yuripetusko** [comment]
Oh, trantsak specific props moved to `query` object. (but docs didn't reflect)

**Comment by Yuripetusko** [comment]
Also doesn't look like cacheTime can be passed to individual contractRead hook now, and only set globally?

**Comment by quagliero** [comment]
> Also doesn't look like cacheTime can be passed to individual contractRead hook now, and only set globally?

@Yuripetusko `cacheTime` was replaced by `gcTime` in react-query so that's probably why you're not seeing it.

https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5#rename-cachetime-to-gctime

**Comment by Yuripetusko** [comment]
> gcTime

oh wow, missed it somehow. Thanks
