### ISSUE TITLE
Why you guys blur the document when not focused?

### ISSUE THREAD

**Issue by GHChrisSu** [wevm/wagmi#3419]
### What is the type of issue?

Something else

### What is the issue?

This is a kind of issue let reading people losing focus.......

### Where did you find it?

https://wagmi.sh/react/api/hooks/useReadContract

**Comment by Songkeys** [comment]
This is the default behavior of the [code focus feature](https://vitepress.dev/guide/markdown#focus-in-code-blocks) from vitepress.

But I agree with you - in many cases, the blurred part is actually important to us to know the context. For example, in your link:

<img width="742" alt="code block of abi example" src="https://github.com/wevm/wagmi/assets/22665058/c1273ede-3529-44f5-85ba-28e03e49e5f4">

The reader actually cares about where to put the `abi` parameter, i.e. inside the first arg of `useReadContract `. I always need to hover to see the "global view", which is quite disturbing.

I think the "code focus" feature is suitable for cases where most of code can be ignored to the reader (e.g., some trivial skeleton code that has to write to make code runnable but not important at all). In our case, most code blocks should probably use the [line highlighting feature](https://vitepress.dev/guide/markdown#line-highlighting-in-code-blocks) instead.

<img width="471" alt="code block with lines highlighted" src="https://github.com/wevm/wagmi/assets/22665058/7edda58b-9ed8-40fa-b26c-2f26408e9ce9">

**Comment by jxom** [comment]
Working on improving the code focus feature to be a bit more readable. Here is a sneak peak:

https://github.com/wevm/wagmi/assets/7336481/6ebddc4e-3784-45b0-9473-37f9a6351640
