### ISSUE TITLE
Switch chain with WalletConnect

### ISSUE THREAD

**Issue by artur-laptev** [wevm/wagmi#3431]
### Describe the bug

Im getting error when trying to switch chain in MetaMask mobile app

<img width="663" alt="image" src="https://github.com/wevm/wagmi/assets/11542480/0801d424-7475-4fd5-acfc-e300c166a00c">

### Steps To Reproduce

1. Connect wallet using WalletConnect and MetaMask (scan qr-code with mobile app)
2. In MetaMask mobile app switch chain

### Wagmi Version

2.1.1

### Viem Version

2.0.6

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Minimal reproduction: https://stackblitz.com/edit/new-wagmi-hqmh1m

```
An error occurred when attempting to switch chain. Details: {"code":-32602,"message":"May not specify default MetaMask chain."}
```

Seems like a wallet-specific issue with MetaMask as Rainbow and Uniswap both work fine with WalletConnect.

**Comment by artur-laptev** [comment]
Switch chain in metamask app (mobile)

**Comment by tmm** [comment]
Upstream issue: https://github.com/MetaMask/metamask-mobile/issues/3269#issuecomment-1779584700
