### ISSUE TITLE
Donating Funds to WAGMI

### ISSUE THREAD

**Issue by Lfada** [wevm/wagmi#3432]
### What is the type of issue?

Something else

### What is the issue?

Hi Wagmi maintainers. I'm Lucas, a core contributor to the Drips project (https://www.drips.network/). I help recipients of donations through their learning and onboarding process. 

[Octant](https://octant.build/) (a project from the Golem Foundation) has been using https://github.com/wevm/wagmi. It's one of their most critical dependencies!

Octant’s core contributors appreciate the work you all do and want to make sure you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/).

Who can I talk to about it? cc: @tmm, @jxom, @markdalgleish, @roninjin10 

### Where did you find it?

n/a

**Comment by tmm** [comment]
How do we set things up?

**Comment by Lfada** [comment]
> How do we set things up?

You would need to first [claim the account](https://www.drips.network/app/drip-lists/30178668158349445547603108732480118476541651095408979232800331391215): , which means you need to prove you are one of the admins of the GitHub repo.

**Comment by Lfada** [comment]
@tmm just realized I never got notified of your response. 

For context, this is part of a Dependency Funding initiative to donate/support FOSS repositories. Octant is donating these funds to WAGMI via Drips, which is a continuous streaming and splitting platform. 

What Drips allows you to do, is to claim the donations and then split them into your critical dependencies and/or amongst other maintainers. A great example is Ethers.js, which is splitting 40% of all incoming funds to their dependencies as you can see [here](https://www.drips.network/app/projects/github/ethers-io/ethers.js). 

[Here's](https://www.drips.network/app/projects/github/wevm/wagmi) WAGMI profile in Drips. A maintainer/admin of this GH repo would need to claim the profile to retrieve the funds. 

For a step-by-step guide on the claim process, watch [this video](https://www.youtube.com/watch?v=AOl_XkgWv-A) and for more detailed information, [here](https://docs.drips.network/claim-your-repository/) you can find the docs. 

Please let me know if you have any questions. Feel free to contact me here or on tw/X: @lukfada

**Comment by tmm** [comment]
Set up! Thanks!

Aside: Bummer that Drips isn't using Wagmi. If you all are interested in chatting, let me know! Would be cool to get another Svelte project using Wagmi Core so we can eventually battle test a Wagmi Svelte adapter :)

**Comment by roninjin10** [comment]
This is dope @Lfada! I bet the optimism foundation would be interested in looking at this

**Comment by Lfada** [comment]
@tmm let's chat. The team is down to talk about that, but also very curious to hear any feedback you have. 

Thanks for the tweets, we appreciate it. It's amazing the number of dependencies being funded downstream by WAGMI. Think I counted 20 😱

Let me know what your availabilities are next week :) 

@roninjin10, we are in touch with them. Great folks!

**Comment by tmm** [comment]
Wild! Good idea with the split. Set it up and makes complete sense! Huge fan of everything so far.

**Comment by tmm** [comment]
> Let me know what your availabilities are next week :)

@Lfada free any day after 3p EST. Can send invite to dev@wevm.dev

**Comment by Lfada** [comment]
Great! thanks for the shoutouts @tmm. Sending an invite for this Tuesday :)

Have a great weekend!

**Comment by Lfada** [comment]
btw, just sent an invite and when I added [dev@wevm.dev](mailto:dev@wevm.dev) it said "group members cannot be added" Did you get an invite? If not, is there another email I can send it to? feel free to share privately on tw or here.

**Comment by tmm** [comment]
Can you send an email to that address and I'll reply?
