### ISSUE TITLE
`useWaitForTransactionReceipt` status is `pending` when no hash is provided.

### ISSUE THREAD

**Issue by quagliero** [wevm/wagmi#3437]
### Describe the bug

Consider the following code:
```ts
  const { writeContract, data: hash } = useWriteContract();

  const { data, status } = useWaitForTransactionReceipt({
    hash: hash,
  });

// status: pending
  ```

The writeContract status is `idle` as it has yet to be invoked, but the `status` on the receipt is `pending`. Should the status not be `idle` in this instance? While it awaits a transaction hash to kick things off, at which point it would be `pending`? Previously we have used the `status` on useWaitForTransaction as the source of truth for UI state on buttons (showing pending/disabled states) as it moves from idle to pending to success/error when tx completes.

Alongside this I've noticed that useWaitForTransactionReceipt no longer has an `onSuccess` function. We have previously used this to invalidate query keys after a tx completed, is the suggested method for this to listen to the `status` within a useEffect?

### Wagmi Version

2.1.12

### Viem Version

2.0.6

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
This is expected.

- `status === 'pending'` - The query has no data yet
- `status === 'error'` - The query encountered an error
- `status === 'success'` - The query was successful and data is available

For more info, check out the [TanStack Query docs.](https://tanstack.com/query/latest/docs/react/guides/queries#query-basics)
