### ISSUE TITLE
Celo compatibility broken in Wagmi V2 

### ISSUE THREAD

**Issue by jmrossy** [wevm/wagmi#3442]
### Describe the bug

When making calls via the `useReadContract` hook, a decimals-encoded `chainId` field is being included in the `eth_call` params. This causes Geth to choke. `chainId` must be excluded or encoded as hex. I'm uncertain if the problem is with wagmi itself or with Viem. The error doesn't seem to repro for other EVM chains.

<img width="899" alt="Screenshot 2024-01-13 at 3 04 16 PM" src="https://github.com/wevm/wagmi/assets/710751/9d06de8d-bf41-44ab-9eb8-1ffd86c0d369">

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-dgdu8j?file=src%2Fwagmi.ts,src%2FApp.tsx

### Steps To Reproduce

Example call: 
```ts
  const { data: celoResult, error: celoError } = useReadContract({
    address: celo.contracts.multicall3.address,
    abi: muticallAbi,
    functionName: 'getBlockNumber',
    args: [],
    chainId: celo.id,
  });
```

### Wagmi Version

2.2.0

### Viem Version

2.0.6

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Looks like an easy fix. Need to change [this](https://github.com/wevm/wagmi/blob/main/packages/core/src/actions/readContract.ts#L53-L55).

```diff
+ const { chainId, ...rest } = parameters
const client = config.getClient({ chainId })
+ return viem_readContract(client, rest)
```

**Comment by jmrossy** [comment]
@tmm thanks for the quick response. I've confirmed that change fixed the issue in my local project.
Here's a PR with the fix: https://github.com/wevm/wagmi/pull/3443
