### ISSUE TITLE
Type 'number | undefined' is not assignable to type '1 | 5 | undefined'.

### ISSUE THREAD

**Issue by oxSaturn** [wevm/wagmi#3445]
### Describe the bug

So I was trying to pass the `chainId` to `getPublicClient`:

```
const config = createConfig({
  chains: [mainnet, goerli],
  connectors: [injected(), walletConnect({ projectId })],
  transports: {
    [mainnet.id]: http(),
    [goerli.id]: http(),
  },
});

const { chainId } = getAccount(config);
  const client = getPublicClient(config, {
    chainId,
  });
```
And run into the below error:

```
Type 'number | undefined' is not assignable to type '1 | 5 | undefined'.
  Type 'number' is not assignable to type '1 | 5 | undefined'.(2322)
```

Here's the type of `GetAccountReturnType`, the type of `chainId` here is either number or undefined:

```
export type GetAccountReturnType =
  | {
      address: Address
      addresses: readonly [Address, ...Address[]]
      chain: Chain | undefined
      chainId: number
      connector: Connector
      isConnected: true
      isConnecting: false
      isDisconnected: false
      isReconnecting: false
      status: 'connected'
    }
  | {
      address: Address | undefined
      addresses: readonly Address[] | undefined
      chain: Chain | undefined
      chainId: number | undefined
      connector: Connector | undefined
      isConnected: boolean
      isConnecting: false
      isDisconnected: false
      isReconnecting: true
      status: 'reconnecting'
    }
  | {
      address: Address | undefined
      addresses: readonly Address[] | undefined
      chain: Chain | undefined
      chainId: number | undefined
      connector: Connector | undefined
      isConnected: false
      isReconnecting: false
      isConnecting: true
      isDisconnected: false
      status: 'connecting'
    }
  | {
      address: undefined
      addresses: undefined
      chain: Chain | undefined
      chainId: undefined
      connector: undefined
      isConnected: false
      isReconnecting: false
      isConnecting: false
      isDisconnected: true
      status: 'disconnected'
    }
```

And here's the type of `getPublicClient`:

```
export function getPublicClient<
  config extends Config,
  chainId extends config['chains'][number]['id'], // <------- type defined here, so they don't match right?
>(
  config: config,
  parameters: GetPublicClientParameters<config, chainId> = {},
): GetPublicClientReturnType<config, chainId> {
  const client = config.getClient(parameters)
  return client.extend(publicActions) as GetPublicClientReturnType<
    config,
    chainId
  >
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-xmqqg8?file=src%2FApp.tsx

### Wagmi Version

latest

### Viem Version

latest

### TypeScript Version

5.0.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
#3447 will fix this. You'll want to use `account.chain?.id` instead. More info about that in the PR.

```ts
const account = getAccount(config)
const ensName = await getEnsName({
  address: '0x...',
  chainId: account.chain?.id,
  //                      ^? (property) id: 1 | 5 | undefined
})
```

**Comment by oxSaturn** [comment]
> #3447 will fix this. You'll want to use `account.chain?.id` instead. More info about that in the PR.
> 
> ```ts
> const account = getAccount(config)
> const ensName = await getEnsName({
>   address: '0x...',
>   chainId: account.chain?.id,
>   //                      ^? (property) id: 1 | 5 | undefined
> })
> ```

Thanks, but seems there's another problem with `useAccount` when no `config` was passed:

```ts
const { chain } = useAccount();
const { chain: chain2 } = useAccount({config});
console.log(chain?.id);
console.log(chain2?.id);
```


![CleanShot-KxRepDL1@2x](https://github.com/wevm/wagmi/assets/126733611/00e2af77-fe1f-48d7-8b1e-64a961d8b8d1)
![CleanShot-iMPSA1au@2x](https://github.com/wevm/wagmi/assets/126733611/676427f7-c116-4bd3-9dc8-58913af91c1f)

**Comment by tmm** [comment]
What's the issue? I can't tell from screenshots what is going on.

**Comment by oxSaturn** [comment]
> What's the issue? I can't tell from screenshots what is going on.

Sorry, just updated the stackbliz example to show the problem https://stackblitz.com/edit/vitejs-vite-xmqqg8?file=src%2FApp.tsx

![CleanShot-OAwpEgQ6@2x](https://github.com/wevm/wagmi/assets/126733611/d35bebaf-fde5-426f-9bf2-b2a2a131dfc8)

**Comment by tmm** [comment]
You need to [register your `config` with TypeScript.](https://wagmi.sh/react/typescript#config-types)

```diff
export const config = createConfig({
  chains: [mainnet, goerli],
  connectors: [injected()],
  transports: {
    [mainnet.id]: http(),
    [goerli.id]: http(),
  },
});

+ declare module 'wagmi' {
+   interface Register {
+     config: typeof config;
+   }
+ }
```

**Comment by oxSaturn** [comment]
> You need to [register your `config` with TypeScript.](https://wagmi.sh/react/typescript#config-types)
> 
> ```diff
> export const config = createConfig({
>   chains: [mainnet, goerli],
>   connectors: [injected()],
>   transports: {
>     [mainnet.id]: http(),
>     [goerli.id]: http(),
>   },
> });
> 
> + declare module 'wagmi' {
> +   interface Register {
> +     config: typeof config;
> +   }
> + }
> ```

Thanks :) I should check the document more carefully.
