### ISSUE TITLE
GasPrice is undefined on `estimateFeesPerGas` return object

### ISSUE THREAD

**Issue by toniocodo** [wevm/wagmi#3454]
### Describe the bug

When fetching fee data using `estimateFeesPerGas` from `wagmi/core`, returned object contains `gasPrice: undefined` while I expect to receive current fee per gas

### Steps To Reproduce

1. Setup wagmi with following config
```
export const wagmiConfig = createConfig({
  chains: [mainnet],
  connectors,
  transports: {
    [mainnet.id]: fallback([
      http(
        `${import.meta.env.VITE_ALCHEMY_RPC}${import.meta.env.VITE_ALCHEMY_ID}`,
      ),
      http(),
    ]),
  },
});
```

2. Call `estimateFeesPerGas` (here with react-query)
```
import { useQuery } from '@tanstack/react-query';
import { estimateFeesPerGas } from '@wagmi/core';
import { useConfig } from 'wagmi';

export const Test = () => {
  const config = useConfig();
  const { data } = useQuery({
    queryKey: ['test', config],
    queryFn: () => estimateFeesPerGas(config),
  });

  console.log(data);

  return <div>Test</div>;
};

```
2. Observe the returned object with `undefined` gasPrice
![image](https://github.com/wevm/wagmi/assets/13216617/e0144482-f6c2-4088-a2ca-14e26887aa20)

### Wagmi Version

2.2.1

### Viem Version

2.0.10

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

`useGasPrice` hook seems to work properly

**Comment by tmm** [comment]
When `'type'` is `'eip1559'` (default if you don't pass `type`), [`gasPrice`](https://wagmi.sh/core/api/actions/estimateFeesPerGas#gasprice) is `undefined`.
