### ISSUE TITLE
usePrepareContractWrite -- error --  ChainMismatchError: Chain mismatch: Expected "BNB Smart Chain", received "Arbitrum One".

### ISSUE THREAD

**Issue by taoxiaofeng** [wevm/wagmi#3455]
### Describe the bug

Hello, this is a sample address (https://stackblitz.com/~/github.com/taoxiaofeng/w3m-modal-demo). After successfully connecting to the wallet, change the network in the select box below, and app-index will be prompted. .js:31 ChainMismatchError: Chain mismatch: Expected "BNB Smart Chain", received "Arbitrum One". Example of how to change this error
<img width="654" alt="image" src="https://github.com/wevm/wagmi/assets/21038118/5a999256-f8e8-4c12-857f-a587b1facc36">

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/taoxiaofeng/w3m-modal-demo

### Steps To Reproduce

Problem example address：https://stackblitz.com/~/github.com/taoxiaofeng/w3m-modal-demo

### Wagmi Version

1.4.13

### Viem Version

1.21.4

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

{
  "name": "nextjs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@nextui-org/react": "^2.2.9",
    "@types/node": "20.6.2",
    "@types/react": "18.2.22",
    "@types/react-dom": "18.2.7",
    "@web3modal/wagmi": "^3.5.6",
    "autoprefixer": "10.4.15",
    "eslint": "8.49.0",
    "eslint-config-next": "13.5.1",
    "framer-motion": "^10.18.0",
    "next": "13.5.1",
    "postcss": "8.4.30",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.3",
    "typescript": "5.2.2",
    "use-debounce": "^10.0.0",
    "viem": "1.21.4",
    "wagmi": "1.4.13"
  }
}

**Comment by tmm** [comment]
Please attach a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). The example you supplied is not minimal.
