### ISSUE TITLE
Defining a "Connection"

### ISSUE THREAD

**Issue by nbran** [wevm/wagmi#3456]
### What is the issue?

The concept of a "connection" (i.e., Connection array returned by [getConnections](https://wagmi.sh/react/api/hooks/useConnections)) could use a little more description throughout the documentation. 

At face value, it's somewhat obvious what this should be, but it can get confusing given that there are a few closely-named concepts that have distinct meanings (e.g., connector, connection, connector client). 

When reading the documentation, the meaning of connectors and clients surfaces quickly, but that's not the case for connections. Other than the implicit conclusion of a unique combination of accounts, chainId & connector (based on the [connection object](https://wagmi.sh/core/api/createConfig#connection)) there is currently no further information/context available. 

### Where did you find it?

- https://wagmi.sh/react/api/hooks/useConnections
- https://wagmi.sh/core/api/actions/getConnections
- https://wagmi.sh/core/api/createConfig#connection

**Comment by tmm** [comment]
Started a section here: https://wagmi.sh/react/guides/faq#how-does-wagmi-work Suggestions welcome! Will spend some more time improving in the future.
