### ISSUE TITLE
`Connector not connected` error when calling `useWriteContract` with a mock connector

### ISSUE THREAD

**Issue by iceanddust** [wevm/wagmi#3458]
### Describe the bug

I recently migrated to Wagmi v2 and I'm currently rewriting the tests of my project. However, I noticed that the `useSimulateContract` doesn't seem to be picking up the mock connector connection as I'm getting the following error when calling the hook
```
 FAIL  src/useApproveToken.test.tsx > Approve and read allowance for token > Should approve token and read allowance
ConnectorNotConnectedError: Connector not connected.

Version: @wagmi/core@2.2.1

Ignored nodes: comments, script, style
<html>
  <head />
  <body>
    <div />
  </body>
</html>
 ❯ new BaseError node_modules/.pnpm/@wagmi+core@2.2.1_@types+react@18.2.46_react@18.2.0_typescript@5.3.3_viem@2.0.10/node_modules/@wagmi/core/dist/esm/errors/base.js:31:9
 ❯ new ConnectorNotConnectedError node_modules/.pnpm/@wagmi+core@2.2.1_@types+react@18.2.46_react@18.2.0_typescript@5.3.3_viem@2.0.10/node_modules/@wagmi/core/src/errors/config.ts:45:2
 ❯ Module.getConnectorClient node_modules/.pnpm/@wagmi+core@2.2.1_@types+react@18.2.46_react@18.2.0_typescript@5.3.3_viem@2.0.10/node_modules/@wagmi/core/src/actions/getConnectorClient.ts:99:10
 ❯ Module.writeContract node_modules/.pnpm/@wagmi+core@2.2.1_@types+react@18.2.46_react@18.2.0_typescript@5.3.3_viem@2.0.10/node_modules/@wagmi/core/src/actions/writeContract.ts:116:5
 ❯ Object.mutationFn node_modules/.pnpm/@wagmi+core@2.2.1_@types+react@18.2.46_react@18.2.0_typescript@5.3.3_viem@2.0.10/node_modules/@wagmi/core/dist/esm/query/writeContract.js:24:46
 ❯ Object.fn node_modules/.pnpm/@tanstack+query-core@5.17.1/node_modules/@tanstack/query-core/src/mutation.ts:190:5
 ❯ run node_modules/.pnpm/@tanstack+query-core@5.17.1/node_modules/@tanstack/query-core/src/retryer.ts:186:23
 ❯ Module.createRetryer node_modules/.pnpm/@tanstack+query-core@5.17.1/node_modules/@tanstack/query-core/build/modern/retryer.js:134:5
 ❯ executeMutation node_modules/.pnpm/@tanstack+query-core@5.17.1/node_modules/@tanstack/query-core/src/mutation.ts:184:29
 ❯ Mutation.execute node_modules/.pnpm/@tanstack+query-core@5.17.1/node_modules/@tanstack/query-core/src/mutation.ts:234:24

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "details": undefined,
  "docsBaseUrl": "https://wagmi.sh/core",
  "docsPath": undefined,
  "metaMessages": undefined,
  "shortMessage": "Connector not connected.",
  "version": "@wagmi/core@2.2.1",
  "walk": "Function<walk>",
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-buxset?file=src%2FuseApproveToken.test.tsx

### Steps To Reproduce

Run `pnpm test` and you should be able to see the same error I shared above in the console.

### Wagmi Version

2.2.1

### Viem Version

2.0.10

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
`useContractSimulate` works fine [here](https://stackblitz.com/edit/new-wagmi-dbuaih?file=src%2FuseApproveToken.test.tsx%2Csrc%2FuseApproveToken.ts). You should probably hook up Vitest to something like [Anvil](https://github.com/wevm/anvil.js) like we have things set up in this repo.

**Comment by iceanddust** [comment]
I'm getting a similar error locally that the one in the example you shared, after the simulation passes, and when calling the `write` function, account appears as undefined. It seems like the connection to the mock connector is lost some time in the middle of the hook, or in a subsequent call (I'm noticing the hook gets called multiple times during the rendering but only in the first one account is defined).

I am using a local testnet for the tests, set up in the wagmi config as localhost.
