### ISSUE TITLE
Cannot find module 'wagmi/codegen' or its corresponding type declarations.

### ISSUE THREAD

**Issue by linghuccc** [wevm/wagmi#3460]
### Describe the bug

I am writing a rainbowkit nextjs project, so I initiated a nextjs project by "npx create-next-app@latest". 
Then I manually installed rainbowkit and wagmi by "npm install @rainbow-me/rainbowkit wagmi viem". 
After that, I installed wagmi cli by "npm i --save-dev @wagmi/cli". 
Then I generated wagmi.config.ts file by "npx wagmi init".
After modified wagmi.config.ts file, I run "npx wagmi generate" to generate generated.ts file. 

The first line of the generate generated.ts file is as below:
```
import {
  createUseReadContract,
  createUseWriteContract,
  createUseSimulateContract,
  createUseWatchContractEvent,
} from 'wagmi/codegen'
```

And my VS code window reports below error:
Cannot find module 'wagmi/codegen' or its corresponding type declarations.

Then I tried to install wagmi by "npm install wagmi viem@2.x @tanstack/react-query", below are the warnings I receive:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: mas-awareness@0.1.0
npm WARN Found: viem@1.21.4
npm WARN node_modules/viem
npm WARN   peer viem@"~0.3.19 || ^1.0.0" from @rainbow-me/rainbowkit@1.3.3
npm WARN   node_modules/@rainbow-me/rainbowkit
npm WARN     @rainbow-me/rainbowkit@"^1.3.3" from the root project
npm WARN   6 more (@safe-global/safe-apps-sdk, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer viem@"~0.3.19 || ^1.0.0" from @rainbow-me/rainbowkit@1.3.3
npm WARN node_modules/@rainbow-me/rainbowkit
npm WARN   @rainbow-me/rainbowkit@"^1.3.3" from the root project
```

package.json:
`{
  "name": "myproject",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@rainbow-me/rainbowkit": "^1.3.3",
    "@tanstack/react-query": "^4.36.1",
    "ethers": "^6.10.0",
    "next": "14.0.4",
    "react": "^18",
    "react-dom": "^18",
    "viem": "^2.1.0",
    "wagmi": "^1.4.13"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@wagmi/cli": "^2.0.3",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}
`

And the error remains. Please advise. Thank you.

### Steps To Reproduce

npx create-next-app@latest

npm install @rainbow-me/rainbowkit wagmi viem

npm i --save-dev @wagmi/cli

npx wagmi init

Modify wagmi.config.ts file

npx wagmi generate

### Wagmi Version

1.4.13

### Viem Version

2.1.0

### TypeScript Version

5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
If you are using Wagmi v1, you must use Wagmi CLI v1.
