### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'http')

### ISSUE THREAD

**Issue by IcyKit** [wevm/wagmi#3482]
### Describe the bug

Hello, I ran into a problem, a couple hours ago the project was working, but now it crashes with Uncaught TypeError: Cannot read properties of undefined (reading 'http') error

It happens exactly in the place where the `defineWagmiConfig` config is declared.

```ts
const projectId = "My Project Id"

const metadata = {
  name: 'Web3Modal',
  description: 'Web3Modal Example',
  url: 'https://web3modal.com',
  icons: ['https://avatars.githubusercontent.com/u/37784886']
}

const chains = [mainnet, arbitrum]

const wagmiConfig = defaultWagmiConfig({chains, projectId, metadata})
```

If I remove this line, the problem disappears

<img width="873" alt="Снимок экрана 2024-01-18 в 21 43 39" src="https://github.com/wevm/wagmi/assets/84917134/84fec800-db14-433c-9a18-0db1ed02c876">

### Wagmi Version

1.4.13

### Viem Version

2.2.0

### TypeScript Version

4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
`defaultWagmiConfig` is a Web3Modal API. You should follow up with them.

**Comment by glitch-txs** [comment]
sounds like you have mixed dependencies, http is from Wagmi v2. . Happy to follow up [here](https://github.com/orgs/WalletConnect/discussions) 🤝
