### ISSUE TITLE
useContractReads ignores batch size from WagmiConfig

### ISSUE THREAD

**Issue by kim-hera** [wevm/wagmi#3485]
### Describe the bug

`useContractReads` ignores batch size from WagmiConfig. It was working perfectly on V1.

### Scenario 1
wagmiConfig's batch size = 1024 * 10
useContractReads's batch size = undefined
![image](https://github.com/wevm/wagmi/assets/108852708/2e07a8c0-ede2-4a57-8f98-bf2805ab526e)![image](https://github.com/wevm/wagmi/assets/108852708/a75bd2b9-5be3-4342-9b9d-7849e028e5df)

**Result**
36 requests
![image](https://github.com/wevm/wagmi/assets/108852708/cf26ebd8-a15f-4259-8ccf-2448290b735b)

### Scenario 2
wagmiConfig's batch size = 1024 * 10
useContractReads's batch size = 1024 * 10
![image](https://github.com/wevm/wagmi/assets/108852708/d4faf1c7-69c5-4c76-832f-1b6976416957)
![image](https://github.com/wevm/wagmi/assets/108852708/a947f0ae-230b-497a-bcf8-3e953d0057a0)

**Result**
4 requests
![image](https://github.com/wevm/wagmi/assets/108852708/3a5cc720-2cf6-46c4-8972-61f6a42d7c9c)

### Expectation
Both scenario should yields the same request counts.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-frqhda?file=src%2FApp.tsx

### Steps To Reproduce

1. Go to https://stackblitz.com/edit/new-wagmi-frqhda?file=src%2FApp.tsx
2. Observe network calls.
3. Uncomment the `batchSize` at `useContractReads`
4. Observe network calls.
5. Compare the call counts.

### Wagmi Version

2.2.1

### Viem Version

2.4.0

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by 1997roylee** [comment]
#3566 Fixed.
