### ISSUE TITLE
hooks fail with 'connection.connector.getProvider is not a function'

### ISSUE THREAD

**Issue by 0xbid** [wevm/wagmi#3491]
### Describe the bug

Periodically, all functions from hooks (e.g. connect, writeContract / writeContractAsync) fails with `connection.connector.getProvider is not a function`.

Most of the time calling it works, but this seems to occur after page refresh.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-gnwhca?file=src%2FApp.tsx - this reproduces my setup, though actually a different error seems to be present, `isConnected` is false even when connected. This may help to show the actual issue though.

### Steps To Reproduce

- Nextjs 13+
- SSR configured

wagmiConfig.ts
```TypeScript
export const wagmiConfig = createConfig({
    // Setup chains
    chains: chains,
    transports: {
        [mainnet.id]: http(),
        [goerli.id]: http(),
        [sepolia.id]: http(),
        [holesky.id]: http()
    },

    // Enable SSR support (needs cookies)
    ssr: true,
    storage: createStorage({
        storage: cookieStorage
    }),

    connectors: [injected()]
});
```

Web3Provider.tsx
```TypeScript
'use client';

// ...

const queryClient = new QueryClient();

const Web3Provider = ({
    children,
    initialState
}: {
    children: React.ReactNode;
    initialState: State;
}) => {
    return (
        <>
            <WagmiProvider config={wagmiConfig} initialState={initialState}>
                <QueryClientProvider client={queryClient}> {children}</QueryClientProvider>
            </WagmiProvider>
        </>
    );
};
```

layout.tsx
```TypeScript
// ...
const initialState = cookieToInitialState(wagmiConfig, headers().get('cookie'));
```

This may also be relevant: I do not use any 3rd party connector (e.g. ConnectKit, Web3Modal, etc). I just do a simple:
```TypeScript
'use client';

// ...

       const { connectors, connect } = useConnect();

        if (!isWalletConnected) {
            try {
                connect({ connector: connectors[0] });
            } catch (e) {
               // ...
            }
        }
```
        

### Wagmi Version

2.3.1

### Viem Version

2.4.0

### TypeScript Version

10.9.1

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

Refreshing the page then trying the action again fixes it.

**Comment by hellno** [comment]
I ran into the same issue and was using the wrong config. I got confused between `getDefaultConfig` from rainbowkit and `createConfig` from @wagmi/core. Might be unrelated to your issue.

**Comment by 0xbid** [comment]
> I ran into the same issue and was using the wrong config. I got confused between `getDefaultConfig` from rainbowkit and `createConfig` from @wagmi/core. Might be unrelated to your issue.

Interesting datapoint though as multiple configurations can lead to this error. In my case I am not even using an official connector, rather just `connectors[0]`.

I'm not super confident in my ability to repo, Ill give it shot later.

**Comment by 0xbid** [comment]
Repro: https://stackblitz.com/edit/new-wagmi-gnwhca?file=src%2FApp.tsx

I learned that `isConnected` is actually still false even when my wallet is connected, which could be the source of the bug.

**Comment by tmm** [comment]
> isConnected is false even when connected

`useConnect` is a mutation hook. You should use [`useAccount().isConnected`](https://wagmi.sh/react/api/hooks/useAccount#isconnecting-isreconnecting-isconnected-isdisconnected) instead.
