### ISSUE TITLE
Closing / clicking outside of MetaMask modal doesn't throw an error

### ISSUE THREAD

**Issue by androidsixteen** [wevm/wagmi#3500]
### Describe the bug

wanted to flag a discrepancy between behavior for different connectors:

when I don't have the MetaMask desktop app enabled, upon connect(), the MetaMask connector shows a modal similar to Coinbase Wallet that has the option to  scan a QR code using their mobile app

if I click out of this however, Wagmi doesn't throw an error the same way it does for Coinbase Wallet

### Steps To Reproduce

Steps to repro:
- Wagmi config should have MetaMask SDK connector
- do *not* have MetaMask browser extension installed/enabled
- connect to MetaMask from application
- at this point, you should see this modal:
<img width="300" alt="MM Modal" src="https://github.com/wevm/wagmi/assets/146510812/955f8e32-921b-4baf-8e53-b32d4718ccb9">

- click outside or close the modal
- Wagmi should throw an error, allowing the app to handle the user rejection, but it doesn't

### Wagmi Version

2.3.1

### Viem Version

2.0.10

### TypeScript Version

5.3.3

### Check existing issues

- [x] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Did some research into this and unfortunately MetaMask [doesn't expose any info](https://github.com/MetaMask/metamask-sdk/blob/b725cfc3dd3edb196685f326f7a935d5b09b4092/packages/sdk/src/ui/InstallModal/InstallModal-web.ts#L86) when you close the connection modal like this so there's nothing we can do on the Wagmi side. You should report this issue upstream https://github.com/MetaMask/metamask-sdk
