### ISSUE TITLE
type inference is not working with @wagmi/cli:2.0.4 wagmi generate

### ISSUE THREAD

**Issue by vmaark** [wevm/wagmi#3505]
### Describe the bug

type inference is not working based on the output of `wagmi generate`. `as const` is missing from the end of the objects.

### Link to Minimal Reproducible Example

https://github.com/vmaark/wagmi-generate-bug

### Steps To Reproduce

`git clone git@github.com:vmaark/wagmi-generate-bug.git`
`pnpm install`
`pnpm generate`

### Wagmi Version

2.0.4

### Viem Version

2.0.0

### TypeScript Version

5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by vmaark** [comment]
the reprodunction repository is a foundry project which does not depend on either wagmi or viem directly, just wagmi/cli. For simplicity I committed the generated typings which won't work in TypeScript due to missing `as const`.

**Comment by tmm** [comment]
The Wagmi CLI only adds const assertions if it detects you are using TypeScript. If you add a `tsconfig.json` file in the project, it will add const assertions.

**Comment by vmaark** [comment]
> The Wagmi CLI only adds const assertions if it detects you are using TypeScript. If you add a `tsconfig.json` file in the project, it will add const assertions.

Thanks for the clarification!

This might be opinionated, but wagmi/cli is the only js dependency I have in my foundry project, of course it's not a big deal to add TypeScript, but considering there's a `wagmi.config.ts` configuration file, it could include a flag to generate it.

**Comment by tmm** [comment]
> but considering there's a wagmi.config.ts configuration file, it could include a flag to generate it.

Good point. Happy to accept a PR adding this. Should be very simple. Just need to update [this function](https://github.com/wevm/wagmi/blob/main/packages/cli/src/utils/getIsUsingTypeScript.ts#L6) to look for a TypeScript Wagmi CLI config file.

**Comment by vmaark** [comment]
> > but considering there's a wagmi.config.ts configuration file, it could include a flag to generate it.
> 
> Good point. Happy to accept a PR adding this. Should be very simple. Just need to update [this function](https://github.com/wevm/wagmi/blob/main/packages/cli/src/utils/getIsUsingTypeScript.ts#L6) to look for a TypeScript Wagmi CLI config file.

https://github.com/wevm/wagmi/pull/3506
