### ISSUE TITLE
Inconsistent address strings

### ISSUE THREAD

**Issue by nbran** [wevm/wagmi#3507]
### Describe the bug

The addresses contained in the address array returned by the useConnect hook change after a wallet updates its addresses. 

I noticed inconsistent behavior when connecting to a MetaMask wallet: The accounts (`Address[]`) in the `data.accounts` object returned by `useConnect` hook change if accounts are added/removed in MetaMask. The change is a small one: the letter case of some of the characters in the addresses changes.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-x4tlxa?file=src%2FApp.tsx

### Steps To Reproduce

1. Connect with MetaMask
2. Select one or more accounts from your wallet
3. Save addresses returned by `data.accounts`
4. In MetaMask, add a new account
5. Reconnect with MetaMask
6. Select the accounts originally selected in step # 2 and the newly one created in step # 5
7. Compare addresses returned by `data.accounts` against those saved in step # 3

### Wagmi Version

2.1.2

### Viem Version

2.0.6

### TypeScript Version

5.0.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

From my own testing:

Before adding an address
![wagmi3](https://github.com/wevm/wagmi/assets/25080013/59a6055a-5434-4816-95c3-ece28e268c47)

After adding an address
![wagmi4](https://github.com/wevm/wagmi/assets/25080013/b69e7278-5631-459d-9c70-40d9939b8377)

In all of my observations the issue has been limited to the last address in the array, which in this example resulted in

`0xd979026e141A2896bD6E52FB3eA230af787e2644`, versus
`0xD979026E141a2896bd6e52FB3eA230Af787E2644`

**Comment by tmm** [comment]
Thanks for the comprehensive issue (love the way you have the table of connectors btw)! Moving this to Viem since it's an issue with the underlying `getAddress` utility. Can track here: https://github.com/wevm/viem/pull/1733

**Comment by tmm** [comment]
Just kidding https://github.com/wevm/viem/pull/1733#issuecomment-1909016659. Re-opening and will have a fix shortly.
