### ISSUE TITLE
Documentation for 0.12.x is not available

### ISSUE THREAD

**Issue by stas** [wevm/wagmi#3513]
### What is the type of issue?

Something else

### What is the issue?

Documentation for 0.12.x was available at https://0.12.x.wagmi.sh, but in fact it show docs for v.1

### Where did you find it?

https://0.12.x.wagmi.sh

**Comment by tmm** [comment]
Here's the [current deployment URL for 0.12.x](https://wagmi-c9sosf44h-wagmi-dev.vercel.app/). Will work on getting that attached to 0.12.x.wagmi.sh. Also, keep in mind you can go through the repo version tags to find the [raw markdown](https://github.com/wevm/wagmi/tree/0.12.x/docs/pages) too.
