### ISSUE TITLE
Bug: next.js dev with --turbo flag, error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by TimonPeng** [wevm/wagmi#3516]
### Describe the bug

![CleanShot 2024-01-26 at 00 34 27@2x](https://github.com/wevm/wagmi/assets/8691151/d24ab5cd-d9ab-42f7-a6da-7430e13fa890)

### Wagmi Version

2.5.2

### Viem Version

2.5.0

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by glitch-txs** [comment]
- make sure you're in the latest version of React Query
- turbo is experimental :v

**Comment by tmm** [comment]
Closing now as there is nothing useful to go off of.
