### ISSUE TITLE
Injected Provider: using okxwallet or okexwallet can't connect with OKX wallet

### ISSUE THREAD

**Issue by Ernest5663** [wevm/wagmi#3521]
### Describe the bug

`export const okxConnector = injected({target: 'okxWallet'})`

using targeted okx wallet, either okxWallet or oKExWallet is not available to connect with the wallet and return ProviderNotFoundError, while using  injected({target: 'metamask'}) is ok to connect with my metamask wallet

### Wagmi Version

2.5.2

### Viem Version

2.5.0

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by glitch-txs** [comment]
You don't even need the injected connector for OKX. Just make sure you're not setting mipd to false.
