### ISSUE TITLE
useBlock hook returns incorrect timestamp for block

### ISSUE THREAD

**Issue by kitanovicd** [wevm/wagmi#3523]
### Describe the bug

I am trying to get some data for specific block such as timestamp. I am using useBlock hook but no matter what block number I provide it always returns timestamp to latest block. I am not sure why it is ignoring block number.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-eyu5tq?file=src%2FApp.tsx

### Steps To Reproduce

In order to reproduce this you can try to fetch block timestamp for some specific block by using useBlock hook. Something like this:
```
  const { data: latestBlockData } = useBlock(latestBlockNumber);
  const { data: prevBlockData } = useBlock(prevBlockNumber);
```
  
 After logging latestBlockData.timestamp and prevBlockData.timestamp you will see that this values are the same even if latestBlockNumber != prevBlockNumber

### Wagmi Version

2.0.3

### Viem Version

2.0.0

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Check out the docs for [`useBlock`](https://wagmi.sh/react/api/hooks/useBlock#blocknumber). You are using the API incorrectly.

**Comment by tmm** [comment]
You were using the API incorrectly before. Separately, there was an issue with passing through hook parameters all the way to Viem. This was fixed by https://github.com/wevm/wagmi/commit/3f8203bd77fcf6b6756640b5971d09741ae3853d
