### ISSUE TITLE
Connector not connected error when passing Viem account from private key

### ISSUE THREAD

**Issue by 0x62** [wevm/wagmi#3531]
### Describe the bug

According to [Private Key & Mnemonic Accounts](https://wagmi.sh/core/guides/viem#private-key-mnemonic-accounts), it's possible to pass a Viem account to the account argument:

```
const account = privateKeyToAccount('0x...') 

const hash = await sendTransaction({ 
  account, 
  to: '0xa5cc3c03994DB5b0d9A5eEdD10CabaB0813678AC',
  value: parseEther('0.001')
})
```

The example doesn't specifically mention it, but based on the type details I'm assuming that this should also be possible for other methods that accept an Account object (like signMessage):

```
const sig = await signMessage(wagmiConfig, {
    message: "test",
    account: privateKeyToAccount(
      "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
    ),
  });
```

However this throws "Connector not connected" error if wagmi is not connected, or an account not found error if connected.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-kmqpfk?file=src%2FApp.tsx

### Wagmi Version

2.x

### Viem Version

2.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
This isn't possible at the moment since the `account` must be attached to the connector. Docs for [`signMessage`](https://wagmi.sh/core/api/actions/signMessage#account):

> Account to use when signing message. Throws if account is not found on [connector](https://wagmi.sh/core/api/actions/signMessage#connector).

**Comment by 0x62** [comment]
The docs here should be updated then: https://wagmi.sh/core/guides/viem#private-key-mnemonic-accounts

> It is possible to utilize Viem's [Private Key & Mnemonic Accounts](https://viem.sh/docs/accounts/local.html) with Wagmi by explicitly passing through the account via the account argument on Wagmi Actions.

**Comment by tmm** [comment]
Thanks for the reminder! Thought you were talking about something else. Will have a PR up shortly to fix this.
