### ISSUE TITLE
Typescript compile error after upgrading from v1 to v2

### ISSUE THREAD

**Issue by call-by** [wevm/wagmi#3534]
### Describe the bug

ERROR in src/config.ts:6:29
TS2554: Expected 0 arguments, but got 1.
     4 | import { injected } from 'wagmi/connectors';
     5 |
  >  6 | const config = createConfig({
       |                             ^
  >  7 |   chains: [optimismSepolia],
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  8 |   connectors: [injected()],
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  9 |   transports: {
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 10 |     [optimismSepolia.id]: http(`https://opt-sepolia.g.alchemy.com/v2/${process.env.REACT_APP_ALCHEMY_ID}`),
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 11 |   },
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 12 | });
       | ^^
    13 |
    14 | export default config;
    15 |

After upgrading from v1 to v2, I'm getting this weird error. After initial upgrade, it was working somehow. I'm not sure if this is related to the node_module/yarn cache issue.
But even after I tried clearing entire node_modules, upgrading to the latest 2.5.4, I'm consistently getting this error.
Do you have any thoughts about this? BTW, I'm using create-react-app@5.0.1.

### Wagmi Version

2.5.4

### Viem Version

2.5.0

### TypeScript Version

4.9.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Wagmi required [TypeScript >=5.0.4](https://wagmi.sh/react/typescript#requirements).
