### ISSUE TITLE
In Vite, importing @wagmi/connectors triggers a warning. “Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code.”

### ISSUE THREAD

**Issue by 597800451** [wevm/wagmi#3553]
### Describe the bug

I just imported @wagmi/connectors in my Vite Vue project, and without doing anything else, a warning is triggered in the browser. It seems to be specifically related to the Coinbase Wallet SDK.

![image](https://github.com/wevm/wagmi/assets/5043738/564ae311-7300-40a5-9b30-ca7d1b2cc7d6)

"dependencies": {
    "@wagmi/connectors": "^4.1.12",
    "@wagmi/core": "^2.6.3",
    "viem": "^2.7.1"
  },

### Wagmi Version

2.6.3

### Viem Version

2.7.1

### TypeScript Version

vite vue javascript

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
[You need to shim `Buffer`](https://github.com/wevm/wagmi/blob/fb55e1d9734dedc368d2c1ed0c93b91178887c55/playgrounds/vite-core/src/main.tsx#L8)

**Comment by 597800451** [comment]
Alright, but I haven't considered using Coinbase Wallet. I mean, I just want to introduce 'injected,' but it still triggers this warning. Of course, I can just ignore it

**Comment by tmm** [comment]
Please provide a minimal reproduction then and I am happy to take a look.

**Comment by 597800451** [comment]
https://stackblitz.com/edit/vitejs-vite-yrx3xu?file=src%2FApp.vue

![image](https://github.com/wevm/wagmi/assets/5043738/4c97436d-1320-4c50-93e8-e888323433a2)
