### ISSUE TITLE
Crash Extension when use WagmiProvider in Content scripts but work in popup scripts

### ISSUE THREAD

**Issue by conghbnb** [wevm/wagmi#3556]
### Describe the bug

Uncaught (in promise) TypeError: Cannot destructure property 'info' of 'providerDetail' as it is null.

### Wagmi Version

2.2.1

### Viem Version

2.x

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by jxom** [comment]
You might need to disable `multiInjectedProviderDiscovery` on the Wagmi Config.

**Comment by conghbnb** [comment]
> You might need to disable `multiInjectedProviderDiscovery` on the Wagmi Config.

many thanks, it's work for me
