### ISSUE TITLE
Missing some query properties QueryParameter, omitted in typescript, but not mentioned anything about that in the docs.

### ISSUE THREAD

**Issue by WingsDevelopment** [wevm/wagmi#3564]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

The documentation links to `useQuery` from the React-Query documentation but does not mention anything about omitting some properties.

Documentation:

query
TanStack Query parameters. See the [TanStack Query query docs](https://tanstack.com/query/v5/docs/react/reference/useQuery) for more info.

Here is a typescript code for query paramaters:
```
export type QueryParameter<
  queryFnData = unknown,
  error = DefaultError,
  data = queryFnData,
  queryKey extends QueryKey = QueryKey,
> = {
  query?:
    | Omit<
        UseQueryParameters<queryFnData, error, data, queryKey>,
        'queryFn' | 'queryHash' | 'queryKey' | 'queryKeyHashFn' | 'throwOnError'
      >
    | undefined
}
```

I am curious about why these properties are omitted. Can I use them regardless?

For instance, will setting queryKey work or not?

**Library version**: "wagmi": "^2.5.4"

### Where did you find it?

https://wagmi.sh/react/api/hooks/useReadContract

query section

typescript code is found:
wagmi/src/types/properties.ts > QueryParameter

**Comment by tmm** [comment]
[Added](https://github.com/wevm/wagmi/commit/2d403889beba65640ef3288b113c28393ffdceda) a note to the docs. These properties are omitted because they are used internally to make Wagmi work.
