### ISSUE TITLE
Cannot create wagmi project

### ISSUE THREAD

**Issue by henrygagnier** [wevm/wagmi#3573]
### Describe the bug

```
PS C:\Users\hg585\OneDrive\Desktop\AnchorUSD\website> npm init wagmi
'wagmi' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path C:\Users\hg585\OneDrive\Desktop\AnchorUSD\website
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c wagmi

npm ERR! A complete log of this run can be found in: C:\Users\hg585\AppData\Local\npm-cache\_logs\2024-02-07T02_31_45_350Z-debug-0.log
PS C:\Users\hg585\OneDrive\Desktop\AnchorUSD\website>
 ```
```
{
  "dependencies": {
    "@tanstack/react-query": "^5.18.1",
    "viem": "^2.7.6",
    "wagmi": "^2.5.6"
  }
}
```

### Link to Minimal Reproducible Example

N/A

### Steps To Reproduce

There is not much to reproduce as I have not created a project yet. I have used wagmi v1 for projects just fine in the past. Is this an NPM issue?

I also tried to create a project manually (next.js) but was getting loads of errors when I installed and used wagmi.

I also installed the latest version of NPM.

### Wagmi Version

2.5.6

### Viem Version

2.7.6

### TypeScript Version

^5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by glitch-txs** [comment]
```
pnpm create wagmi
```
