### ISSUE TITLE
Sign message happens several times when firing on connecting wallet

### ISSUE THREAD

**Issue by kingnight153** [wevm/wagmi#3574]
### Describe the bug

I tried to automatically signing message with useAccount hook:
```
  const { connector: activeConnector }  = useAccount({
    onConnect: () => {
      signMessage()
    }
  })
```
But it fired 4 times at once (attached image is for Metamask, but it happens for others as well):
<img width="371" alt="image" src="https://github.com/wevm/wagmi/assets/68669216/3aac0b93-26ba-4180-a001-4d1c5a2c5c01">

### Wagmi Version

1.4.13

### Viem Version

1.21.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Try Wagmi v2

**Comment by kingnight153** [comment]
Tried. But not work as well

**Comment by kingnight153** [comment]
```
  useAccountEffect({
    onConnect(data) {
      console.log('Connected!', data)
        signMessage({
          message: DEFAULT_PUBLIC_KEY_MESSAGE
        })
    },
  })
```
