### ISSUE TITLE
EtherscanConfig missing the optimismSepolia api url

### ISSUE THREAD

**Issue by FaisalAli19** [wevm/wagmi#3578]
### Describe the bug

Hello,

I am using the etherscan plugin to get the read and write function from the contract from optimism sepolia testnet. But typescript keep throwing this warning

`The expected type comes from property 'chainId' which is declared here on type 'EtherscanConfig<1 | 5 | 11155111 | 10 | 420 | 137 | 80001 | 42161 | 421613 | 56 | 97 | 128 | 256 | 250 | 4002 | 43114 | 43113 | 42220 | 44787>'`

And If i run the wagmi generate command I get this error

<img width="439" alt="Screenshot 2024-02-08 at 1 08 39 AM" src="https://github.com/wevm/wagmi/assets/20942500/23849f77-afdd-4976-a6ee-e60cb6db2d8f">

After debugging the code I found that Etherscan API key is missing the optimism sepolia API key.

<img width="855" alt="Screenshot 2024-02-08 at 12 59 40 AM" src="https://github.com/wevm/wagmi/assets/20942500/ee76f081-7181-4585-acdc-ce7e2f25e0f4">

Thanks in advance.

### Steps To Reproduce

```
import { defineConfig } from '@wagmi/cli';
import { actions, etherscan, react } from '@wagmi/cli/plugins';
import { optimismSepolia } from 'wagmi/chains';
import "dotenv/config";

export default defineConfig({
  out: 'src/generated.ts',
  contracts: [],
  plugins: [
    etherscan({
      apiKey: process.env.ETHERSCAN_API_KEY!,
      chainId: optimismSepolia.id,
      contracts: [
        {
          name: 'uSwap',
          address: {
            [optimismSepolia.id]: process.env.CONTRACT_ADDRESS as `0x${string}`,
          },
        },
      ],
    }),
    react(),
    actions({
      readContract: true,
    }),
  ],
});

```

### Wagmi Version

1

### Viem Version

1

### TypeScript Version

^5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Feel free to open a PR adding this to `@wagmi/cli@2`
