### ISSUE TITLE
Coinbase Wallet first connection issue with some chains

### ISSUE THREAD

**Issue by mmaurello** [wevm/wagmi#3585]
### Describe the bug

For some chains, using the `coinbaseWallet` connector doesn't work for the first connection, but clicking a second time does the trick.

Not sure if it is a problem from wagmi/connectors or something specific for Coinbase Wallet

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-3rarhp?file=src%2Fwagmi.ts

### Steps To Reproduce

Using the Coinbase Wallet browser extension:
1- Click on the CoinbaseWallet button to connect
2- Sign the connection in the browser extension, notice that it says "Connected"
3- note that in the app, it still shows as disconnected
4- Click on the CoinbaseWallet again and this time there is a successful connection
5- If you disconnect and try to connect again, the issue starts over from point 1

### Wagmi Version

2.5.6

### Viem Version

2.7.3

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

I managed to overcome this in my app by adding a reconnection on error when connecting to the coinbaseWallet connector, so it is not very critical, but still will be nice to know the source of the issue

**Comment by tmm** [comment]
> For some chains

For what chains specifically?

**Comment by mmaurello** [comment]
The one in the example, `moonbeam`, but also all the rest I tried that come from the polkadot exosystem. `moonriver`, `moonbaseAlpha`, `acala`, `karura`, `astar`,
