### ISSUE TITLE
Workaround for Vite dev dynamic import of `CoinbaseWalletSDK` introduced in PR #473 is needed again

### ISSUE THREAD

**Issue by wonu** [wevm/wagmi#3586]
### Describe the bug

Issue #383's problem has resurfaced since commit [895f28e](https://github.com/wevm/wagmi/commit/895f28e873af7c8eda5ca85734ff67c8979fd950#diff-b05598fc1a520e04372175e02a71b5110937ac12bb448dd939b163f5ad8ee463).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-jxnjko

### Steps To Reproduce

1. https://vite.new/react-ts (StackBlitz with Vite react-ts template)
2. npm install wagmi viem@2.x @tanstack/react-query
3. default setup as [docs](https://wagmi.sh/react/getting-started) says
4. `TypeError: CoinbaseWalletSDK is not a constructor` occurs in console and the button is unresponsive.

If install `wagmi@2.5.5` instead `latest(2.5.6)` it works well. (except that it requires click the button twice..)

### Wagmi Version

2.5.6

### Viem Version

2.7.8

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by chybisov** [comment]
We also experience this issue. Also, when there is an error `TypeError: CoinbaseWalletSDK is not a constructor,` reconnect functionality stops working because when we iterate through the connectors and we have an error, there is no catch block to handle it. 

<img width="946" alt="image" src="https://github.com/wevm/wagmi/assets/18644653/fe711876-087f-464f-8a2f-19cd238e5bc4">

https://github.com/wevm/wagmi/blob/main/packages/core/src/actions/reconnect.ts#L68

**Comment by enesozturk** [comment]
+1 confirming that having the same error with `wagmi@2.5.6` but not with `wagmi@2.5.5`.

Stack trace:
```js
Uncaught (in promise) TypeError: CoinbaseWalletSDK is not a constructor
    at Object.getProvider (@web3modal_wagmi.js?v=e91df78f:148:15)
    at async reconnect (chunk-SA6P325H.js?v=15838233:2350:23)
    getProvider                 @ @web3modal wagmi. js?v=e91df78f: 148
    await in getProvider (async)
    onMount                     @ chunk-SA6P325H.js?v=15838233:2890
    Hydrate                     @ wagmi.js?v=ac9173bf:296
    renderWithHooks             @ react-dom client.js?v=ff4dfOda:19183
    mountIndeterminateComponent @ react-dom client.js?v=ff4df0da: 21912

```
