### ISSUE TITLE
useChains is not exported, though it is documented

### ISSUE THREAD

**Issue by Dzivenu** [wevm/wagmi#3587]
### Describe the bug

Your docs show **useChains** as an available method, but it is not exported.

Here is my import:
![image (2)](https://github.com/wevm/wagmi/assets/19816720/79548414-2f55-4aee-88d5-3f53c287adde)

And here is the error from Vite:
![image (1)](https://github.com/wevm/wagmi/assets/19816720/1877a74e-3aed-482e-bf4e-58e4b3bf5f2b)

**useChains** is documented, here is the docs: https://wagmi.sh/react/api/hooks/useChains

Interestingly, in the version in Github, you find it exported but in the version on npm it is not.

Here is the export in Github: https://github.com/wevm/wagmi/blob/main/packages/react/src/exports/index.ts#L83

Here are the exports from NPM, wagmi version 2.5.6. notice there is no export of **useChains**.
![wagmi-npm](https://github.com/wevm/wagmi/assets/19816720/6a41f66c-9c32-40b9-b7fb-9ea025041a85)

### Steps To Reproduce

Follow the manual installation guide as detailed here: https://wagmi.sh/react/getting-started#manual-installation

> 

- > `yarn add wagmi viem@2.x @tanstack/react-query`
- > `import { useChains } from 'wagmi'`

### Wagmi Version

2.5.6

### Viem Version

2.x

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by henrygagnier** [comment]
I was just about to make an issue for this! Getting the same issue, while other parts of wagmi are working just fine.

`import { useChains } from 'wagmi'`
`'"wagmi"' has no exported member named 'useChains'. Did you mean 'useChainId'?`

**Comment by tmm** [comment]
Will be released by https://github.com/wevm/wagmi/pull/3581
