### ISSUE TITLE
Error: connection.connector.getProvider is not a function

### ISSUE THREAD

**Issue by 0xbid** [wevm/wagmi#3589]
### Describe the bug

Periodically, all functions from hooks (e.g. connect, writeContract / writeContractAsync) fails with connection.connector.getProvider is not a function.

Refreshing page fixes it.

It only occurs with *Rabby wallet*, Metamask stays connected always and does not run into the issue.

### Steps To Reproduce

Nextjs 13+
SSR configured

wagmiConfig.ts
```ts
export const wagmiConfig = createConfig({
    // Setup chains
    chains: chains,
    transports: {
        [mainnet.id]: http(),
        [goerli.id]: http(),
        [sepolia.id]: http(),
        [holesky.id]: http()
    },

    // Enable SSR support (needs cookies)
    ssr: true,
    storage: createStorage({
        storage: cookieStorage
    }),

    connectors: [injected()]
});
```

Web3Provider.tsx
```ts
'use client';

// ...

const queryClient = new QueryClient();

const Web3Provider = ({
    children,
    initialState
}: {
    children: React.ReactNode;
    initialState: State;
}) => {
    return (
        <>
            <WagmiProvider config={wagmiConfig} initialState={initialState}>
                <QueryClientProvider client={queryClient}> {children}</QueryClientProvider>
            </WagmiProvider>
        </>
    );
};
```

layout.tsx
```ts
// ...
const initialState = cookieToInitialState(wagmiConfig, headers().get('cookie'));
This may also be relevant: I do not use any 3rd party connector (e.g. ConnectKit, Web3Modal, etc). I just do a simple:

'use client';

// ...

       const { connectors, connect } = useConnect();

        if (!isWalletConnected) {
            try {
                connect({ connector: connectors[0] });
            } catch (e) {
               // ...
            }
        }
 ```

### Wagmi Version

2.3.1

### Viem Version

2.4.0

### TypeScript Version

10.9.1

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

I think it would be really helpful to know more about how `connection.connector.getProvider` could occur from a dev perspective, e.g. what is going on. Then we can narrow down why it doesn't work with Rabby.

**Comment by tmm** [comment]
Please try the latest version of Wagmi. If that doesn't work, then happy to take a look into this.

**Comment by 0xbid** [comment]
> Please try the latest version of Wagmi. If that doesn't work, then happy to take a look into this.

I've updated to the most recent versions:
```json
    "viem": "^2.7.8",
    "wagmi": "^2.5.7"
```

And still regularly hit the issue.

It would be great if you could look into it further, let me know if you would like any more details.

**Comment by shunkakinoki** [comment]
Get the same issue here w/ the latest versions!

**Comment by glitch-txs** [comment]
wer repro 👀

**Comment by shunkakinoki** [comment]
In my case, it was a wrong `wagmiConfig` - fixed it with proper config, apologies for the confusion 🙌

**Comment by 0xbid** [comment]
> In my case, it was a wrong `wagmiConfig` - fixed it with proper config, apologies for the confusion 🙌

What was wrong? Can you post your previous wagmiConfig and new one?

**Comment by 0xbid** [comment]
@shunkakinoki can you explain what you did? 🙏

**Comment by mlenser** [comment]
We've had this same issue for a while. We're following the setup on https://docs.walletconnect.com/web3modal/nextjs/about.

@shunkakinoki any idea what was wrong in the config?

**Comment by 0xbid** [comment]
Experience has been the same here, after more thorough testing we realized that it occurs on all wallets. However, Rabby definitely hits it the most. I suspect something to do with chains / chain switching.

**Comment by 0xbid** [comment]
my code is just:
```
import { defaultWagmiConfig } from '@web3modal/wagmi/react/config';
import { cookieStorage, createStorage } from 'wagmi';
import { mainnet, goerli, sepolia, holesky } from 'wagmi/chains';

export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID;

if (!projectId) throw new Error('Project ID is not defined');

// Create wagmiConfig
export const wagmiConfig = defaultWagmiConfig({
    chains: [mainnet, goerli, sepolia],
    projectId, // required

    ssr: true,
    storage: createStorage({
        storage: cookieStorage
    })
});
```

**Comment by duytien-ortho** [comment]
I have same error here, my app use both pages router and app router. I had to change to config of provider for app to same in _app.tsx in pages router, and then it work
`
export const wagmiConfig = createConfig({
  chains: [sepolia, mainnet],
  transports: {
    [sepolia.id]: http(alchemyHttpUrl),
    [mainnet.id]: http(alchemyHttpUrl),
  },
  ssr: false,
  connectors: [
    walletConnect({
      projectId,
      showQrModal: false,
      metadata: metadata,
    }),
    injected({
      shimDisconnect: true,
    }),
  ],
});
`

**Comment by codedbyjordan** [comment]
getting the same issue after setting up with WalletConnect through their guide with Next.js 14

**Comment by Robarelli** [comment]
I'm having the same issue, using the latest versions of wagmi and viem as of today. Setup exactly as described in the docs. Only difference is that I'm using the defaultWagmiConfig from Web3Modal which I believe just wraps createConfig anyways:

```
  const config = defaultWagmiConfig({
    chains: [{...primaryNetwork, rpcUrls}],
    projectId: projectId!,
    metadata,
    ssr: true,
    storage: createStorage({
      storage: cookieStorage
    })
  });
```

I did try the suggestion from @maggo which was to set ssr to false, but that caused a lot of performance issues with page rendering, so I don't believe that to be a working solution for this.

**Comment by jxom** [comment]
^ please provide a reproduction with _only_ the `wagmi` dependency.

**Comment by 0xbid** [comment]
> ^ please provide a reproduction with _only_ the `wagmi` dependency.

I am pretty sure it can be reproduced with any Nextjs style setup (using SSR). The Next example would work.

The key seems to be when in development mode (e.g. `npm run dev`) when making code changes that would cause the page to re-build, this triggers. I think @maggo has outlined the issue well with a consistent way to reproduce.

**Comment by jxom** [comment]
Might be worth trying again. I made some updates today to improve SSR hydration.
