### ISSUE TITLE
useDisconnect does not disconnect browser extension

### ISSUE THREAD

**Issue by epleaner** [wevm/wagmi#3600]
### Describe the bug

I am using the Connect Wallet example shown in the official docs (https://wagmi.sh/examples/connect-wallet).

After I have clicked Metamask and connected my account via the Metamask browser extension, I see my wallet in the example UI as connected and a button to Disconnect. When I click Disconnect, I am shown the list of connectors again, but my Metamask browser extension shows that my account is still connected.

I expect my account to be disconnected in my Metamask browser extension after pressing Disconnect – and, vis-à-vis in code, after calling disconnect().

### Link to Minimal Reproducible Example

https://wagmi.sh/examples/connect-wallet

### Wagmi Version

2.0.3

### Viem Version

2.0.3

### TypeScript Version

5.0.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
See https://github.com/wevm/wagmi/issues/69#issuecomment-1011131480
