### ISSUE TITLE
Update useReadContract Example To Show Tanstack Params

### ISSUE THREAD

**Issue by codingwithmanny** [wevm/wagmi#3617]
### What is the type of issue?

Something else

### What is the issue?

# Context

This may be opinionated, but I believe that this will help new devs understand tanstack a bit better, and avoid multiple triggered RPC requests sent and prevent being rate limited, and ultimately create a slightly better development process.

The initial example for [useReadContract](https://wagmi.sh/react/api/hooks/useReadContract#usage) shows how a hook that fires the request right away. The dilemma is when a developer has multiple useReadContracts in the same file and aren't seeing how to avoid triggering a request right away.

This can then lead to developers handling the hook with another hook (aka `useEffect`) or placing each of these `useReadContract` hooks in their own components and not showing it until it's absolutely needed, which leads to excessive React components.

_Example_

```tsx
  {anotherContractResult?.data
     ? <DependentComponentThatMakesAnotherContractRead}
     : null
  }
```

From an RPC perspective, if the app is reliant on the injected provider, and has multiple requests, there is a good chance that they will start to get rate limited because of mishandling of requests.

# Proposed Solution

Show in the usage section, another example with "controlled requests" / "alternative approach" (open to suggestions on the name) to show that new devs don't have to overcome this with additional hooks, or multiple components.

```tsx
import { useReadContract } from 'wagmi'
import { abi } from './abi'

function App() {
  const result = useReadContract({
    abi,
    address: '0x6b175474e89094c44da98b954eedeac495271d0f',
    functionName: 'totalSupply',
  },
  {
    enabled: false // Tanstack config to prevent the request from being triggered onload
  });

  const onClickButton = () => {
    result.refetch();
  };

  return <>
    <button onClick={onClickButton}>Fetch</button>
  </>; 
}
```

### Where did you find it?

- https://wagmi.sh/react/api/hooks/useReadContract
- https://wagmi.sh/react/api/hooks/useReadContracts
- https://wagmi.sh/react/api/hooks/usePrepareTransactionRequest
- https://wagmi.sh/react/api/hooks/useBalance
- etc

**Comment by tmm** [comment]
Seems like the thing that trips folks up (or at least what we see a lot) is setting `args` dynamically, e.g. with `useState`. Think it makes the most sense to add a section with this to the [TanStack Query](https://wagmi.sh/react/guides/tanstack-query) section of the docs.

**Comment by tmm** [comment]
Yeah down for linking to it somewhere. Also, not all hooks use TanStack Query, e.g. `useAccount`, `useConfig`, `useClient`, but point taken!

**Comment by codingwithmanny** [comment]
Definitely open to having anything mentioned or emphasized, to get devs just use the idea that they can control hooks/requests better.

**Comment by tmm** [comment]
We mention TanStack Query in a bunch of places already and it's the [first guide](https://wagmi.sh/react/guides/tanstack-query) in the guides section so closing this for now. Feel free to open a PR with something more actionable. Incomplete list of places it's mentioned:

- [Why Wagmi](https://wagmi.sh/react/why#performance)
- [Installation](https://wagmi.sh/react/installation#package-manager)
- [Getting Started > Installation](https://wagmi.sh/react/getting-started#manual-installation)
- [Getting Started > Setup](https://wagmi.sh/react/getting-started#setup-tanstack-query)
- [TanStack Query guide](https://wagmi.sh/react/guides/tanstack-query)
- [FAQ > How does Wagmi work?](https://wagmi.sh/react/guides/faq#how-does-wagmi-work)
- [`query` property on individual hooks](https://wagmi.sh/react/api/hooks/useReadContract#query)
- [TanStack Query exports for individual hooks](https://wagmi.sh/react/api/hooks/useReadContract#tanstack-query)
