### ISSUE TITLE
Setting a cookie in Next.js in a server action causes a Hydrate warning and wagmi stays in "reconnecting"

### ISSUE THREAD

**Issue by smauret** [wevm/wagmi#3629]
### Describe the bug

When a server action sets a cookie with `cookies().set("myCookie", "value")` and wagmi is setup using a cookie store, then after the action has been performed, a warning is thrown and wagmi is stuck in `reconnecting` status:

```js
Warning: Cannot update a component (`Page`) while rendering a different component (`Hydrate`). To locate the bad setState() call inside `Hydrate`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at Hydrate (webpack-internal:///(app-pages-browser)/./node_modules/wagmi/dist/esm/hydrate.js:12:13)
    at WagmiProvider (webpack-internal:///(app-pages-browser)/./node_modules/wagmi/dist/esm/context.js:13:13)
    at Providers (webpack-internal:///(app-pages-browser)/./app/providers.tsx:39:11)
    at body
    at html
```

The only way to get wagmi to reconnect is to refresh the page.

I have created a [repo](https://github.com/smauret/wagmi-next-bug-repro) with minimum setup to reproduce.

### Link to Minimal Reproducible Example

https://github.com/smauret/wagmi-next-bug-repro

### Steps To Reproduce

1. Setup wagmi with a cookie store
2. Trigger a server action that sets a cookie
3. See warning in browser console + wagmi account status stays "reconnecting"

### Wagmi Version

2.5.7

### Viem Version

2.7.3

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

There are a couple of similar issues, and they might all be related, but this issue specifically uses the wagmi cookie store and setting cookies.
The cookie setup is slightly different than in the docs because I use rainbowkit (explanation [here](https://github.com/rainbow-me/rainbowkit/issues/1777#issuecomment-1959525167)) and I don't believe that is an issue.

**Comment by jxom** [comment]
Fixed
