### ISSUE TITLE
Type error: Type parameter declaration expected.

### ISSUE THREAD

**Issue by Vlad7is7lav** [wevm/wagmi#3630]
### Describe the bug

I try to build Next app but get next error
![изображение](https://github.com/wevm/wagmi/assets/59703093/d8732218-6f37-4724-836e-83897083c2a7)

My package.json looks: 
![изображение](https://github.com/wevm/wagmi/assets/59703093/2e2ca912-d9bf-416d-a404-e551a5cd4bc8)

And _app.tsx
![изображение](https://github.com/wevm/wagmi/assets/59703093/57662f35-911c-4c75-bbf3-3ab612d82775)

Can anybody to help me?

### Wagmi Version

2.5.6

### Viem Version

2.7.6

### TypeScript Version

4.8.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Incorrect TypeScript version. Read the docs.
