### ISSUE TITLE
Runtime error after minifying: Custom Account Abstractions walletClients are not working.

### ISSUE THREAD

**Issue by johanneskares** [wevm/wagmi#3640]
### Describe the bug

I'm using an external walletClient from a different package `@zerodev`. I'm using it inside a custom wagmi connector. The special case about this walletClient is, that it doesn't have a `signTransaction` function implemented, only `sendTransaction`, as this is not possible with Account Abstraction Wallets to sign a transaction without sending.

In my case I was trying to use the simple `useSendTransaction` hook. I had this really weird behaviour where the code was working as expected in `dev` mode, but after building it (Next.js) I got a runtime error. After quite some digging, I found out why.

I pinned it down to this line:
https://github.com/wevm/wagmi/blob/b1a84627dc814563b4874a514b10942d6f15b56b/packages/core/src/utils/getAction.ts#L34

In my case, `actionFn.name` had a value of `w` (probably the minified function name) and `name` had a value of `sendTransaction`. `actionFn.name` was not `null` or `undefined`. So I was always using the fallback function. 

The fallback `sendTransaction` implementation uses `signTransaction` internally, which is not implemented in Account Abstraction Clients, that's why I got the error.

### Steps To Reproduce

- Return a walletClient from a custom connector that doesn't implement `signTransaction `, only `sendTransaction`
- Try to send a transaction with e.g. `useSendTransaction`

### Wagmi Version

2.5.7

### Viem Version

2.7.14

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by johanneskares** [comment]
I fixed it here:
https://github.com/wevm/wagmi/pull/3642

Would be great if this could be merged, I'm running a patched version at the moment.

**Comment by MrKampla** [comment]
I also have a similar error, but with `writeContract` action:
```
TransactionExecutionError: A smart account cannot sign or send transaction, it can only sign message or userOperation.
Please send user operation instead.
Version: viem@2.7.22
    at getTransactionError (getTransactionError.js:18:12)
    at sendTransaction (sendTransaction.js:144:105)
    at async writeContract (writeContract.js:38:18)
```
I have a next.js project, I've created a kernel smart account client using permissionless.js, and I'm using `useWriteContract` hook in order to call a function on a smart contract. The funny thing is that it works flawlessly for `sendTransaction`action, so I doubt it's "permissionless" lib's fault.
Any ideas what might be causing this?

**Comment by johanneskares** [comment]
I'm pretty sure these are related, because there's some problems where wagmi uses the fallback implementations of the client, not original ones from the AA client. These fallback implementations are not compatible with how Smart Wallets work (e.g. `signTransaction` doesn't work on a smart account client, since the transaction can only be bundled by the bundler.)
