### ISSUE TITLE
Missing viem chains on Wagmi

### ISSUE THREAD

**Issue by Fluffynorth** [wevm/wagmi#3646]
### Describe the bug

Phoenix is showing on viem but cant acces it on wagmi 
https://github.com/wevm/viem/blob/main/src/chains/definitions/phoenix.ts

### Wagmi Version

2.5.7

### Viem Version

2.7.13

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Upgrade your Viem verson.
