### ISSUE TITLE
sending transactions does not appear to work on Base (??) 

### ISSUE THREAD

**Issue by crazyrabbitLTC** [wevm/wagmi#3649]
### Describe the bug

Attempting to use the hook "useSendTransaction" does not pop up a wallet confirmation modal when on Base. The same code, but when used on Mainnet Ethereum will work fine. 

I also was unable to get "useContractWrite" to work when on Base.  I'm getting no response from my browser wallet (I tested Metamask and Brave).

### Link to Minimal Reproducible Example

https://github.com/crazyrabbitLTC/wagmi-bug-demo

### Steps To Reproduce

Steps I took are: 

I created a new project using: 

`pnpm create wagmi`

I edited the `wagmi.ts` file to look like this (I added Base) 

```import { http, createConfig } from 'wagmi'
import { mainnet, sepolia, base } from 'wagmi/chains'
import { coinbaseWallet, injected, walletConnect } from 'wagmi/connectors'

export const config = createConfig({
  chains: [base],
  connectors: [
    injected(),
    coinbaseWallet({ appName: 'Create Wagmi' }),
    // walletConnect({ projectId: process.env.NEXT_PUBLIC_WC_PROJECT_ID }),
  ],
  ssr: true,
  transports: {
    [base.id]: http(),
    [mainnet.id]: http(),
  },
})

declare module 'wagmi' {
  interface Register {
    config: typeof config
  }
}
```

Then I added the component `SendTransaction` to `page.tsx` in the `app` folder. 

```function SendTransaction() {
  const { 
    data: hash, 
    isPending, 
    sendTransaction 
  } = useSendTransaction() 

  async function submit(e: React.FormEvent<HTMLFormElement>) { 
    e.preventDefault() 
    const formData = new FormData(e.target as HTMLFormElement) 
    const to = formData.get('address') as `0x${string}` 
    const value = formData.get('value') as string 
    sendTransaction({ to, value: parseEther(value) }) 
  } 

  return (
    <form onSubmit={submit}>
      <input name="address" placeholder="0xA0Cf…251e" required />
      <input name="value" placeholder="0.05" required />
      <button 
        disabled={isPending} 
        type="submit"
      >
        Send 
        {isPending ? 'Confirming...' : 'Send'} 
      </button>
      {hash && <div>Transaction Hash: {hash}</div>} 
    </form>
  )
}```

It looks like this: 

```'use client'

import { useAccount, useConnect, useDisconnect, useSendTransaction } from 'wagmi'
import { parseEther} from 'viem'

function App() {
  const account = useAccount()
  const { connectors, connect, status, error } = useConnect()
  const { disconnect } = useDisconnect()

  return (
    <>
      <div>
        <h2>Account</h2>

        <div>
          status: {account.status}
          <br />
          addresses: {JSON.stringify(account.addresses)}
          <br />
          chainId: {account.chainId}
        </div>

        {account.status === 'connected' && (
          <button type="button" onClick={() => disconnect()}>
            Disconnect
          </button>
        )}
      </div>
      <SendTransaction/>

      <div>
        <h2>Connect</h2>
        {connectors.map((connector) => (
          <button
            key={connector.uid}
            onClick={() => connect({ connector })}
            type="button"
          >
            {connector.name}
          </button>
        ))}
        <div>{status}</div>
        <div>{error?.message}</div>
      </div>
    </>
  )
}
function SendTransaction() {
  const { 
    data: hash, 
    isPending, 
    sendTransaction 
  } = useSendTransaction() 

  async function submit(e: React.FormEvent<HTMLFormElement>) { 
    e.preventDefault() 
    const formData = new FormData(e.target as HTMLFormElement) 
    const to = formData.get('address') as `0x${string}` 
    const value = formData.get('value') as string 
    sendTransaction({ to, value: parseEther(value) }) 
  } 

  return (
    <form onSubmit={submit}>
      <input name="address" placeholder="0xA0Cf…251e" required />
      <input name="value" placeholder="0.05" required />
      <button 
        disabled={isPending} 
        type="submit"
      >
        Send 
        {isPending ? 'Confirming...' : 'Send'} 
      </button>
      {hash && <div>Transaction Hash: {hash}</div>} 
    </form>
  )
}

export default App
```

When on mainnet, the `sendTransaction` function works as expected, popping up the Metamask modal. However when connect to Base (and the wallet manually selected to base), it does not do anything. Console.log does not help to figure out what is happening either, it seems to not react. 

### Wagmi Version

"latest"

### Viem Version

"latest"

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

I tried searching to see if there was anything related to using Base as opposed to Mainnet ethereum, any differences i needed to keep in account and I didn't find anything.

**Comment by rcbgr** [comment]
Can you add your browser version and extension version? I'm not able to recreate w/ MetaMask

**Comment by crazyrabbitLTC** [comment]
For Chrome I'm on Version 121.0.6167.184 (Official Build) (arm64) and Metamask 11.7.5.

For Brave [Version 1.62.165 Chromium: 121.0.6167.184 (Official Build) (arm64)](https://brave.com/latest/) (although I notice it's asking me to upgrade)

**Comment by crazyrabbitLTC** [comment]
Adding a "I swear I'm not crazy" video demo of whats happening. 
https://github.com/wevm/wagmi/assets/1938013/d8bac1fd-4164-4817-b106-ddd6a873ea2a

**Comment by crazyrabbitLTC** [comment]
Update: So in the example I have uploaded, I'm actually *only* able to do the send while connected to mainnet, any other network fails. In this case I only have "Base" enabled in the example code.

**Comment by rcbgr** [comment]
ha. we will get to the bottom of this. if you haven't connected with will, can you display the developer console in the video, so what we can see the error? did you manually add base in metamask or select it from their network list? i'm on the same version of metamask and mine is showing the blue dot next to the network

**Comment by crazyrabbitLTC** [comment]
Interesting! Theres nothing in the console, even if I wrap in a try catch I don't catch any error. I didn't think about HOW I added base to my metamask, is there a preferred recommended tool to do that?

**Comment by crazyrabbitLTC** [comment]
Oh I'm wrong there is an error in the console (I just removed Base and added it again via Metamask)

```{
    "code": -32603,
    "message": "Internal JSON-RPC error.",
    "data": {
        "code": -32000,
        "message": "failed with 600000000 gas: insufficient funds for gas * price + value: address 0x17403889<<MyAddressHere>>B00c have 3450068968123456 want 10000000000000000",
        "cause": null
    }
}```

Thats more familiar, however, in my experience thats not a reason to not pop up the metamask. So something is still happening there. 

Also, when I experiment with `useWriteContract` hook, it still won't pop anything up in the metamask, however it legitimately does not put any error in the console at all.

**Comment by taycaldwell** [comment]
> Interesting! Theres nothing in the console, even if I wrap in a try catch I don't catch any error. I didn't think about HOW I added base to my metamask, is there a preferred recommended tool to do that?

Base Mainnet is included in MetaMask by default. If you have to add it manually you may need to update your MetaMask extension.

**Comment by taycaldwell** [comment]
If you are adding it manually as a custom network, what RPC url and configuration are you using?

is the wallet address you are connected with funded with ETH on Base Mainnet to cover gas fees?

**Comment by crazyrabbitLTC** [comment]
@taycaldwell - Metamask autoupdates itself, but I did remove base and re-add it and now it looks like how you would expect "blue circle", however, it still not working. 

When I have no funds, in this example code, metamask does not pop up. This is not the correct behavior though, if I don't have enough funds, metamask should pop up and tell me I don't have enough funds. 

In a second example I have on my machine, when I try to use "useContractWrite", having funds does not impact the fact that the pop up does not show up.

**Comment by crazyrabbitLTC** [comment]
I updated the example that won't run on my machine with a "useContractWrite" which also does not work.

**Comment by crazyrabbitLTC** [comment]
For whats it's worth, I tried on a second machine and it's also not working. I also tried with coinbase wallet on the second machine and no notification popped up either. 

So am I just totally crazy or?

**Comment by crazyrabbitLTC** [comment]
@taycaldwell to answer your questions specifically: I deleted the Base connection had and reinstalled with the stock metamask option. So I should be using normal stock Base. 

For the question on funding: 

SendTransaction: 
- When I do not have any funding, nothing pops up in metamask and there is no error, when I do have funds metamask does pop up
UseContractWrite: 
- There is no difference between having funds or not, nothing pops up.

**Comment by lukasrosario** [comment]
hey @crazyrabbitLTC, this looks like expected behavior to me. in the example video you're trying to send more funds than you have available on Base. it works on mainnet because you have enough funds there. i would expect that if you lower the amount you're trying to send that it would work on Base as well.

im not as familiar with Metamask to comment on whether or not the popup should show even if you dont have enough funds, but the internal JSON RPC error you're getting makes it sound like the metamask provider is intentionally not opening the wallet because of a lack of funds. i recommend reaching out to them if you think this is incorrect / a regression.

**Comment by crazyrabbitLTC** [comment]
@lukasrosario As a note this also doesn't work with Coinbase Wallet in my testing. In fact, nothing happens when I attempt to make the tx with coinbase. 

Similarly, when I attempt to interact with a contract, there is no pop up. In the code, there is no warning or error returned from the browser wallet about this either. 

I'll see if I have a chance to reimplement the example with Ethers to see if the behavior is the same. 

Otherwise, what are devs supposed to do when interacting with a contract then? This seems like an obvious edge case that should be caught?

**Comment by lukasrosario** [comment]
sorry should have been more clear -- i would expect the same behavior for Coinbase Wallet too.

re the contract interaction, it looks like you're trying to call `transferFrom` on an EOA. if you change the `address` field in the `writeContract` to an ERC-20 (eg USDC `0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913`) you should see the popup. the "error" in this case can be seen in the network tab. there is a simulation that happens before the popup opens, and that simulation fails (returns null), so the popup does not open.

**Comment by crazyrabbitLTC** [comment]
Got it. So I think I'll close this issue, it seems like the problem is how I was expecting this to work, rather than how it actually works. Thanks @lukasrosario for the clarification! 

I think its worth maybe adding to the docs that if viem detects the transaction won't succedd that it blocks it at the simulation stage. (Which, now that I understand that, does feel very useful!) 

Thank you!
