### ISSUE TITLE
Cannot add chains with empty `blockExplorers` to MetaMask

### ISSUE THREAD

**Issue by tash-2s** [wevm/wagmi#3652]
### Describe the bug

When attempting to add the Foundry chain to MetaMask, I encounter the following error:

```
MetaMask - RPC Error: Expected null or array with at least one valid string HTTPS URL 'blockExplorerUrl'.
```

I discovered that adding the `blockExplorers` parameter resolves the issue.

Wagmi configures `wallet_addEthereumChain`'s `blockExplorerUrls` based on the chain's `blockExplorers`. The current Wagmi implementation leads to an empty array for `blockExplorerUrls` when chains lack `blockExplorers`.

https://github.com/wevm/wagmi/blob/4ba761df16ceaa4746ccb0705ea8e514630b1c1b/packages/core/src/connectors/injected.ts#L373-L393

According to [MetaMask documentation](https://docs.metamask.io/wallet/reference/wallet_addethereumchain/), they require "One or more URLs", indicating that the empty array triggers the error.

I propose excluding `blockExplorerUrls` for chains that do not have `blockExplorers`.

### Steps To Reproduce

Create a project:
```
pnpm create wagmi@2.0.10 --template vite-vanilla
```

Apply this diff:
```diff
diff --git a/src/main.ts b/src/main.ts
index 257488e..47c0748 100644
--- a/src/main.ts
+++ b/src/main.ts
@@ -1,11 +1,17 @@
-import { connect, disconnect, reconnect, watchAccount } from '@wagmi/core'
+import { connect, disconnect, reconnect, watchAccount, switchChain } from '@wagmi/core'
 import { Buffer } from 'buffer'
+import { foundry } from '@wagmi/core/chains'
 
 import './style.css'
 import { config } from './wagmi'
 
 globalThis.Buffer = Buffer
 
+const button = document.createElement('button')
+button.textContent = 'Switch to foundry'
+button.onclick = () => switchChain(config, { chainId: foundry.id })
+document.body.appendChild(button)
+
 document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
   <div>
     <div id="account">
diff --git a/src/wagmi.ts b/src/wagmi.ts
index 3bce606..ebadbf5 100644
--- a/src/wagmi.ts
+++ b/src/wagmi.ts
@@ -1,16 +1,15 @@
-import { coinbaseWallet, injected, walletConnect } from '@wagmi/connectors'
+import { injected } from '@wagmi/connectors'
 import { http, createConfig } from '@wagmi/core'
-import { mainnet, sepolia } from '@wagmi/core/chains'
+import { mainnet, sepolia, foundry } from '@wagmi/core/chains'
 
 export const config = createConfig({
-  chains: [mainnet, sepolia],
+  chains: [mainnet, sepolia, foundry],
   connectors: [
     injected(),
-    coinbaseWallet({ appName: 'Create Wagmi' }),
-    walletConnect({ projectId: import.meta.env.VITE_WC_PROJECT_ID }),
   ],
   transports: {
     [mainnet.id]: http(),
     [sepolia.id]: http(),
+    [foundry.id]: http(),
   },
 })
```

Run the project, connect MetaMask, and switch to the Foundry chain; then, the following error occurs:
```
MetaMask - RPC Error: Expected null or array with at least one valid string HTTPS URL 'blockExplorerUrl'.
```

<img width="754" alt="Screenshot 2024-02-28 at 21 36 27" src="https://github.com/wevm/wagmi/assets/81064017/2f82948e-600d-4c44-96bb-1ad9257e50a9">

By modifying as follows:
```diff
diff --git a/src/wagmi.ts b/src/wagmi.ts
index ebadbf5..1a91b83 100644
--- a/src/wagmi.ts
+++ b/src/wagmi.ts
@@ -2,8 +2,10 @@ import { injected } from '@wagmi/connectors'
 import { http, createConfig } from '@wagmi/core'
 import { mainnet, sepolia, foundry } from '@wagmi/core/chains'
 
+const f = { ...foundry, blockExplorers: { default: { name: "", url: "https://example.com" } } }
+
 export const config = createConfig({
-  chains: [mainnet, sepolia, foundry],
+  chains: [mainnet, sepolia, f],
   connectors: [
     injected(),
   ],
```

The error is resolved, and everything works as expected:

<img width="979" alt="Screenshot 2024-02-28 at 21 39 55" src="https://github.com/wevm/wagmi/assets/81064017/ee5284f3-08d1-40c6-8a8a-de6d80abea48">

### Wagmi Version

2.6.5

### Viem Version

2.7.16

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Thanks for the detailed issue @tash-2s! You are welcome to submit a PR (excluding `blockExplorerUrls` for chains that do not have `blockExplorers`) if you want credit. Otherwise, will get to this soon.

**Comment by tash-2s** [comment]
@tmm Thanks for taking a look. Let me try quickly!
