### ISSUE TITLE
Issues with Sending Transactions to Goerli via WalletConnect connections

### ISSUE THREAD

**Issue by meri-maki** [wevm/wagmi#3655]
### Describe the bug

To test my contract I'm forced to use goerli, so I faced some issues

I have a form which sends eth to contract to buy tokens
```
	const {
		data: hash,
		sendTransaction,
		isPending,
	} = useSendTransaction({
		mutation: {
			onError(error) {
				console.log(`Error send`, error)
			},
			onSuccess(data) {
				console.log("Success send", data)
			},
		},
	})

	const { isLoading: isConfirming, isSuccess: isConfirmed } = useWaitForTransactionReceipt({
		hash,
	})

	const onSubmitForm = useCallback(
		(e) => {
			e.preventDefault()
			sendTransaction?.({ to: contract, value: debouncedAmount ? parseEther(debouncedAmount) : undefined, chainId: 5 })
		},
		[debouncedAmount, sendTransaction]
```

logic is super simple and works fine when I use browser wallet (in my case Metamask for Chrome). Transactions successfully confirms

When I tried to connect my Zerion wallet with WalletConnect I get this error when sumbitting form:
<img width="415" alt="Снимок экрана 2024-02-29 в 16 32 53" src="https://github.com/wevm/wagmi/assets/97887955/89223164-950a-4eed-92c8-5738b7056728">

https://github.com/meri-maki/goerli

### Link to Minimal Reproducible Example

https://goerli-two.vercel.app/

### Steps To Reproduce

1. open https://goerli-two.vercel.app/ on **desktop** or **mobile**
2. connect Zerion (for example) via WC Qr (**desktop**) or via Zerion wallet in modal (**mobile**)
3. enter any value in input
4. try sending transaction

### Wagmi Version

2.5.7

### Viem Version

2.7.16

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

PS: I've also noticed that auto connect feature always works, is there a way to disable it? and let user connect from scratch on every page reload?

**Comment by jxom** [comment]
The "unknown RPC" error usually arises from the Wallet. Best to get in touch with WalletConnect or Zerion to resolve this issue.
