### ISSUE TITLE
useChainId() doesn't return the correct chainId

### ISSUE THREAD

**Issue by samishal1998** [wevm/wagmi#3663]
### Describe the bug

The useChainId seems to return the default chainId if the connected chain is not in the list of the chains in wagmi provider.
However, the useNetwork() returns the correct chain 

### Steps To Reproduce

- Setup a `WagmiConfigProvider` with a specific list of chains
- Connect with a chain not from the list.
- use both `useNetwork().chain?.id` and `useChainId` and compare the results.

> Hi. Thank you for reply, I tried using `chainId` from `useAccount`, but it always returns the first chainId from wagmi config list, even though I switch networks in a wallet. We are currently testing WalletConnect -> Internet Money Wallet. here is my config for reference:
> 
> ```javascript
> import { http, createConfig } from 'wagmi'
> import { pulsechain, pulsechainV4 } from 'wagmi/chains'
> import { walletConnect } from 'wagmi/connectors'
> 
> const projectId = process.env.REACT_APP_WALLETCONNECT_PROJECT_ID || '';
> 
> export const config = createConfig({
>   chains: [pulsechain, pulsechainV4],
>   connectors: [
>     walletConnect({ 
>       projectId
>     }),
>   ],
>   transports: {
>     [pulsechain.id]: http(),
>     [pulsechainV4.id]: http(),
>   },
> })
> ```
> 
> **NOTE**: If I use MetaMask to connect it works. So my guess it is related to WalletConnect v2 provider. Since this `await connection.connector.getProvider({ chainId })` fails with error `getProvider(); is not a function` when I connect with WalletConnect option using wagmi setup above.
> 
> At the moment I applied a temporary solution: `const chainId = process.env.REACT_APP_ENVIRONMENT === 'prod' 
>  REACT_APP_CHAIN_ID : REACT_APP_CHAIN_ID_TESTNET ;`, since we only use one network, but it is not optimal for multiple chain setup.

_Originally posted by @Evirtual in https://github.com/wevm/wagmi/discussions/972#discussioncomment-8115757_

### Wagmi Version

1.4.13

### Viem Version

1.21.4

### TypeScript Version

5.0.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

Some one already raised the issue before but it was closed https://github.com/wevm/wagmi/issues/3205

**Comment by tmm** [comment]
This is the intended behavior

https://github.com/wevm/wagmi/blob/main/packages/core/src/createConfig.ts#L264
