### ISSUE TITLE
useReadContracts and useReadContract have different cache behaviour

### ISSUE THREAD

**Issue by agsola** [wevm/wagmi#3672]
### Describe the bug

While useReadContracts uses the cache and retrieves the latest cached value, useReadContract doesn't.
Just changing a useReadContract to a useReadContracts with just one contract makes my app behave differently, which shouldn't. Or at least, it is not documented.

### Steps To Reproduce

Create a localhost project.
- Use useReadContract to fetch data. Do it online, it will work.
- Disconnect from Internet and refresh. You will get undefined.
- Change useReadContract to useReadContracts with the same information. Fetch data.
- Disconnect from Internet and refresh. You will get the previous value (which is fine)

### Wagmi Version

2.5.7

### Viem Version

2.7.19

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by 1997roylee** [comment]
Could u provide a Minimal Reproducible for it?

**Comment by Yuripetusko** [comment]
I just tested it with  `@tanstack/react-query-devtools` and couldn't reproduce. All my read queries were marked as stale. Keep in mind that react-query still fetches the data even if stale time did not elapsed, the only difference is that if there's a cache for queryKey, then it's immediatly returned by useQuery, but request is still made on the background and cache is updated
