### ISSUE TITLE
useWaitForTransactionReceipt doesn't throw error when transaction reverts

### ISSUE THREAD

**Issue by inclinedmind** [wevm/wagmi#3674]
### Describe the bug

When a transaction reverts due to an out of gas failure, useWaitForTransactionReceipt doesn't return an error, and the loading variable stays true. FailureReason and failureCount are set, but error should also be set and isLoading should be set to false too. 

### Link to Minimal Reproducible Example
https://stackblitz.com/edit/new-wagmi-nwxapp?file=src%2FApp.tsx

Steps to reproduce:
-connect your wallet on sepolia
-click `send approve tx` button
-manually edit the gas limit in your wallet to 26000

_No response_

### Steps To Reproduce

-use goerli (I've reproduced on both goerli and on a tenderly fork of mainnet so far)
-manually set gas limit to be too low on a transaction
-check values returned by useWaitForTransactionReceipt

### Wagmi Version

2.5.7

### Viem Version

2.7.15

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by 1997roylee** [comment]
Could u provide a Minimal Reproducible?

**Comment by inclinedmind** [comment]
@1997roylee I updated my issue with a Minimal Reproducible link and instructions. I'm seeing slightly different behavior in the Minimal Reproducible than in my app. The error does eventually get set in this example, but it happens several seconds after the failureReason gets set. Ideally there wouldn't be this long delay, and the error would be set and isLoading set to false as soon as there's a failureReason, unless I'm missing something.

<img width="691" alt="Screen Shot 2024-03-06 at 2 40 07 PM" src="https://github.com/wevm/wagmi/assets/138821869/e18b1355-26f6-4686-900d-cf1b0f5f896b">

**Comment by inclinedmind** [comment]
@Yuripetusko Makes sense! I understand retrying if the request to the node fails, but in this case where the request succeeds with a tx reverted error, there's no need to retry imo, maybe that's something wagmi can account for. Anyways, thanks for the advice on how I can handle it on my end.

**Comment by Yuripetusko** [comment]
> @Yuripetusko Makes sense! I understand retrying if the request to the node fails, but in this case where the request succeeds with a tx reverted error, there's no need to retry imo, maybe that's something wagmi can account for. Anyways, thanks for the advice on how I can handle it on my end.

it's a default tanstack query behaviour. When useQuery hook `queryFn` throws an error, it auto retries silently (so it doesn't actually report thrown error but swallows it and retires)
