### ISSUE TITLE
writeContractAsync from useWriteContract not throwing correct error type. (and message)

### ISSUE THREAD

**Issue by WingsDevelopment** [wevm/wagmi#3676]
### Describe the bug

I am executing simple deposit function that requires approval of tokens first, and I am getting ContractFunctionExecutionError instead of ErrorNotEnoughAllowance error type. 

On contract it is thrown ErrorNotEnoughAllowance type, and also when checking in tenderly dashboard, i can see that type(ErrorNotEnoughAllowance) is thrown, but in catch in my code I only get ContractFunctionExecutionError.
Also message is not good: "Execution reverted: Execution reverted"

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-bhkgrc?file=src%2FApp.tsx

### Steps To Reproduce

Just trigger any action(token transfer) that needs approval without approving it first..

### Wagmi Version

2.5.4

### Viem Version

2.0.0

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

I've also tryed writeContractAsync  from wagmi/core it works the same. I've also tried downgraded versions, no luck either..

Also missing data from error object, which makes it impossible to parse..

**Comment by pociej** [comment]
I expierience the same issue. What is more frustrainting is that it was working before i updated to wagmi 2.
This seems to be critical bug.

**Comment by Yuripetusko** [comment]
FYI This Minimal Reproducible Example doesn't work because the supplied abi doesn't even have `deposit` function

**Comment by jxom** [comment]
Your ABI doesn't include the `ErrorNotEnoughAllowance` error.
