### ISSUE TITLE
wagmi-ethers adapter useEthersProvider error

### ISSUE THREAD

**Issue by VIC452700** [wevm/wagmi#3680]
### Describe the bug

Hi, wagmi team.
I am trying to use wagmi ethers adapter now.

reference url - https://wagmi.sh/react/guides/ethers
But there are some issues in there.

![image](https://github.com/wevm/wagmi/assets/133695515/9b23f571-2e85-47a1-acf6-79a2a4d11365)

##### wagmi-ethers.tsx (whole code) #####

import { useMemo } from 'react'
import { FallbackProvider, JsonRpcProvider, BrowserProvider, JsonRpcSigner } from "ethers";
import type { Account, Chain, Client, Transport } from 'viem'
import { type Config, useClient, useConnectorClient } from 'wagmi'

export function clientToProvider(client: Client<Transport, Chain>) {
  const { chain, transport } = client
  const network = {
    chainId: chain.id,
    name: chain.name,
    ensAddress: chain.contracts?.ensRegistry?.address,
  }

  if (transport.type === 'fallback') {
    const providers = (transport.transports as ReturnType<Transport>[]).map(
      ({ value }) => new JsonRpcProvider(value?.url, network),
    )

    if (providers.length === 1) return providers[0]
    return new FallbackProvider(providers)
  }

  return new JsonRpcProvider(transport.url, network)
}

/** Action to convert a viem Client to an ethers.js Provider. */
export function useEthersProvider({ chainId }: { chainId?: number } = {}) {
  const client = useClient<Config>({ chainId })
  return useMemo(() => clientToProvider(client), [client])
}

export function clientToSigner(client: Client<Transport, Chain, Account>) {
  const { account, chain, transport } = client
  const network = {
    chainId: chain.id,
    name: chain.name,
    ensAddress: chain.contracts?.ensRegistry?.address,
  }
  const provider = new BrowserProvider(transport, network)
  const signer = new JsonRpcSigner(provider, account.address)
  return signer
}

/** Hook to convert a viem Wallet Client to an ethers.js Signer. */
export async function useEthersSigner({ chainId }: { chainId?: number } = {}) {
  const { data: client } = useConnectorClient<Config>({ chainId })
  return useMemo(() => (client ? clientToSigner(client) : undefined), [client])
}

#### error message ####
Argument of type '{ account: Account | undefined; batch?: { multicall?: boolean | { batchSize?: number | undefined; wait?: number | undefined; } | undefined; } | undefined; cacheTime: number; ... 8 more ...; extend: <const client extends { ...; } & Partial<...>>(fn: (client: Client<...>) => client) => Client<...>; } | undefined' is not assignable to parameter of type 'Client<Transport, Chain>'.
  Type 'undefined' is not assignable to type 'Client<Transport, Chain>'.
    Type 'undefined' is not assignable to type 'Client_Base<Transport, Chain, Account | undefined, undefined>'.

How to fix it?

### Wagmi Version

2.5.7

### Viem Version

2.7.20

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by russell0430** [comment]
same document  ,i got another error 
Module '"wagmi"' has no exported member 'useClient'

**Comment by russell0430** [comment]
maybe add a "!" to the useClient like
`const client = useClient<Config>({ chainId })!`
it erase the warning but may get something wrong in runtime

**Comment by Robarelli** [comment]
I'm having the same issue. Implemented the ethers adapter functions as described in the docs ( https://wagmi.sh/react/guides/ethers). When adding useEthersSigner to my React component

```typescript
const SomeComponent = () => {
  const signer = useEthersSigner();
  
  useEffect(() => {
    console.log('SIGNER: ', signer);
  }, [signer]);
}
```

When a page is reloaded, the signer will have a value. However, when navigating to a new page, it will all of a sudden become undefined.

**Comment by jxom** [comment]
Please follow @russell0430's suggestion for now. Feel free to raise a PR to update the docs.
