### ISSUE TITLE
useSimulateContract hook parameters typing

### ISSUE THREAD

**Issue by mhmmdhajizade** [wevm/wagmi#3700]
### Describe the bug

Hi. I am using wagmi on my dApp and I am trying to call a useWriteContract. As I read in docs you can call useSimulateContract before calling writeContract. As the documentation suggests useSimulateContract has these parameters: 
 `{
    abi,
    address: '0x6b175474e89094c44da98b954eedeac495271d0f',
    functionName: 'transferFrom',
    args: [
      '0xd2135CfB216b74109775236E36d4b433F1DF507B',
      '0xA0Cf798816D4b9b9866b5330EEa46a18382f251e',
      123n,
    ],
  }`
but when I use this in my code I only get these parameters: 
![image](https://github.com/wevm/wagmi/assets/87321633/aba35466-7f0c-4f24-b7be-de01f0f3f742)

and when I try to add abi and functionName manually it doesn't show any errors but also it doesn't generate functionName type as expected.

### Steps To Reproduce

`const { data } = useSimulateContract({});`

### Wagmi Version

2.5.7

### Viem Version

2.8.4

### TypeScript Version

5.4.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
This is an issue with Viem's types and `typescript@5.4.2`. In the meantime, you can downgrade to `typescript@5.3.3` and it should work.

**Comment by mhmmdhajizade** [comment]
> This is an issue with Viem's types and `typescript@5.4.2`. In the meantime, you can downgrade to `typescript@5.3.3` and it should work.

Tried this but unfortunately still got the problem

**Comment by jxom** [comment]
Seems to work fine for me. Happy to look into this further if you can create a minimal reproducible example via a breaking [type test](https://github.com/wevm/wagmi/blob/main/packages/react/src/hooks/useSimulateContract.test-d.ts).
