### ISSUE TITLE
Error: An unknown RPC error occurred.

### ISSUE THREAD

**Issue by maruf1111121** [wevm/wagmi#3702]
### Describe the bug

without metamask SendTransaction notworking
![image](https://github.com/wevm/wagmi/assets/162223892/f3b3ec7f-e511-4b5f-a0fd-a7dbc7b8fed4)

### Wagmi Version

 2.5.7

### Viem Version

2.8.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.

**Comment by maruf1111121** [comment]
![image](https://github.com/wevm/wagmi/assets/162223892/421af137-e267-4c54-87f5-8093aca0f177)

**Comment by maruf1111121** [comment]
if it's closed give me link or any information I can check that and fix it
