### ISSUE TITLE
Connection with injected wallet

### ISSUE THREAD

**Issue by AleksHirsch** [wevm/wagmi#3705]
### Describe the bug

Hey pals, i'm using RainbowKit in my app and this is my config
```tsx
export const config = createConfig({
  chains: [sepolia],
  connectors: getWalletConnectors(),
  ssr: true,
  transports: {
    [sepolia.id]: http('https://rpc.ankr.com/eth_sepolia'),
    [mainnet.id]: http('https://rpc.ankr.com/eth'),
  },
})
```

`getWalletConnectors` returns some rainbowkit providers except metamask and brave (which appear as installed due to `multiInjectedProviderDiscovery` being enabled by default)

The problem is that if I connect my MetaMask, disconnect and refresh the page - the connection to metamask is persisted, but it should be kept disconnected as `shimDisconnect` is true by default. And here's where things get weird. Every disconnect + refresh updates local storage with new entry:

`wagmi.<random wallet name>.disconnected: true`

I disconnect, refresh and again - new entry with random wallet I haven't even used appears. After disconnecting a few times, it starts working as expected - the connection is lost until I connect manually. Can someone tell me what's going on? :D

Even if you go to https://www.rainbowkit.com/docs/introduction I have to disconnect 2 times to make it work 🤔

### Wagmi Version

2.5.7

### Viem Version

2.7.19

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Duplicate #3606
