### ISSUE TITLE
Possible error handling issue with connectors

### ISSUE THREAD

**Issue by imaksp** [wevm/wagmi#3717]
### Describe the bug

See this code:
https://github.com/wevm/wagmi/blob/898bb062a84afac80011a1c95b33bd9475fc7679/packages/core/src/connectors/injected.ts#L163-L171

& this too:
https://github.com/wevm/wagmi/blob/898bb062a84afac80011a1c95b33bd9475fc7679/packages/connectors/src/metaMask.ts#L83-L91

here no error is thrown if error code is not _UserRejectedRequestError_ or _ResourceUnavailableRpcError_ ,
so any other error type will not bubble up.

### Link to Minimal Reproducible Example

NA

### Wagmi Version

4.1.18

### Viem Version

2.8.11

### TypeScript Version

5.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

[metamask sdk connector](https://wagmi.sh/core/api/connectors/metaMask) has some issue due to this bug, if user closes QR modal popup without scanning, it was hanging, did not report previously as we were not using this sdk connector, & currently also we are not using it. but this still requires a fix.

**Comment by jxom** [comment]
This is intended behaviour, as we want to still connect if we cannot get the account selection prompt to appear (ie. swallow the error). MetaMask should throw an error instead of hanging – so probably a bug on their side.

**Comment by imaksp** [comment]
I was talking about QR code flow of Metamask SDK , it was hanging if user closes QR modal after clicking connect.

**Comment by jxom** [comment]
Yes, that is likely a bug of MetaMask SDK. Best to open an issue on their repo.

**Comment by imaksp** [comment]
I think there is some misunderstanding will add reproduction later, if user closes QR modal without taking any action mm sdk might be throwing some error which is being ignored by this lib, so I think issue is within this lib.

**Comment by jxom** [comment]
Ah right. I see. I am surprised MM SDK is not throwing the expected "user rejected request" error like they should.
