### ISSUE TITLE
TrustWallet Extension "approve" method not works

### ISSUE THREAD

**Issue by Pasha8914** [wevm/wagmi#3718]
### Describe the bug

Chrome Version 122.0.6261.129 (Official Build) (arm64)
Trust Wallet Extension 2.9.1

When the approve method is called, trust wallet extension lags and infinite loading appears

### Link to Minimal Reproducible Example

https://github.com/Pasha8914/wagmi-approve/blob/main/package.json

### Steps To Reproduce

https://youtu.be/Tq8GZS-R5M0

### Wagmi Version

2.5.11

### Viem Version

2.x

### TypeScript Version

5.4.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
This looks like a Trust Wallet issue. I'd follow up with them.

**Comment by Pasha8914** [comment]
> This looks like a Trust Wallet issue. I'd follow up with them.

Thank you, that's exactly what I needed. So that the TrustWallet team doesn't try to redirect blame to wagmi.
