### ISSUE TITLE
waitForTransactionReceipt in 2.8.13

### ISSUE THREAD

**Issue by nsnull0** [wevm/wagmi#3724]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

The doc is not giving the correct example.

I am following the doc, but I got this error instead, not sure how to fix it.

![Screenshot 2024-03-19 at 22 44 43](https://github.com/wevm/wagmi/assets/26643922/e47bc25d-a851-42f9-bedd-d84f1c1e1d20)

### Where did you find it?

https://wagmi.sh/core/api/actions/waitForTransactionReceipt#waitfortransactionreceipt

**Comment by tmm** [comment]
Works fine for me in this [TypeScript Playground](https://www.typescriptlang.org/play?ts=5.3.3#code/JYWwDg9gTgLgBAbzgCxjMAaOBjKBTAQxjwGEIA7AM2AHMsB3A4GAMWgBUoDyBnA7GMAoAlPNjzAw8AL5xKUCCDgByAAKMaIYAHps0PMoBQoSLERxIAGwCeNCnFnzFK9QU069+Xcia8jhvAAPU3g9XlCKaho4AF4cfCJSSNoACgRDOBwfYF4ALjgAbStbCgBdDAy4GC5eEJ589MzMoogbO3IAOmAAE1L81HQUgEoKzOkK6SHDQzCeeGruPgEhclFxSXg4gkZmOB3WDhqlwRExCSkUsKisRpQCHmR85QAGQIAWbAIAdjw8ADYAKwAJm6AK+fy+AA5KEC-nhIZCvtgAIxvACcBAARs8vgBmAGUN7I7p4XFfTGfUGQ7Boyh-bq4vBUoFvSjIgGYr5vbrKCZTBa8fgnVZnDZAA)
