### ISSUE TITLE
useEstimateGas only works for transfers

### ISSUE THREAD

**Issue by garrettparris** [wevm/wagmi#3727]
### Describe the bug

I want to estimate the gas used for writing to a contract method but I cant seem to find the proper method to use. Intuitively, I tried to implement using `useEstimateGas` only to find it doesnt have the input parameters to support estimates on a contract method.

### Wagmi Version

2.5.7

### Viem Version

2.7.22

### TypeScript Version

latest

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by garrettparris** [comment]
related ethers js feature for visibility

https://docs.ethers.org/v6/api/contract/#BaseContractMethod-estimateGas

**Comment by tmm** [comment]
Viem has a [`estimateContractGas`](https://viem.sh/docs/contract/estimateContractGas) action (PR welcome to add the Wagmi Action/Hook). You can use that or you can encode the contract data and pass it to `useEstimateGas`.
