### ISSUE TITLE
Wallet connect connector: getNamespaceChainIDs() function always return empty array

### ISSUE THREAD

**Issue by hoangbtmrk** [wevm/wagmi#3741]
### Describe the bug

In the package supporting WC 2.0 of flutter published by WalletConnect [walletconnect_flutter_v2](https://pub.dev/packages/walletconnect_flutter_v2), they are implementing correctly according to the WC namespaces document that doesn't contain `chains` list in the session namespace.
You can see the WC docs about namespaces [here](https://docs.walletconnect.com/advanced/glossary#namespaces)

However, when I investigate code of wallet connect connector in wagmi repository, you get namespace chains IDs by accessing session namespaces chains and check if the returned chainIDs list include chainID to request method `wallet_addEthereumChain`, as I said above, the session namespaces chains is empty so it always call that method every time getProvider function is called. 
Further, the `sendTransaction`, `signMessage` actions always call `getConnectorClient` (with accountType isn't `local`). So method `wallet_addEthereumChain` is called when user use `sendTransaction` or `signMessage` action. It caused error in wallet app that doesn't support multi-chain, and doesn't support method `wallet_addEthereumChain`

Please help update the function `getNamespaceChainsIds()`, you can get the `chains` by separate from `accounts`: `eip155:11155111:0x8A7234737F81E4CeA5F8C7979Ce54801BAFd4718`

### Wagmi Version

2.6.9

### Viem Version

2.8.13

### TypeScript Version

5.0.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by glitch-txs** [comment]
> the session namespaces chains is empty

Why do you think it's empty, could you share steps to repro?

**Comment by tmm** [comment]
Minimal reproduction required

**Comment by hoangbtmrk** [comment]
> > the session namespaces chains is empty
> 
> Why do you think it's empty, could you share steps to repro?

I'm building a flutter wallet app and using walletconnect_flutter_v2 package, when I use the testing app to connect to the official web3 modal example: https://lab.web3modal.com/library/wagm

Whenever request sign message, it returns error `No handler found for chainId:method -> eip155:11155111:wallet_addEthereumChain`, it is because my wallet app doesn't support wallet_addEthereumChain method, and after investigate the wagmi code, I discovered the reason DApp always request that method (even I connected to the correctly network of my wallet) is my wallet app doesn't return chains list in session namespace and it match with [the latest WC 2.0 document](https://docs.walletconnect.com/advanced/glossary#namespaces) - the session namespace just include accounts, methods, events. 

The specific reasons why DApp always call method `wallet_addEthereumChain` when request sign_message or send_transaction I have described above.

I tried testing web3Modal with ethers, and it worked, I can sign message with my wallet.

Could you help me check it soon? @glitch-txs. Many thanks

**Comment by glitch-txs** [comment]
Could you open an issue on the Flutter repo of WalletConnect please
