### ISSUE TITLE
Unable to keep selected chainId on page refresh

### ISSUE THREAD

**Issue by naward-cs** [wevm/wagmi#3743]
### Describe the bug

Link between connected and non connected for persisted data invalid.
Following setup
- SSR true
- two chains [mainnet, sepolia]
- storage: cookies
- using useSwitchChain to change chainId when wallet is connected or not connected

when refresh:
- wallet connected => chainId stays in sync with page refresh
- wallet not-connected and using useSwitchChain to change chainId => chainId does not stay in sync with page refresh, it reverts to config's chainlist order and changes the cookies and config.state for chainId to first chain in config chainlist.

It appears the initialstate is leveraging only when wallet is connected (looking at connections only) and not looking at chainId within the intialprops when connections is empty or current:undefined.

### Wagmi Version

2.5.12

### Viem Version

2.8.12

### TypeScript Version

5.4.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Minimal reproduction required
