### ISSUE TITLE
useContractReads read data error 

### ISSUE THREAD

**Issue by DevMac9990** [wevm/wagmi#3745]
### Describe the bug

{...x20TokenContract, address:  tokenAddress, functionName: 'getWithdrawTime', args: [address as `0x${string}`]}
return error datas

function getWithdrawTime(address user) public view returns (uint256) {
    if(block.timestamp > userWithdrawTime[user] && userWithdrawTime[user] > 0){
        uint256 lastTime = block.timestamp.sub(userWithdrawTime[user]);
        if(lastTime < withdrawInterval){
            return withdrawInterval.sub(lastTime);
        }
    }
    return 0;
}
调用合约方法读取数据的时候，数据错乱
![duqushujju](https://github.com/wevm/wagmi/assets/164744303/1153443b-55de-4654-bbd9-18b041a7c9bc)

### Steps To Reproduce

![duqushujju](https://github.com/wevm/wagmi/assets/164744303/d0fcfa09-e077-4a81-b80e-1e651d383780)

### Wagmi Version

^2.5.1

### Viem Version

^2.5.1

### TypeScript Version

^5.0.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Not clear what the issue is. Please include a minimal reproduction and explain what the issue is.
