### ISSUE TITLE
Connection to WalletConnect wallets persists on repetitive reconnections

### ISSUE THREAD

**Issue by meri-maki** [wevm/wagmi#3749]
### Describe the bug

On mobile when reconnecting to WalletConnect via Web3Modal, the connection request is not sent to the wallet app
When connected this way (without approve in wallet app) the redirect popups do not appear on any interactions (sendTransaction/writeContract)

Normal flow (first connection):

https://github.com/wevm/wagmi/assets/97887955/ad6d995d-ef2b-48fa-9259-9a56ca036c0d

Second connection to same wallet after page reload (wagmi config has  ```reconnectOnMount={false}```):

https://github.com/wevm/wagmi/assets/97887955/5727e825-f562-4445-8917-2e273b7aa268

The connection happens without redirection and confirmation and later transactions fire but without redirect popup

additional discussion: https://discord.com/channels/492410046307631105/1221767594474995712

### Link to Minimal Reproducible Example

https://wc-connect-five.vercel.app/

### Steps To Reproduce

https://github.com/meri-maki/wc-connect
(npm i
npm run start)

https://wc-connect-five.vercel.app/
open on mobile
connect with WalletConnect to Zerion/Trust (default chain is set to sepolia)
try sending transaction - fires with popup
reload page
connect again to same wallet
try sending transaction - fires without popup

### Wagmi Version

2.5.12

### Viem Version

2.8.18

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
It's likely an issue with one of those specific wallets. Please add a minimal reproduction that only uses Wagmi (not Web3Modal).
