### ISSUE TITLE
useChainId() doesn't return the correct chainId

### ISSUE THREAD

**Issue by jaan1025** [wevm/wagmi#3751]
### Describe the bug

Seems like the useChainId hook get the chain id from store, instead of real state from wallet.

Like the closed issue: https://github.com/wevm/wagmi/issues/3663, this may return wrong chainId.

It feels kind of weird to do that. What if I want to check I'm on the correct chain before doing transaction?

### Wagmi Version

2.5.7

### Viem Version

2.7.12

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by jxom** [comment]
If you want to extract connector (wallet) chain ID, you can do:

```tsx
const { data: client } = useConnectorClient()
const chainId = client.chain.id
```

> What if I want to check I'm on the correct chain before doing transaction?

Wagmi already checks this for you.
