### ISSUE TITLE
wagmi generate with foundry plugin bug

### ISSUE THREAD

**Issue by gigamesh** [wevm/wagmi#3752]
### Describe the bug

I think this is happening because there is a `IERC721TokenReceiver` in the forge-std package, which gets imported into every contract library using foundry. So it effectively gets imported and compiled multiple times. Apparently that confuses wagmi?

`Contract name "IERC721TokenReceiver" must be unique.`

![image](https://github.com/wevm/wagmi/assets/32403632/a0ceeb41-dc45-40c5-bfe1-5fa453ccda3c)

### Wagmi Version

2.5.11

### Viem Version

2.8.14

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by gigamesh** [comment]
update: I was able to get this working by adding contracts to the `exclude` array. Not ideal but seems ok now.

**Comment by matmilbury** [comment]
This should be reopened. Nice that we have a workaround but the bug is still there.
