### ISSUE TITLE
[bug] [Android and IOS] When I create a Telegram bot to open a webview, which opens a website (using Rainbowkit and Wagmi) to connect to a blockchain wallet, I encounter an issue

### ISSUE THREAD

**Issue by LeMinhTuAnh** [wevm/wagmi#3753]
### Describe the bug

link open telegram bot: https://t.me/halving_btc_1_bot/test

https://github.com/wevm/wagmi/assets/39867010/3f5cdda4-a05b-4999-bfe3-60fc894e8b40

Because we need to use a Telegram bot to develop a game in telegram (instead of redirecting to a browser)

I Hope you can view and fix this

### Wagmi Version

2.5.12

### Viem Version

2.9.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Needs minimal reproduction
