### ISSUE TITLE
`switchChainAsync` hangs if the target chain is already active (MetaMask)

### ISSUE THREAD

**Issue by alex-grover** [wevm/wagmi#3755]
### Describe the bug

https://github.com/wevm/wagmi/assets/3088615/c2b854d5-b53a-41db-93d1-46987bf835aa

Related: #3417

The `switchChainAsync` function from `useSwitchChain` hangs if the target chain is already active and I'm using MetaMask. See screen recording above.

* It works properly if the current chain is different than the target chain
* It works properly with Rainbow browser extension wallet regardless of whether the target chain is already active

The desired UX here is to ensure the user has the correct chain active before sending a transaction. The chain switching needs to happen every time, because if the user changes chains in their wallet directly, wagmi's `useChainId` hook returns a different chain than the actual active one (unless I'm doing something wrong here). This works in most cases, except with MM if the correct chain is already active.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-kpgz4e?file=src%2FApp.tsx

### Steps To Reproduce

* Connect MM to example app
* Change chains once, if necessary
* Try changing chains to the same chain you just activated - neither success or error messages log to the console

### Wagmi Version

2.5.7

### Viem Version

2.7.19

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by alex-grover** [comment]
Workaround: it appears you can get the wallet's active `chainId` with `useAccount` - the distinction was slightly confusing for me, but the following works and avoids the above bug:

```ts
const { chainId } = useAccount()
const { switchChainAsync } = useSwitchChain()

async function execute() {
  if (chainId !== chain.id) await switchChainAsync({ chainId: chain.id })
  // ...
}
```

**Comment by tmm** [comment]
Should raise this with MetaMask.
