### ISSUE TITLE
useChainId return is different between server side and client side

### ISSUE THREAD

**Issue by berkaycirak** [wevm/wagmi#3758]
### Describe the bug

I am doing a dapp where I am using useChainId to read connected chain. However, it references a chainId based on config on the server side whereas it reads chainId from localstorage (wagmi.store) on the client side imo. These two chainIds usually diverge. What is your solution to be consistent on both side

![image](https://github.com/wevm/wagmi/assets/81809211/1463bfd7-f2b7-44e9-9c0b-1b303ec13f17)

**Comment by tmm** [comment]
Server-side storage is for optimistic rendering and is revalidated and can be different on the client.
