### ISSUE TITLE
Injected connector does not re-connect when browser closed and reopen

### ISSUE THREAD

**Issue by yulafezmesi** [wevm/wagmi#3785]
hey, when i connected with injected connector and prefresh page, it's perfectly reconnect the injected wallet again. 

however, when i close all tabs and browser, and try to open same page again, the metamask password popup does not open. in this case metamask popup locked (expected) but the metamask connection needs to be triggered.

as you can see here, when i close browser and open again, it shows the address first and suddenly disappeared without triggering popup again.

https://github.com/wevm/wagmi/assets/45617686/4224e141-4b6e-4ab2-a3a5-3e0b499c3803

### Link to Minimal Reproducible Example

https://new-wagmi-mfdots.vercel.app

### Steps To Reproduce

for the better replication, deployed the static website: https://new-wagmi-mfdots.vercel.app

you can find the codes here: https://stackblitz.com/edit/new-wagmi-mfdots

### Wagmi Version

2.5.18

### Viem Version

2.9.8

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by jxom** [comment]
I would say this is expected. When the MetaMask extension is locked, the wallet is technically now disconnected – there is no way we can extract accounts/connection state. I wouldn't say attempting to reconnect upon page-load with a prompt is the best UX (this is an anti-pattern for Web APIs such as permission, popups, etc), so I think the best approach for now is to leave it as-is.
