### ISSUE TITLE
Passing `config` through parameters doesn't work

### ISSUE THREAD

**Issue by youPickItUp** [wevm/wagmi#3792]
### Describe the bug

I tried passing `config` through parameters to hooks (outside of `WagmiContext`), but it throws `WagmiProviderNotFoundError`. Parameters aren't pass down to hooks called inside hooks, which causes the error and, to me, conceptually doesn't make sense.

https://github.com/wevm/wagmi/blob/8e9ee793c4f378de523239bb8db63cbf09cc980e/packages/react/src/hooks/useReadContract.ts#L88

Not sure if this is intended use case :shrug: 

### Wagmi Version

2.5.18

### Viem Version

2.9.9

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Nice find! Looks like there were multiple places where `config` wasn't passed through directly. https://github.com/wevm/wagmi/pull/3793 addresses this.
