### ISSUE TITLE
WagmiProvider rerender triggering "Cannot update a component while rendering a different component" 

### ISSUE THREAD

**Issue by Ashoat** [wevm/wagmi#3794]
### Describe the bug

Just upgraded to Wagmi 2. I'm rendering a `WagmiProvider` in a parent component that ends up rerendering (not remounting) that `WagmiProvider` in certain situations.

After some debugging, I determined that the code [here](https://github.com/wevm/wagmi/blob/b80236dc623095fe8f1e1d10957d7776fb6ab48b/packages/core/src/hydrate.ts#L33) will trigger a call to `reconnect` during every render of `Hydrate` [here](https://github.com/wevm/wagmi/blob/0a3393a5802699ef6330f796633243d656ed896d/packages/react/src/hydrate.ts#L21), which is itself rendered by `WagmiProvider` [here](https://github.com/wevm/wagmi/blob/0a3393a5802699ef6330f796633243d656ed896d/packages/react/src/context.ts#L24).

In our case, the `reconnect` call is triggering a component that uses the `useWalletClient` hook to re-render. This is a no-no in React, as we're setting state during render. We see this error:

```
Warning: Cannot update a component (SomeComponent) while rendering a different component (Hydrate). To locate the bad setState() call inside Hydrate, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
```

I'm not sure what the right solution is. I know that there are (limited) cases where calling `setState` from render is appropriate, such as [animation transitions](https://legacy.reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops). I'm not sure if this particular use qualifies. My instinct is that it doesn't, but I haven't thought about it too deeply. (I also wonder if this error is supposed to fire even for appropriate uses... perhaps the doc I linked is outdated?)

Apologies for not having a MRE... I have limited cycles right now and was able to work around the issue by ~~explicitly passing in `reconnectOnMount={false}`~~ lifting `WagmiProvider` higher in the component tree. Figured it was still better to create an issue, since I suspect that many others are going to be experiencing this soon.

### Wagmi Version

2.5.18

### Viem Version

2.9.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by Ashoat** [comment]
`reconnectOnMount` turns out to be be only one way that `setState` can be called by `hydrate`. Renamed and updated this issue to reflect that.

I was able to get around it by lifting `WagmiProvider` up higher in the component tree. That said, I still feel that Wagmi should be able to handle `WagmiProvider` being rerendered. I suspect (but am not sure) that the approach here is non-idiomatic for React, but I don't understand the tradeoffs (or other context) that lead to it being taken.

**Comment by jxom** [comment]
`WagmiProvider` should indeed be placed at a level where the first mount occurs to behave properly with hydration.
