### ISSUE TITLE
useChainId returns default chainId even if the current chain is not default.

### ISSUE THREAD

**Issue by berkaycirak** [wevm/wagmi#3799]
### Describe the bug

 I am using `useChainId`, and my config is 
```js
export const config = getDefaultConfig({
  appName: 'Heroes NFT',
  projectId: projectId,
  chains: [avalanche, herotestnet],
  ssr: true,
});
```
on the client, when I refresh the page on the herotestnet chain, it returns me two chainIds ( one for avalanche and the other is herotestnet) 

```js
const chainId = useChainId()
console.log(chainId) // I see two different value when I refresh the page on the herotestnet
```

### Expected Behavior

I expected to get only one chainId even if the current chain is different from default chain

### Wagmi Version

2.5.7

### Viem Version

2.7.16

### TypeScript Version

5.0.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Is a wallet connected? `useChainId` updates to keep in sync with the current connected account. Please attach a minimal reproduction if you want me to look into this further.
