### ISSUE TITLE
Coinbase Wallet enableMobileWalletLinking showing Coinbase Wallet open app website

### ISSUE THREAD

**Issue by marcusmolchany** [wevm/wagmi#3801]
### Describe the bug

I am trying to use wagmi in a react-native-webview to login to my Expo app using Coinbase Wallet mobile. The webview shows the `npm create wagmin@latest` site on a next app from vercel. I've included the option `enableMobileWalletLinking: true`, because we _do not_ want our login page to open up inside of Coinbase Wallet's dapp browser, instead we want to Wallet Link to connect, sign a message, and then stay within our Expo app.

Currently, when we choose Coinbase Wallet as our connection option, we get redirected to Coinbase Wallet, are shown the connect sheet in the Coinbase Wallet app, and then when we return to our app showing the webview, the webview has changed to show a Coinbase Wallet website that forwards us to the iOS App Store.

|screenshot|
|--|
|![IMG_19ACE33CC395-1](https://github.com/wevm/wagmi/assets/2160046/a9102c94-a968-4c94-9533-16a6c4e5ceea)|

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-wiqtks?file=src%2Fwagmi.ts

### Steps To Reproduce

- Set your `VITE_WC_PROJECT_ID`
- Create an Expo app with a `react-native-webview`
- set `app.json` `expo.ios.infoPlist.LSApplicationQueriesSchemes` to `["cbwallet"]`
- Present the `react-native-webview` with https://stackblitz.com/edit/new-wagmi-wiqtks?file=src%2Fwagmi.ts and choose "Coinbase Wallet" as the login option

### Wagmi Version

2.5.19

### Viem Version

2.9.9

### TypeScript Version

5.4.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by marcusmolchany** [comment]
For anyone experiencing this issue, we got around temporarily by doing:

```tsx

const coinbaseRedirectUrls = Object.freeze([
  "https://go.cb-w.com/",
  "https://v3eo.app.link/",
]);

export const isCoinbaseRedirectUrl = (url: string): boolean =>
  coinbaseRedirectUrls.some((coinbaseRedirectUrl) =>
    url.startsWith(coinbaseRedirectUrl)
  );

// in our component render function
  return(
        <WebView
          ref={webviewRef}
          source={{ uri: /* your login url */ }}
          onMessage={(event) => {
            // handle postMessage back to react-native-webview
            // with `event.nativeEvent.data)`
          }}
          onNavigationStateChange={(event) => {
            // note: handle coinbase wallet redirect
            if (isCoinbaseRedirectUrl(event.url)) {
              console.log("handling coinbase redirect url", event.url);
              // note: prevent react-native-webview from loading
              // the coinbase redirect url
              webviewRef?.current?.stopLoading();
              // note: use expo Linking to open the coinbase redirect url
              // which will deeplink into the coinbase wallet app
              Linking.openURL(event.url);
              return;
            }
          }}
        />
  );
```

**Comment by tmm** [comment]
Wagmi now uses the v4 of the CB SDK so this should no longer be an issue.
