### ISSUE TITLE
Multicall: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [wevm/wagmi#3807]
### Describe the bug

That error appeared even when I supply an empty array to the [multicall](https://wagmi.sh/core/api/actions/multicall#multicall) function:

![image](https://github.com/wevm/wagmi/assets/7723097/c788edbb-a02c-4fce-836f-32f6b1c83a85)

### Steps To Reproduce

Just use multicall with empty array supplied to `contracts`, then you can see it in VSCode:

```ts
        const vestingsData = await multicall(teamFinanceWagmiConfig, {
          contracts: [],
        })
```

### Wagmi Version

2.5.19

### Viem Version

2.9.15

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by jxom** [comment]
I can't reproduce this in my minimal reproduction: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCxjMAaOBjKBTAQxjwGEIA7AM2AHMsQBXAGxmGwKabgF85KoIIOAHIAAgHcCNEMAD02aHmEAoUJFiI4IAsHLk8MLAGc8kJsAI8+AoWMnS5C-POQ7yRlcrwAPdfAXu-hTUNHAAvDj4RKTBtAAUCMpwOK66RgBccADa2rr6hnAmZhYAuhhJcDBQBO5+GYgVyTlu+QB0wAAmJZmo6HEAlOXJTUUQ5gTtXT1oYANDPOXc-crKAUbw+EbM8BEEksDwjCxsHExxASFYickBVQTYMPVZZcpLQA

Could you please provide a minimal reproducible example via a separate repo (or TypeScript playground), and open a new issue? Thanks!

**Comment by Doko-Demo-Doa** [comment]
Found a solution, I have to put `"strictNullChecks": true,` to `tsconfig.json`. That means I have to also modify some other files to comply with the null checks, but it's ok.
