### ISSUE TITLE
How to use Custom rpc url instead of default?

### ISSUE THREAD

**Issue by meri-maki** [wevm/wagmi#3821]
### Describe the bug

In one of the projects I noticed that the default RPC URL for BNB Smart Chain is referred to as 'not a match for a know provider for this chain' and as it might be worrying/confusing for the user that wants to add this chain, I decided to try to replace the rpc url for bsc for the recommended one mentioned here (https://docs.bnbchain.org/docs/rpc/#bsc-mainnet-chainid-0x38-56-in-decimal)

![2024-04-15_22-17-37](https://github.com/wevm/wagmi/assets/97887955/860ba645-7ae9-41e1-b184-1b0ad9d24790)

However, even when I added the fallback urls it still connects with default one (rpc.ankr)
Am I correct that the fallback only runs if the default fails? But what if I need to use the custom url all the time and several ones - different for each chain?

Could you please help 🙏 

Adding ```unstable_connector``` didn't work...

repo is here: https://github.com/meri-maki/custom-rpc

### Link to Minimal Reproducible Example

https://custom-rpc.vercel.app/

### Steps To Reproduce

Open https://custom-rpc.vercel.app/
Remove BNB smart chain from the chain list in Metamask Browser Extension
Connect Wallet to mainnet or sepolia
Click on BNB to switch Chain
See the rpc url in popup

### Wagmi Version

latest

### Viem Version

latest

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by jxom** [comment]
Wagmi does not use the RPC URLs defined in `transport`s when prompting to add a network. You will need to modify the `bsc` chain (passed to `chains`) with the target RPC URL.

```tsx
import { defineChain } from 'viem'

const customBsc = defineChain({
  ...bsc,
  rpcUrls: {
    default: {
      http: ['https://...']
    }
  }
})
```
