### ISSUE TITLE
shimDisconnect is ignored

### ISSUE THREAD

**Issue by mqklin** [wevm/wagmi#3828]
### Describe the bug

Ref:
https://github.com/wevm/wagmi/issues/3603

I've put breakpoints inside injected.js file debugger. You can see that `injected` is called two times, and for the second time it's called with shimDisconnect undefined => true:
![image](https://github.com/wevm/wagmi/assets/9456433/e4feb5e4-493a-4770-be95-e8644dcbd243)

And after that the code that should not be run, is actually run: 
![image](https://github.com/wevm/wagmi/assets/9456433/1966001e-5029-4632-a114-6db5196837cc)

I've extensively described the process here: https://github.com/wevm/wagmi/pull/3608

### Wagmi Version

@wagmi/core@2.6.17

### Viem Version

2.9.19

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by jxom** [comment]
How can I reproduce this? I am not sure we should be setting a global variable for `shimDisconnect` as more than one injected connector can be instantiated.

**Comment by mqklin** [comment]
I'll create a repro soon. But for now I can say the it's called for the second time here: https://github.com/wevm/wagmi/blob/de17905c91436703cd42c45475e8e7e26a631c0e/packages/core/src/createConfig.ts#L115
You can see that it's called with `target`, but `shimDisconnect` is not passed there.

I agree that global variable is not a good solution, as i described here: https://github.com/wevm/wagmi/pull/3608#issuecomment-1977133799

To make it work "clean", shimDisconnect should be passed to `midp` lib (https://github.com/wevm/wagmi/blob/de17905c91436703cd42c45475e8e7e26a631c0e/packages/core/src/createConfig.ts#L92C36-L92C61), but I'm not sure you want to pass `shimDisconnect` to `midp` lib.

**Comment by mqklin** [comment]
@jxom i've just reused Playground from docs and set shimDisconnect as false: https://stackblitz.com/edit/vitejs-vite-srzqhu?file=src%2Fwagmi.tsx
(https://wagmi.sh/react/guides/connect-wallet)
