### ISSUE TITLE
`showQrModal: true` on walletConnect connector doesn't show the QR code

### ISSUE THREAD

**Issue by endophasie** [wevm/wagmi#3833]
### Describe the bug

I want to make the wallet connect QR code appear first when `showQrModal: true`: 

<img width="365" alt="image" src="https://github.com/wevm/wagmi/assets/3120209/5285fe19-33a4-4a29-9b57-7a34005e58f3">

but instead modal renders same Connect Wallet:

<img width="365" alt="image" src="https://github.com/wevm/wagmi/assets/3120209/52646d10-3652-4fde-a074-a1c31f8f0bee">

### Steps To Reproduce

```
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { createWeb3Modal } from '@web3modal/wagmi/react'
import { defaultWagmiConfig } from '@web3modal/wagmi/react/config'
import { WagmiProvider } from 'wagmi'
import { mainnet } from 'wagmi/chains'
import { walletConnect } from 'wagmi/connectors'

const queryClient = new QueryClient()
const connector = walletConnect({
  projectId,
  showQrModal: true,
})

const chains = [mainnet] as const
const config = defaultWagmiConfig({
  chains,
  connectors: [connector],
  projectId,
  metadata,
})

createWeb3Modal({
  wagmiConfig: config,
  projectId,
})

export function Web3ModalProvider({ children }) {
  return (
    <WagmiProvider config={config}>
      <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
    </WagmiProvider>
  )
}
```

### Wagmi Version

2.5.20

### Viem Version

2.9.19

### TypeScript Version

5.4.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by glitch-txs** [comment]
This is not a Wagmi issue, but you can try:

```ts
import { useWeb3Modal } from '@web3modal/wagmi/react'

export default function Component() {
  const { open } = useWeb3Modal()

  open({  view: 'ConnectingWalletConnect' })
  
  //...
```

if you're using Web3Modal the `showQrModal` flag should be set to `false` otherwise it will open two modal.
