### ISSUE TITLE
@solana/web3.js needs to be update to 1.77.4 or later. High Severity

### ISSUE THREAD

**Issue by jtardioli** [wevm/wagmi#3836]
### Describe the bug

I have wagmi installed at version `0.12.19` which is the most recent version before the `1.x.x` breaking changes. I'm getting the following dependabot alert

![image](https://github.com/wevm/wagmi/assets/85530348/0c0414c8-78fc-43f7-9734-3f385e94b74c)

I can see wagmi is using version `1.77.3` this should be updated to `1.77.4`

![image](https://github.com/wevm/wagmi/assets/85530348/6323ca17-1552-4b31-a8ec-36236e06a15c)

### Steps To Reproduce

1. Install wagmi at `0.12.19`
2. Observe it is using version 1.77.3 of @solana/web3.js 

### Wagmi Version

0.12.19

### Viem Version

x.y.z

### TypeScript Version

5.0.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by jxom** [comment]
This is a downstream issue on the Coinbase SDK, so it might be worth raising an issue there.

AFAIK, the Wagmi v2 (which uses the latest Coinbase SDK) does not contain the `@solana/web3.js` dependency.

If you cannot upgrade to Wagmi v2 yet, you could override the `@solana/web3.js` with [npm overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides).

**Comment by jtardioli** [comment]
I made and issue with coinbase-wallet-sdk. Ill make another issue here they update it
https://github.com/coinbase/coinbase-wallet-sdk/issues/1196

**Comment by fan-zhang-sv** [comment]
hi @jtardioli thx for flagging this, we removed solana provider dependency from 3.9, feel free to try out [3.9.3](https://www.npmjs.com/package/@coinbase/wallet-sdk/v/3.9.3) or [4.0.0-beta.7](https://www.npmjs.com/package/@coinbase/wallet-sdk/v/4.0.0-beta.7) as a quick patch for this
