### ISSUE TITLE
Error when signing a message via QR code with a device on a different chain

### ISSUE THREAD

**Issue by goshatravin** [wevm/wagmi#3840]
### Describe the bug

When attempting to connect and sign a message to a wallet via QR code scanning, an error occurs if the scanning device's blockchain network is different from the networks configured in WAGMI's settings.

Expected: switching network prompt 

### Steps To Reproduce

1. Configure wagmi with a specific set of blockchain networks.
3. Attempt to connect a wallet using a QR code from a device that is on a different blockchain network.
4. Click sign message
5. Observe the error.

https://stackblitz.com/edit/new-wagmi-poptbs?file=src%2FApp.tsx

```
An error occurred when attempting to switch chain.

Details: Chain not configured.
```

Version: @wagmi/core@2.6.17
Version: viem@2.9.20

### Wagmi Version

 @wagmi/core@2.6.17

### Viem Version

viem@2.9.20

### TypeScript Version

5.1.6

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by isaacschwab** [comment]
I'm also seeing a similar issue with the WalletConnect Connector. However, I'm seeing this error when using chains that are defined in my config (mainnet, and sepolia), and I'm connected to them in my Wallet (Metamask Mobile). 

The reproduction of this error is very inconsistent, probably related to some interaction with WalletConnect.

**error from useSignMessage**

```An error occurred when attempting to switch chain.
Details: undefined is not an object (evaluating
'(n=this.namespaces[il)!=null?
n:this.namespaces[${i}:${s}]).defaultChain=s') Version:
viem@2.9.31```

**Comment by tmm** [comment]
The following is a valid error and you should either add the chain to your Wagmi Config or prompt the user to switch to a supported chain.

```
An error occurred when attempting to switch chain.

Details: Chain not configured.
```
