### ISSUE TITLE
[BUG] Module '"@wagmi/core"' has no exported member 'Chain

### ISSUE THREAD

**Issue by RafaDSan** [wevm/wagmi#3845]
### Bug Found

`Module '"@wagmi/core"' has no exported member 'Chain'` even with wagmi version ^2.

### What I am doing
We are trying to import `chain` from `@wagmi/core` to add a new blockchain, which is still in alpha to the list of chains with the following code:

``` typescript
import { Chain } from "@wagmi/core";

export const ETH_KAKAROT = {
  id: 1_802_203_764,
  name: "Kakarot Sepolia",
  network: "kakarot_sepolia",
  nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  rpcUrls: {
    default: { http: ["https://sepolia-rpc.kakarot.org"] },
    public: { http: ["https://sepolia-rpc.kakarot.org"] },
  },
  blockExplorers: {
    default: {
      name: "KakarotSepoliaScan",
      url: "https://sepolia-explorer.kakarot.org",
    },
  },
  contracts: {
    multicall3: {
      address: "0xca11bde05977b3631167028862be2a173976ca11",
      blockCreated: 11_907_934,
    },
  },
} as const satisfies Chain;

```

### What I have tried
I've seen the issue [314](https://github.com/wevm/references/issues/314) and tried to upload the `"@wagmi/core"` to the latest version, using `npm install @wagmi/core`  but it still didn't work. So, I am opening this issue as the other issue was closed.

### Link to Minimal Reproducible Example

https://github.com/blockful-io/swaplace-dapp/tree/develop

### Steps To Reproduce

1. git clone (this repository)[https://github.com/blockful-io/swaplace-dapp/tree/develop]  (develop branch)
2. run the command `npm i  --legacy-peer-deps`
3. check the file `wagmi-custom-chains.ts`

### Wagmi Version

`@wagmi/core": "^2.6.9"`

### Viem Version

`"viem": "^1.19.11"`

### TypeScript Version

`"typescript": "^5"`

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by glitch-txs** [comment]
You have an issue with dependencies, you're installing both Wagmi v1 and v2

**Comment by RafaDSan** [comment]
> You have an issue with dependencies, you're installing both Wagmi v1 and v2

I think you referring to both `wagmi` in the `package.json` right? (`"@wagmi/core": "^2.6.9",` and ` "wagmi": "^1.4.7",`) even with only `"@wagmi/core": "^2.6.9",` the problem still persists, I've tested it.

1. Delete ` "wagmi": "^1.4.7",`
2. Delete `node_modules`
3. `npm install` (only with `"@wagmi/core": "^2.6.9"`)
4. The error perssists

**Comment by glitch-txs** [comment]
probably because you're using Viem v1, and Wagmi v2 exports `Chain` from that package if I'm not mistaken

**Comment by RafaDSan** [comment]
> probably because you're using Viem v1, and [Wagmi v2 exports `Chain` from that package](https://github.com/wevm/wagmi/blob/main/packages/react/src/exports/chains.ts)

I've updated viem to `"viem": "^2.9.25",` with `"@wagmi/core": "^2.6.9",` but I am still getting the same error, even deleting the node_modules, installing the viem and etc.

**Comment by glitch-txs** [comment]
Could you push the changes in your MRE?

**Comment by RafaDSan** [comment]
> Could you push the changes in your MRE?

Sorry, I can't update that one. You can use my [fork](https://github.com/RafaDSan/swaplace-dapp/tree/wagmi-test) tho.
Also, I've noticed that when using `import { type Chain } from "viem"`  instead of `import { Chain } from "@wagmi/core"` the import does work. 
Could you help me with a question? What is the difference when import of `viem` and of `wagmi` especially for the use case where I am creating a custom network to communicate with it, as this network is not present in the wagmi?

**Comment by glitch-txs** [comment]
> What is the difference when import of viem and of wagmi

No difference. In your fork you haven't updated the lock file, you need to delete it together with node_modules and reinstall

**Comment by RafaDSan** [comment]
> > What is the difference when import of viem and of wagmi
> 
> No difference. In your fork you haven't updated the lock file, you need to delete it together with node_modules and reinstall

As there is no difference, I'll go with `viem` then, because I've tried to delete the lock file, the node_modules and then reinstall as you suggested but it still failed

**Comment by glitch-txs** [comment]
can you update your fork? The lock file points to Wagmi v1

**Comment by tmm** [comment]
```ts
import type { Chain } from '@wagmi/core/chains'
```

**Comment by RafaDSan** [comment]
> ```ts
> import type { Chain } from '@wagmi/core/chains'
> ```

It worked.
Thx for the help @tmm and @glitch-txs
