### ISSUE TITLE
bug: The inferred type of this node exceeds the maximum length the compiler will serialize

### ISSUE THREAD

**Issue by pfista** [wevm/wagmi#3846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.25

### Current Behavior

I'm using wagmi/cli with Foundry plugin to generate types for my contracts and this is leading to a typescript error.

```typescript
import { defineConfig } from '@wagmi/cli'
import { foundry } from '@wagmi/cli/plugins'

export default defineConfig({
  out: 'src/generated.ts',
  plugins: [
    foundry({
      project: '../../apps/contracts/',
      forge: {
        clean: true,
        build: true,
        rebuild: true,
      },
    }),
  ],
})
```

```typescript
import { getContract, Address, parseAbi, createWalletClient, http, publicActions} from 'viem'
import { privateKeyToAccount } from 'viem/accounts'
import { wagmiCliGeneratedAbi } from './generated.js' 

const ownerAccount = privateKeyToAccount(process.env.BLOCKCHAIN_OWNER_WALLET_PRIVATE_KEY as Address)

const ownerClient = createWalletClient({
  account: ownerAccount,
  chain: getChain(),
  transport: http(process.env.BLOCKCHAIN_NETWORK),
}).extend(publicActions)

const myContract = getContract({
  address: process.env.BLOCKCHAIN_CONTRACT as Address,
  abi: wagmiCliGeneratedAbi,
  client: ownerClient,
})

```

Which leads to this error: 

```typescript
TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
```

Given that the generated json abi from wagmi has unused portions, I even tried manually adding the ABI like so: 

```typescript

const myContract = getContract({
  address: process.env.BLOCKCHAIN_CONTRACT as Address,
  abi: parseAbi([
    'function purchasePriceOfReservedTokens(address account, uint256 id) view returns (uint256)',
    'function suspendedTalent(string _ticker) view returns (bool)',
    'function buyTalentAdmin(string _ticker, uint256 _amount, uint256 _price, address _userAddress)',
    'function sellTalentAdmin(string _ticker, uint256 _amount, uint256 _price, address _userAddress)',
    'function confirmTalent(string _ticker, address _talentWallet, uint256 _price)',
    'function suspendTalent(string _ticker, bool _suspend)',
    'function tickerToTokenId(string _ticker) view returns (uint256)',
    'function createTalent(string _ticker) returns (uint256)',
  ]),
  client: ownerClient,
})

```

This resolved the typescript error `TS7056` for some of my other contracts, but not for this one given it has more functions that my code requires. 

I'm not sure what to do from here to ensure I get the proper typing for my contracts in viem. Adding an explicit type seems infeasible as the dynamic typing happening with viem is quite complex.

### Expected Behavior

I should be able to use wagmi generated ABIs with `getContract` without running into TS7056 error during compilation

### Steps To Reproduce

Run `pnpm run build` in the provided stackblitz.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-vq3eiz?file=index.ts

**Comment by tmm** [comment]
Change the following in `index.ts` so you are using the const-asserted ABI instead of the JSON version.

```diff
- import exampleAbi from './abi.json'; // Generated from wagmi.config.ts
+ import {exampleAbi} from './generated.js'; // Generated from wagmi.config.ts
```

**Comment by pfista** [comment]
@tmm thanks for taking a look, but it still fails to build with your suggestion

https://stackblitz.com/edit/viem-getting-started-dw2gsw?file=index.ts

**Comment by pfista** [comment]
> This [TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQYQDbBoB2MANHAOZow4QlQbJlwAWMMYcAvnAGZQQQcAOQA3QiGEAoKcjoBneBgBGwOAF44AbSlxEuvXEVY0AWQCuMFcAIwAngC4RROmAx2VeNMNIG99sDQnYTkiRShzJmgfPzhgIjBLeScdQ0MkIgwQIJEAfWMoAC8fOJI0KEy8ABU7QODQmAYmOABJAFEAJRwAJgAGEoCc4QwAExH0eXlhbl80vQRYtMzs4NyrLxIcDCgRqdm5vXjsCoxq2qGGpvgWqtPiGm3dmIP-c+DR8bRJ57mufbSMlkhrkIAB3IjlEpHcqVGp1EQfCZ7OCDd5jJHTP6xAC6+yx81iqJEaFE9x+egwLiIdhAEHMyT4p3kaH+pUSMAZqTmCxecGWQzA6HEdPkAHlwZDWWloSczvDhuivntFoYiQrPt8pYZ4iM0AAPNAjJyNcwslX47kqvT84IQ0HiiFQclzGWwt4IxWaq0o93qjFaw5EXUGo0oiJmg4WvS42I2kQO8ryFjAMBVBhhXjldAjH4Wnmq30ksmsyl0Gkipy8JkR7UJJIpFX5g5x4bIOTmEjO6VlWVwoaIpVdgvygde3k6-WGyvVrVRuAxpZA4IABQw9MNuf2TZ98qLnZLVPL9OneGZrPi7M5je9LbWEAA1sQWjmA6Vjm75eYjt0AKwANiHV5P2-f9ANKYMp0ZU8azSOcCV5W8sjpfdvVdU4+2CL8SF-ADXzVLCYBwsCJxDE8z3NLVt0XFY8gKQoAEFaQ7GBiJ7D8hgIoi8N9TjQNfEjIKraDZ0ovklzyGAIChNj0N9UdkTVeTpIg0MhOZGYcVZFtbg2GAACE6QoNhNwMbc1T3FiDzLJiGTUmC2XrbRrwQ8ThDvR8iGfVj31k4DsL4718JA3DUKDSdVJnCjnJeRCmJQ8cZLlDjgrAoL-JChKVLI+y9Dg-QXJoty6MY5DLNCnykswlLuL8wiAsy8LspE6Lm1c3J+EEbyYV8-tPWVXlFL61isqg8jI1ZBdDG0u4SAAZQgPAXwMPNCULUl4sMUtqRsprYgvRyuQBG9XMYdsNoONDKo9DV+peQabuGxrRpyjS0km61XIAVQSNdmSW3Kt1iYxsAsKxVFsRxnFcdxPG8Vk1V4DsmGAOhnX2jkGwOQFCrWYBkEfJ1yEujCRHCeIKAGX0yaICnXu5MScaQ5jpIqknhF43Cd2S9LMVE29BTxuG326q72eqrmqp5umAQZ4F1ygeihqJxK2aU8h7oxaX5y01zlHMOwdPuRWQHiZ06Q4A7JpWtJgbMSxrAh21oY8ZQvGdBGkZgFGiDRusMacrHZdWL38clYXeypxpycp+VqdpvLseBdZ7gAdVOLxLPD9i0Qe9W5KGrX5iDvIBeQIXiZ48W0rqgCtfe4uQjoXhgCgEBDfOuBzcvFIrcBm2rBB+3weAewnZ+l23fh31EaIZHUfPP3OUT4O8YJlmRbZuOY6GLfuHrltUEwbB27KtIu4O5eRHXiPaq4iWRA5zFe9MoGB7tsGbBHyGxEIUF3enz23tfbdwDvTW88tr7Z2uv6e+fpByF0QA3XGodCZZx6sELeedY5RxprzTSsZXJUBgB0L45RSQlWYgZcwRlT6GHPv7LQl9hCQPQQ-KulcpZcGfvBQwttQYOy-sEcQaA-5T3lDPOePsF4gMYQ3Fhos1awKUnvHWhVgDyGNqbVk9Cl5yOVqzX0ygIALW3sEIxJiVHLT7rwt+-Dh6jxEMI0Rq1xGAPnntReKQmHuSfC+NBotH5YO5jXJ+qihjqJPrQIgzdW4bm0ZYGRTD5Fs3MXgUxIhUmhKsS-fuJg7GfwcT-ER-9XGzy9u47sMj96uSpGXM2CSL56P8WzQJsDH6WIBjkmxeSh4FO-okdAJShgSPKVIjxMjGxNIriOJWSiC4JymSrfOuc5kPQQUk-RG8OE1y0NidJYt0q7LwYHFsyTtk4SOUEyWOy9nrMWQY+Uyg7DYAUoY55XxjmGGqYVOgnQcAAEZ-k-h-HpLAyAWAkLLsAUk-06ENIYRs5pbyXkABZ9lPNRVkzpPC9B8N6Y7EQAy4YuOGW4sZlSDqTNOZsm+vUVka3gQs6lSKZn0uWZrJlrkzm3z4m0lKdzmXTOCXfauREBVcppVA4QGKPlXIye8qYdcwnBF+V0QFwLIVoGhXE2IOivH3K2Y8hVaK5XSuNVium248UfwJUU5xaQPZlKAdIy2yqRBgkdPUi2CKDW0pzjAhl3wOmWtfj0m1gjHG-yGcEEZzrxmuoIYVNw65YV6D1doRFQqzHGLSaazJwbrbdMHuGwpTjo0iFjRU2sEyTkSpZXSgN7LGV8zrVmthPNTXtLnN8gU5goDgowMyChJBRS8BIcyKAMKqgPmILdNN8LdGCqWTyzmorQIFusbi2x+KI12vLcISt5Lq2UtrYVblDbBymuUZys9krWEHJCZ2-l3a3XCAGQO5ky4oCC1HeOshhpp0eXkC0Igs0rBFC9Yk31UrWlrtrlwvEm6jDbpLd-KkbgJ7EodQAp1VbAxVNfegFwSM0AJigEmFMkGE3YvykW9+AjCnoZhq7LDw5SW4aPfhk9YC2ohzXne0WmDYG7xvcCJm+563XJFec9donVil3Lsu4VvK4OfJluAidisVltrgZqVZHKJqvuZHgaoM0YCaM453BdPdENdK3WGhjaHnaw33Ye4B3H1NtVGCbKRknoGXv082qlbVmSZx05kvNOa1Pa0TTvagFmqMMO4bR+zxbHNjwwy5sR7HJHuZ9beUL57s0mMixYhDsWMHUFXOuRLnJktWpQ+lyNxTssxrJXlurRnwPFHid6xdralP1DoI0Rg1w-l9H2de+roa0v2P6X21jQEcujI6-qlsMoqxly8gJlJ5q83muDR9Qq8hzBgEgLAYDPZNuLas31tbA2HlDAi7A-N5WaMNYc3NjLzHJ4kraxx1boDPM4z42HHTQm1QiZbTjE78hAhBiKxkqLpW0lKoq6Tek8ORgn1qzZ7JOLkOfb6UIqNrWK3tZdfl3jq8weDdJjgimpqRM9owZj4gupsdmdxxm6D97ntqle9N3Js3ifNftWx-7uXKf9dvX5h90mV0WqOzvNnYVOe6TnbdqDS7HvFdzS9qLG67OE5F7astZOD0U-jUl19ydNiPE1+mw66Reei0uKN1okSHeTfmYZ-HKWTf0a+2L1zVuKVU9l+Dhn+zme25p1AadgHfHc9kTrw1ynV0yfg0Luj+TbVMcw6HgH0v7uFTtGRxHunXmso5SzkQI2MzlDIxRsAKec+paD6L4QBest-fJ8X63MuxNxTC3T+XKms9K4bqCEeLBxgYHF-Ou72hn7YjgIOlACgYAyFCIoFABB7gaBQOgEw+BCAkAABRIAb3D6AMAnBsA4BfgAlNwZ-Mh9TnfgLv7-w2rhH6ISiRGyYCv3Xz6mCF6D1AADoYCShrByBkAD8SA38pAgA) works fine. If you can reproduce this issue here, happy to look into it further.

The issue is reproduced in the this [stackblitz link I shared](https://stackblitz.com/edit/viem-getting-started-dw2gsw?file=index.ts). The TypeScript playground you shared does not construct the walletClient in the same way that I did, which is proably why it was working in your example. 

To see the bug, as well as the code that is working [check this stackblitz](https://stackblitz.com/edit/viem-getting-started-dw2gsw?file=index.ts). 

`talentCardsMarketContractBroken` will cause the compilation error, where as `talentCardsMarketContract` with the explicit typing does not @tmm

**Comment by jxom** [comment]
I can't reproduce it in this [TypeScript Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYygUwIYzQdQwG3zRgGF9g0A7GAGjgAsYYw6wBXAI3OQEFkZgESgGc6Ac2IkhMKBn50YATzBo4PACbr0w4XAC+cAGZQIIOAHIAbhRDmA3AChQkWIiMQ2lLYrocMwtABlNEhyDF9-VQNjUwtrNBAAemR6DGAReydwaHgkMChgSyw0AGk0RQAVCD5kD2p9IxMzKxtEuVrPGGFMhzQADxd4WpF4foxwIh4OYDgAXjgAbQc4RGWVuGEYYoBZNi3p8iUALgtKITAMRQwuNHMaNZWlFRPzYc2oNn5oO4e4dPYuiclut1khKOM0C8APqbDBQABedz+1DQUHB+AqykhFmGMjk8AAkgBRABKJAATAAGJFPbHmDCabTdfT3EErBC-EHgkB0qFbIjUEhw9TdVlslbpbBogiY5446SyfhwAkVAhUUjC0Wc9a0l4MrRoHQ-cV6MUgsEQ6EQADulFRSMlqPRsrp+qZNKxesZhuZpt+AF0xX72b9dRY0JZ1cb1hgzpRFCAPMIToYCAEzciAcnFtqOeKVty6fkI4I2MIAPK2+0ZkGO6UYz0WN0+6PisP071GmvrdLqfpodQnGRsNDd4NsvP5wsvO3Wyt2qCttl152NjsGrvax5r5ub-PIvt9AdDj6j7XjlaB37Tizz1HCejAMAVWQiQyo9DqaPjyfbuXmCMowzWMhATJMUzTM9a0oLMgVzLc4BvelkA6agl2gqVV3-XctX3dscPQnsvH7QcjEgscMyvLlLQsAAFDAywHb8xV-OB20AtDgLjMCywg-B01+f49mzYEJwQpC+QgABrKgCS-bsJRResXReNhJXJABWAA2Qi-zpNTqE0nSFIPEi+IEk1u1Y6ieWhcY6hgXTkUwmU1wMmAjKc9t3M8kzezMsj+KgtkL1BcSaPMGEtgRHhE06JyV1c-8fO0ry3PU1K-OIo9SNTIKKNzRCIskh0lKw11O1FNid0q0rD2PQKAhZAMMyQ1UBRgAAhDwxEYZi1lY9jI0434QPjOLszyiyiNgnNxWs9YJJgaTZPkhDEobZKMuMhDvO2hLsoaqbgpBUKQ33CT7PirKXM2-T9pMvbDMy9bDty8jzys8LbIsKK4XhWKHIO26VIsFKdrw9Lnoh-N-Jy8yTvWM7Vgu4qYlsG6nSSiqN1w-N8NqrL6ve-LPpa68Iva9VAggfA1pWH9QzXDjHK40CJoRjMhMBOaxNRn7kNQ1nXpBmrcbS7DCde4nObJkEqMWiKAFUYIYgJ6ea871lhbBdn2YBDkUGdzkua4iCXdtDE8fhBEoJduZEwqluAZAZMXOgNtB8x3nSMQPX-H3KD9zWJyKgWoSuzjnKxu7VIe6qtuh8wQ-NMPeXyF3bg9srsbjpOFChjzUpT0E0+hRioA0cXs9FyXq4TnH3RLhWCwijg2EqNVqA0EB0iXDxmGEoEFcZkEdbQPXrgN4BjlOE2rhuC21ytygbaEe2YKH3nU+d13q2j5S10Dv2C4DmRfeT5GLXD-l1TwQhiFK2vG5bU+X6NEv2TL36M+QLOD-KnnIuxkG5AM8s3VqEVhiGGAFAEAVMRoggHrNBYI8WK-HHpPA4M8jZz1Vgvc2GZLbWwEOvLmm8eYLGvryAQe93YANzhYY+-s6TMP0C3b+rx0DFAQcLJBewUHUJeE-GOXtwYsLAcXPQaCBoYK2LrPYU9DYvHiNaJe-4V5rztuQlBTtioVxEYfOu7o35enFp-Nwu83aGMAUw8+QcJF2IKA4iBFMBYSBgCSQ0qJIyA06N1NgvU+HrGQVvKhnCbGMPMOI0xYN9rsKDOgse8iJ6KOwbPFoaA1FEOXiQ22G9BERJrqIsWJjQFNlqgktxdJgDCB7n3DMoTKFCIsJE2OFgOAQFpo48wnTulVIZkk7WKSsHTwyao9RdJNGkO0YJChIkWmRWWjJSgck2liPjk9YBl8OFIVqbwqQlAYFwKYo0gRYTFnrLXH0-APSbk7MSbI5JOw0ljNwZk7JTMNF5LIXMlBuyIpxj-v3c5zSikMPadEzZhdwHSMeVrFYmDXnKIsOwdAkyXjTPyTosJeiBZXOMa-cp64m5X3BZ7UpRKCbmLJUhAl91oaoJ6eDJlFjLnFKMQy4BTLYlQsZf6S+VlyU50hRwRQ2AqrtjFRKwV5MbJ0iEKSEgABGZVGkNKdSwCkLxf9CinN+E0hZwrn4vGlYaAALHc8VFqHlrFHsMl5+sUXmDRVnL5UyfmzOgro+axqSmEq7MSgibK-WcrMWU6lpKhV0o5bYvl2zeXiJDTGiFGz87EqTbSiK9LTXWsldcvNsr5aQIFoqskqr1U6rQHqjWKxDVAnZamgtErLW8rNcIS1AyQ6sSRU6nBKiKCfJBMQ1eMyClhIBaWqs7sDWgqNSmilAb81LttYMp5DqFF9vGYOjFFgsW-O9ROktRY1b6v4YPMFC6RVe3uW2rptyu32sRSM5F-a4g7pyd80d2K-m4t9Vek1FT66RpbMm7NsaokxIzfE0Kk6ixsCgCkSIfjqDlkMF4gIUBIzqCqCsvGda50NtDXGqDWzYUyIRRsF9W73kTM-R679B6Zp-tDgB-179l0caLax8DTbE4Jug0nVx8qXhoqQwEWiBQ-5oYwz4gcuGqDCAJJQQI0VERnIvfO3ji6uW+UE9sx9Qzn2OqUW+8wcYLgELdcO3JjGvXMcoXBl46AzjWzQHeKAD4nwgs08PeFKMN2pJo8bfBZtrM6ls1o8dlC8U0JdtYiDkLmG8rYVm8OkdWZ8d05lfTsLo3FV-v-HTkiQFkakfl8OFcq5lOK0BiNlKP6wePS8AIhBeH1PswR3ziwKMBeM5u0zGSLOm0XvRzFnrouO3-cVBkvdtFZfDVShrvoKu8gCJl2rvT713O28JxWAt1sdZ8-8-zPbqODfecNqzu7zD7s65mC5nCYSP0Sze7bd7+lwuqS14g9FGLHaPXaozVGTPpNox+91427OTb899ux-0AeXu09etcuJFSEiVVSHpwavtrso72i7omEPhb0lDqLOKkcCzrKmP+azXvNptW2vNnbcf7dYWwMAgwlNKRpyTuA9bFiNs27e4l9zDPrv60FwneDLNhZu3dmH29S5WP3pt5LxLUurehMIMsKgvA5o6e90Xu2mtw+9rrqgOGu7BK6ydoHEuQcDbBwOrJ8uJsU60zfeLquUdn2cSfDX9jg6s9bgdi3xErcdUR57ukButvdI+w+1nT7HdS+d++13Y293u9-ZT2P9P+N6bKzpLtof2fCD132SP6p8P88I4L4jUSRdSpN71s7oO3ku6HRFr95Pc8iScxYW+gpNTR7gtN-FBe6Ro-xMqA5o-eU48oqduRHfnV0ch9n6HHuiNsbDU4i+KWg+rrZy8WhbsqgKdWbWuv3Xwl75I9CwvUi2+r6d53mXI3CGb9uznw9eeZwskPM48CJF9KkQ9OE8Q3xUQPMvMwAx8esV9nl39nUrs5cs9f9t9+9d8Zs4oo5NtSMYUX9msLBrQZ56AtAMBu9bdAc11-Q4B-AUAhBNhHAHA3h4BZt0gagHI5g4AM4ihsAyhKhqgUIHIAAKNYfICAP+HQAAOioEsFkM6gABlywSASgSAAAJHgAkAAOShB4AABFtg9CoQcAeBlDlCiQKgoRaISQCQAA1HgCoIkKEEoIkAATQYN0Gqx9AcAAEpWDgBDA4AxCABCKQmQ4QeQygRQlQtQjQ7Q0wwICoHgEkAALShBIHLF0IqBJB4BIAqH8ICxgHoBMGtEQiyTgCJCgBMCgDEPMHiPUK0J0P0JSLSMyOyNyPyMKL+F0DOHgHW3MECIcD0CcBCPCMiJ9BiLiNUOaKSP0NSKsNyJIDSMMMCCyJyLyIKKKJKLKJtEqIqJqLqIaKaMSNaKhCWKJBWLWI2K6O2N6NqUQggEGMfhGLGOCNCIiJMCiJmKULmPONMKuJuJJHWKhG2DSPcJsPuJ6N2MnFKPKMOOqNqOgFOIBJaKBIsOuIqFWNBI2IhJJChM2O6J2L6OeNeMcneIcAcDuzgA8RIFSHSDEOKMnCICGEZMoEcAlAmKmLkIUNkOuIcLmFmHmHMD7EjHwAgDAB5DQhZN+CQ3SF4MMDqG8C5IaDQCCj+B5J+OmP5MFOFNFNhDEAvjlJBAVMoF4L8ACGCFCGAAwDVIMA1KalYnNMtMiAdLWHQBgAQwtPNMcDGLYOYI4PUDmzIAoHqHmFQEwGwHvjZLDPVDEMnHaAchOE4MoG4M6DFHNJOHpI5OZLFCgIrxyBOEYGYDEN5OiP5LOIxP0N0OsJwHLEJP8PuD0H8PkL6GwC8HLM4G4D4BmWEBGMDJGDYmtyFCgBFG2DhBklIAVHxE6hMBWV4PpNnP4ETLWBwhOArL+OrIWMuKxJBLBIJKJJhNJMYN8J0DFCnhODGAmDQCmGACzPIHVFTJDPSHjOoBbMCKAA) which forks all the code in your example.

Could be worth comparing the TSConfig in the playground (which is generally the best default) to yours?
