### ISSUE TITLE
How does this work? It does not exist. c

### ISSUE THREAD

**Issue by CaiJohn** [wevm/wagmi#3847]
### What is the issue?

import { alchemyProvider } from 'wagmi/providers/alchemy'
as in https://1.x.wagmi.sh/react/providers/configuring-chains

The package does not exist. 

### Where did you find it?

import { alchemyProvider } from 'wagmi/providers/alchemy'
as in https://1.x.wagmi.sh/react/providers/configuring-chains

The package does not exist.

**Comment by tmm** [comment]
Check to make sure you have `wagmi@1` installed.
