### ISSUE TITLE
dependency version mismatch (non blocking)

### ISSUE THREAD

**Issue by grmkris** [wevm/wagmi#3851]
### Describe the bug

i ve been using PNPM which reports dependency miss-matches 

```
 wagmi 2.5.20
  └─┬ @wagmi/connectors 4.1.26
    └─┬ @metamask/sdk 0.14.3
      ├─┬ @metamask/sdk-communication-layer 0.14.3
      │ └─┬ socket.io-client 4.7.5
      │   └─┬ engine.io-client 6.5.3
      │     └─┬ ws 8.11.0
      │       └── ✕ unmet peer utf-8-validate@^5.0.2: found 6.0.3 in @metamask/sdk-communication-layer
      └─┬ @metamask/sdk-install-modal-web 0.14.1
        └─┬ react-i18next 13.5.0
          └── ✕ unmet peer i18next@">= 23.2.3": found 22.5.1 in @metamask/sdk-install-modal-web
```

is not direct problem of wagmi i suppose, but i wonder if anyone else experiencing this? I prefer my projects to be without these, so my ocd doesn't kill me everytime i install deps

no issues in runtime though

### Steps To Reproduce

install latest wagmi and run pnpm install

### Wagmi Version

2.5.20

### Viem Version

2.9.26

### TypeScript Version

5.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
best to raise upstream https://github.com/MetaMask/metamask-sdk

**Comment by grmkris** [comment]
done, maybe worth checking if you can go to latest metamask-sdk 
https://github.com/MetaMask/metamask-sdk/blob/8ee0a839a8e58deabf0d64588bdbeb3f72cc16b1/packages/sdk-communication-layer/package.json#L3 (`"version": "0.18.5"`) i don't think they fixed it already in that version but maybe worth checking it out
