### ISSUE TITLE
unhandledRejection ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by AlbertFiat24** [wevm/wagmi#3853]
### Describe the bug

When using last version of wagmi 2.5.21 when building get this error, using NextJS

unhandledRejection ReferenceError: navigator is not defined
    at file:///Users/albert/Developer/reactdapp/node_modules/wagmi/node_modules/@wagmi/connectors/dist/esm/metaMask.js:4:95
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15) {
  type: 'ReferenceError'
}

### Steps To Reproduce

npm run build

### Wagmi Version

2.5.21

### Viem Version

2.x

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by phi0411141** [comment]
I also have same issue with latest version
