### ISSUE TITLE
BigInt value can't be serialized in JSON

### ISSUE THREAD

**Issue by tien** [wevm/wagmi#3855]
### Describe the bug

Using `readContractQueryOptions` with BigInt in `args` will result in a query key containing BigInt, crashing `react-query` serialization.

### Wagmi Version

2.5.20

### Viem Version

2.9.26

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tien** [comment]
@tmm I'm not persisting the data though, the query **key** them self contains `BigInt` values.

**Comment by tien** [comment]
@tmm this can be easily reproduced by doing
```ts
import { readContractQueryOptions } from 'wagmi/query';

// Observe that the query key which will be used by `react-query` contains BigInt 0n
// which will throw a serialization error
console.log(
  readContractQueryOptions(
    {},
    {
      args: [0n],
    }
  )
);
```

**Comment by tmm** [comment]
This test works fine https://github.com/wevm/wagmi/commit/67ac1eb0785d49989d2817787a0ee6ed92d02262

Either attach a minimal reproduction or break the test.

**Comment by tien** [comment]
@tmm the test show that it's incorrect. See how the `0n` bigint is included in the query key? This will break if you try to use it with react-query `useQuery` or `useSuspenseQuery` (as instructed in wagmi docs on how to use suspense)

**Comment by tien** [comment]
As in doing this will lead to a crash, because react query can't handle bigint

```ts
useSuspenseQuery(readContractQueryOptions(config, {
   args: [0n],
});
```

**Comment by tmm** [comment]
> the test show that it's incorrect

You said the bug could be reproduced by doing [this](https://github.com/wevm/wagmi/issues/3855#issuecomment-2079500375). The test reflects that.

---

Either you need to handle serialization yourself or you can import `hashFn` from `wagmi/query` (used [internally](https://github.com/wevm/wagmi/blob/main/packages/react/src/utils/query.ts#L140)):

```ts
import { hashFn } from 'wagmi/query'

useSuspenseQuery(readContractQueryOptions(config, {
  args: [0n],
  queryKeyHashFn: hashFn, // for bigint support
});
```

**Comment by tien** [comment]
@tmm thanks for clarifying the manual serialisation part. That's what I'm doing right now.

But I didn't know that you are expected to do that, and that the lib expose a utility function for that. Maybe the docs should includes that as well.
