### ISSUE TITLE
Wallet Connection is not functional

### ISSUE THREAD

**Issue by vinu679** [wevm/wagmi#3861]
### Describe the bug

When we use "@solana/web3.js": "^1.91.7" along with wagmi/core V2, Wallet connection QR model not opening. Insted it's throws below Error.

ERROR TypeError: Cannot set property signal of [object AbortController] which has only a getter

### Steps To Reproduce

install wagmi version 2 and then install solana packages.

"@solana/wallet-adapter-base": "^0.9.23",
 "@solana/web3.js": "^1.91.7",

### Wagmi Version

^2.0.2

### Viem Version

^2.0.3

### TypeScript Version

~5.4.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by glitch-txs** [comment]
Can you run this script and share the output 

```sh
npm ls @walletconnect/sign-client
```
