### ISSUE TITLE
`usePrepareTransactionRequest` fails `eth_maxPriorityFeePerGas` rpc call on MetaMask injected connector

### ISSUE THREAD

**Issue by holic** [wevm/wagmi#3865]
### Describe the bug

I am using `usePrepareTransactionRequest`, which internally calls `eth_maxPriorityFeePerGas` using the connector client, which fails on injected MetaMask connector:

<img width="559" alt="image" src="https://github.com/wevm/wagmi/assets/508855/e727d849-7761-4d7e-82b2-e3952c61d028">

```
{
    "code": -32601,
    "message": "The method \"eth_maxPriorityFeePerGas\" does not exist / is not available.",
    "data": {
        "origin": "http://localhost:5173",
        "cause": null
    }
}
```

### Wagmi Version

2.6.0

### Viem Version

2.9.20

### TypeScript Version

5.4.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by holic** [comment]
I worked around this for now with:

```ts
const fees = useEstimateFeesPerGas({ chainId });
const prepared = usePrepareTransactionRequest({
  chainId,
  to,
  value,
  maxPriorityFeePerGas: fees.data?.maxPriorityFeePerGas,
});
```

**Comment by tmm** [comment]
https://github.com/MetaMask/metamask-extension/issues/24225

**Comment by jxom** [comment]
I think we can resolve this by not using the connector client for `usePrepareTransactionRequest`. It's not needed.
