### ISSUE TITLE
shimDisconnect is ignored

### ISSUE THREAD

**Issue by mqklin** [wevm/wagmi#3874]
### Describe the bug

Connecting a MetaMask wallet asks to connect a wallet to a site even if shimDisconnect is false. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-srzqhu

### Steps To Reproduce

1) Go to https://stackblitz.com/edit/vitejs-vite-srzqhu
2) Click "MetaMask"
3) Connect to the site
4) Click Disconnect
5) Click "MetaMask" again. You'll see this popup, which should not be shown:
![image](https://github.com/wevm/wagmi/assets/9456433/7e846faf-a015-43c2-9353-68739e27cabe)

### Wagmi Version

latest

### Viem Version

latest

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
This is because you have both `injected` and `metaMask` connectors set up in your config and [`multiInjectedProviderDiscovery`](https://wagmi.sh/core/api/createConfig#multiinjectedproviderdiscovery) is set to `true` by default.

**Comment by mqklin** [comment]
@tmm https://stackblitz.com/edit/vitejs-vite-srzqhu?file=src%2Fwagmi.tsx please check this.
I removed everything except `injected`:
```
  multiInjectedProviderDiscovery: false,
  connectors: [injected({ shimDisconnect: false })],
```
Now it always connects only the first account, even after I click Disconnect. I expect it to let me select an account to connect, not just select the first one. Is it intended? Or a bug?

**Comment by mqklin** [comment]
https://github.com/wevm/wagmi/assets/9456433/27232aaa-0edd-4cb5-a0db-6da4636edd11
