### ISSUE TITLE
useEnsAddress on L2s

### ISSUE THREAD

**Issue by sergical** [wevm/wagmi#3877]
### Describe the bug

ChainDoesNotSupportContract: Chain "OP Mainnet" does not support contract "ensUniversalResolver". This could be due to any of the following: - The chain does not have the contract "ensUniversalResolver" configured. Version: viem@2.7.6 at 

### Steps To Reproduce

Config:

```ts
export const config = createConfig({
  chains: [mainnet, polygon, arbitrum, optimism, sepolia, base],
  multiInjectedProviderDiscovery: false,
  transports: {
    [mainnet.id]: http(),
    [polygon.id]: http(),
    [arbitrum.id]: http(),
    [optimism.id]: http(),
    [sepolia.id]: http(),
    [base.id]: http(),
  },
})
```

Call
```
const ensAddress = useEnsAddress({
  name: normalize('sergiy.eth'),
  chainId: 10 //optimism.id
})
```

### Wagmi Version

2.5.7

### Viem Version

2.7.6

### TypeScript Version

5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Error message explains the issue. ENS contracts are not deployed.

**Comment by sergical** [comment]
> Error message explains the issue. ENS contracts are not deployed.

So this is at the chain level? Is there a way to view which chains have the contract deployed? Latest version of wagmi seems to only allow `1` as the chainId parameter, so it's mainnet only?

**Comment by tmm** [comment]
https://docs.ens.domains/web/multichain
