### ISSUE TITLE
coinbase and walletconnect connectors don't have icons

### ISSUE THREAD

**Issue by heyitsarpit** [wevm/wagmi#3879]
### Describe the bug

`connector.icon` does not exist for `coinbaseWallet` and `walletConnect` imported from `'wagmi/connectors'`.

### Link to Minimal Reproducible Example

https://wagmi-conector-bug.vercel.app/

### Steps To Reproduce

Here is the repository with the code 
https://github.com/heyitsarpit/wagmi-conector-bug

### Wagmi Version

2.7.1

### Viem Version

2.9.29

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by glitch-txs** [comment]
we could add it for WalletConnect if it's ok for Tom and Jake

**Comment by jxom** [comment]
Icon is only used for EIP-6963 Injected Connectors. We probably won't add it to other connectors as consumers typically have differing requirements & standards for icons.
