### ISSUE TITLE
@wagmi/connectors@4.3.1 requires @wagmi/core@2.8.1 specfically

### ISSUE THREAD

**Issue by topleft1562** [wevm/wagmi#3881]
### Describe the bug

Looks like wagmi/connectors is requiring wagmi/core 2.8.1 so upgrading to 2.9.0 creates issues.
would be nice to be able to upgrade all packages and stay with latest!

### Steps To Reproduce

upgrade @wagmi/core to 2.9.0 and @web3modal to 4.1.11

### Wagmi Version

2.8.0

### Viem Version

2.9.31

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by jxom** [comment]
Should be good now.
