### ISSUE TITLE
useWatchContractEvent doesn't work properly when using watched hooks

### ISSUE THREAD

**Issue by rin-st** [wevm/wagmi#3883]
### Describe the bug

I need to listen to events using `useWatchContractEvent` and it's working fine. At the same time I need to watch balance of some address. I'm using technique from [v1 to v2 migration guide](https://wagmi.sh/react/guides/migrate-from-v1-to-v2#removed-watch-property) to watch balance. But when I'm adding it `useWatchContractEvent` doesn't work locally (`hardhat`, `foundry`) and works from time to time on `sepolia` (not every event). At the same time `onError` of `useWatchContractEvent` triggers often. Example from pinned app
```
InvalidInputRpcError: Missing or invalid parameters.
Double check you have provided the correct parameters.

URL: https://rpc.sepolia.org
Request body: {"method":"eth_getFilterChanges","params":["0xe113405727fb7f30c30ea40767b77639"]}

Details: filter not found
Version: viem@2.9.31
    at withRetry.delay.count.count (chunk-ADKPSZLC.js?v=ae0a275b:1698:19)
    at async attemptRetry (chunk-ADKPSZLC.js?v=ae0a275b:1662:22)
```

Error from `hardhat` network:
```
TypeError: Cannot read properties of null (reading '0')
    at getFilterChanges (getFilterChanges.js:100:20)
    at async unwatch.emitOnBegin (watchContractEvent.js:110:32)
    at async poll (poll.js:23:13)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-cauhct?file=src%2FApp.tsx

### Steps To Reproduce

use `useWatchContractEvent` and at the same time other [watched value](https://wagmi.sh/react/guides/migrate-from-v1-to-v2#removed-watch-property)

### Wagmi Version

^2.5.12 (also tried last version)

### Viem Version

^2.8.16 (also tried last version)

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by banteg** [comment]
filter are stateful, they don't work on public rpc providers. i think the methods needs to be updated to use eth_getLogs polling instead and maintain the filter state locally.

**Comment by Hotmanics** [comment]
> filter are stateful, they don't work on public rpc providers that load balance between several nodes. i think the method needs to be updated to use eth_getLogs polling instead and maintain the filter state locally. i think there is already a fallback looking at [viem](https://viem.sh/docs/contract/watchContractEvent.html) documentation.

Could you elaborate on this?

useWatchContractEvent doesn't seem to fire when we are expecting it to. 

You're saying it has something to do with the filtering?

Glad to provide dev work once we can identify the problem!

**Comment by nikitayutanov** [comment]
Ran into the same problem, with the difference that I'm using bare `watchContractEvent` action (and only it, there are no another watch functions or hooks).

In my case feels like if `watchContractEvent` is active long enough and `onError` argument is provided, soon enough it'll start to return this alongside with errors specified in the original post:
```ResourceNotFoundRpcError
    at withRetry.delay.count.count (buildRequest.ts:130:21)
    at async attemptRetry (withRetry.ts:44:22)Caused by: RpcRequestError
    at request (http.ts:131:19)
    at async withRetry.delay.count.count (buildRequest.ts:104:18)
    at async attemptRetry (withRetry.ts:44:22)
```
`onLogs` though is working as expected, and if `onError` is not provided there are no any differnces in `watchContractEvent`'s functionality at all.

**Comment by neocybereth** [comment]
@nikitayutanov I'm having the exact same issue on my end with `watchContractEvent` *AND* `useWatchContractEvent`. It works but it's very intermittent.

**Comment by nikitayutanov** [comment]
@neocybereth I've changed my RPC provider and it seems to have fixed the problem.
