### ISSUE TITLE
wagmi provider not found, using wagmi hooks within npm package

### ISSUE THREAD

**Issue by znevo** [wevm/wagmi#3885]
### Describe the bug

Our npm package exports react components which use wagmi hooks.

After upgrading the wagmi and viem peer deps of our package to v2 we began encountering the following error when using our component in a next.js app (which is properly wrapped with a wagmi provider):

```WagmiProviderNotFoundError: `useConfig` must be used within `WagmiProvider`.```

### Link to Minimal Reproducible Example

https://github.com/decentxyz/fresh-turbo

### Steps To Reproduce

i have created a fresh turborepo [here](https://github.com/decentxyz/fresh-turbo)

the starter example is two next.js apps: 'web' and 'docs', and a shared package 'ui' with a button component imported by both next.js apps.

i added rainbowkit v2 to the 'web' app, and used useAccount with [this commit](https://github.com/decentxyz/fresh-turbo/commit/0862a1562013d059a96f0798c9409bd3a3f4d66a#diff-fd023d75d1ed8133295c3359120c1f334b252c95341a0c411018fd0e8411c5e3R59-R60) and no issues using the hook

added useAccount hook and wagmi peer dep to the button component in the shared ui package with [this commit](https://github.com/decentxyz/fresh-turbo/commit/53f7973e05a78d6bd286ecd781de4789756eb1f9#diff-54e976c9e25a1c11aa59c088a36d31acd884abaeb450882b0e0b0e5076a83508R13-R14) and this causes the following wagmi error in the next.js app

```WagmiProviderNotFoundError: `useConfig` must be used within `WagmiProvider`.```

same repo on the [v1 branch](https://github.com/decentxyz/fresh-turbo/tree/v1), i followed the same exact steps but this time using wagmi/viem/rainbow v1

added rainbowkit v1 to the 'web' app and used useAccount with [this commit](https://github.com/decentxyz/fresh-turbo/commit/43e5038f533bddcbc17bdf8952898b3dd9a96780) and no issues using the hook

again i added the useAccount hook and wagmi peer dep in the button component in the shared ui package with [this commit](https://github.com/decentxyz/fresh-turbo/commit/e303fad28d5cdb0536f7ce5abee5ca3ad56ca3cd), but this time with everything on v1 and it is working just fine

### Wagmi Version

2.5.11

### Viem Version

2.8.12

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
Please make the reproduction more minimal.
