### ISSUE TITLE
WAGMI and NEXTJS latest have conflicts

### ISSUE THREAD

**Issue by klclee** [wevm/wagmi#3937]
### Describe the bug

Hi the issue is on NextJS latest. To replicate:

* `npx create-next-app@latest nextjs-blog --use-npm`
* `npm i wagmi`
Error:

npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-i18next@13.5.0
npm WARN Found: i18next@22.5.1
npm WARN node_modules/i18next
npm WARN i18next@"22.5.1" from @metamask/sdk@0.20.3
npm WARN node_modules/@metamask/sdk
npm WARN @metamask/sdk@"0.20.3" from @wagmi/connectors@4.3.10
npm WARN node_modules/@wagmi/connectors
npm WARN 1 more (@metamask/sdk-install-modal-web)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer i18next@">= 23.2.3" from react-i18next@13.5.0
npm WARN node_modules/react-i18next
npm WARN peer react-i18next@"^13.2.2" from @metamask/sdk-install-modal-web@0.20.2
npm WARN node_modules/@metamask/sdk-install-modal-web
npm WARN
npm WARN Conflicting peer dependency: i18next@23.11.4
npm WARN node_modules/i18next
npm WARN peer i18next@">= 23.2.3" from react-i18next@13.5.0
npm WARN node_modules/react-i18next
npm WARN peer react-i18next@"^13.2.2" from @metamask/sdk-install-modal-web@0.20.2
npm WARN node_modules/@metamask/sdk-install-modal-web

### Steps To Reproduce

* `npx create-next-app@latest nextjs-blog --use-npm`
* `npm i wagmi`

### Wagmi Version

2.8.7

### Viem Version

2.10.5

### TypeScript Version

5.4.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

The bot here is pretty agressive. Think is the 3 close of the same issue with no explaination. If you guys dont support NEXTJS please let us know. Or provide some kind of explaintion before closing please.

**Comment by tmm** [comment]
Wagmi supports Next.js and the message you pasted looks like a warning, not an error.

Looks like conflicting dependency version between [`@metamask/sdk`](https://github.com/MetaMask/metamask-sdk) and your project. You should open an upstream issue [there](https://github.com/MetaMask/metamask-sdk).
