### ISSUE TITLE
Base Etherscan not in `etherscan` plugin on @wagmi/cli@latest

### ISSUE THREAD

**Issue by jrfrantz** [wevm/wagmi#3938]
### Describe the bug

I landed Base Etherscan support landed in `@wagmi/cli/plugins/etherscan` a while back. 

But when I `yarn -D @wagmi/cli@latest`, in my repo, base and base sepolia are not supported. The version when I `yarn list @wagmi/cli` is `2.1.4`

When I check node_modules (`@wagmi/cli/src/plugins/etherscan.ts > apiUrls`, which is where the typing seems to come from), I don't see base or base sepolia listed

### Steps To Reproduce

`yarn add @wagmi/cli@latest`

in wagmi.config.ts,
```ts
import { defineConfig } from '@wagmi/cli'
import { blockExplorer, etherscan } from '@wagmi/cli/plugins'
import { baseSepolia } from 'viem/chains'

export default defineConfig({
  out: 'util/generated.ts',
  contracts: [],
  plugins: [
    etherscan({
      apiKey: process.env.ETHERSCAN_API_KEY!,
      chainId: baseSepolia.id,
      contracts: [{
        name: 'CreatorLootboxToken',
        address: {
          [baseSepolia.id]: '0x009e6dd75a009f22a7eca670d6e8dea672c8ccf5',
        },
      }]
    })
  ],
})

```

### Wagmi Version

2.9.0

### Viem Version

2.10.5

### TypeScript Version

5.4.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

When I check the file in github, I see one failed (hanging) test and a red ❌ next to my commit that added it. https://github.com/wevm/wagmi/blob/main/packages/cli/src/plugins/etherscan.ts

**Comment by tmm** [comment]
Looks like [this release](https://github.com/wevm/wagmi/actions/runs/8482288315/job/23241346987) failed and there was another changeset that came in right after it that cleared the release.

https://github.com/wevm/wagmi/commit/1122678bbad0232590bd4060a73752de2c84982d will catch `@wagmi/cli` up!
