### ISSUE TITLE
When connect to metaMask, got onError triggered before user doing something in wallet.

### ISSUE THREAD

**Issue by zslucky** [wevm/wagmi#3943]
### Describe the bug

![image](https://github.com/wevm/wagmi/assets/15725589/c51fabdb-2098-4cda-a461-ba76bd487e94)

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/busy-sinoussi-vg29c7?file=%2Fsrc%2Fcontainers%2FDemo.jsx%3A16%2C1

### Steps To Reproduce

1. Go to reproducible example.
2. Click the `Connect` button.
3. Select desktop -> connect with metamask web extension.

you will see the `onError` and `onSettled` triggered before user do something.

### Wagmi Version

2.9.2

### Viem Version

2.10.9

### TypeScript Version

5.36.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

everything is ok for `walletconnect`, but not ok for metaMask web extension.

**Comment by tmm** [comment]
Minimal reproduction is not accessible.

> Devbox not found
> It's likely that the Devbox you're trying to access doesn't exist or you don't have the required permissions to access it.

**Comment by zslucky** [comment]
https://codesandbox.io/p/live/5d5f7136-296b-4d53-aa14-38c75a77c34e?file=%2Fsrc%2Fcontainers%2FDemo.jsx%3A16%2C1
@tmm

**Comment by tmm** [comment]
This error is thrown directly by the MM extension when there is already a connect pending (e.g. `'eth_requestAccounts'`).

**Comment by zslucky** [comment]
But seems I did nothing...
