### ISSUE TITLE
Example from the docs doesn't work anymore

### ISSUE THREAD

**Issue by mqklin** [wevm/wagmi#3948]
### What is the issue?

https://wagmi.sh/react/guides/connect-wallet#playground
There is just white screen 
![image](https://github.com/wevm/wagmi/assets/9456433/e8d8b769-3160-415c-91ec-171a9ad3bbbf)

### Where did you find it?

https://wagmi.sh/react/guides/connect-wallet#playground

**Comment by 0x33dm** [comment]
I have reported it as well [here](https://github.com/stackblitz/core/issues/3053) and [here](https://github.com/stackblitz/core/issues/3053) @tmm [posted this video](https://github.com/wevm/wagmi/issues/3942#issuecomment-2117698628) but unfortunately he doesn't wait for the app to start before finishing the video.

I tested on Windows 10 and Arch Linux, with Chrome / Firefox / Opera.

**Comment by tmm** [comment]
Works fine for me.

https://github.com/wevm/wagmi/assets/6759464/77b4ebb8-5b20-4f6c-9e21-07974dae763a

**Comment by 0x33dm** [comment]
It's now working for me.

This URL also works -> https://new.wagmi.sh/ 

Does new.wagmi.sh works for you @mqklin ?

**Comment by mqklin** [comment]
Yes, now good.
