### ISSUE TITLE
 Foundry Plugin Error - Contract Name "IERC721TokenReceiver" Must Be Unique

### ISSUE THREAD

**Issue by alexx855** [wevm/wagmi#3951]
# Bug description

When setting up a new create wagmi project and configuring Foundry according to the documentation, an error occurs during the wagmi generate command. The error message indicates that the contract name "IERC721TokenReceiver" must be unique.

## Steps to Reproduce

1. Initialize a new `create wagmi` project.
2. Configure Foundry wagmi plugin.
3. Create a new Foundry project using `forge init`.
4. Attempt to generate wagmi artifacts with `wagmi generate`.

```
> wagmi generate
✔ Validating plugins
⠹ Resolving contracts
Contract name "IERC721TokenReceiver" must be unique.
 ELIFECYCLE  Command failed with exit code 1.
```

My Configuration File (wagmi.config.ts)

```typescript
export default defineConfig({
  out: 'src/generated.ts',
  contracts: [],
  plugins: [
    foundry({
      project: '../hello_foundry',
    }),
  ],
})
```

### Cause
The issue is caused by a conflict with forge-std version 1.8.0 or higher, which is installed by default with Foundry.

### Solution
To resolve this issue, i downgraded forge-std to version 1.7.6. Following these steps:

1. Remove the current version of forge-std:
```bash
forge remove foundry-rs/forge-std
git commit -m "Removed foundry-rs/forge-std"
```
2. Install version 1.7.6 of forge-std:
```bash
forge install foundry-rs/forge-std@v1.7.6
forge clean
```

### Wagmi Version

latest

### Viem Version

latest

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

Let me know if i can help somehow!

**Comment by script-money** [comment]
Meet the some issue
