### ISSUE TITLE
`wagmi generate` stuck

### ISSUE THREAD

**Issue by oxSaturn** [wevm/wagmi#3952]
### Describe the bug

I'm working on upgrading a wagmi v1 project to v2, but ran into this issue as below:

![image](https://github.com/wevm/wagmi/assets/126733611/72a101a9-b28a-41c6-8d54-79214130d1cd)

As you can see,`wagmi generate` command was stuck there forever.

So I just modified the cli code to see if I can find something wrong:

![Screenshot-eFw46A6B@2x](https://github.com/wevm/wagmi/assets/126733611/d592b0a8-ee61-47bb-bc62-81e86accff1a)

Here's the result of running `wagmi generate`:

```sh
✔ Validating plugins
✔ Resolving contracts
✔ Running plugins
✔ Writing to ./lib/wagmiGen.ts
Done
```
Obviously, the `generate` function proceeded without any problem.

I'm not sure what's going on here.

I can insert a `process.exit(0)` right after the `await generate(options)`:

![Screenshot-jRlPK5Mo@2x](https://github.com/wevm/wagmi/assets/126733611/475220bd-23d1-4452-a8d7-f3192269fd1c)

Then everything would work as expected, but I'm not sure it's the right fix.

I'm wondering if anyone ran into this problem? And how did you solve it? Or it would be a bug?

### Wagmi Version

latest

### Viem Version

latest

### TypeScript Version

^5.4.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by oxSaturn** [comment]
Ok, here's what I found with `process._getActiveHandles()`:

![Screenshot-UTdOkukV@2x](https://github.com/wevm/wagmi/assets/126733611/fca411be-45a3-43de-a658-99882230d200)

Seems websocket is open somewhere due to walletconnect when running `wagmi generate` command:

![Screenshot-DXcpGQdD@2x](https://github.com/wevm/wagmi/assets/126733611/25545890-7539-4cee-a237-1f12107f2ca3)

**Comment by oxSaturn** [comment]
@tmm Hey, sorry about the haste issue without a reproduction, it's a huge project and took me a while to figure out what's going on, and here's the reproducible repository you can check out and run `wagmi generate` to reproduce.

https://github.com/oxSaturn/wagmi-generate-bug

The culprit is I'm importing a variable from `constants` which would be used in `_app.tsx` as well, obviously it's triggering the walletconnect to connect without close, hence hang `wagmi generate` command.

**Comment by oxSaturn** [comment]
> Is this only reproducible when you are using RainbowKit?

Just pushed another commit to test without rainbowkit, obviously it's still reproducible with the `walletConnect` connector from wagmi.

**Comment by oxSaturn** [comment]
@tmm Can you reproduce it with my repository? If so, can you please reopen this issue?

**Comment by tmm** [comment]
Haven't had a chance to try to reproduce yet, but it's on my todo list.
