### ISSUE TITLE
Playground SSR example will throw "ChainNotConfiguredError: Chain not configured."

### ISSUE THREAD

**Issue by 0x33dm** [wevm/wagmi#3953]
### Describe the bug

As reported [in this issue](https://github.com/wevm/wagmi/issues/3942) having SSR enabled on wagmi will potentially lead to an unrecoverable error ( as in a broken website that doesn't render to any of the users ) because of some unguarded interaction between cookies / localstore / wagmi config.

On my personal project, I have had a problem where we only have `fantom` and `bsc` on the config, but localStorage was trying to load `chained` 1, which leads to some sort of BSOD on Vercel production environment blocking users from using the entire website.

I suspect the problem lies on

 - Include mainnet ( or any other chain ) in your list of chains as you start working on your project
 - Replace with another chain ( for instance, change it for fantom )
 - For some reason, the localStorage / cookies will not forget the mainnet chainId, and eventually, this will lead to a crash due to the Wagmi frontend code trying to load a chain that is actually not listed anymore on the config.

I believe if this error "ChainNotConfiguredError: Chain not configured" occurs when initially loading the website ( perhaps from SSR / localStorage / etc.), Wagmi should check if the chain still exists on the configuration, and if not, just default to the first one or allow marking a chain as "default".

Also, in my case, the chainId on useChainId started starts correctly with chainId 250, but then Wagmi on the frontend didn't align with it. I believe it has something to do with the SSR / Cookies

I have reported [this issue here](https://github.com/wevm/wagmi/issues/3942) but unfortunately the issue is now closed automatically because I wasn't able to provide a minimal reproduction example ( as the time of writing https://new.wagmi.sh doesn't work for me, as reported [here](https://github.com/wevm/wagmi/issues/3942#issuecomment-2120430887) and [here](https://github.com/stackblitz/core/issues/3053)

### Link to Minimal Reproducible Example

https://github.com/0x33dm/wagmi-chain-not-configured-error

### Steps To Reproduce

I have now copied the code from here: https://github.com/wevm/wagmi/tree/main/playgrounds/next into a new repository, which you can clone here: https://github.com/0x33dm/wagmi-chain-not-configured-error

In my case, to reproduce the error, I have to:

```bash
git clone https://github.com/0x33dm/wagmi-chain-not-configured-error
cd wagmi-chain-not-configured-error
pnpm install
pnpm dev
```

This will launch the website on `localhost:3000` on my machine; I'll see the following logs on the command line ( server side:

````bash
chainId from useChainId is 250
````

And I will see this on the frontend:

````bash
chainId from useChainId is 250
page.tsx:383 chainId from useChainId is 250
````

And then the website will crash:

![image](https://github.com/wevm/wagmi/assets/166445471/32b63bc7-421c-4525-869a-b01f7ca7a58c)

I believe the problem here is that I have my own project previously running on `localhost:3000`, which now has only `fantom` and `bsc` running. However, when changing the config from wagmi ( now with the playground example ), wagmi will still try to connect to `fantom` even though fantom isn't anymore on the config.

I think this error is pretty much what my users and other developers from my project are experiencing. At some point, `wagmi` used `chainId` 1, but now it's not available anymore, which results in an uncaught error and the entire website crashing.

To reproduce, you might have to run the original config from the repo first and then change the list of "chains" to include different chains. For instance, change it to fantom and/or bsc.

### Wagmi Version

2.9.2

### Viem Version

2.*

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

https://github.com/wevm/wagmi/issues/3942

**Comment by Alirizabakir** [comment]
Hey @0x33dm . I'm having the same problem and I've just started researching. Feel free to let me know when you find a healthy result. Thanks

**Comment by 0x33dm** [comment]
> Hey @0x33dm . I'm having the same problem and I've just started researching. Feel free to let me know when you find a healthy result. Thanks

There was an update on wagmi regarding this following another issue I created.

Anyway, this is how my config on VERCEL looks like, i make a unique KEY per environment and it's also based on the chains in the configuration, i believe this helps having less issues when you change the number of chains or change environments, etcs.

Let me know if there is something on my config that can be improved, i would appreciate it too ( : 

ps: i followed you on X, drop me a message there. ✌️ 

````ts
const chains = [optimism, arbitrum] as const

const chainIds = chains.map((chain) => chain.id).join(',')

const key = `wagmi-${process.env.NEXT_PUBLIC_VERCEL_ENV}-chains-${chainIds}`

export const config = createConfig(
  getDefaultConfig({
    chains,
    transports: {
      [optimism.id]: http(undefined, { batch: true }),
      [arbitrum.id]: http(undefined, { batch: true })
      // [mainnet.id]: http(undefined, { batch: true })
    },
    ...
    storage: createStorage({
      key,
      storage:
        typeof window !== 'undefined' && window.localStorage
          ? window.localStorage
          : noopStorage
    })
  })
)
````

**Comment by Alirizabakir** [comment]
Thank you for the answer. I created a similar solution myself, it looks nice now, but I also liked your solution very much and think I will use it.
