### ISSUE TITLE
Playground code won't build, prevents users from creating minimal reproduction for server side issues with wagmi 

### ISSUE THREAD

**Issue by 0x33dm** [wevm/wagmi#3954]
### Describe the bug

Currently, I'm having some production errors with Wagmi that don't happen in dev.

In order to try that locally I need to run "pnpm build" then "pnpm start".

In order to report the issue here I need a "reproduceable" example so I thought it would be a good idea to use the files from the Next.js [playground found here](https://github.com/wevm/wagmi/tree/main/playgrounds/next) the problem is that when trying to run "pnpm build" on that example it won't build for a few different reasons:

1. that playground depends on workspace:* for wagmi, which is easily solvable installing installing wagmi from npm.js ( i.e. pnpm remove wagmi;pnpm install wagmi )
2. tsconfig.json module resolution needs to be changed from "bundler" to "node".

Then finally once this basic setup is done, executing "pnpm build" will result on:

````
Type error: Page "src/app/page.tsx" does not match the required types of a Next.js Page.
  "Repro" is not a valid Page export field.
````

![image](https://github.com/wevm/wagmi/assets/166445471/cb047953-896b-408d-85ca-9b57df70c5c3)

### Link to Minimal Reproducible Example

https://github.com/0x33dm/wagmi-playground-wont-build

### Steps To Reproduce

clone: https://github.com/0x33dm/wagmi-playground-wont-build
pnpm install
pnpm build

### Wagmi Version

2.9.2

### Viem Version

2.*

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by 0x33dm** [comment]
Once i fix the "Repro" error by not exporting it ( I don't think it needs to be exported in the first place ) then executing "pnpm build" will result in a different error.

![image](https://github.com/wevm/wagmi/assets/166445471/943d621c-9ad0-4d06-890c-54bfb15ad512)

**Comment by tmm** [comment]
> 2. tsconfig.json module resolution needs to be changed from "bundler" to "node".

It should be `"bundler"`. Can see the official Next.js template setup [here](https://github.com/vercel/next.js/blob/canary/packages/create-next-app/templates/default/ts/tsconfig.json#L11) (the playground was created from that).
