### ISSUE TITLE
Update your SIWE example code to support 1271

### ISSUE THREAD

**Issue by mihoward21** [wevm/wagmi#3956]
### What is the type of issue?

Something else

### What is the issue?

Your current sample code for using sign-in with ethereum does not include a provider in the call to `.verify(...)`, meaning it won't support erc-1271 signature verification (i.e. contract wallets like gnosis safe).

Think it'd be good for you all to include that in your example code since I'm sure lots of people work directly off of it.

### Where did you find it?

https://1.x.wagmi.sh/examples/sign-in-with-ethereum

**Comment by tmm** [comment]
v1 docs are aren't receiving updates. We'll have a new SIWE example once https://github.com/wevm/viem/pull/2280 is out.
