### ISSUE TITLE
Unable to disconnect wallet correctly by useDisconnect hook

### ISSUE THREAD

**Issue by jeasonstudio** [wevm/wagmi#3958]
### Describe the bug

I attempted to build a simplest connect button component, but I found that when repeatedly connecting and disconnecting, it cannot disconnect normally.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/wagmi-usedisconnect-bug-x4vjcp

### Steps To Reproduce

1. connect wallet
2. disconnect
3. connect wallet
4. cannot disconnect here

### Wagmi Version

2.9.2

### Viem Version

2.10.11

### TypeScript Version

5.0.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment]
@jeasonstudio what connector(s) are not working for you? Works fine for me.

(Unrelated: Your TypeScript version is not in the [peer dependency version range](https://github.com/wevm/wagmi/blob/main/packages/react/package.json#L92).)

**Comment by tmm** [comment]
@jeasonstudio what wallet are you using?

(Unrelated: Your TypeScript version is not in the [peer dependency version range](https://github.com/wevm/wagmi/blob/main/packages/react/package.json#L92).)

**Comment by jeasonstudio** [comment]
> @jeasonstudio what wallet are you using?
> 
> (Unrelated: Your TypeScript version is not in the [peer dependency version range](https://github.com/wevm/wagmi/blob/main/packages/react/package.json#L92).)

I used the metamask wallet and the problem can be reproduced. In addition, I tried rainbow wallet and okx wallet, but neither happened.
(I also updated the typescript version in codesandbox to 5.0.4, but that has nothing to do with the issue)

Thanks for replying.

**Comment by glitch-txs** [comment]
MetaMask extension or mobile?

**Comment by tmm** [comment]
If you are going to use `injected()` directly, you should turn off [`multiInjectedProviderDiscovery`](https://wagmi.sh/react/api/createConfig#multiinjectedproviderdiscovery). At some point, we may even deprecate `injected` because [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963) is the future and `window.ethereum` (default `injected`) is not.
