### ISSUE TITLE
Error: 'wagmi' provider is missing. Ensure that 'wagmi' hooks are used within the context of a 'wagmi' provider in the npm package.

### ISSUE THREAD

**Issue by yantao0527** [wevm/wagmi#3965]
### Describe the bug

After updating the 'wagmi' and 'wagmi-injected-ethereum' (viem) peer dependencies to version 2 in our npm package, a compatibility issue has arisen. Our package exports React components that utilize 'wagmi' hooks for functionality. However, when these components are implemented in a Next.js application—despite the application being correctly encapsulated within a 'WagmiProvider'—the following error is triggered:

WagmiProviderNotFoundError: The hook `useConfig` is being called outside of the 'WagmiProvider' context. This hook must be invoked within the component tree that has 'WagmiProvider' at its root.

### Link to Minimal Reproducible Example

http://localhost:3000

### Steps To Reproduce

n/a

### Wagmi Version

2.5.10

### Viem Version

2.8.12

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by alyavasilyeva** [comment]
I have the same issue
