### ISSUE TITLE
Coinbase connector - doesn't disconnect when EIP-6963 is active

### ISSUE THREAD

**Issue by glitch-txs** [wevm/wagmi#3982]
### Describe the bug

When `multiInjectedProviderDiscovery` is active and the Coinbase connector is used, the Coinbase button will be duplicated:

1. Connect with Coinbase extension
2. Disconnect
3. Refresh the page
4. Sometimes the connection still persists.

After disabling `multiInjectedProviderDiscovery` this bug is not reproducible.

### Link to Minimal Reproducible Example

https://github.com/glitch-txs/coinbase-mre

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.9.6

### Viem Version

2.12.1

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by glitch-txs** [comment]
hi @nateReiners could you check on this?

**Comment by tmm** [comment]
Probably best to check with the Coinbase Wallet SDK team to see if this is okay with them.

https://github.com/coinbase/coinbase-wallet-sdk

Don't think we want to be in the business of adding wallet-specific logic to filter connectors.

**Comment by nateReiners** [comment]
> Don't think we want to be in the business of adding wallet-specific logic to filter connectors.

@tmm any wiggle room here? Only showing the connect button for our SDK (`coinbaseWalletSDK`) and not extension (`com.coinbase.wallet`) if both connectors are present would solve both the duplicate button issue and the disconnect issue mentioned above.

**Comment by tmm** [comment]
> duplicate button issue

Folks can do this in their application code if they want. It's not scalable to add one-off rules like this.

> disconnect issue

`coinbaseWallet` (when using the browser extension) and `injected` sharing the same provider seems like the core issue. 

If there was a programmatic way to disconnect, then `injected` could connect, then disconnect, and `coinbaseWallet` wouldn't have any trouble connecting (`metaMask` and `injected` work this way via [`'wallet_revokePermissions'`](https://github.com/MetaMask/metamask-improvement-proposals/blob/main/MIPs/mip-2.md)).

**Comment by nateReiners** [comment]
Okay makes sense, thanks for the info about `wallet_revokePermissions`
