### ISSUE TITLE
globalThis is not defined

### ISSUE THREAD

**Issue by samaritanz** [wevm/wagmi#3986]
### Describe the bug

when i open the link in the tokenpocket wallet,it didnt show any thing,just black srceen,and it shows globalThis is not defined in the vconsole
![bug](https://github.com/wevm/wagmi/assets/62387737/10d5dbe3-51b4-4c5f-ae68-12d659a4f6be)

### Steps To Reproduce

use android 9 phone ,open the link in the tokenpocket wallet,and it will reproduce

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

latest

### Viem Version

latest

### TypeScript Version

^5.0.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by samaritanz** [comment]
the link https://wagmi-demo-118.pages.dev/

**Comment by jxom** [comment]
Wagmi is [optimized for modern browsers](https://wagmi.sh/core/installation#requirements). For example, `globalThis` and optional chaining `?` was introduced in browsers ~5-7 years ago. I would suggest to add extra compilation to the Wagmi module if you would like to target older browsers.

**Comment by samaritanz** [comment]
ths screen shows two problem,and now i solve the globalThis problem,but the unexpected token ,i dont know how to solve

**Comment by samaritanz** [comment]
can u give me some extra compilation example, i find some,but it didnt work
