### ISSUE TITLE
Special contract address does not send requests

### ISSUE THREAD

**Issue by codedryan** [wevm/wagmi#3995]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

```javascript
useReadContract({
  abi: ERC20Abi,
  address: '0x000000000000000000000000000000000000000B',
  functionName: 'symbol'
});
```
The above example will not send the http request, it is when I change the last B of the contract address to lower case that I can successfully send the http request. Like this:
```javascript
useReadContract({
  abi: ERC20Abi,
  address: '0x000000000000000000000000000000000000000b',
  functionName: 'symbol'
});
```

### What Wagmi package(s) are you using?

wagmi, create-wagmi

### Wagmi Version

^2.9.3

### Viem Version

^2.11.1

### TypeScript Version

^5.4.5

### Anything else?

"react": "^18.3.1",
"react-dom": "^18.3.1",
"vite": "^5.2.11"

**Comment by codedryan** [comment]
https://stackblitz.com/edit/new-wagmi-mm68nz?file=src%2FApp.tsx

**Comment by codedryan** [comment]
@tmm https://stackblitz.com/edit/new-wagmi-mm68nz?file=src%2FApp.tsx

**Comment by jxom** [comment]
`0x000000000000000000000000000000000000000B` isn't a valid address.

**Comment by codedryan** [comment]
@jxom Thanks for the answer. You're right.
