### ISSUE TITLE
Connector fails to update chain after wallet chain switch and page refresh

### ISSUE THREAD

**Issue by chybisov** [wevm/wagmi#3998]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

After establishing the connection and changing the chain in the wallet, the new chain doesn't get picked up after the page refresh, and the connector shows the initially connected chain.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-wdirrm

### Steps To Reproduce

1. Connect wallet to MetaMask connector (let's say the initial chain is Optimism - 10)
2. Switch chain inside MetaMask (e.g., switch to Polygon - 137) - this gets reflected correctly and shows a new chain
3. Refresh the page
4. After reconnection, the connector shows that the chainId is 10, while it should be 137

### What Wagmi package(s) are you using?

wagmi, @wagmi/connectors

### Wagmi Version

2.9.6

### Viem Version

2.12.1

### Anything else?

This also affects all hooks returning current chain information like `useAccount`

**Comment by tmm** [comment]
Looks like a MetaMask Chrome extension issue. You can reproduce by running RPC requests in the browser console directly.

```
await window.ethereum.request({ method: 'eth_requestAccounts' }) // connect
await window.ethereum.request({ method: 'eth_chainId' }) // 0x1
await window.ethereum.request({ method: 'wallet_switchEthereumChain', params: [{ chainId: '0x89' }] }) // switch to polygon
await window.ethereum.request({ method: 'eth_chainId' }) // 0x89
// switch in mm extension ui
await window.ethereum.request({ method: 'eth_chainId' }) // 0x89, should be 0x1
```

In the video, you can see that the listener is fired for when the chain switches back to Mainnet via the MetaMask extension UI, but when you call 'eth_chainId' again, the response is not updated.

https://github.com/wevm/wagmi/assets/6759464/56f79c9f-cd29-41f7-ae86-2355adb3649e

Confirmed that this is not an issue with the MetaMask Firefox Add-on or Rainbow Chrome extension.

**Comment by tmm** [comment]
Linking up https://github.com/MetaMask/metamask-extension/issues/25097

**Comment by tmm** [comment]
Small patch if anyone wants to apply while MM fixes the issue

https://github.com/wevm/wagmi/commit/71b49b1a5173b93d7d0b2fafaf152a07339c4572

**Comment by chybisov** [comment]
@tmm thank you for taking a look! I'll track MM issue 🙂
