### ISSUE TITLE
Latest connector updates break build on vercel with next 14 node 20.x

### ISSUE THREAD

**Issue by gaboesquivel** [wevm/wagmi#3999]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

There's a package alias on the coinbase wallet connector that cant be resolved 
![image](https://github.com/wevm/wagmi/assets/391270/63658bdf-2166-423f-978a-f0af3dff1042)

Version `2.9.3` works fine.

My source can be found at https://github.com/bitcashorg/smartsale/tree/blog. 

### Link to Minimal Reproducible Example

https://github.com/bitcashorg/smartsale/tree/blog

### Steps To Reproduce

deploy a next 14 app to vercel with latest wagmi version

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

wagmi@2.9.8

### Viem Version

viem@2.13.2

### TypeScript Version

^5.4.5

### Anything else?

I'm using turborepo with bun

**Comment by tmm** [comment]
What version of Bun are you using? Please create a minimal reproduction (e.g. not using Turborepo).

**Comment by gaboesquivel** [comment]
Problem solved by adding the package to workspace nohoist array 
<img width="198" alt="image" src="https://github.com/wevm/wagmi/assets/391270/aaf10895-6933-4982-bd9e-51f01856b83d">

https://github.com/bitcashorg/smartsale/pull/220
