### ISSUE TITLE
Use Balance returns 404 after I connect my wallet

### ISSUE THREAD

**Issue by kelvindoe22** [wevm/wagmi#4002]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I am testing out the wagmi api, and I think the useBalance is making a network call that returns a 404 response. This happens when i connect my wallet. If i don't, no 404 error is returned. This is the error message 
`XHRGET
https://rpc.walletconnect.com/v1/profile/reverse/0x52ce8f12BE8a23c8B76b8913307eEAf918999a07?projectId=6115e730c04e9740ece33ddaf97274bf
[HTTP/2 404  297ms]

1

{"status":"FAILED","reasons":[{"field":"address","description":"No name for address is found"}]}
`
 in case you want to investigate. Remember I am following the exact documentation.
This is my request in case anyone was wondering
```
const balance = useBalance(
    {
      address : '0xsomething
    }
  )
  ````

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

10.2.0

### Viem Version

10.2.0

### TypeScript Version

5.4.5

**Comment by glitch-txs** [comment]
Hi, are you using Web3Modal?

**Comment by kelvindoe22** [comment]
Yes
