### ISSUE TITLE
SSR Storage race-condition when using cookieStorage

### ISSUE THREAD

**Issue by hiendv** [wevm/wagmi#4008]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Hi,
I was trying to do wagmi SSR with cookieStorage according to https://wagmi.sh/react/guides/ssr. Both Next.js App Dir and Remix. And met a race-condition problem with wagmi if one client with valid cookies is reconnecting and another trying to load the page. The latter will initially receive HTML response from the first.

### Link to Minimal Reproducible Example

https://github.com/hiendv/wagmi-race-condition

### Steps To Reproduce

```sh
# 1 Fresh install with wagmi
npm create wagmi

# 2 Update the codebase to support SSR and cookieStorage
# https://wagmi.sh/react/guides/ssr

# 3 Run dev server
npm run dev

# Simulate a normal wallet connect using browser like this
curl 'http://localhost:3000/' \
  -H 'Cookie: wagmi.store={"state":{"connections":{"__type":"Map","value":[["554eeb85994",{"accounts":["0xfoobar"],"chainId":11155420,"connector":{"id":"io.metamask","name":"MetaMask","type":"injected","uid":"554eeb85994"}}]]},"chainId":1,"current":"554eeb85994"},"version":2}' 

# Now, whenever we open the page, even without any cookies, we receive the initial resp
curl 'http://localhost:3000' | grep 0xfoobar
```

### What Wagmi package(s) are you using?

@wagmi/core, create-wagmi

### Wagmi Version

2.9.8

### Viem Version

2.13.3

### TypeScript Version

5.4.5

### Anything else?

I suspect it comes from Zustand's persistence.

**Comment by hiendaovinh** [comment]
The issue alone doesn't pose much of a threat but the impact could be comparable to various cache poisoning scenario.

**Comment by tmm** [comment]
Requests are from the same origin. First request sets config state, second request ends up reading from that.

**Comment by hiendv** [comment]
Thanks for taking your time reading this. I don't quite understand the term `same origin` you are referring to. From my point of view, this is a bug with wagmi which might be a privacy concern or a mismatching hydration error at least.

**Comment by tmm** [comment]
Updated the guide!

https://wagmi.sh/react/guides/ssr#persistence-using-cookies

**Comment by hiendv** [comment]
I see, that's my workaround too, having a factory for wagmiConfig so I can create a new one when it's SSR.
```ts
  const config = typeof window === "undefined" ? factory() : wagmiConfig;
```
