### ISSUE TITLE
SubWallet wants to connect if using MetaMask

### ISSUE THREAD

**Issue by kacperkurek** [wevm/wagmi#4018]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

SubWallet actions are calling when MetaMask is connected 

### Link to Minimal Reproducible Example

https://github.com/kacperkurek/test-wagmi

### Steps To Reproduce

1. Login with SubWallet and disconnect.
2. Login with MetaMask

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.9.9

### Viem Version

2.13.7

### TypeScript Version

5.3.3

### Anything else?

Tried to use rainbowkit but with same effect

**Comment by tmm** [comment]
This looks like an issue with SubWallet and not Wagmi.
