### ISSUE TITLE
`chainId` from `useAccount` hook returns wrong chain id on mount (MetaMask)

### ISSUE THREAD

**Issue by magiziz** [wevm/wagmi#4026]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

When connecting to MetaMask EIP-6963 connector it returns wrong `chainId` from `useAccount` on mount after refresh. I'm not sure if it's a Wagmi or MetaMask issue.

### Link to Minimal Reproducible Example

https://github.com/magiziz/wagmi-mm-chainId-bug

### Steps To Reproduce

- Connect to MetaMask with ethereum chain
- Open MetaMask and switch to linea chain
- Reload and you'll see ethereum chain id instead of linea chain id (59144)

https://github.com/wevm/wagmi/assets/53529533/fd6f52fd-a4ec-4a8e-bfc8-1e639c6f1ff8

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.9.10

### Viem Version

2.13.7

### TypeScript Version

5.4.5

### Anything else?

RainbowKit is also impacted by this. Here is the issue https://github.com/rainbow-me/rainbowkit/issues/2038

**Comment by tmm** [comment]
See https://github.com/wevm/wagmi/issues/3998
