### ISSUE TITLE
Can't connect to MetaMask after disconnecting

### ISSUE THREAD

**Issue by magiziz** [wevm/wagmi#4027]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

If a user creates their own MetaMask connector by using `injected()` (EIP-1193) from `wagmi/connectors` it will cause a bug where MetaMask (EIP-6963) won't be able to connect again after disconnecting. User would manually have to refresh the page to be able to connect again.

### Link to Minimal Reproducible Example

https://github.com/magiziz/wagmi-connect-mm-bug

### Steps To Reproduce

- Connect to MetaMask (EIP-6963 connector)
- Disconnect
- Try connecting again (it'll fail saying "Connector already connected")

https://github.com/wevm/wagmi/assets/53529533/e9c80107-8043-4fdf-b685-69c3a359bc03

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.9.10

### Viem Version

2.13.7

### TypeScript Version

5.4.5

### Anything else?

RainbowKit is having the same issue. Here is the issue https://github.com/rainbow-me/rainbowkit/issues/2033

**Comment by tmm** [comment]
The custom `injected` connector and EIP-6963 connector both share the same EIP-1193 provider instance so when the EIP-6963-based connector connects, the custom `injected` connector gets connected via the [`onConnect`](https://github.com/wevm/wagmi/blob/main/packages/core/src/connectors/injected.ts#L156) event. This event allows Wagmi to support connections directly via a browser extension UI.

https://github.com/wevm/wagmi/assets/6759464/4e2b1fca-2a70-4c3e-9908-833fcfb4f50d

I highly recommend not using `window.ethereum` if possible as EIP-6963 is now the standard. Using `window.ethereum` and EIP-6963 together will likely result in issues like this.
