### ISSUE TITLE
trouble with providing a nonce for a Gnosis Safe transaction

### ISSUE THREAD

**Issue by Pasha8914** [wevm/wagmi#4029]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I need to send multiple transactions to [Gnosis Safe](https://gnosis-safe.io/), but Gnosis Safe does not automatically increment the nonce immediately after signing a transaction. Therefore, I need to provide the nonce manually, but Gnosis Safe ignores this argument.

However, their code specifies that the arguments should be considered: [Gnosis Safe code](https://github.com/safe-global/safe-core-sdk/blob/main/packages/protocol-kit/src/utils/transactions/utils.ts#L45).

### Link to Minimal Reproducible Example
code: https://github.com/Pasha8914/wagmi-safe-bug
preview: https://pasha8914.github.io/wagmi-safe-bug

### Steps to Reproduce the Issue

1. Start the demo project from [this repository](https://github.com/Pasha8914/wagmi-safe-bug/tree/main).
2. Open [Safe Global](https://app.safe.global/).
3. Navigate to the **Apps** section.
4. Select **My Custom Apps**.
5. Paste your local app URL.
6. Click **Send 2 txs**.

**OR**

1. Open [Safe Global](https://app.safe.global/).
2. Navigate to the **Apps** section.
3. Select **My Custom Apps**.
4. Paste https://pasha8914.github.io/wagmi-safe-bug
5. Click **Send 2 txs**.

You will observe that the first and second transactions have the same nonce, although different nonces were provided.

### What Wagmi package(s) are you using?

wagmi, @wagmi/connectors, @wagmi/core, create-wagmi

### Wagmi Version

wagmi-2.9.10

### Viem Version

2.13.7

### TypeScript Version

5.2.2

### Anything else?

https://github.com/wevm/wagmi/assets/43392281/ac429b85-f077-4bfc-b5ed-c54ee24ac635

**Comment by tmm** [comment]
> However, their code specifies that the arguments should be considered: [Gnosis Safe code](https://github.com/safe-global/safe-core-sdk/blob/main/packages/protocol-kit/src/utils/transactions/utils.ts#L45).

FYI Wagmi doesn't use `@safe-global/protocol-kit` so this logic does not apply to Wagmi.

**Comment by Pasha8914** [comment]
> > However, their code specifies that the arguments should be considered: [Gnosis Safe code](https://github.com/safe-global/safe-core-sdk/blob/main/packages/protocol-kit/src/utils/transactions/utils.ts#L45).
> 
> FYI Wagmi doesn't use `@safe-global/protocol-kit` so this logic does not apply to Wagmi.

I am convinced that connectors should work explicitly, with no ifs and no buts. In this case, the behavior is unclear and incorrect.

The Safe Connector was created to interact with the Gnosis Safe Wallet. Currently, the Safe Connector does not fulfill its intended purpose and limits functionality (optional parameters are ignored).

I believe it's time for Wagmi to update the safe connector and use [Safe{Core} SDK](https://docs.safe.global/sdk/overview) because Safe Connector  [references a package that hasn't been updated for 5 months](https://github.com/wevm/wagmi/blob/main/packages/connectors/package.json#L51), and it has [outdated libraries](https://github.com/safe-global/safe-apps-sdk/blob/main/packages/safe-apps-sdk/package.json#L40) in its dependencies.

<img width="1279" alt="image" src="https://github.com/wevm/wagmi/assets/43392281/a9a4af39-c7f5-4a6e-8138-8168d2c65496">

Previously, the Gnosis Safe documentation contained information about safe-apps-sdk, but now it is gone (exist only in the Glossary) and the [safe-apps-sdk docs link](https://docs.safe.global/safe-core-aa-sdk/safe-apps) redirects [to the repository](https://github.com/safe-global/safe-apps-sdk).

**Comment by tmm** [comment]
Let's track in the [upstream issue](https://github.com/safe-global/safe-apps-sdk/issues/578) you created. Can reach out to the Safe team to see what they recommend for packages moving forward.
