### ISSUE TITLE
Missing `useBytecode` hook for VueJS 

### ISSUE THREAD

**Issue by Skanislav** [wevm/wagmi#4034]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

We recently started using https://github.com/unicape/use-wagmi, but it was replaced by @wagmi/vue. During the update, I noticed a missing hook that wasn’t implemented.

There is a hook for React called useBytecode, which you can find here: https://wagmi.sh/react/api/hooks/useBytecode. This hook was included in the previous use-wagmi package (https://github.com/unicape/use-wagmi/blob/main/packages/vue/src/hooks/useBytecode.ts).

I just wanted to know if it was left out on purpose, and I’m also offering to help add it if needed.

### What Wagmi package(s) are you using?

@wagmi/vue

### Wagmi Version

@wagmi/vue@0.0.14

### Viem Version

2.0

**Comment by tmm** [comment]
Feel free to create a PR!
