### ISSUE TITLE
Reconnect sometimes times out on v2

### ISSUE THREAD

**Issue by traderben** [wevm/wagmi#4037]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

On initial page load the useAccount hook fails to reconnect on slow devices.
I refresh the page and expect the previously connected wallet to be connected instead it ends up being disconnected.

I added some logging and observed useAccount returns the connected account address with status "reconnecting". Normally the status changes to "connected" after a little bit, but on slow devices it instead changes to "disconnected" and the account address becomes undefined. When this happens the autoreconnect does not complete. I can reproduce this consistently in my dapp by setting cpu throttling to 4x. I simulated a slow device by adding additional work to my minimal repro.

I added the following code to the getting started set up to reproduce:
 const [x, setX] = useState(0);

  useEffect(() => {
    if (x < 100) {
      setX(x + 1);
    }
  }, [x]);
  console.log("account:", account);

  if (x > 10) {
    for (let i = 0; i < 10; i++) {
      (async () => {
        for (let j = 0; j < 1000; j++) {
          console.log("Random number: ", Math.random());    
        }
      })();
    }
  }
  
It was a little finicky, so you might need to change some constants based on your processor. I reproduced without any CPU throttling.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-nknyne?file=src%2FApp.tsx

### Steps To Reproduce

Connect a wallet (I tested using Rabby). Wait until the page shows connected. Refresh the page, observe that the page shows reconnecting and then disconnected.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.9.5

### Viem Version

2.12.0

### TypeScript Version

5.1.6

**Comment by tmm** [comment]
Haven't been able to reproduce. This is also an older Wagmi version. Please try to create a consistent minimal reproduction with the latest Wagmi version (`2.9.12` at time of writing).

**Comment by traderben** [comment]
I can reproduce on 2.9.12 as well. new.wagmi.sh defaults to 2.0.1, but I just updated it to 2.9.12 and ran pnpm install. 

As I said the reproduction is a bit finicky since it depends on your machine. If you have too much extra work for your processor the page doesn't load, and if you have too little work than it finishes reconnecting before timing out. You should be able to tune the constants to work for your machine.

**Comment by traderben** [comment]
We were able to reproduce both on a 2021 MacBook Pro with an Apple M1 and a Surface laptop with 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   3.00 GHz which is a pretty wide range, so I'm a little surprised you are unable to reproduce. What do you observe when following the reproduction steps and what type of machine/processor did you use? Also which wallet are you using to connect?

**Comment by glitch-txs** [comment]
I was able to repro, the reconnecting status keeps there like ~10sec and shows as disconnected

**Comment by tmm** [comment]
Would love to hear your thoughts on https://github.com/wevm/wagmi/pull/4042
