### ISSUE TITLE
useWaitForTransactionReceipt status stucks in isConfirming

### ISSUE THREAD

**Issue by RojhatToptamus** [wevm/wagmi#4055]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

**useWaitForTransactionReceipt** status gets stuck in **isConfirming**  and only transitions to **isConfirmed** several minutes after the transaction is confirmed. Using [transport](https://wagmi.sh/react/api/createConfig#usage) with a custom RPC in config did not help as well.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-x5ehb4?file=app%2Fpage.tsx

### Steps To Reproduce

Complete the form and submit the TX.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.8.0, 2.10.0

### Viem Version

2.14.0

### TypeScript Version

5.4.5

**Comment by tmm** [comment]
Unfortunately, Sepolia's public RPC is pretty brittle with load balancing. If you try use a paid RPC URL (or at least one that is higher performance) it should work.
