### ISSUE TITLE
Exodus wallet freezes on 'wallet_revokePermissions' method

### ISSUE THREAD

**Issue by alx-khramov** [wevm/wagmi#4064]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Hey! Just letting you know, that some wallets may freeze here: https://github.com/wevm/wagmi/blob/b4d9ef79deb554ee20fed6666a474be5e7cdd522/packages/core/src/connectors/injected.ts#L271-L274

For example, [Exodus wallet](https://exodus.com/) awaits this request for 5 minutes (until timeout I guess) and only after that it disconnects. The `disconnect` transaction stays in the `pending` state for that time period.

I understand that the problem is on the wallet's side, and I'm going to report it to the Exodus team, but maybe it would be good to add some short timeout for`wallet_revokePermissions` request on the wagmi side. 

### What Wagmi package(s) are you using?

wagmi, @wagmi/core

### Wagmi Version

2.10.2

### Viem Version

2.13.3

**Comment by tmm** [comment]
If anyone wants to pick this up, all you need to do is [add a `withTimeout` call similar to what we do in the `safe` connector.](https://github.com/wevm/wagmi/blob/72fd3a4246580972ae88ba4f67bf3664e6111c32/packages/connectors/src/safe.ts#L106)

**Comment by MukulKolpe** [comment]
Hey @tmm, can I work on this issue?

**Comment by alx-khramov** [comment]
@MukulKolpe I'm already preparing the PR
