### ISSUE TITLE
Duplicate identifier "Register"

### ISSUE THREAD

**Issue by AlansaladA** [wevm/wagmi#4069]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

The document says that the type of merged config is like this:
declare module "wagmi" {
interface Register {
config: typeof config
}
}

It was working before, but now it gives an error：
Duplicate identifier "Register". ts(2300)
index.d.ts(77, 692): "Register" is also declared here.

Then I noticed that Register is defined as a type in the new version. How should I declare the type of config now? I don’t want to introduce it in the hook every time.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.10.2

### Viem Version

2.x

### TypeScript Version

5.4.3

**Comment by dalechyn** [comment]
could reproduce it with `typescript@rc`: https://github.com/dalechyn/wagmi-register-type-issue
