### ISSUE TITLE
wallet get disconnected of page refreshes and cookies was not deleted this will happening when we dissconnect on the dynamic page 

### ISSUE THREAD

**Issue by arunkumar201** [wevm/wagmi#4073]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

i am using wagmi and web3Modal (nextjs 14) , i am getting issue with wallet connection 
-The wallet connection occasionally disconnects upon page changes or occasional page refreshes. I've implemented cookies with SSR (server-side rendering) set to true.

i am using latest versions
-i followed the https://github.com/wevm/wagmi/blob/main/playgrounds/next/src/wagmi.ts  playground example 

### Link to Minimal Reproducible Example

https://github.com/arunkumar201/web3-siwe

### Steps To Reproduce

- connect the wallet with metamsk
- then come to the home page 
- and now re-connect the wallet 
- if you refreshes the page ,then your wallet gets disconnected 
example :- https://web3-siwe.vercel.app/
github: - https://github.com/arunkumar201/web3-siwe

https://github.com/wevm/wagmi/assets/70876302/aab68712-47a9-4a82-920f-b28a0cd86788

### What Wagmi package(s) are you using?

wagmi, @wagmi/connectors, @wagmi/core

### Wagmi Version

latest

### Viem Version

latest

### TypeScript Version

5.4.4

### Anything else?

i am using nextjs + cookies based wallet session.

**Comment by tmm** [comment]
The example you provided is not minimal. Please attach a minimal reproduction that only uses Wagmi/Viem without third-party connect libraries.

**Comment by arunkumar201** [comment]
i have tested using wagmi next playground example , same issue is being encountered .
- code :- https://github.com/arunkumar201/wagmi/tree/wallet-disconnect-issue-ssr
- demo :- https://wagmi-gz40.onrender.com/

**Comment by tmm** [comment]
Updated the SSR guide: https://wagmi.sh/react/guides/ssr#persistence-using-cookies

**Comment by arunkumar201** [comment]
@tmm same issue still persists: When connecting on the home page and then navigating to any dynamic page, a hard refresh on the dynamic page causes problems. If we disconnect the wallet, return to the home page, reconnect the wallet, and refresh the page, the wallet disconnects again. The 'wagmi.io.metamask.disconnected' cookie value remains true and does not get updated. This issue was tested on the latest Next.js playground example using the updated version of getConfig() .

**Comment by kr-arunp** [comment]
> Updated the SSR guide: https://wagmi.sh/react/guides/ssr#persistence-using-cookies

not working  https://github.com/wevm/wagmi/issues/4073#issuecomment-2187856149
