### ISSUE TITLE
What are values being passed to useReadContract & useSimulateContract hooks' params?

### ISSUE THREAD

**Issue by dspoonia7** [wevm/wagmi#4086]
### What is the type of issue?

Documentation is missing

### What is the issue?

How do the `address`, `args`, and `account` fields' values/addresses differ, and how can I get the values of these fields?

1. I am getting this error: `The contract function "balanceOf" returned no data ("0x")`.
2. One param value is `useAccount() => address`, but it's unclear which param this should be used for, and what should be used for other params. 
`useSimulateContract` and `useReadContract` both hooks have these `address`, `args`, and `account` params:

<img width="735" alt="Screenshot 2024-06-26 at 3 19 39 PM" src="https://github.com/wevm/wagmi/assets/8257269/d0f62caf-c987-49c7-8dd0-024730e452b7">

3. Below address value is being used across all pages of the documentation but nowhere is mentioned what this hard-coded value is, is this some default value?
<img width="548" alt="Screenshot 2024-06-26 at 3 06 54 PM copy" src="https://github.com/wevm/wagmi/assets/8257269/02acd47f-f6b8-413a-950e-0c75a4464c47">

### Where did you find it?

I am building an application to wrap and unwrap eth, and implementing hook `useSimulateContract` for the same.

Any help would be appreciated.

**Comment by dspoonia7** [comment]
@simonindelicate @DangyWing was following this thread of yours, can you help on this? https://github.com/wevm/wagmi/discussions/1715#discussioncomment-4797021,

**Comment by tmm** [comment]
https://wagmi.sh/vue/api/composables/useSimulateContract#parameters
