### ISSUE TITLE
Can't catch error

### ISSUE THREAD

**Issue by AlansaladA** [wevm/wagmi#4087]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

When I call the approve method of the contract or operate to import tokens into the wallet（walletClient.data?.watchAsset）, if I click reject in metamask, the user rejection cannot be captured in the catch and the execution continues. Also, when I want to switch to a chain that has not been added to the wallet, the console reports an error but it is not catched in the code.

But when I try to switch back to version 2.9.9, I can catch the error.

I have submitted an issue before, but it was closed because no reproduction was provided. Although I later replied with a link to the reproduction, it has not been processed, so I submitted it again

### Link to Minimal Reproducible Example

https://github.com/AlansaladA/wagmi-catch-error-reproduction

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.10.7

### Viem Version

2.15.1

### TypeScript Version

5.4.3

**Comment by tmm** [comment]
This [issue](https://github.com/MetaMask/metamask-sdk/pull/877/commits/e9d117dab9348de03169b55e7d85132d5721fa01#diff-b359323630611bfb6067d1d6127788a4625c89c4bf813891f33e3d9a3f581cd7R67-R69) was introduced in `@metamask/sdk@0.20.5` and will be fixed when https://github.com/MetaMask/metamask-sdk/pull/917/commits/e6d93b63067b7eda61f25ea267803290abbce8b7 is released. In the meantime, you can apply [this patch](https://github.com/MetaMask/metamask-sdk/pull/917/commits/e6d93b63067b7eda61f25ea267803290abbce8b7) or use the `injected` connector (which does not have this issue).
