### ISSUE TITLE
EIP-6963 connectors are not announced becuase of Bitski wallet

### ISSUE THREAD

**Issue by magiziz** [wevm/wagmi#4090]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

If you install Bitski wallet and get this view:

<img width="384" alt="bitski-view" src="https://github.com/wevm/wagmi/assets/53529533/1d9bf32d-003a-4def-b180-dceba88d52cc">

The other EIP-6963 connectors will not get announced unless you disable the Bitski wallet extension.

<img width="1727" alt="image" src="https://github.com/wevm/wagmi/assets/53529533/4016638d-38e9-4fa7-8afd-6623a66380b7">

### Link to Minimal Reproducible Example

https://github.com/magiziz/wagmi-eip6963-repro

### Steps To Reproduce

- Install Bitski wallet and have other wallet extensions installed
- Refresh the page and you'll see no EIP-6963 connectors getting annoucned. It's probably because of this error:

<img width="960" alt="image" src="https://github.com/wevm/wagmi/assets/53529533/7461f023-fd41-4e52-abd1-3430e8ac3608">

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.10.7

### Viem Version

2.16.3

### TypeScript Version

5.5.2

**Comment by tmm** [comment]
Looks like this is because Bitski decided to not follow EIP-6963 for some reason, using `walletId` instead of `rdns`. Show follow up with them!

![001060_Google Chrome_2024-06-27-09 53 50@2x](https://github.com/wevm/wagmi/assets/6759464/671aae19-282a-4deb-bc6f-8f93d4d0d916)

**Comment by tmm** [comment]
Looks like Bitski is [shutting down in three days](https://www.bitski.com/) so probably not worth even following up.
