### ISSUE TITLE
cookieToInitialState causing error on server action redirect

### ISSUE THREAD

**Issue by alexsserban** [wevm/wagmi#4093]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Following the [SSR guide](https://wagmi.sh/react/guides/ssr), the documentation points us to use the following with NextJS App Router:
`const initialState = cookieToInitialState(getConfig(), headers().get('cookie'))`

On normal requests, everything is working fine, but when you `redirect` from within a `server action`, `headers().get('cookie')` returns the serialised cookies, which causes an error from `cookieToInitialState`

```
Stack trace:
 ⨯ SyntaxError: Unexpected token '%', "%7B%22stat"... is not valid JSON
    at JSON.parse ()
    at RootLayout (./src/app/layout.tsx:29:85)
    at stringify ()
    at AsyncLocalStorage.run (node:async_hooks:346:14)
```

There are 2 solutions for this issue:
1. We treat it as a documentation error, and we can replace `headers().get('cookie')` with either `decodeURIComponent(headers().get('cookie'))`, either using the new [cookies](https://nextjs.org/docs/app/api-reference/functions/cookies) hook with something like this 
```
  const cookieStore = cookies()

  const cookie = cookieStore
    .getAll()
    .map(c => c.name + '=' + c.value)
    .join('; ')
```

2. Probably the better approach of making `cookieToInitialState` work with serialised cookies.

### Steps To Reproduce

Use `const initialState = cookieToInitialState(getConfig(), headers().get('cookie'))` in NextJS 14 and redirect from a server action.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.10.8

### Viem Version

2.16.3

### TypeScript Version

5.4.5

### Anything else?

Next JS 14

**Comment by tmm** [comment]
PR welcome to update the documentation. Not sure it's worth adding Next.js-specific logic to `cookieToInitialState` since other frameworks could have different APIs and a cookie string is universal.
