### ISSUE TITLE
Disconnected session cookie not removed after connecting again

### ISSUE THREAD

**Issue by dengpeng** [wevm/wagmi#4097]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

When calling `disconnect`, wagmi would normally store a session cookie like `wagmi.io.metamask.disconnected` so the page stays disconnected after a refresh.

However, this cookie should be cleared/removed if the user connects again. This removal of the "disconnected" cookie currently only works when the the "connect" call is made on the root `/` and first level pages (e.g. `/foo`) but **NOT** on pages that are deeper (e.g. `/bar/qux` or `/a/b/c`).

### Link to Minimal Reproducible Example

https://wagmi-bug.vercel.app/

### Steps To Reproduce

(Code is available at https://github.com/dengpeng/wagmi-bug)

- Correct behavior:
   1. Go to https://wagmi-bug.vercel.app/ or https://wagmi-bug.vercel.app/foo.
   2. Connect wallet then disconnect wallet
   3. Now a session cookie `wagmi.io.metamask.disconnected` is set.
   4. After a successful connect on that page once again, the cookie `wagmi.io.metamask.disconnected` is removed. ✅
   
- Incorrect behavior:
   1. Go to https://wagmi-bug.vercel.app/bar/qux or https://wagmi-bug.vercel.app/a/b/c
   2. Connect wallet then disconnect wallet
   3. Now a session cookie `wagmi.io.metamask.disconnected` is set.
   4. After a successful connect on that page once again, the cookie `wagmi.io.metamask.disconnected` is NOT removed. ❌
   6. This will lead to wallet not automatically re-connecting after the page is reloaded. ⚠️

### What Wagmi package(s) are you using?

wagmi, @wagmi/core

### Wagmi Version

@wagmi/core@2.11.5, wagmi@2.10.8

### Viem Version

2.16.3

### TypeScript Version

5

**Comment by arunkumar201** [comment]
yeah same issue 

https://github.com/wevm/wagmi/issues/4073

**Comment by evgenyboxer** [comment]
Yep confirm this issue exists.

My fix for now is to delete `wagmi.*.disconnected` cookies when you are connected.

**Comment by redianmf** [comment]
I tried to opt out the `storage` object in createConfig method. The `wagmi.*.disconnected`, `wagmi.store`, etc. are saved in localStorage. 
Are there any other scenario where these object could be stored? so that it can be handled correctly

**Comment by goosewobbler** [comment]
I had a poke at this, it seems setting a different cookie path fixes the issue as cookies with the path `/` are not recognised on e.g. `/a/b/c`.
