### ISSUE TITLE
useReadContract is not updating data on some computers/browsers but not others with identical code

### ISSUE THREAD

**Issue by briandoyle81CB** [wevm/wagmi#4098]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Hello!  I'm using `useReadContract` to read the `balanceOf` an NFT contract for a provided `address`.

On some computers, or even different browsers on the same computer, the code works as expected.

**Without modification**, on others, it does not ever update `data`.  This persists even if the `address` parameter is hardcoded.

Changing the contract, or other minor parts of the code can flip a computer or browser from working to non-working, or vice versa.  Otherwise, the issue is consistent.  It will always work on a given computer/browser combo, or it will never work.

Further testing shows that the `isPending` state is being triggered on non-working computers, but `data` never updates from `undefined`

Invalidating the query also does not trigger `data` being populated.

### Link to Minimal Reproducible Example

https://github.com/briandoyle81CB/dao-gate

### Steps To Reproduce

1. Clone the repo
2. Install dependencies with `bun install`
3. Run the app with `bun run dev`
4. Click the button to open the QR code scanner
5. Scan the "pay me" QR code of any smart wallet
6. Observe that EITHER: the console logs a Balance: 0n, or the `balanceData` `useEffect` is never triggered
7. Purchase an NFT from the auction.  Note this uses real Base ETH, but is very cheap.  Happy to send enough to cover it:  https://testnet.nouns.build/dao/base/0x354ef633fb3ba2c427f18fc39fcf96a31d0fd577/101
8. After completing the auction process and claiming the NFT, verify it is in your wallet
9. Click the button to scan the QR code and scan again
10. Observe that EITHER:  The console logs a balance of 1n and the app displays the address as Authorized --OR-- the Balanced is not logged and the app shows the default of "No" for Authorized
11. IF the browser/computer combo is in the fail state:  open `src/app/page.tsx` and hardcode your address as the argument for `useReadContract`
12. Observe that `data` is never returned. 

If it doesn't fail, try again on a different browser and/or computer

RE Dependencies, the project only has wagmi/cli @latest, which is installing 2.9.11

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.9.11

### Viem Version

1.1.4

### TypeScript Version

5.3.3

**Comment by briandoyle81CB** [comment]
The relevant code is here:  https://github.com/briandoyle81CB/dao-gate/blob/main/src/app/page.tsx

**Comment by tmm** [comment]
Spent some time trying to reproduce and wasn't able to unfortunately (sounds like there might be a race condition from what you described). Happy to look into this further if there's some way to consistently reproduce. Also, curious about the following.

- What browsers and/or operating systems have this issue?
- What address(es) does this issue happen with?
- Does this happen when you use Viem directly?
- Are you using a high-availability RPC service? (e.g. Alchemy, Infura, QuickNode)

**Comment by briandoyle81CB** [comment]
Thanks for looking!  I'm hopeful that this is a random edge case, but worried about it being too common - seen in about half of the 8-12 browser/machine combos we've tested, with > half machines showing the fail state on at least one browser.

But this is using the way I'm teaching how to use `useReadContract` (https://docs.base.org/base-camp/docs/reading-and-displaying-data/configuring-useReadContract) and we haven't seen or heard something like this reported before, or experienced it ourselves.

Do you see anything less than optimal in the implementation?:  https://github.com/briandoyle81CB/dao-gate/blob/main/src/app/page.tsx

* Only tested on Sonoma, but with Firefox, Chrome, Brave, and Safari with no patterns emerging
* Tested with the current address`0x038ee341181e1090159eab1f4ba2c28f4b50330d` and `0x354ef633fb3ba2c427f18fc39fcf96a31d0fd577`, with no patterns on fail or success with either contract
*  I haven't tried using viem directly, but I'll do that either tonight or tomorrow
* No change in fail or success state from changing the RPC service, and fail or success states are always consistent
