### ISSUE TITLE
Metamask connetor not working via CDN

### ISSUE THREAD

**Issue by artemkopytko** [wevm/wagmi#4115]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Metamask connector fails if wagmi is being used via CDN. I've used the instruction [from the documentation](https://wagmi.sh/core/installation#cdn) 

Code:
`<script type="module">
    import { createClient } from 'https://esm.sh/viem'
    import { http, createConfig, getAccount, connect } from 'https://esm.sh/@wagmi/core@2.x'
    import { injected, metaMask } from 'https://esm.sh/@wagmi/connectors'
    import { mainnet, sepolia } from 'https://esm.sh/@wagmi/core@2.x/chains'

    const config = createConfig({
      chains: [mainnet, sepolia],
      transports: {
        [mainnet.id]: http(),
        [sepolia.id]: http(),
      },
    })

    const result = await connect(config, { connector: metaMask() })

    const { address } = getAccount(config)

    console.log('address', address)
  </script>
`

The error is listed below:
<img width="1512" alt="Screenshot 2024-07-05 at 15 55 45" src="https://github.com/wevm/wagmi/assets/13777605/fd1266e6-17b4-4b06-9a42-efdf6fbd4ae0">

Stackblitz demo is attached

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-8jmj3p?file=index.html&terminal=dev

### Steps To Reproduce

Just press "Run" and take a look at the console

### What Wagmi package(s) are you using?

@wagmi/connectors, @wagmi/core

### Wagmi Package(s) Version(s)

@wagmi/core@2.11.0

### Viem Version

2.17.1

### Anything else?

P.S. Injected and coinbaseWallet connectors works perfect. The problem is met with metamask only

**Comment by jxom** [comment]
Thanks for the issue! Might be best to raise this on the MetaMask SDK repository: https://github.com/MetaMask/metamask-sdk

**Comment by artemkopytko** [comment]
> Thanks for the issue! Might be best to raise this on the MetaMask SDK repository: https://github.com/MetaMask/metamask-sdk

Hey! But I'm not importing metamask directly. It is being imported via https://esm.sh/@wagmi/connectors

**Comment by jxom** [comment]
Yes, but bundling errors within MetaMask SDK is not our issue.
