### ISSUE TITLE
Coinbase connector throwing 401 error code

### ISSUE THREAD

**Issue by karega** [wevm/wagmi#4117]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Using latest version of wagmi to connect to web3 provider.  Library throwing 401 error on POST request to https://as.coinbase.com/metrics.

![image](https://github.com/wevm/wagmi/assets/190614/35dfa1f0-698c-41de-aaec-4e71b374428a)

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.10.9

### Viem Version

2.17.0

### TypeScript Version

N/A

**Comment by tmm** [comment]
Thanks for the issue! Might be best to raise this on the Coinbase Wallet SDK repository: https://github.com/coinbase/coinbase-wallet-sdk
