### ISSUE TITLE
coinbaseWallet > appLogoUrl not working and default favicon url won't add `/` after domain

### ISSUE THREAD

**Issue by rajpraful** [wevm/wagmi#4119]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I am passing the appLogoUrl to the function, but the logo is broken in UI. After inspecting I found that it's using default favicon itself. 

Favicon works for me but it's broken as it's missing `/` in the image URL after the domain like below
`https://domainNameassets/favicons/apple-touch-icon-180x180.png`

Where the expected URL is ``https://domainName/assets/favicons/apple-touch-icon-180x180.png``

### What Wagmi package(s) are you using?

@wagmi/connectors

### Wagmi Package(s) Version(s)

5.0.21

### Viem Version

2.x

**Comment by tmm** [comment]
Probably worth follow up upstream on Coinbase Wallet SDK https://github.com/coinbase/coinbase-wallet-sdk

**Comment by tmm** [comment]
Probably worth following up upstream on Coinbase Wallet SDK https://github.com/coinbase/coinbase-wallet-sdk
