### ISSUE TITLE
@wagmi/vue version 0.0.25, cannot detect Connection Status

### ISSUE THREAD

**Issue by kevinchung0516** [wevm/wagmi#4126]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Using @wagmi/vue version ^0.0.25, refresh the page after connecting to the wallet, and the walletconnect button cannot detect that it is connected.
When I switch back to 0.0.24, it can be successfully detected

### Steps To Reproduce

1. npm install @web3modal/wagmi @wagmi/core @wagmi/connectors viem
2. npm install @wagmi/vue viem@2.x @tanstack/vue-query

https://docs.walletconnect.com/appkit/vue/core/installation
https://wagmi.sh/vue/getting-started

### What Wagmi package(s) are you using?

@wagmi/connectors, @wagmi/core, @wagmi/vue

### Wagmi Package(s) Version(s)

0.0.25

### Viem Version

2.17.3

### TypeScript Version

js

**Comment by tmm** [comment]
Tried reproducing quickly and wasn't able so please add a minimal reproduction, and I'll be happy to look into it!
