### ISSUE TITLE
Dangerous 3rd party dependency

### ISSUE THREAD

**Issue by rafinskipg** [wevm/wagmi#4127]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Through the walletconnect dependency theres a package that is flagged as dangerous, as it can execute arbitrary code. 

I think maybe it deserves some security research, since wagmi is spread through all the crypto industry

The package is called `untun` 

![image](https://github.com/wevm/wagmi/assets/1152768/8a309d8a-94f6-4a94-9e72-791c950c296c)

### What Wagmi package(s) are you using?

@wagmi/connectors

### Wagmi Package(s) Version(s)

2.10.10

### Viem Version

2.x

**Comment by rafinskipg** [comment]
https://github.com/WalletConnect/walletconnect-monorepo/issues/5176

**Comment by tmm** [comment]
Let's track in the upstream issue. If you don't use the `walletConnect` connector, the code should not be included in your build.
