### ISSUE TITLE
WalletClient type mismatching

### ISSUE THREAD

**Issue by koa202405** [wevm/wagmi#4134]
### What is the issue?

Docs says that `useWalletClient` will get viem `WalletClient` type, but actually, it get `UseWalletClientReturnType`, which doesn't satisfy the viem. I didn't know whether it is a docs issue. 

I use viem and want to get a viem `WalletClient` type from wagmi, how can I do that?

docs: https://wagmi.sh/react/api/hooks/useWalletClient#usewalletclient

### Where did you find it?

N/A

**Comment by tmm** [comment]
```ts
const { data } = useWalletClient()
data
// ^? const data: WalletClient
```
