### ISSUE TITLE
Wagmi cli foundry plugin defaultExcludes list is replaced when specified

### ISSUE THREAD

**Issue by KholdStare** [wevm/wagmi#4151]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

```ts
export default defineConfig({
  out: "typescript/generated/wagmi.ts",
  contracts: [],
  plugins: [
    foundry({
      exclude: ["proxy/**.sol/**"],
    }),
  ],
});
```

All the default excludes are no longer used, because the whole list is overwritten https://github.com/wevm/wagmi/blob/main/packages/cli/src/plugins/foundry.ts#L110 .

Perhaps the lists should be merged? Or at the very least, `defaultExcludes` should be exported so the merge can be done by the user https://github.com/wevm/wagmi/blob/main/packages/cli/src/plugins/foundry.ts#L14.

### What Wagmi package(s) are you using?

@wagmi/cli

### Wagmi Package(s) Version(s)

@wagmi/cli@npm:2.1.15

### Viem Version

viem@npm:2.17.4

### TypeScript Version

5.1.3

**Comment by tmm** [comment]
Exported the default excludes for now. Can revisit merging them by default in a later version.
