### ISSUE TITLE
create wagmi templates don't work

### ISSUE THREAD

**Issue by rube-de** [wevm/wagmi#4158]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I tried to create a new wagmi project with a template according to https://1.x.wagmi.sh/cli/create-wagmi
When I use `npm init wagmi --template next-connectkit` it still asks me for the framework and the variant and will have no dependencies for connectkit installed. It only uses the specified template as the name of the project.

### Steps To Reproduce

npm init wagmi --template next-connectkit

### What Wagmi package(s) are you using?

create-wagmi

### Wagmi Package(s) Version(s)

2.0.13

### Viem Version

2.17.9

**Comment by tmm** [comment]
`create-wagmi@2` has different options. Can check out the docs here: https://wagmi.sh/cli/create-wagmi

If you still want to use `create-wagmi@1` (for `wagmi@1`), you need to specify the version.

```bash
npm init wagmi@1 --template next-connectkit
```
