### ISSUE TITLE
Missing type in ConnectErrorType when using connect method from useConnect

### ISSUE THREAD

**Issue by redianmf** [wevm/wagmi#4183]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

**What I am doing**
I am using connect method from useConnect hook and then using onError callback to get the error message

**Expected**
onError have error object with type ConnectErrorType which I expect to have `shortMessage` key
![image](https://github.com/user-attachments/assets/69f4a52a-e5f5-4dca-8c4b-1751606dabb6)

**Reality**
Property `shortMessage` does not exist on type ConnectErrorType 
![image](https://github.com/user-attachments/assets/ca70bbaa-7410-49bb-91e6-7729fcdf390a)

There are only 3 property shown in error object
![image](https://github.com/user-attachments/assets/848de1ca-5160-4faa-bff0-5e444e4a61ba)

### Link to Minimal Reproducible Example

https://github.com/redianmf/react-web3/blob/master/src/pages/Home.tsx

### Steps To Reproduce

1. Clone
2. npm i
3. go to /src/pages/Home.tsx

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.2

### Viem Version

2.18.6

### TypeScript Version

5.2.2

### Anything else?

Using React + Vite

**Comment by tmm** [comment]
The error type can also be `Error` (unhandled error coming from upstream SDK, wallet, RPC, etc.) so you need to narrow down `error` if you want `shortMessage`.

[TS Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYygUwIYzQYQgOwDNgBzAGjgAsYYwKBXAZ1wPzWXgF85CoIQ4AcgDuGEiGCCAUKEixEcEBmD42XHnwEixEgPTJKy-I2lTkBRvHNFScALwp0WFjZIAKBFLgpDKxgC44AG0lFTUAXTIvOBgoDGM5GADEaO8QozUAOmAAE3DA6lo3AEoo704ozmKzC3gkazYOOG4HJhdGmBKpGtV2TujPb28GvuhA62ISTJGOaEYggAZwgEIy5rXBoYIAUSg+KDc0PehilKGh4EI4N0FGSmgYAFk0RkYxNEE4FTgj-dPf6CZO4PZ6vd6pC5XQ7HKCZfAYEBoex2ByCACqzCgACU0AArPpoHI4gCO9BeMF2+0E-xhQPusFBbxIaAhFWibOqQA)

```ts
import { createConfig, http, useConnect } from 'wagmi'
import { mainnet } from 'wagmi/chains'

const config = createConfig({
  chains: [mainnet],
  transports: {
    [mainnet.id]: http(),
  },
})
const { connect } = useConnect()

connect(
  {
    connector: config.connectors[0]!,
  },
  {
    onError(error) {
      if ('shortMessage' in error) error.shortMessage
      if (error.name === 'UserRejectedRequestError') error.shortMessage
    },
  },
)
```
