### ISSUE TITLE
useWriteContract cannot return hash normally when using wallet-connect connector

### ISSUE THREAD

**Issue by c0da523** [wevm/wagmi#4187]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I am doing approve operation using wallet connect ;

```
  const { data: hash, error, isPending, writeContract } = useWriteContract();
```
The hash is always undefined and `isPending` always return true ;

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-1i1mxn?file=package.json

### Steps To Reproduce

1. Click connect btn and choose wallet connect ;
2. Input any number in the textinput, then click the mint button;
3. Approve the transaction operation showing on your mobile;
4. Waiting for the transaction confirmed (But it will not);

### What Wagmi package(s) are you using?

wagmi, @wagmi/connectors

### Wagmi Package(s) Version(s)

2.12.2

### Viem Version

2.13.7

### TypeScript Version

5.2.2

### Anything else?

no

**Comment by tmm** [comment]
Works fine for me. What wallet are you using with WalletConnect?

**Comment by c0da523** [comment]
> Works fine for me. What wallet are you using with WalletConnect?

Metamask, and Sepolia testnet.

**Comment by c0da523** [comment]
> Works fine for me. What wallet are you using with WalletConnect?

Have you ever tried this link? Using Metamask mobile app to scan the wallect-connect qrcode, then switch to sepolia network

**Comment by lozyloop12** [comment]
I get the same bug but it only happen with Android device, IOS device still work good
