### ISSUE TITLE
Wrong connect status of useAccount with Rabby

### ISSUE THREAD

**Issue by vvvvvv1vvvvvv** [wevm/wagmi#4194]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I set up a reproduce demo https://github.com/vvvvvv1vvvvvv/rainbowkit-connect-bug and deploy it on vercel https://rainbowkit-connect-bug-xi.vercel.app/

When use `useAccount` with Rabby Wallet, the `isConnected` status may start with `false` then change to `true` and finally change to `false`, but as I checked the request of `eth_accounts` has been responded correctly

I am core engineer of Rabby Wallet, if you think this is issue of Rabby Wallet, please let me know what may caused it, I will try to fix it

### Link to Minimal Reproducible Example

https://rainbowkit-connect-bug-xi.vercel.app/

### Steps To Reproduce

1. Connect with Rabby Wallet
2. Refresh the page until account info is not displayed
3. Check the console you will find as below image(the purple console is from Rabby debug version, for let you check the rpc requests)
https://github.com/vvvvvv1vvvvvv/rainbowkit-connect-bug/blob/master/src/pages/index.tsx#L10 here is the code of console
![image](https://github.com/user-attachments/assets/eae9277d-cb62-409d-a682-83b7434c4d00)

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.9.2

### Viem Version

2.9.31

**Comment by tmm** [comment]
Thanks for reporting! I'm not able to reproduce using version `0.92.85`. If you can reproduce predictably with just Wagmi (no RainbowKit), happy to look into it more.

https://github.com/user-attachments/assets/3a27d259-96d4-4f33-a9a6-88f9e086f794

**Comment by vvvvvv1vvvvvv** [comment]
@tmm try reproduce it on https://rainbowkit-connect-bug-xi.vercel.app/ it can only reproduce on production, can't reproduce in local dev server

**Comment by vvvvvv1vvvvvv** [comment]
https://github.com/user-attachments/assets/be5ca66a-8d0d-4ef5-ab97-0de91d67a086

**Comment by vvvvvv1vvvvvv** [comment]
@tmm Can you reopen this issue?

**Comment by tmm** [comment]
Please add a minimal reproduction that only uses Wagmi.

**Comment by vvvvvv1vvvvvv** [comment]
https://github.com/vvvvvv1vvvvvv/wagmi-reproduce
After removing RainbowKit, the issue indeed cannot be reproduced. This is quite strange. I will create another issue on the RainbowKit repository.
