### ISSUE TITLE
EIP-1193 auto-injected connector connections don't persist on page refresh if previously disconnected with ssr enabled

### ISSUE THREAD

**Issue by kristiegiles** [wevm/wagmi#4195]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

When connecting with WalletConnect, the connection reliably persists when you refresh the page. However, if you connect with MetaMask or another wallet via the EIP-1193 auto-injected connector, you get disconnected on page refresh if you have previously disconnected via `disconnectAsync` from `useDisconnect`. 

It seems the ssr cookies like `wagmi.io.metamask.disconnected: true` are set on disconnect:

<img width="295" alt="Screenshot 2024-08-07 at 11 01 05 AM" src="https://github.com/user-attachments/assets/20c4076e-2e41-4973-8241-45d2d7c6b46b">

And they are not removed or set to `wagmi.io.metamask.disconnected: false` when you reconnect via `connectAsync` from `useConnect`. If you manually delete these cookies after reconnecting, you will no longer be logged out on refresh. 

It seems like it may be best for wagmi to handle deleting these cookies or setting them to false on connect. 

I removed the following ssr configuration from my config, and that fixed the issue:
```
  ssr: true,
  storage: createStorage({
    storage: cookieStorage,
  }),
```

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.10.9

### Viem Version

2.17.3

### TypeScript Version

5.1.3

### Anything else?

Relevant part of connector config:

```
const config = createConfig({
  ssr: true,
  chains: [mainnet, sepolia ],
  storage: createStorage({
    storage: cookieStorage,
  }),
  ...
})
```

Using React 18.3.1, Next.js 13.4.19, Turborepo, Bun

**Comment by tmm** [comment]
Try upgrading to the latest Wagmi version. Might be related to https://github.com/wevm/wagmi/issues/4097, which was fixed yesterday.
