### ISSUE TITLE
Viem has a [`estimateContractGas`](https://viem.sh/docs/contract/estimateContractGas) action (PR welcome to add the Wagmi Action/Hook). You can use that or you can encode the contract data and pass it to `useEstimateGas`.

### ISSUE THREAD

**Issue by hskang9** [wevm/wagmi#4198]
Viem has a [`estimateContractGas`](https://viem.sh/docs/contract/estimateContractGas) action (PR welcome to add the Wagmi Action/Hook). You can use that or you can encode the contract data and pass it to `useEstimateGas`.

_Originally posted by @tmm in https://github.com/wevm/wagmi/issues/3727#issuecomment-2008680030_
            
Is there any example code to accept encoded data? I don't see that anywhere in the documentation.

**Comment by jxom** [comment]
https://www.typescriptlang.org/play/?target=99#code/JYWwDg9gTgLgBAbzgVwM4FMCiqagIYzoDieqcAvnAGZQQhwDkA7ngOYjAMBQoksicdADsAxhAAm6AGLJRuCEIAiBPABpBUEQCYADAEEARsArVa9BgDdg6ENy5ihOAeJUAuOK1ImAvCgzZcEAJiUgAKBC44OBcYPHdhMUkZOWAFZVjwyKi4PCN4zV1DYHU4LKiqWRF5IQA5PBB0dwY8MDBaC3QGVTKcqFZUdwBtBh0ADx0Jyanpmdm5qa64HSEAXSzyAEpuqJgIJrHuTcigA

**Comment by hskang9** [comment]
One problem @jxom, The app crashes whenever `encodeFunctionData` function receives undefined data, and when a result value from useSimulateContract is refetching, the error happens every time. Even importing from a json file causes an error. 
encodeFunctionData({
    abi: erc20Abi,  
    functionName: 'approve',
    args: ['0x0000000000000000000000000000000000000000', 0n]
  })

**Comment by jxom** [comment]
That’s expected. You need to give it defined values.
