### ISSUE TITLE
`WagmiProviderNotFoundError` for hooks generated by `@wagmi/cli` in monorepo

### ISSUE THREAD

**Issue by atahanyorganci** [wevm/wagmi#4201]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

We have a `pnpm` monorepo with `turbo` with a Next.js application and a API that uses a shared workspace package that exports `wagmi` hooks and `viem` actions generated by `@wagmi/cli`. Next.js application crashes with `WagmiProviderNotFoundError` when any of the hooks are used even if it is wrapped in `QueryClientProvider` and `WagmiProvider`. Passing a `Config` object from `useConfig` fixes the issue. Is there a way to solve issue without passing it manually everywhere? 

### Link to Minimal Reproducible Example

https://github.com/atahanyorganci/wagmi-turborepo

### Steps To Reproduce

- Install dependencies via `pnpm install`
- Run `pnpm build`  in `packages/contracts` to generate 
- `pnpm` dev and navigate to `localhost:3000`

Context
- `apps/web` is the Next.js application
- `packages/contracts` exports `wagmi` hooks and `viem` actions generated by `@wagmi/cli`

### What Wagmi package(s) are you using?

wagmi, @wagmi/cli

### Wagmi Package(s) Version(s)

2.12.5

### Viem Version

2.19.4

### TypeScript Version

^5

**Comment by tmm** [comment]
Guessing this is an issue with Turborepo and pnpm. If you can reproduce without Turborepo, happy to look into it more.
