### ISSUE TITLE
[Bug] switchChain is not working

### ISSUE THREAD

**Issue by davidli108** [wevm/wagmi#4218]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

1. To reproduce
 - connect wallet to Arbitrum One network (Any other network is possible but not Sepolia). You will see the popup to switch to Sepolia but don't switch.
 - Refresh the page
 - As soon as page is refreshed, you should see popup to switch to Sepolia. But it doesn't happen.

2. List of related npm package versions
 - wagmi: 2.12.7
 - @web3modal/wagmi 5.1.1
 - viem: 2.19.8
 - @tanstack/react-query 5.52.0

### Steps To Reproduce

 https://codesandbox.io/p/sandbox/test-switchchain-hdn6hr
 - connect wallet to Arbitrum One network (Any other network is possible but not Sepolia). You will see the popup to switch to Sepolia but don't switch.
 - Refresh the page
 - As soon as page is refreshed, you should see popup to switch to Sepolia. But it doesn't happen.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.7

### Viem Version

2.19.8

### Anything else?

Link to minimal reproducible example
https://codesandbox.io/p/sandbox/test-switchchain-hdn6hr

**Comment by tmm** [comment]
Please create a minimal reproduction that only uses Wagmi.
