### ISSUE TITLE
[Bug] switchChain is not working

### ISSUE THREAD

**Issue by davidli108** [wevm/wagmi#4219]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

1. To reproduce
 - connect wallet to Ethereum main network (Any other network is possible but not Sepolia). You will see the popup to switch to Sepolia but DON'T switch.
 - Refresh the page
 - As soon as page is refreshed, you should see popup to switch to Sepolia. But it doesn't happen.
2. List of related npm package versions
 - wagmi: 2.12.7
 - viem: 2.20.0
 - @tanstack/react-query 5.52.0

### Steps To Reproduce

 Here is the link: https://codesandbox.io/p/sandbox/test-switchchain-hdn6hr
 - connect wallet to Ethereum main network (Any other network is possible but not Sepolia). You will see the popup to switch to Sepolia but DON'T switch.
 - Refresh the page
 - As soon as page is refreshed, you should see popup to switch to Sepolia. But it doesn't happen.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.7

### Viem Version

2.20.0

**Comment by W3stside** [comment]
why do you expect it to switch to `sepolia` on refresh if you didn't switch (as step 1 states not to do)?

**Comment by davidli108** [comment]
For example, a user's wallet is now in the Ethereum network and the user opens my website.
In this case, this user's wallet should be switched to Sepolia network.
But this doesn't happen

**Comment by imBinyameen** [comment]
Any updates on this?

**Comment by jxom** [comment]
You will need to check if the Dapp is also not reconnecting to the Wallet.

```diff
- const { isConnected } = useAccount()
+ const { isConnected, isReconnecting } = useAccount()

// ...

-if (chainId && isConnected && curChainId !== +chainId) {
+if (chainId && !isReconnecting && isConnected && curChainId !== +chainId) {
```

Could probably get this to function correctly without this kind of workaround, but I would generally advise against non-permissive popups.
