### ISSUE TITLE
Issue: Chain ID Discrepancy for kakarotSepolia in wagmi/chains

### ISSUE THREAD

**Issue by harshcrop** [wevm/wagmi#4231]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Issue: Chain ID Discrepancy for kakarotSepolia in wagmi/chains

**Description**

When trying to connect to the kakarotSepolia chain using the wagmi library, the chain ID returned by the library is 107107114116. However, according to the Kakarot Sepolia documentation, the correct chain ID should be different (please specify the correct chain ID here).

This discrepancy causes the wallet connection to fail or incorrectly connect to the wrong chain.

**Steps to Reproduce**

```
Import the kakarotSepolia chain from wagmi/chains in your project:
import { kakarotSepolia } from "wagmi/chains";

```
Attempt to connect to the chain using a wallet:

```
const config = createConfig(
  getDefaultConfig({
    appName: "MyApp",
    walletConnectProjectId: "your_project_id",
    chains: [kakarotSepolia],
    transports: {
      [kakarotSepolia.id]: http("https://sepolia-rpc.kakarot.org"),
    },
  })
);
```
Observe that the chain ID being used is 107107114116 instead of the documented chain ID.

**Expected Behavior**

The chain ID for kakarotSepolia in the wagmi library should match the chain ID documented in the Kakarot Sepolia documentation. This would ensure correct wallet connections and prevent issues related to chain mismatches.

**Actual Behavior**

The chain ID used by the wagmi library for kakarotSepolia is 107107114116, which does not match the documented chain ID in the Kakarot Sepolia documentation.

**Screenshots**

Please see the attached images showing the chain ID discrepancy:

Image 1: Current chain ID from the wagmi library
<img width="567" alt="Screenshot 2024-08-30 at 12 44 38 PM" src="https://github.com/user-attachments/assets/5a1fed32-7176-473b-938a-a55c8baeb82e">

Image 2: Documented chain ID in the Kakarot Sepolia documentation
<img width="441" alt="Screenshot 2024-08-30 at 12 48 32 PM" src="https://github.com/user-attachments/assets/b21e8f9c-34dc-485c-a20c-55d579e1a7e7">

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.5.13

### Viem Version

2.9.3

### TypeScript Version

5.5.4

**Comment by tmm** [comment]
Feel free to create a PR on [Viem](https://github.com/wevm/viem)!
