### ISSUE TITLE
useWaitForTransactionReceipt - isLoading is true even after the transaction is completed. 

### ISSUE THREAD

**Issue by Venkateshb2877** [wevm/wagmi#4235]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

This issue occurs only when the transaction is taking more time to execute. Whereas when the transaction is instant it is fine as expected.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.0

### Viem Version

2.x

### TypeScript Version

5

**Comment by Venkateshb2877** [comment]
On Form submit this function is called.

	`const onSubmit = (data: AuctionInformationType) => {
		......rest of the code
		setApprovalForAll(reverseAuctionAddress, true);  ///blockchain call for approval
	};`

Below code is the blockchain function for approval
      `const setApprovalForAll = (address: string, status: boolean) => {
		console.log(`Setting Approval for`);
		writeContract({
			address: ratAddress,
			abi: ratAbi,
			functionName: "setApprovalForAll",
			args: [address, status],
		});
		console.log(adminAccount.address);
	};`
	
Once the blockchain is approved, backed api called is dispatched.

     `const {
		isLoading: isConfirming,
		isSuccess: isConfirmed,
		data,
	} = useWaitForTransactionReceipt({
		hash,
	});

	useEffect(() => {
		if (error) {
			toast.error(error?.message);
			setNftApproved(false);
			setLoading(false);
		}

		if (isConfirmed) {
      //once blockchain approval isSuccess then backend api is called.
      dispatch(PostCreateAuction(body));
      setLoading(false);
    }
	}, [isConfirmed, isConfirming, error, data]);`


Sometimes when the approval function takes longer time to complete the transaction, isLoading is frozen as true and isConfirmed(i.e isSuccess) as false. Even after the completion of transaction, isSuccess remain as false and api call is not made.
The state of isConfirming and isSuccess are not updated.

This issue arises only when the transaction takes more time to complete. When it is fast, it works as expected. 


Please find the TypeScript Playground Below.

[Link](https://www.typescriptlang.org/play/?ssl=115&ssc=3&pln=115&pc=12#code/EQVwzgpgBAxgNgSwgOwC7ANwCgsILYAOA9gE6pQDKBCyyEJUAZiUXlMAAID0YJMXMVsTpowXKjTolMuQqXKoAngWgBvKACUiRVBVQBDVNAC+TFm048+XEKgRwwM-MTJR1JQwEEAJt5IQwMAAaKH8AN3pITxAYOyJkHz8AsChTZlZ2bl5+W3sxQWRGBABzJzlXdXAIABEEMAJDGAALEKqKCDgIWNJUswzLbJs7By4m7QBrR2xneVCvACMEPoss61yRj1RPRYA6ACsweLKXcnDIiGjYhHjtpfSVqxzhsTOSKJi4hIAhAEl9w+Qx1m6gACkQwKgAML+QwXD7XZC9e6ZR5DPI8RAwAJcfTePA0IGuJQqNxQAByEAA7pdPl8iN5FEjzCjBusxGBMdjcfjkAAVZQBQnkdQAcQgqAAqpASD9vEz+qsnuiqjLvELSQAvekaAJEOARBhpZmcMZEcaMUh4Lj+Q76yJcLVq6blYVQKoAUUYjC6qFakD0sPlFhhsXVlUgADFLUH2CHUABaU3jeMWkh4MNQVBEfQQmPAOPxrM5uyMRQZ8VNegS5AIVApI39MJIdPOk6kqqeGCCEBoP0QADq+lrUZIvI8yDA+iu8R1WIQBF9bsg-ZItYgkPiqA8sTzlP0xXxGY1ecdGZ+yAItgjSDgcobFh2OxxvkL48n04nXHmOYQMHjNFTPBDARLgAH0aEvdBsCwApcxpBFz0A4D4goZoICAqAAF4oA1HYiHmPYfQAClULAAEh4PiUCyX0PAIAALhwnYIVXZBiiIgBKHYeSIgBGEJgBBToc2gFAjAYfR4XiKBkFoiBgA4oJyK+BBvFAyEmn0NiIFAgAZfBa0Y3CWJodiuP8YoIAADyIrgAD0AG0AAZ4wATgAXQAagAEi4ASVLlDStMsqB9PxcgwDGEBbygeZoH0KBKTGToZJAPA4ukRTlNU0CIwgHSQXoLE0H3BicPIsjmK3UzOIqnYLOs2y7KIpyAB8HN4tz3IAHW8AAqDiiO6nZes8jiAH5fP81SoDy6BIqIaK5TiqAEu8Lp8H0EZkDSjLHA4ur-CKOgiIqsiiLCLaQAgDisIAPjcM6yNg8gGjeCBvAANSu6BsLeyM4GzVALp+jjsDIiGyP8VAQBIRF-o+764GuqAHqcqAADIMagBGvp+qAAB5sN4pynPBiHjCUyHSMhsi6MCUrGOAALZvyqAFqW2LoDi1BKXyxF0a0uUSac4AqYp8WsooqTkFAzw8EWtAjKq1izPqiBLJs+znK6ny-PYSjEXlxWIqimKVoSpK9WgHb0voBSqfdZA1N5fAyuM6q2M47iaD4gShIgESoDE+hg+dzM3YdrBjDBnBiWgQ3EMtZC+QFLCmIA+gCfjohGCgRPCmTz5UMrIC7ug+OoBBFgCBSbCaYiJpf06WVGJMtjwazcYUFb9nPeKcHIF0GIsUCRidSnVAdlqepGiaAmJ9iHZ2l0AwjE7T4CfmbRhOQO7y+j6DrLbdbGEkuByEYHsP3zmWk7TFOSPZ8UKBH5IQkb5uIFlEIu57u9GLVyILXW6NMXqPQhhZOo4lxaaWdp0V+8xwri0AgGIwjF1D0BYG8VIVNTDYSqCOPABMC5IU+PyFQd0SIVRtHqA0RltS6jtCQIipCi4IhLuhfQUsY7g3Aeobwhh9CMU0pFEIdRCrO1MiELBpAQiUlXEYDcaBtzkHwUuAcij1yblUZxPh8RczchoJ2bsaB04di7CbPROBnoGPIN4OoDRUDNHMZAGeTjmjWNsROcgDkVQ-2fpKaUsp3KuIgGgiABN27FCocABS+ifFQAcoULYBACAsAiN4EIQ8ySMFSekogmTQkEP9GvSJ29rZaSoWfBwN0Em5gcoDXE0jAm6WzA4tixSNERK3jvQOe8iI1MgLHbxDSGiKCaVkwJIJ9ATPaV0toZSCYUmpDLOkDIqGqFMDmckVJDbrMUCM8BMAYTrxljqeoBjfrdI6D6UgREiIQlhOPbQq9YS3Uwg9J5RgdhGOQDsE5gczkfljuRD0XpiKcXuhA0Z5AZrYTFEE+gsovFkQQHnIiqlQFnSHlKZF3hMXeBGWRYw5FKZJPcqC2FUAUIgCQbWdORFBEGEYmwh+5CBQfIejTMiQ82nNK9lua6xLwFPLIKBOwdF050EpFAaosJrEVTFagCVbtmLinlUYR5BhxWSogDsSyqBNUQE4lS6lihA4MGwsq1VdEDXigjNFOAABNS1qLwEKzQE0dOehVbav0LqtVhqACym4mhQs8lAXiXEGjeADGQIiAAmASosRV2KgIIxk2FfU1RtXq+1RqFUcRjbieNwNk3sFTeTcBZCjBxp1YWow6cAAG3lVAWoDcYeMbbPWoCaF2ttmbjDNughDcBeragQv8MgLE6djU7ARkyoROwnYuzdrdeMcrYQLoDZAf1ga7VZhzV7Yt1b02Zsnd6ads7sITvRVelAs6uBQD4qTdGfUoAAGYABspMoAfsTQAFjTYk8ZjEVn7PpFmmFZFJIflArJOijFmX6B2IbaiclxZkUWGpZowUdKIHCsh5dAV1JwMsnpAyvozo4dAt6HSKg+BiWIwYHYpG5qgUKkxkqlksOoCsrLXucSsN5rdoxWtH0y3GqwygNSeqWOodXaBV2h6iDHrMnxs0KBwLeEYn-ZAP8zpwc+KBWiqBGKeRQ2hmWcsFY9mo5DYzCJQKXUQA4pQxHFCXvoI+6AkbgAZtmY4cWxhyZDxmXM3ERFxlmqHp4NJGStojk8HAOARFXjvA-IkG0wRMwkGFRgKAXBivzEBjAcYeGaCwC2nAJgPR9AJcKVtMlo7RXiniwU1zyXUuMtxEkMefdVbZLXuARiFTd5cphbBa2OxAbsWbSvOwbF86Ndc3VkgzbiUKLXMorck9qGOd8DlximxsvvyM4sE7CwEBYavjOz4NEkPsDi6tpLpAUtwDFkZkgxQwCMQcn1nLw3DDgHciFkDtp9VzaIn8kxJtflHeSCM0LNj+EVTqPyjpxRGJ1GUUUNM0j0dgFfl2ZIOOwB44QGmD64sUN4LCYOYcpAxxaXfJ8WcEB5zAx5aIloZKqXgu9LEB5k2eXTc6LNog7FgB1CgJM0yYsoC4-iPjnkxQIczehzLlIYA36BEV8rwoVO6JErPROTXUuiLAFkdIGRJBsHjW4skUqGuJda5Q4rlDjvvngBCLz4l6KX02+xZDIsEIdg26Ijbx39NJyWWJby8UuT8kZI+oMrawzyaJ9QJjmqQy6kVVJejjFhvVcfWxVASvVfivxFnaVog5XKuIga51raSvid65SH2lAsUpzd3Dg1pYsuYA1Y+jsLAVeq8ONns48NYIITQiBXCD8RFt4MlPRPyfrT2l54zwXyfpKSUhAcqX43NP2+U4J2xO32CQgocpdBGxgvIWi+Ly+wFsJDYXOEJAHYKGQ8QxDwk6jxgBERCoF4Uw2JooYof7Ars4BA-76rB4wbi5Q6W6wHL7wGXITgQEQxh5TyR4YFf4IFXIR726kBO4Mzx7kyH7koOREHnIkE4HZIvyd4P42LQywyIinQQwEwOJhCwBwA5hgCPYQCYQBaUgphOrAB3RnQEyAQ0rICILhSYSqBwLeAIJ0rhRES0r0qoAcSmDwDCGiHiGSFXypYyFPR8EIACFGGBAmEBaMCdBWRMDOHxgKINZQB7DgAliKDxg8x8w95mFOo4xWTxgAAclhtMZEBM54kE14HQ3gT0Y6Qh9hckph8YAArFwLxImsAMkWRIhmIcAOhqIfkdEWRAQEIViMlOtCQOIU7OJLfDfGUQUfHOIUYFZOgAUVAhCPQKob0eJFbqUXJApIftETbsGs7pZKoTbmANZvBqITHtMRAOMZDFwLIdEbEReFeDeEkRUXYSIekcAJIdkbkeUdEUUeIaRkFNpJRuFBcbTFUVOBALUf0cAI0aHN3rFDNHhtpHLlRo8aHgKOIbbBlECZAhrNAv0aoIMfQFbjceRjpGFLWGMQUZMSsbMeQW8GxjlLcRRiiagMsVQasckRsVAZDNsfEXsQUYcQ4acTkXkQUVcczDlBxlxsVAYJZBCZUdUa8XqHUQ0WgF8ZWD8XKPRlAAAKQvqdQiwcQ8ntHADRI8lwn1GwlQl9EsKslqTslFRiSlRokVEYkklYnYLzHsb5ScZ6k8YQDElx6knRHknJHWG2GpFHF0SqHNoMm5FQB4B+GfqZjWQJhgBsAWhoDxiQD4jbwxT+BCF2ARDNrGCbFbH8GCHGHHGdEJgOQADE36eZEAAA7J+u5DIRoIYPnIjoEATFwPwcmbTC6QUc9G6SYaoF6VIT1k0PGD6XgHABEbFKQHUfGImv2SQIOTmQWU5BOROYmgWaEiwD2OtN4BGWwAQPGAGVUX2X6UOXVjAKNotKgIgHQPGMgPENABaLuX9tvKOfQPGMUB4H4YBn+omQUXWbTLCV4JWfMRyL+Cak5CEOEbdP5o+DsAFpGqdp+cxJyERBEQYQUdWbWc6TWTYbIc6XEbsYkbSc2ccd6UyRUSyehsbPZjyc8TUQKe8Z8QwN8U5tJLRCbAqSCUqf3CqRqeJAMSxfCSUTZoRWgIaRMdiVMSaaoHMQsSZtxUSZQfaWsRDE6VsWhagAkbeJhemR6ScVkYyTySyUpipvJAUSRfybeORcKZRaKbJhHHRPRSoOIcyuKG7PGGVltMxcUNCWqaqVblpZHLBUafxZiUJdifMe5XRHaaVFJWRDJfWamXSeka2Thb6f6YGV0cuXVuGZGQgNGXKLGcBAmUmXBRFVhSpZmfGDmXmd+oWcWTIdWAgAAI4owaCeC8hQCyjwXIU5U2GNmRUenRXtm1adndm9nhEjmDnDlXljnZlTmTlOQzlzmKyLmJWrnrl9WxXbnnl7m2CHkQDHmnk7mjbDU3l3mzLxiPnozPkVGvnUz6ayghUxFIVhCnVNU3VWHXWvkulplpEqXBE9ZOHWReE+Hop+GyZRH1nzC2BZjIBtEMW656E8ntViGtkFVJRrixTFD+EsCUjwxhEkw4xrnxXBmhmbgRnoSpUCm+k0DuEHXoxQBtry7LbjTsC7lvCkAbV0ABZMzACmDHW0ynVkSqBU3FBQA00EwSC0ChwbFQBMyL6BhkhECUis2IVA2oAg1PWPVyFcCATJl3WbGxykpAA)

**Comment by raycaballero** [comment]
I'm also encountering this issue now.
