### ISSUE TITLE
Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by TrejGun** [wevm/wagmi#4239]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

related to https://github.com/wevm/wagmi/issues/1625  https://github.com/wevm/wagmi/issues/3516 https://github.com/wevm/wagmi/issues/3744

All of those tickets describe the bug but there is no solution yet. I guess I know the actual problem but did not find a solution yet

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/4dc42483-e3f4-4aeb-b736-706bcf8f067f">

Look at my console. It shows that the application uses 2 different QueryClientProvider.
JS one is from wagmi and CJS is from my project 
this happens because my project is not ESM
now the question is - how to make wagmi to use the same version?!

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.8

### Viem Version

2.21.1

### TypeScript Version

5.5.4

**Comment by W3stside** [comment]
you are probably using 2 different versions of `@tanstack/react-query` or `wagmi` somewhere
1. `yarn why @tanstack/react-query` and then `yarn why wagmi`
2. check your `yarn.lock` for versions
3. not sure your environment as its not pasted here but check your `package.json` `type` property
4. to force `resolutions` in `yarn` check https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by TrejGun** [comment]
@W3stside  

nope

<img width="573" alt="image" src="https://github.com/user-attachments/assets/593b0d0c-2fe5-4a99-b54b-1507cad90a11">

**Comment by TrejGun** [comment]
@tmm here is minimal reproduction
https://github.com/TrejGun/kamasutra-fe

**Comment by TrejGun** [comment]
here is the solution

https://github.com/fkhadra/react-toastify/issues/1061#issuecomment-1933786361

**Comment by TrejGun** [comment]
this works too

https://www.codejam.info/2024/02/esm-cjs-dupe.html

**Comment by meowdao** [comment]
@tmm fuck you for your approach silently close tickets. ppl spent time writing about their problems just to see your fucking ignorance. I swear you are aware about this problem thats why you had wagmi@cjs in the past but it is only for v1 and now this looks like - if you have not migrated to esm - go fuck yourself

**Comment by tmm** [comment]
The minimal reproduction is not public 🫡

![001345_Firefox_2024-09-04-10 23 33@2x](https://github.com/user-attachments/assets/55b98b75-3b72-4cca-a821-d2850ad902f5)

**Comment by TrejGun** [comment]
@meowdao ruuuude

@tmm fixed

steps
```
npm i
npm start
```

then go to the tab with deployment

the fix is in
https://github.com/TrejGun/kamasutra-fe/blob/master/webpack.config.ts#L35
just comment it out
