### ISSUE TITLE
changing chain on Metamask won't change chain on useChainId() and useAccount()

### ISSUE THREAD

**Issue by 0x33dm** [wevm/wagmi#4256]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I have a very unexpected error when in my application the user is connected to ARBITRUM chain and `useChainId()` will return the correct chain.

But then if the user opens MetaMask and changes the chain to ethereum mainnet, then `useChainId()` will keep reporting the wrong chainId.

Sometimes the `chainId` on `useAccount()` are different as well.

---

When I did a new test using Stackblitz the problem seemed to be worse, where I would change to any chain and the chainId won't change; sometimes I would disconnect the network, and the old chainId will be reported on `useChainId()` but not on the `chainId` from `useAccount()`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-qem9ah?file=src%2FApp.tsx

### Steps To Reproduce

1. open https://stackblitz.com/edit/new-wagmi-qem9ah?file=src%2FApp.tsx
2. use `Metamask` to connect
3. change the chainId on MetaMask and look at the screen, you will see the chainId not changing and/or being reported differently from the `useAccount` and `useChainId()` hook.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.8

### Viem Version

2.21.2

### TypeScript Version

5.2.2

### Anything else?

I'm using CHROME, on OSX 14.4, with what i believe to be the latest version of MetaMask.

**Comment by Yuripetusko** [comment]
yes useChainId has an important caveat and i've got caught in it before too

```
Only returns chain IDs for chains configured via createConfig's chains parameter.

If the active connection chainId is not from a chain included in your Wagmi Config, useChainId will return the last configured chain ID.
```

So if you change the chain to the one that is not specified in wagmi config, then it will fall back to the first chain in chains array

**Comment by 0x33dm** [comment]
> yes `useChainId` has an important caveat and i've got caught in it before too
> 
> ```
> Only returns chain IDs for chains configured via createConfig's chains parameter.
> 
> If the active connection chainId is not from a chain included in your Wagmi Config, useChainId will return the last configured chain ID.
> ```
> 
> So if you change the chain to the one that is not specified in wagmi config, then it will fall back to the first chain in chains array. Can't say if this constitutes a bug, but it's definitely something that should be improved. Perhaps it should return null or undefined instead of falling back to configured chain

Unfortunately i don't think it's that simple, `useChainId()` has put me in trouble before by returning 1 in different cases that ended up with my application crashing really badly.

I tried to reproduce it here, on my [updated example](https://stackblitz.com/edit/new-wagmi-qem9ah?file=src%2Fwagmi.ts) ( which now includes optimism and arbitrum as part of the config ).

# useChainId() is returning 1 even before i connect my wallet and while my wallet is connected to ARB.

<img width="605" alt="image" src="https://github.com/user-attachments/assets/b6c328be-2943-4d63-bf72-e35ec79f56d9">

# useChainId() is returnin 1 after i connect MetaMask using Arbitrum, even though arbitrum is part of the config:

<img width="1529" alt="image" src="https://github.com/user-attachments/assets/559f4e1f-d247-4c64-b7e9-eaa987d892fe">

# after connecting with OP and changing to ARB useChainId and account chainId are getting stuck

 - this one is new for me, it wasn't happening before

<img width="1448" alt="image" src="https://github.com/user-attachments/assets/2922df4f-c89d-442d-ac3d-2503195050a3">




MetaMask: i assume latest version
OSX 14.4
Chrome: 128

**Comment by Yuripetusko** [comment]
I never use this hook, always use chainId from `useAccount()`. IMO useChain and useChainId should mostly be used if you need to get configured chains

**Comment by Yuripetusko** [comment]
Would love for wevm team to chime in, but IMO it's not a bug, but more like a badly explained / communicated functionality. Perhaps renaming this hook to `getConfigChainId` or something like that would be clearer. I got caught with this one too, since then I just simply never use this hook as it's too easy to forget it's caveats

**Comment by 0x33dm** [comment]
> Would love for wevm team to chime in, but IMO it's not a bug, but more like a badly explained / communicated functionality. Perhaps renaming this hook to `getConfigChainId` or something like that would be clearer. I got caught with this one too, since then I just simply never use this hook as it's too easy to forget it's caveats

yeah i'll do that from now on. still i think my test displayed a bug, i connected on OP, OP is on the config and it still returns ethereum mainnet.

<img width="702" alt="image" src="https://github.com/user-attachments/assets/8fae8102-395c-4826-b580-85802575b45c">

**Comment by tmm** [comment]
Your [updated example](https://stackblitz.com/edit/new-wagmi-qem9ah?file=src%2Fwagmi.ts%3AL7) does not include `optimism` and `arbitrum` in `chains`, which is why `useChainId` never updates to `optimism` or `arbitrum`.

```diff
export const config = createConfig({
- chains: [mainnet, sepolia],
+ chains: [mainnet, sepolia, optimism, arbitrum],
  connectors: [
    injected(),
    coinbaseWallet({ appName: 'Create Wagmi' }),
    walletConnect({ projectId: import.meta.env.VITE_WC_PROJECT_ID }),
  ],
  transports: {
    [mainnet.id]: http(),
    [sepolia.id]: http(),
    [optimism.id]: http(),
    [arbitrum.id]: http(),
  },
});
```

**Comment by 0x33dm** [comment]
> Your [updated example](https://stackblitz.com/edit/new-wagmi-qem9ah?file=src%2Fwagmi.ts%3AL7) does not include `optimism` and `arbitrum` in `chains`, which is why `useChainId` never updates to `optimism` or `arbitrum`.
> 
> ```diff
> export const config = createConfig({
> - chains: [mainnet, sepolia],
> + chains: [mainnet, sepolia, optimism, arbitrum],
>   connectors: [
>     injected(),
>     coinbaseWallet({ appName: 'Create Wagmi' }),
>     walletConnect({ projectId: import.meta.env.VITE_WC_PROJECT_ID }),
>   ],
>   transports: {
>     [mainnet.id]: http(),
>     [sepolia.id]: http(),
>     [optimism.id]: http(),
>     [arbitrum.id]: http(),
>   },
> });
> ```

My bad, I just mistakenly added to transports only, it's [now updated](https://stackblitz.com/edit/new-wagmi-qem9ah?file=src%2Fwagmi.ts)

--

Anyhow, there is either a bug here or the docs needs to be updated accordingly.

## The docs don't explicity say it's going to return 1 even if you're not connected
 
<img width="337" alt="image" src="https://github.com/user-attachments/assets/cd934c9c-3476-4307-9817-c12255c5bd20">

## It probably should not return 1 if you're not connected to website

It shouldn't return 1 if it's not connected to 1, I'm sure i been caught on this one before and only now i realise this was the real reason why the application was getting lost, i was getting 1 for chainID even when the user was not connected to the website

## This info block should be at the very top of the docs, not at the end?

 - Perhaps should explain as well that it will return 1 even if the user is not connected

<img width="730" alt="image" src="https://github.com/user-attachments/assets/0050d506-f0b9-485e-a503-4a65d6cede77">

## Use for useChainId isn't really clear

 What's the use for `useChainId` ? If you use it to get the current chain and it's not related to the user's wallet? Shouldn't it be deprecated?

## after connecting with OP and changing to ARB useChainId and account chainId are getting stuck

This was reported on the initial issue, still happens to be on stackblitz

**Comment by tmm** [comment]
> The docs don't explicity say it's going to return 1 even if you're not connected

When not connected, `config.state.chainId` defaults to the first chain you passed to `createConfig` (unless there is a value in storage). This is `1` if `mainnet` is first, but could be any other chain ID. There's a note under [`createConfig#chainId`](http://wagmi.sh/react/api/createConfig#chainid).

> It probably should not return 1 if you're not connected to website

The reason a chain ID is returned when you are disconnected is because you can still perform read actions or [`switchChain`](http://wagmi.sh/react/api/hooks/useSwitchChain) when disconnected.

> This info block should be at the very top of the docs, not at the end?

Leaving where it is as it's best in-context with the return type IMO.

> Use for useChainId isn't really clear

`useChainId` is a reactive version of `config.state.chainId`, similar to how `useConnections` is a reactive version of `config.state.connections`. It's used a lot internally and for those building hooks downstream.

> after connecting with OP and changing to ARB useChainId and account chainId are getting stuck

Looks fine to me.

https://github.com/user-attachments/assets/4cf4fc3b-6fc3-41eb-8af7-04931c65f683
