### ISSUE TITLE
useWriteContract() not showing transfer Amount - USDT BEP20 (walletconnect - trustwallet)

### ISSUE THREAD

**Issue by solaris-rig** [wevm/wagmi#4270]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I create smart contract call as per following:
import { useWriteContract } from "wagmi";

const { writeContractAsync } = useWriteContract();

const data = await writeContractAsync({
address: '0x55d398326f99059fF775485246999027B3197955', // USDT Contract Address
functionName: 'transfer',
abi: abis,
args: [
toAddress,
txAmount ,
],
})

Tested on trustwallet mobile

result photo

![WhatsApp Image 2024-09-13 at 02 54 51_22276cd3](https://github.com/user-attachments/assets/6360fb0b-c636-42ab-b74e-82baa633270e)

when clicked confirm, it send correct USDT amount,
Please help figure out how to make the wallet show USDT Amount

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.8

### Viem Version

2.21.4

### TypeScript Version

5.0.4

**Comment by jxom** [comment]
You will need to get in touch with Trust Wallet as to why they are not displaying that.
