### ISSUE TITLE
Expected 0 arguments, but got 1 when createConfig

### ISSUE THREAD

**Issue by phamhongphuc1999** [wevm/wagmi#4272]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I installed wagmi for my personal project, and everything was seemingly ok while coding but when I tried to build my project, I encountered the problem below:
<img width="535" alt="Screenshot 2024-09-13 at 20 17 28" src="https://github.com/user-attachments/assets/2986674f-f512-46dd-867f-eb424460db65">

I absolutely had no idea about this problem. Below I list some my project configs

```js
"@tanstack/react-query": "^5.56.2",
"viem": "2.x",
"wagmi": "^2.8.1",
```

```js
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import {
  createConfig,
  CreateConnectorFn,
  http,
  useAccount,
  useConnect,
  useDisconnect,
  useSwitchChain,
WagmiProvider
} from 'wagmi';
import { bsc, bscTestnet } from 'wagmi/chains';

const queryClient = new QueryClient();

const wagmiConfig = createConfig({
  chains: [bsc, bscTestnet],
  connectors: [connectorFns.metamask, connectorFns.coinbase],
  transports: { [bsc.id]: http(), [bscTestnet.id]: http() },
});

return <WagmiProvider config={wagmiConfig}>
     <QueryClientProvider client={queryClient}>
 {children}
</QueryClientProvider>
</WagmiProvider>
```

### Link to Minimal Reproducible Example

https://github.com/phamhongphuc1999/web-practice

### Steps To Reproduce

Simply run `yarn install` and `yarn build`.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

^2.8.1

### Viem Version

2.x

### TypeScript Version

^4.6.3

**Comment by tmm** [comment]
Wagmi requires TypeScript >=5.0.4.

https://wagmi.sh/react/typescript

**Comment by phamhongphuc1999** [comment]
> Wagmi requires TypeScript >=5.0.4.
> 
> https://wagmi.sh/react/typescript

It works, seemingly my project is too old.

**Comment by pellyadolfo** [comment]
This can be also the vscode version if you are using it, despite your project has version higher tha  5.0.4.

**Comment by phamhongphuc1999** [comment]
> This can be also the vscode version if you are using it, despite your project has version higher tha 5.0.4.

yes, I update typescript version up to 5.0.4 and it works, my project is too old and I forgot to update some critical dependencies.
