### ISSUE TITLE
Bug in useBalance

### ISSUE THREAD

**Issue by DFINEX** [wevm/wagmi#4274]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Hello, with a standard call useBalance. 

![carbon](https://github.com/user-attachments/assets/26961536-f9ff-4833-af3e-c1d3585e6134)

I get this error ![Screen](https://github.com/user-attachments/assets/70096d30-e2cf-44a5-a6ff-6ac6acdccf6f)

### Steps To Reproduce

`<script lang='ts' setup>
  
  	import { useAccount, useBalance } from '@wagmi/vue'
  
  	const { address } = useAccount()
  
  	const token = computed(() => '0x2Ec1c429385Bd6175A8758012A43B2eB211710C4')

	const { data, isLoading } = useBalance({ address, token })

</script>

<template>

	<p v-if="!isLoading" class="font-bold text-2xl tracking-more-wider">
        {{ data?.formatted }} {{ data?.symbol }}
    </p>

</template`

### What Wagmi package(s) are you using?

@wagmi/vue

### Wagmi Package(s) Version(s)

0.0.40

### Viem Version

2.21.1

### TypeScript Version

5.5.4

### Anything else?

using:
@wagmi/vue: 0.0.40
@wagmi/core: ^2.13.4

**Comment by jxom** [comment]
Please upgrade `@tanstack/react-query`.
