### ISSUE TITLE
Passing an empty array in useReadContracts will never resolve and isSuccess will be false

### ISSUE THREAD

**Issue by ThanosDi** [wevm/wagmi#4281]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I dynamically create the array needed to pass to `useReadContracts` function which sometimes this array will be empty. When this is the case data will be `undefined` and `isSuccess` will be `false`.

For example:
```ts
  const { data, isSuccess } = useReadContracts({
    contracts: possiblyEmptyIdsArray..map((id) => ({
      address:  '0x00',
      functionName: 'functionName',
      abi: Abi,
      args: [id]
    }))
  });
  // {data: undefined, isSuccess: false}
```

Since this is a React hook I can't call it conditionally and this creates issues.

I would expect the `isSuccess` to be true and `data` to be an empty array.

Right now I handle it like this
```ts
  const { data = [], isSuccess } = useReadContracts({
    contracts: possiblyEmptyIdsArray.map((id) => ({
      address:  '0x00',
      functionName: 'functionName',
      abi,
      args: [id]
    })),
    query: {
      enabled: Boolean(possiblyEmptyIdsArray.length > 0),
    },
  });

  // If possiblyEmptyIdsArray is empty, successfully return
  return { data, isSuccess: possiblyEmptyIdsArray.length === 0 || isSuccess };
``` 
but it would be great for this to be handled internally.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-crw69j?file=src%2FApp.tsx

### Steps To Reproduce

```ts
const { data, isSuccess } = useReadContracts({
    contracts: [],
    query: {
      enabled: true,
    },
  });
  console.log({ data, isSuccess });
```

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.10.9

### Viem Version

2.16.5

### TypeScript Version

5.5.3

### Anything else?

The framework is React version 18.3.1

**Comment by tmm** [comment]
This is the expected behavior since it's not making any requests as an empty array does not have the required values (`address`, `abi`, `functionName`) even if `enabled` is set to `true`.

https://github.com/wevm/wagmi/blob/main/packages/react/src/hooks/useReadContracts.ts#L72-L82

Also, `isSuccess` (or `status === 'success'`) means the query was successful and data is available.
