### ISSUE TITLE
Switch between connected accounts/ addresses

### ISSUE THREAD

**Issue by abhiseanetwork** [wevm/wagmi#4282]
### What is the type of issue?

Documentation is missing

### What is the issue?

How to switch in between connected accounts/ addresses from through switch account in the same connector?

### Where did you find it?

https://wagmi.sh/core/api/actions/switchAccount#switchaccount

**Comment by tmm** [comment]
There isn't a way to switch between addresses for the current account unfortunately as there isn't a standardized API for this.
