### ISSUE TITLE
bug: metamask connector on mobile cannot open page because address is invalid

### ISSUE THREAD

**Issue by ques122** [wevm/wagmi#4292]
### Check existing issues

- [x] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Currently, I’m encountering an error when using the MetaMask connector on mobile. It used to work fine, but recently the error started occurring.

**Condition**: MetaMask wallet is not installed on the mobile device.

**Action**: Click the button to connect to MetaMask.

**Actual**:
- On Safari, an error popup says: "Safari cannot open the page because the address is invalid."
- On Chrome, a warning appears about navigation.

**Expected**: Redirect to the MetaMask App Store.

Please check it for me, thanks!

### What Wagmi package(s) are you using?

wagmi, @wagmi/connectors

### Wagmi Package(s) Version(s)

2.12.13

### Viem Version

2.x

### TypeScript Version

^5.3.2

**Comment by Jomossey** [comment]
@ques122 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[MetamaskNetwork DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by ques122** [comment]
Hi @tmm,
I have added a minimal reproduction. Please check it for me, thanks!

**Comment by tmm** [comment]
Best to track in this upstream issue

https://github.com/MetaMask/metamask-sdk/issues/1042
