### ISSUE TITLE
 MetaMask Gas Parameters Issue with writeContractAsync

### ISSUE THREAD

**Issue by gordilovvv** [wevm/wagmi#4303]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Hi! i'm having an issue when using writeContractAsync with MetaMask. When I try to execute contract write function (like approve or transfer), the transaction fails with an “Internal JSON-RPC error”.

The general error message I see is:
**`Internal JSON-RPC error.`**

When I check MetaMask, I see more details:
**`{
  "code": -32603,
  "message": "Internal JSON-RPC error.",
  "data": {
    "code": -32000,
    "message": "transaction underpriced: tip needed 25000000000, tip permitted 1500000000",
    "cause": null
  }
}`**

I use the Polygon Amoy testnet and don’t calculate gas myself, as I know WAGMI does this automatically. So, is the error on my side or MetaMask’s side? Thanks!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-27qjgx?file=src%2FApp.tsx

### Steps To Reproduce

1. Connect Metamask
2. Connect to Polygon Amoy Chain
3. Click on Approve for all tokens

<img width="459" alt="Error response in example" src="https://github.com/user-attachments/assets/dc6afd89-ed66-4152-934e-4b60eb91bdca">

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.12

### Viem Version

2.21.9

### TypeScript Version

5.0.2

### Anything else?

React @18.2.0

**Comment by tmm** [comment]
Looks like it works fine for me and I get a MM prompt. Likely a spurious issue.

https://github.com/user-attachments/assets/3290a97c-be3f-4f9e-840e-e2a59998cb65
