### ISSUE TITLE
Can't writeContract due to this issue "ConnectorNotConnectedError: Connector not connected."

### ISSUE THREAD

**Issue by web3techlord** [wevm/wagmi#4309]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

As I was following the steps of wallet connection in documentation, I had some problems.
First of all, when I reload the webpage, wallet is not connected automatically. Exactly I think it's stored in local storage, but w3m-button is not connected and just shows "Connect Wallet" text. When I click it and metamask wallet to connect, metamask connection gives an error. 
![image](https://github.com/user-attachments/assets/f286ab60-4dca-4125-8756-1f4b980d3afa)
When I run writeContract method to sign tx, it gives another error. (I attached a screenshot)
![image](https://github.com/user-attachments/assets/4629f711-e9e5-4f9c-afa3-effafa8c28e0)
I couldn't get the problem completely. I just think it might be an issue on the versions of modules.
Thank you. I need any quick help.

### What Wagmi package(s) are you using?

wagmi, @wagmi/core

### Wagmi Package(s) Version(s)

wagmi@^2.12.16, @web3modal/wagmi@^5.1.10

### Viem Version

viem@^2.21.16

### TypeScript Version

I don't use TypeScript

### Anything else?

React jsx
`"react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.26.2",
    "react-scripts": "5.0.1",`

**Comment by redDwarf03** [comment]
@web3techlord have you find the issue ?
