### ISSUE TITLE
MetaMask connector breaks Coinbase Async Connection on iOS Safari and Android

### ISSUE THREAD

**Issue by tiagofilipenunes** [wevm/wagmi#4320]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Similar to the issue #4058 but with the async `connectAsync` method, for iOS and Android. When I remove the metamask connector, I'm able to connect again to Coinbase Wallet.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-qy2psg

### Steps To Reproduce

Edited from issue #4058 

1. Set up a blank project with the `metaMask` and `coinbaseWallet` connectors **using asyncConnect**
2. Attempt to connect with Coinbase on iOS Safari or Android
3. Error `This app doesn't support smart wallets`, with an indication to check out the COOP Policy doc on how to fix it.
4. Unable to connect after

### What Wagmi package(s) are you using?

wagmi, @wagmi/connectors

### Wagmi Package(s) Version(s)

2.12.17

### Viem Version

2.x

**Comment by tmm** [comment]
Works fine for me. Please update your Wagmi version and share a video if it doesn't work.

https://github.com/user-attachments/assets/afc99fc3-b462-4fde-b68a-6ba4fe62fdd4
