### ISSUE TITLE
BigInt serialization issue in useReadContract/useReadContracts hooks

### ISSUE THREAD

**Issue by nakedfool** [wevm/wagmi#4322]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

After updating `@tanstack/react-query` to version 5.59.0, I've encountered a critical issue with the `useReadContract` and `useReadContracts` hooks from wagmi. 

When attempting to pass a `BigInt` value as an argument to any read function, the following error occurs:
`typeerror: do not know how to serialize a bigint`

This error also leads to unexpected behaviour from hook:

1. it results in a BSOD.
2. the error appears to be a silent failure - neither a boolean nor an error object is received from the hooks and therefore a BSOD.

There is a discussion already on wagmi discord and a possible workaround for this type of issue, but i would love to see if there is a way for wagmi team to patch it so we do not need to introduce workarounds in our codebase, see discussion [here](https://discord.com/channels/1156791276818157609/1291668830875029525)

### Steps To Reproduce

1. Update  `@tanstack/react-query` to version `5.59.0`
2. Pass any `BigInt` value to the either `useReadContract` or `useReadContracts`

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.17

### Viem Version

2.21.16

**Comment by rocketman-21** [comment]
Also running into this as of today. Might be helpful @nakedfool https://github.com/wevm/wagmi/issues/3855

Here's my MRE https://github.com/wkocjan/nouns-flows/pull/25/files

**Comment by jxom** [comment]
Opened a fix: https://github.com/TanStack/query/pull/8151

**Comment by jxom** [comment]
Please upgrade to `@tanstack/react-query@5.59.3`
