### ISSUE TITLE
sendTransactionAsync from useSendTransaction() hook doesn't return a transaction hash

### ISSUE THREAD

**Issue by mohanramCypherD** [wevm/wagmi#4335]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I'm using sendTransactionAsync function from the useSendTransaction() hook to send native tokens. Here is how I use the function:

```
async function sendNativeCoin({
    transactionToBeSigned,
    chainId,
  }: {
    transactionToBeSigned: EthTransaction;
    chainId: number;
  }): Promise<TransactionResponse> {
    try {
      const response = await sendTransactionAsync({
        account: transactionToBeSigned.from as `0x${string}`, // eg: 0x1940821a0875867d32de4d6da184574cafbdc491
        to: transactionToBeSigned.to as `0x${string}`, // eg: 0x1940821a0875867d32de4d6da184574cafbdc491
        chainId: chainId, // eg: 137
        value: BigInt(transactionToBeSigned.value), // eg: 1000000000000000
        data: transactionToBeSigned?.data ?? '0x', // eg: 0x
      });
      return response;
    } catch (e) {
      console.log('error in sendNativeCoin : ', e);
      throw e;
    }
  }
 ```
  
 I'm using [Appkit](https://docs.reown.com/appkit/react-native/core/installation) modal from Reown to connect to my app using wallet connect. When this function is called the transaction actually happens successfully but the function does not return any hash. It just waits for a long time and throws this error:
 
 ```
LOG  error in sendNativeCoin :  [TransactionExecutionError: An unknown RPC error occurred.

Request Arguments:
  chain:  undefined (id: 137)
  from:   0x2860f3a9C202dbec6C74aB9cAE43DE6aeaE59E22
  to:     0x2860f3a9C202dbec6C74aB9cAE43DE6aeaE59E22
  value:  0.001 ETH
  data:   0x
  gas:    21000

Details: Request expired. Please try again.
Version: 2.21.15]

```
Earlier the same function used to return a transaction hash. I've updated the wagmi libraries to latest version, so wondering if there is any issue with the recent versions or the function parameters have changed ?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-cwm18l?file=src%2FApp.tsx

### Steps To Reproduce

I faced this problem when implementing with Appkit from Reown. 
Connect any wallet like Metamask, Trust Wallet, Safe Pal to my app. 
On sending native tokens like POL in Polygon chain resulted in this behaviour.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.17

### Viem Version

2.21.19

### TypeScript Version

5.0.4

### Anything else?

My application is build with React Native (v0.72.4). 
I faced this when connecting using wallet connect to Trust Wallet, Safe Pal.

I'm attaching a screen recording for better understanding of the issue. Here you can see that the transaction actually happens successfully, but the sendTransactionAsync doesn't return the transaction hash.

https://github.com/user-attachments/assets/b983c697-3816-46b2-98bd-a0f7a2e4d3c2

**Comment by tmm** [comment]
This test works fine https://github.com/wevm/wagmi/commit/9b40025489031a36e7784fb91caa36fd03f21f88

Happy to look into more if you can break the test or create a more minimal reproduction (just Wagmi without AppKit).
