### ISSUE TITLE
extractRPCUrls should check if a chain's transport exists

### ISSUE THREAD

**Issue by gwpjp** [wevm/wagmi#4360]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I upgraded from 2.11.3 to 2.12.0.  I have hooked up RainbowKit.  When attempting to connect through WalletConnect, I get the following error in my console `Cannot destructure property 'value' of 'undefined' as it is undefined.` and the QR Modal does not open, which means the user cannot connect via WalletConnect.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.0

### Viem Version

2.21.32

### Anything else?

Running this in a React app.

**Comment by gwpjp** [comment]
After doing some debugging, I had included a chain (goerli) in my createConfig for which I did not specify a transport.  When I removed this chain, then the error was not thrown.

**Comment by tmm** [comment]
> After doing some debugging, I had included a chain (goerli) in my createConfig for which I did not specify a transport. When I removed this chain, then the error was not thrown and the QR Modal opened as expected.

Are you using TypeScript? If so this, should be caught at compile time ([TypeScript Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYygUwIYzQYQgOwDNgBzAGjgAsYYw4BfOQqCEOAcgHcMSRh2AUKEixEcEBmD58aGBRIQ0UADbAGTFmy48+AemSVJ+AM6CByAsfgWipOAF4U6LLgLESACgQC4KQ1OMALjgAbQkpGTk4BSVVAF0yHzgYKAwTERggxCTfMKNIgDpgABM44OpaDwBKRN96AXoqoA)).

```ts
import { createConfig, http } from 'wagmi'
import { mainnet, goerli } from 'wagmi/chains'

const config = createConfig({
  chains: [mainnet, goerli],
  transports: {
    [mainnet.id]: http(),
    // Property '5' is missing in type '{ 1: HttpTransport; }' but required in type 'Record<1 | 5, Transport<string, Record<string, any>, EIP1193RequestFn>>'.(2741)
  },
})
```

**Comment by gwpjp** [comment]
I am using Typescript but it was not caught.  I had set the type of the chains array as follows:

`const chains: Chain[] = [mainnet, goerli];`

and when I passed this to createConfig, it was not flagged by Typescript for a missing transport on '5'.

However, if I do not specify the type directly, like this:

`const chains = [mainnet, goerli];`

then Typescript does flag the missing transport on '5'.

**Comment by tmm** [comment]
`const chains = [mainnet, goerli] as const` should do the trick!
