### ISSUE TITLE
Safe connector not working, throwing a `SafeAppProvider` is not a constructor error

### ISSUE THREAD

**Issue by iceanddust** [wevm/wagmi#4364]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I'm trying to open my Vite dApp as a Safe app, it works well inside the Safe wallet context, but the Safe connector will not connect. After digging for a bit and doing some debugging I found out there is a `SafeAppProvider is not a constructor` error thrown by the connector.

I see there has been similar issues fixed for other connectors before, like [this one](https://github.com/wevm/wagmi/pull/3940), so perhaps the solution for this connector is similar

### Link to Minimal Reproducible Example

https://github.com/iceanddust/wagmi-safe-connector-issue

### Steps To Reproduce

- Install packages and run dev server
- Go to https://app.safe.global/ and select (or open) a safe
- Go to the `Apps` tab, and then to `My custom apps` tab
- Click `Add custom Safe App`, and enter the URL (Should be `http://localhost:5173/` if you're running locally)
- Check the checkbox and click `Add`, then open the Safe app
- Inside the app, click on the `Safe` connector and see the error pop up, the connector will never connect

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.25

### Viem Version

2.21.34

**Comment by 1997roylee** [comment]
It seems that Vite is encountering a bug when importing the Safe Global Provider SDK

**Comment by 1997roylee** [comment]
You should try to replace the config by this:

```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  root: "src",
  envDir: "./",
  build: {
    outDir: "./dist",
  },
  plugins: [react()],
  optimizeDeps: {
    include: ["@safe-global/safe-apps-provider"],
  },
});
```

**Comment by iceanddust** [comment]
Thanks, that worked, although I had to write it like this for Vite to detect the dependency `include: ['wagmi > @safe-global/safe-apps-provider']`. I faced a couple more of the known Safe connector issues, but was able to fix/bypass them
