### ISSUE TITLE
autoConnect

### ISSUE THREAD

**Issue by hesiyuetian** [wevm/wagmi#4368]
### What is the issue?

The wagim autoConnect configuration has been removed. How can I configure it to disable the wallet from automatically connecting?

### Where did you find it?

The wagim autoConnect configuration has been removed. How can I configure it to disable the wallet from automatically connecting?

**Comment by duongquocphu** [comment]
you can try this https://wagmi.sh/react/api/WagmiProvider#reconnectonmount
