### ISSUE TITLE
Throw error when call signMessage method

### ISSUE THREAD

**Issue by qiaoqiaoziii** [wevm/wagmi#4374]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### What I am doing:
After connecting to the wallet, I did not close the browser tab page. 
Two days later, when I checked the returns from `useAccount` hook, I found that `status` returned `reconnecting` and `isConnected` returned `true`, and `useConnections` hook returned `[]`. 
Then I called the signMessage method: `signMessage(config, {message})`.
### What I expected:
The signMessage method can be called normally.
### What is actually happening:
I get an error, `r.connector.getChainId is not a function`

### Steps To Reproduce

```
import { signMessage } from '@wagmi/core';
import { useConfig } from 'wagmi';

const config = useConfig();

const request = async () => {
    const message = 'message';
    const signature = await signMessage(config, { message });
}
```

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.12

### Viem Version

2.21.12

### TypeScript Version

5.0.4

### Anything else?

The connected wallet is okx wallet

**Comment by 1997roylee** [comment]
Could you provide a minimal reproducible, I cant reproduce your issue.
