### ISSUE TITLE
WalletConnect Ethereum network estimate gas function not working

### ISSUE THREAD

**Issue by timongll** [wevm/wagmi#4379]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I am trying to estimate the gas required for a contract call. So I do 

```
      const estGas = await contract.estimateGas.function()
```

this only fails on WalletConnect Ethereum

the error is:
```
{
    "error": {
        "reason": "insufficient funds for intrinsic transaction cost",
        "code": "INSUFFICIENT_FUNDS",
        "error": {
            "code": -32000,
            "message": "insufficient funds for gas * price + value: address someAddress have 0 want 100000000000000"
        },
        "method": "estimateGas",
        "transaction": {
            "from": "someAddress",
            "to": "someAddress",
            "value": {
                "type": "BigNumber",
                "hex": "someNumber"
            },
            "data": someData,
            "accessList": null
        }
    }
}
```

### Steps To Reproduce

use wagmi createConfig with mainnet, then try to estimategas for a certain contract call on Ethereum WalletConnect

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.9.3

### Viem Version

^2.17.3

### TypeScript Version

^4.6.3

**Comment by tmm** [comment]
This is an [Ethers.js error](https://github.com/search?q=repo%3Aethers-io%2Fethers.js+INSUFFICIENT_FUNDS&type=code). Better to ask on the [Ethers.js repo](https://github.com/ethers-io/ethers.js).

**Comment by timongll** [comment]
@tmm this issue is only after i start using wagmi though? Its fine on arbitrum. Its the fact that it uses the default cloudflare.eth as the rpc url. Could you help check this?

**Comment by tmm** [comment]
Can't help unless you provide a clear minimal reproduction.
