### ISSUE TITLE
After reload page, the chainId is different from the one in the Metamask.

### ISSUE THREAD

**Issue by AliceW-03** [wevm/wagmi#4382]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

When I connect metamask in my telegram webapp, switch chains, and then reload the page, the chainId is different from the one in the wallet.

I noticed that metamask store a .MMSDK_cached_chainId in the localStorage to persist the chain info. After switching chains, this field retains the old chainId. When the page is reloaded, the retrieved chainId becomes the old value, even though the wallet has already switched to the new chain.

I tried the demo provided by metamask-sdk and found that this issue doesn’t occur there. So, I think the callback that updates the .MMSDK_cached_chainId after switching chains may not be executing, or it might have been overridden.

### Link to Minimal Reproducible Example

https://metamask-cache-chain-id.vercel.app/

### Steps To Reproduce

I deployed a reproduction in my test [bot.](https://t.me/WYFTEST_bot) You can enter the bot and type /metamask.

1. connect wallet
2. switch chain
3. reload in the top right corner.
4. check localStorage

### What Wagmi package(s) are you using?

wagmi, @wagmi/connectors

### Wagmi Package(s) Version(s)

2.12.25

### Viem Version

2.21.37

### TypeScript Version

5.5.3

**Comment by tmm** [comment]
Worth raising on the MetaMask SDK directly
https://github.com/MetaMask/metamask-sdk

**Comment by AliceW-03** [comment]
@tmm Please read my description carefully first.

**Comment by AliceW-03** [comment]
I tried using metamask-sdk directly instead of connecting through wagmi, and the issue does not occur.
