### ISSUE TITLE
http is in vien, not wagni

### ISSUE THREAD

**Issue by oehm-smith** [wevm/wagmi#4393]
### What is the issue?

Howdy, I'm writing a react app and the doco says to use `http` from `wagni`. However it doesn't exist there and instead I found (what I believe is correct) in `viem` (but what happens if using `ethers` instead)?.  My updated code is:

```
import { createConfig } from 'wagmi'
import { mainnet, sepolia, bsc } from 'wagmi/chains'
import {http} from "viem";

export const config = createConfig({
  chains: [mainnet, sepolia, bsc],
  transports: {
    [mainnet.id]: http(),
    [sepolia.id]: http(),
    [bsc.id]: http(rpcURL),
    ...
```

![doco currently says](https://github.com/user-attachments/assets/90daaf5f-7d77-4835-a0bc-6b19ab329f87)

Also I wonder about the `injected` connector statement - is that true as I can't see that used?  Maybe its implicit but if so that should be highlighted.

Otherwise, thanks for your project!

### Where did you find it?

https://wagmi.sh/react/getting-started

**Comment by tmm** [comment]
It's re-exported

https://github.com/wevm/wagmi/blob/main/packages/react/src/exports/index.ts#L434

**Comment by oehm-smith** [comment]
My bad.  I picked up someone's project to work on, installed wagmi and started coding.  What i didn't realise was that they had already installed it (at an old version) and my installation didn't change to the latest version.  Hence I was looking at old code.  Please close this.
