### ISSUE TITLE
Bug: Can't import the named export 'hashForSignTypedDataLegacy' (imported as 'eip712') from default-exporting module

### ISSUE THREAD

**Issue by shayesteMalekpour** [wevm/wagmi#4395]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

when i start building my project its failed due to 
Bug: Can't import the named export 'hashForSignTypedDataLegacy' (imported as 'eip712') from default-exporting module

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.9.2

### Viem Version

2.19.8

**Comment by voroncv** [comment]
```
"resolutions": {
  "@coinbase/wallet-sdk": "4.0.4"
},
  ```
