### ISSUE TITLE
Filter out duplicate EIP-6963 providers does not filter out Metamask Mobile

### ISSUE THREAD

**Issue by tiagofilipenunes** [wevm/wagmi#4404]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

This is a follow-up issue to the functionality introduced in PR #4343 (thank you @tmm!). 

Metamask Mobile uses the `io.metamask.mobile` rdns. This means that using wagmi via the metamask browser on mobile with multiInjectedProviderDiscovery and the metamask connector initialized will still result in duplicated Metamask connectors.

### Link to Minimal Reproducible Example

https://wagmi-tests-2.vercel.app/

### Steps To Reproduce

1. Open Metamask Mobile on iOS or Android
2. Open https://wagmi-tests-2.vercel.app/
3. Two metamask connectors show up instead of one, because the `io.metamask.mobile` rdns is not filtered.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.12.31

### Viem Version

2.21.45

### TypeScript Version

5.3.3

### Anything else?

Can find the code for the reproducible example here: https://stackblitz.com/edit/new-wagmi-pddqi8

**Comment by tmm** [comment]
Nice find! If someone wants to work on this, all they need to do is [add `readonly string[]` to `rdns`](https://github.com/wevm/wagmi/blob/main/packages/core/src/connectors/createConnector.ts#L40) and update a few places in [`createConfig.ts`](https://github.com/wevm/wagmi/blob/main/packages/core/src/createConfig.ts) and [`hydrate.ts`](https://github.com/wevm/wagmi/blob/main/packages/core/src/hydrate.ts) (follow the type errors).

**Comment by tiagofilipenunes** [comment]
Thank you for the quick turnaround @starc007 and @tmm !
