### ISSUE TITLE
Wagmi doesn't support erc20-like functions in a case of USDT on ETH Mainnet

### ISSUE THREAD

**Issue by Georgyskr** [wevm/wagmi#4423]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Hi!
As mentioned in issues #3450 #3321 #3281 #2749 and #2419
USDT isn't ERC20 compatible and hence erc20abi provided by viem - can't be used. 
As mentioned in the #3450 a simple update of an ABI is sufficient to make it through. 
I am making this issue to raise awareness once again, since those issues were closed without a review. But as this must be quite a regular issue for developers, since USDT and Ethereum networks are one of the most liquid tokens/network in there, I think this should be handled by wagmi one way or another.

It's not my place to give an advice on how to fix it, but I will add a hook written before and after fix.
I believe a simple explanation in wagmi docs + an export of USDT-abi should suffice.

### Steps To Reproduce

In the snippet below - I am using a self-imported abi provided in an issue #3450 in case it's a USDT address used.
If you simply use erc20Abi exported from "viem" it will break with 
ContractFunctionExecutionError: The contract function "transfer" returned no data ("0x").

```
import { useQueryClient } from "@tanstack/react-query";
import { USDTAbi } from "modules/hooks/useERC20Approve/USDTAbi";
import { scopeKeyPredicate } from "modules/shared/api/scopeKeyPredicate";
import { useEffect } from "react";
import { Address, erc20Abi } from "viem";
import { useWaitForTransactionReceipt, useWriteContract } from "wagmi";

type ApproveArgs = {
  tokenAddress: Address;
  spender: Address;
  amount: bigint;
};

export const useERC20Approve = () => {
  const queryClient = useQueryClient();
  const { writeContract, writeContractAsync, data, ...restWrite } =
    useWriteContract();
  const { data: receipt, ...restWait } = useWaitForTransactionReceipt({
    hash: data,
  });

  useEffect(() => {
    if (receipt) {
      queryClient.invalidateQueries({
        predicate: scopeKeyPredicate(["allowance"]),
      });
    }
  }, [receipt, queryClient]);

  const approve =
    <T extends typeof writeContract | typeof writeContractAsync>(
      approveFn: T
    ) =>
    ({ tokenAddress, spender, amount }: ApproveArgs): ReturnType<T> => {
      return approveFn({
        abi:
          tokenAddress.toLowerCase() ===
          "0xdac17f958d2ee523a2206206994597c13d831ec7"
            ? USDTAbi
            : erc20Abi,
        address: tokenAddress,
        functionName: "approve",
        args: [spender, amount],
      }) as ReturnType<T>;
    };

  return {
    receipt,
    approve: approve(writeContract),
    approveAsync: approve(writeContractAsync),
    state: restWrite,
    receiptState: restWait,
  };
};
```

### What Wagmi package(s) are you using?

wagmi, @wagmi/connectors, @wagmi/core

### Wagmi Package(s) Version(s)

2.12.26

### Viem Version

2.x

### TypeScript Version

^5.6.3

### Anything else?

React, Next.ts

**Comment by tmm** [comment]
USDT doesn't follow the ERC-20 ABI unfortunately. One of the first things to check when debugging is if the ABI works for the contract you are trying to call.
