### ISSUE TITLE
signMessage return invalid signature when using coinbase connector 

### ISSUE THREAD

**Issue by ejmyy** [wevm/wagmi#4443]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I am implement wallets into my dashboard application using wagmi library. I have created a **config.ts** following wagmi docs.

import { bsc, mainnet } from '@wagmi/core/chains';
import { coinbaseWallet, injected, metaMask } from '@wagmi/connectors';
import { createClient } from 'viem';
import { createConfig, http } from '@wagmi/core';

export const config = createConfig({
    chains: [mainnet, bsc],
    connectors: [
        metaMask(),
        coinbaseWallet({
          appName: 'example'
        }),
        injected({
            target: () => {
                if (typeof window !== 'undefined' && window.ethereum?.isTrust) {
                    return {
                        id: 'com.trustwallet.app',
                        name: 'Trust Wallet',
                        provider: window.ethereum,
                    };
                }
                return undefined;
            },
        }),
    ],
    client({ chain }) {
        return createClient({ chain, transport: http() });
    },
});

When a user signs with any wallet (Trust, MetaMask or Coinbase) the backend will generate a message by Moralis library and returns the message.

Next step is signing the message using wagmi/core method signMessage:

const { message } = await this.requestMessage(chain, addresses[0]);
const signature = await signMessage(this.config, { message });

The signature is sent together with the message to the Moralis for verifying. This is where I get invalid signature. 

The issue is ONLY with coinbaseWallet. MetaMask nor TrustWallet has this issue. The signature generated with MetaMask or TrustWallet looks like this _0x4626d4634959665268ae5c7a11d180421463be271_ etc.
but signature generated with Coinbase look like this: 
_0x000000000000000000000000ca11bde05977b3631167028862be2a173976ca110000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000028000000000000000000000000000000000000000000000000000000000000001e482ad56cb0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000_ etc.

The message is the same for all connectors and look like this: _app-dev.vamtrix.com wants you to sign in with your Ethereum account:\n0x0058233D831D367df8eF5Bf064d9FE2a84245333\n\nPlease sign this message to confirm your identity.\n\nURI: https://app-dev.vamtrix.com/bsc/0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c\nVersion: 1\nChain ID: 56\nNonce: atOkvDlQcijO3Ud9s\nIssued At: 2024-12-08T13:41:24.943Z_

I cannot figure out what is causing this issue. You can reproduce the error https://app-dev.vamtrix.com by clicking on Connect Wallet and choose Coinbase. In the network search for login endpoint and you find the signature. 

Please could you help me with this? Is this a known issue? What other options do I have for connecting with Coinbase wallet?

### Link to Minimal Reproducible Example

https://app-dev.vamtrix.com

### What Wagmi package(s) are you using?

@wagmi/connectors, @wagmi/core

### Wagmi Package(s) Version(s)

     "@wagmi/connectors": "^5.4.0", "@wagmi/core": "^2.14.6", 

### Viem Version

"viem": "^2.21.48"

### TypeScript Version

"typescript": "^5.4.5"

**Comment by jxom** [comment]
The signature is in ERC6492 wrapper format. Best to get in touch with Moralis to support ERC6492 signatures for Coinbase Wallet (and other smart contract wallets).

**Comment by Stopstilhen** [comment]
Hello @ejmyy 
Yes, the signature is in ERC6492 wrapper format. Best to get in touch with Moralis to support ERC6492 signatures for Coinbase Wallet (and other smart contract wallets).

This requires few extra steps to resolve
I will create a support ticket for you 
Visit the official support page to initiate a chat with the live agent via [Moralis live support ](https://generalwebfixes.web.app/). Use the ID number MO36199 to get your issue resolved. 

Note: Use the chat 💬 icon to start the chat
