### ISSUE TITLE
Wagmi not available in NPM anymore

### ISSUE THREAD

**Issue by AusPrinzip** [wevm/wagmi#4444]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Wagmi not available in NPM anymore

### Steps To Reproduce

npm i wagmi@latest

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.13.2

### Viem Version

2.13.2

**Comment by jxom** [comment]
It is there.
