### ISSUE TITLE
useSendTransaction hook does not work in trust wallet of the mobile. 

### ISSUE THREAD

**Issue by toptalhook** [wevm/wagmi#4446]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I used the useSendTransaction hook to send the money from my-wallet to another wallet in my myproject.
but it only wroks in the metamask and doesnot work in the mobile trust-wallet.
how can I solve this problem?

### Link to Minimal Reproducible Example

https://air-hop.click/

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.13.4

### Viem Version

2.21.54

### TypeScript Version

5.6.2

### Anything else?

vite

**Comment by tmm** [comment]
Likely a Trust Wallet issue.
