### ISSUE TITLE
RPC URL for BSC Not Listed in Official BscScan Documentation

### ISSUE THREAD

**Issue by kr-keshav-kk** [wevm/wagmi#4464]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

this is the official rpc list for bsc:
Mainnet BSC RPC Nodes ( ChainID: 56 )
https://bsc-dataseed1.binance.org/
https://bsc-dataseed2.binance.org/
https://bsc-dataseed3.binance.org/
https://bsc-dataseed4.binance.org/
https://bsc-dataseed1.defibit.io/
https://bsc-dataseed2.defibit.io/
https://bsc-dataseed3.defibit.io/
https://bsc-dataseed4.defibit.io/
https://bsc-dataseed1.ninicoin.io/
https://bsc-dataseed2.ninicoin.io/
https://bsc-dataseed3.ninicoin.io/
https://bsc-dataseed4.ninicoin.io/

But the rpc that wagmi initiates is : 
https://rpc.ankr.com/bsc

This mismatch creates  a warning in metamask:
![image](https://github.com/user-attachments/assets/24f73b23-7c14-44ad-92a0-f3e107402790)

### Link to Minimal Reproducible Example

just remove bsc from metamask and try to add through wagmi, you will get the warning

### What Wagmi package(s) are you using?

@wagmi/connectors, @wagmi/core

### Wagmi Package(s) Version(s)

"@wagmi/connectors": "^5.5.3", "@wagmi/core": "^2.15.2",

### Viem Version

"viem": "^2.21.53"

### TypeScript Version

"typescript": "^5.7.2",

**Comment by S-Brenda** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take immediate action and resolve this.

Please write to us using the “Chat Support” icon located on the [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!

**Comment by tmm** [comment]
Feel free to update

https://github.com/wevm/viem/blob/main/src/chains/definitions/bsc.ts#L12
