### ISSUE TITLE
Docs say useReadContracts but should be useReadContract

### ISSUE THREAD

**Issue by poplexity** [wevm/wagmi#4470]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

Docs say useReadContracts but should be useReadContract

### Where did you find it?

https://wagmi.sh/react/api/hooks/useReadContracts
https://github.com/wevm/wagmi/blob/568c905b0f49c6a510b72310601fcf5ca7f37d3b/playgrounds/vite-vue/src/components/ReadContract.vue#L2

**Comment by poplexity** [comment]
Also, to be clear, I see that there is a `useReadContract` in the docs as well, but for me `useReadContracts` doesn't exist on `"@wagmi/vue": "^0.1.3"`

**Comment by tmm** [comment]
`useReadContracts` isn't implemented yet for `@wagmi/vue`
