### ISSUE TITLE
bug: storage.removeItem is not a function

### ISSUE THREAD

**Issue by minionlancer28** [wevm/wagmi#4475]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Dear wagmi team.
When to connect wallet in next.js project, there is issue "TypeError: storage.removeItem is not a function"

I tried like this.
> npm init @rainbow-me/rainbowkit@latest
> npm run dev
Visit browser (http://localhost:3000) and click connect button with metamask wallet.
In that case, there is issue as the follows.

Unhandled Runtime Error
TypeError: storage.removeItem is not a function

Call Stack
Object.removeItem
webpack-internal:\node_modules\@wagmi\core\dist\esm\createStorage.js (28:1)
Object.onAccountsChanged
webpack-internal:\node_modules\@wagmi\core\dist\esm\connectors\injected.js (387:1)

how to fix it?   it is wagmi bug, isn't it?

### What Wagmi package(s) are you using?

wagmi, @wagmi/core

### Wagmi Package(s) Version(s)

2.16.1

### Viem Version

2.17.0

### TypeScript Version

5.5.2

**Comment by kritik-sah** [comment]
Got the Same error TypeError: storage.removeItem is not a function

**Comment by sinolopes** [comment]
Same problem for me, probably due to using next js 15,I tried to use cookie storage but it no longer works with headers()).get("cookie")

**Comment by pr15il** [comment]
this happened in the latest release (wagmi@2.14.4). in the previous release (wagmi@2.14.3) there was no problem

**Comment by minionlancer28** [comment]
Fixed with wagmi@"2.10.2"

**Comment by pr15il** [comment]
@kritik-sah bro why not use "wagmi": "2.14.3"?

**Comment by minionlancer28** [comment]
Running with "2.14.3" ,too.
Thank you.

**Comment by lyfmantle** [comment]
same issue with `2.14.4`, no problem with `2.14.3`

**Comment by chervyachok** [comment]
I'm using @wagmi/vue and faced same issue. Any suggestions how to fix it?

**Comment by dzek69** [comment]
@chervyachok downgrade or wait for next release
