### ISSUE TITLE
bug: header and localStorage: SSR Next >15

### ISSUE THREAD

**Issue by sinolopes** [wevm/wagmi#4477]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

#### Description  

When using Next.js 15 (or later) with `wagmi`, several errors occur due to changes in the cookie management system and the runtime environment. The observed issues are as follows:  

**Error with `headers()` not being awaited**  
   An error is thrown when attempting to use `headers().get("cookie")` in the `RootLayout` component:  
   ```plaintext
   Error: Route "/login" used `headers().get('cookie')`. `headers()` should be awaited before using its value.
   Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
       at RootLayout (src/app/layout.tsx:42:14)
     40 |   const initialState = cookieToInitialState(
     41 |     getConfig(),
   > 42 |     headers().get("cookie")
        |              ^
     43 |   );
     44 |
     45 |   return (
   ```

**Error with `localStorage` in non-SSR-compatible environments**  
   Another error is encountered due to the absence of `localStorage` in the server environment:  
   ```plaintext
   [StorageManagerWeb: getPersistedChannelConfig()] Can't find existing channel config ReferenceError: localStorage is not defined
       at Generator.next (<anonymous>)
       at new Promise (<anonymous>)
       at Generator.next (<anonymous>)
       at new Promise (<anonymous>)
       at Generator.next (<anonymous>)
       at new Promise (<anonymous>)
       at Generator.next (<anonymous>)
   [initializeMobileProvider] failed to get cached addresses: ReferenceError: localStorage is not defined
   [StorageManagerWeb: getCachedChainId()] Error reading cached chainId ReferenceError: localStorage is not defined
   ```

#### Context  

The issue appears to stem from changes in Next.js 15 related to dynamic API management, particularly with `headers()`, as well as `wagmi`'s reliance on client-side APIs such as `localStorage` and `window`.  

### Link to Minimal Reproducible Example

(https://github.com/sinolopes/storage-issue)

### Steps To Reproduce

1. Create a project with Next.js 15 or later.  
2. Install and configure `wagmi` for Web3 connections.  
3. Implement a feature that accesses cookies using `headers()` in a route.  
4. Observe the errors during execution.  

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

wagmi@2.14.4

### Viem Version

viem@2.21.57

### TypeScript Version

typescript@5.7.2

**Comment by sinolopes** [comment]
The localStorage error comes from the metamask connector.

Temporary fix for header: const initialState = cookieToInitialState(
    getConfig(),
    (await headers()).get("cookie")
  );

**Comment by healyxiang** [comment]
I downgrade wagmi version to 2.13.0, then localStorage error  seems to dissappeared.

**Comment by jxom** [comment]
the only change needed is to update the docs:

```diff
-headers().get("cookie")
+(await headers()).get("cookie")
```

ill let someone PR this ;)

**Comment by sinolopes** [comment]
I don't know if it's a problem that the layout is asynchronous. The error with the local storage of the metamask connector explained above is perhaps due to this. If this is not the case and using the asynchronous header does not create a problem, I will make a pull request with the update of the documentation and the next template and I will reopen a dedicated issue for the problem with the metamask connector/SDK

**Comment by jxom** [comment]
If there is an issue with MetaMask SDK, please raise it on their repo: https://github.com/MetaMask/metamask-sdk
