### ISSUE TITLE
get error 'Illegal invocation' when connect wallet

### ISSUE THREAD

**Issue by RodeRickIsWatching** [wevm/wagmi#4479]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

Hi, I'm using RainbowKit to connect my wallet, and it has been working fine until yesterday when I encountered connection issues. According to [#4475 ](https://github.com/wevm/wagmi/issues/4475), I tried downgrading the version. 

Today, I noticed that you have updated the storage, so I attempted to upgrade again, but the problem persists. I also tried using reown to connect, but encountered the same error: Illegal invocation.

![image](https://github.com/user-attachments/assets/242d5f73-591b-48a9-9193-532ace1a892c)

### What Wagmi package(s) are you using?

wagmi, @wagmi/connectors, @wagmi/core

### Wagmi Package(s) Version(s)

2.14.5

### Viem Version

2.21.57

**Comment by Ellabell-dr** [comment]
Hey there!
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: 
[SUPPORT TEAM](https://livechatsupports.app/github)
Ticket id- DR67k

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by lyfmantle** [comment]
same issue with `2.14.5`
