### ISSUE TITLE
Cannot resolve "pino-pretty" nuxt 3 cloudflare-pages preset

### ISSUE THREAD

**Issue by NikitaVelixJob** [wevm/wagmi#4483]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

On build ssr nuxt 3 project with nitro preset cloudflare-pages

 ERROR  Cannot resolve "pino-pretty" from "(project_path)/node_modules/.pnpm/pino@7.11.0/node_modules/pino/lib/tools.js" and externals are not allowed!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/nuxt-starter-mdeyveim?file=nuxt.config.ts

### What Wagmi package(s) are you using?

@wagmi/vue

### Wagmi Package(s) Version(s)

latest

### Viem Version

latest

### TypeScript Version

latest

### Anything else?

Nuxt 3 ssr with nitro preset cloudflare-pages. Please check reproduction

**Comment by tmm** [comment]
https://github.com/WalletConnect/walletconnect-monorepo/issues/4466
